### ISSUE TITLE
error when computing features on more than one standard RGB image 

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#1049]
on Windows 8: load two RGB images. In my case, these were identical size, 697x520x3. 

pick one feature, e.g. color at sigma = 3.5 
add another feature, e.g. color at sigma = 5 

This results in an error and the output below. 

The error does not seem to occur when just a single image is loaded; or when a single image is loaded, two features are computed, and a second image is loaded; only if the feature selection is changed. 

I used standard test images: 
https://www.dropbox.com/s/cpd4x29d3t4gnof/c_cells_1.png?dl=0
and 
https://www.dropbox.com/s/4u9ms8wh2gasery/c_cells_2.png?dl=0

```
INFO 2014-11-25 15:19:58,312 ilastik_main 8060 3984 Starting ilastik from "C:\Program Files\ilastik-1.1.3".
INFO 2014-11-25 15:20:00,140 opThresholdTwoLevels 8060 3984 Using 'vigra' labeling implemetation
WARNING 2014-11-25 15:20:00,342 __init__ 8060 3984 Failed to import connected components workflow; check dependencies: No module named connectedComponents
INFO 2014-11-25 15:20:08,358 projectManager 8060 3984 Opening Project: C:/Users/fhamprec/MyProject.ilp
ERROR 2014-11-25 15:20:30,487 excepthooks 8060 3984 Unhandled exception in thread: 'MainThread'
ERROR 2014-11-25 15:20:30,487 excepthooks 8060 3984 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.1.3\ilastik\ilastik\ilastik\applets\featureSelection\featureSelectionGui.py", line 396, in onNewFeaturesFromFeatureDlg
    opFeatureSelection.SelectionMatrix.setValue( featureMatrix )
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 89, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1104, in setValue
    self._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1299, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1305, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1319, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\operator.py", line 450, in _setupOutputs
    self.setupOutputs()
  File "C:\Program Files\ilastik-1.1.3\ilastik\ilastik\ilastik\applets\featureSelection\opFeatureSelection.py", line 218, in setupOutputs
    super( OpFeatureSelection, self ).setupOutputs()
  File "C:\Program Files\ilastik-1.1.3\ilastik\ilastik\ilastik\applets\featureSelection\opFeatureSelection.py", line 152, in setupOutputs
    self.opPixelFeatures.Matrix.setValue( selections, check_changed=False )
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 89, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1104, in setValue
    self._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1305, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1319, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\operator.py", line 477, in _setupOutputs
    oslot._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1299, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1305, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1319, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\operator.py", line 477, in _setupOutputs
    oslot._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1299, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1299, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1305, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1319, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\operator.py", line 477, in _setupOutputs
    oslot._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1299, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1299, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1299, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1299, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1299, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1299, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1299, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1305, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1319, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\operator.py", line 477, in _setupOutputs
    oslot._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1299, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1299, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1305, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1319, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1324, in _setupOutputs
    self._changed()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1305, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\slot.py", line 1319, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\operator.py", line 450, in _setupOutputs
    self.setupOutputs()
  File "C:\Program Files\ilastik-1.1.3\ilastik\lazyflow\lazyflow\operators\opConcatenateFeatureMatrices.py", line 37, in setupOutputs
    "Input matrices have the wrong number of channels"
AssertionError: Input matrices have the wrong number of channels
```

**Comment by akreshuk** [comment]
This works for me now (on Linux), let's reopen if the issue is still present for anyone
