### ISSUE TITLE
Bug in carving pre-processing

### ISSUE THREAD

**Issue by bpavie** [ilastik/ilastik#1136]
I encountered a bug while running the preprocessing step for a carving project trying to segment a EM dataset ( 4800x4800x141) 8bits.
Ilastik is the last version 1.1.5
The computer has 128GB of RAM and 6 Cores 3.5GHz. It looks like the dataset is too large for the preprocessing (dark-line or dark lines with smoothing)...
```
WARNING: CPLEX is not in the PATH -- automatic tracking will be unavailable.
Loading ilastik from "C:\Program Files\ilastik-1.1.5\ilastik"
Starting ilastik from "C:\Program Files\ilastik-1.1.5".
Watershed...ERROR 2015-08-10 13:40:47,483 log_exception 7216 6536 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\request\request.py", line 293, in _execute self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\slot.py", line 799, in __call__result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.5\ilastik\ilastik\ilastik\workflows\carving\opPreprocessing.py", line 393, in execute
    mst = self._opMstProvider.MST.value
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\slot.py", line 1013, in value
    temp =  self[:].wait()
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\slot.py", line 799, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.5\ilastik\ilastik\ilastik\workflows\carving\opPreprocessing.py", line 215, in execute
    labelVolume = self.LabelImage( *roiFromShape( self.LabelImage.meta.shape ) ).wait()
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\slot.py", line 799, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\operators\opArrayCache.py", line 317, in execute
    return self._executeOutput(slot, subindex, roi, result)
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\operators\opArrayCache.py", line 428, in _executeOutput
    dirtyPool.wait()
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\request\request.py", line 1139, in wait
    self._clear_finishing_requests()
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\request\request.py", line 1220, in _clear_finishing_requests
    req.block()
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\request\request.py", line 455, in block
    self._wait(timeout) # No return value. Use wait()
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\request\request.py", line 738, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.1.5\ilastik\lazyflow\lazyflow\slot.py", line 799, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.5\ilastik\ilastik\ilastik\workflows\carving\opPreprocessing.py", line 180, in execute
    result_view[...] = vigra.analysis.watersheds(volume_feat[:,:].astype(numpy.uint8))[0]
RuntimeError:
Invariant violation!
connected components: Need more labels than can be represented in the destination type.
(c:\install_vc11\src\vigra-head\include\vigra\union_find.hxx:284)
```

**Comment by stuarteberg** [comment]
It looks like the watershed step is attempting to create more than 2^32 superpixels.  That implies that the superpixels it is generating are very small.  Perhaps you can try a higher level of smoothing ("filter scale"), which should result in fewer, larger superpixels.

**Comment by bpavie** [comment]
Thanks for your fast answer! I used the default sigma value (1.6), The dataset (SEM) is quit quit noisy, I tried 3 and it looks to work now... Thanks...

**Comment by stuarteberg** [comment]
Good to hear.  Thanks for letting us know.
