### ISSUE TITLE
Counting: Need workaround for non-threadsafe behavior in scikit-learn

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik#1149]
A user reported seeing the following error when using the counting workflow.  It seems to be due to scikit-learn/scikit-learn#2755.  If that doesn't get fixed any time soon, we should find a workaround in our own code.

<details>
<summary>Click here for traceback details</summary>

```pytb
ERROR 2015-09-15 09:45:08,651 excepthooks 7624 11636 Unhandled exception in thread: 'MainThread'
ERROR 2015-09-15 09:45:08,651 excepthooks 7624 11636 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.1.6\ilastik\ilastik\ilastik\applets\counting\countingGui.py", line 1199, in updateSum
    density = self.op.OutputSum[...].wait()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.6\ilastik\ilastik\ilastik\applets\counting\opCounting.py", line 99, in execute
    pool.wait()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 1148, in wait
    self._clear_finishing_requests()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 1229, in _clear_finishing_requests
    req.block()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 455, in block
    self._wait(timeout) # No return value. Use wait()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.6\ilastik\ilastik\ilastik\applets\counting\opCounting.py", line 93, in predict_block
    data = self.Input[blockKeys[i]].wait()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.6\ilastik\ilastik\ilastik\applets\counting\opCounting.py", line 152, in execute
    data = self.inputs["Input"][key].wait()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.6\ilastik\ilastik\ilastik\applets\counting\countingOperators.py", line 385, in execute
    forests=self.inputs["Classifier"][:].wait()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\operators\valueProviders.py", line 291, in execute
    value = request.wait()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.6\ilastik\ilastik\ilastik\applets\counting\countingOperators.py", line 305, in execute
    pool.wait()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 1148, in wait
    self._clear_finishing_requests()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 1229, in _clear_finishing_requests
    req.block()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 455, in block
    self._wait(timeout) # No return value. Use wait()
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.1.6\ilastik\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.6\ilastik\ilastik\ilastik\applets\counting\countingOperators.py", line 301, in train_and_store
    = self.numRegressors, trainAll = False)
  File "C:\Program Files\ilastik-1.1.6\ilastik\ilastik\ilastik\applets\counting\countingsvr.py", line 563, in fitPrepared
    regressor = self._fit(img[indices, :], dot[indices], newTags, newBoxConstraints)
  File "C:\Program Files\ilastik-1.1.6\ilastik\ilastik\ilastik\applets\counting\countingsvr.py", line 587, in _fit
    regressor.fit(img, dot)
  File "C:\Program Files\ilastik-1.1.6\python\lib\site-packages\sklearn\ensemble\forest.py", line 302, in fit
    for i in range(n_jobs))
  File "C:\Program Files\ilastik-1.1.6\python\lib\site-packages\sklearn\externals\joblib\parallel.py", line 517, in __call__
    self.dispatch(function, args, kwargs)
  File "C:\Program Files\ilastik-1.1.6\python\lib\site-packages\sklearn\externals\joblib\parallel.py", line 312, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "C:\Program Files\ilastik-1.1.6\python\lib\site-packages\sklearn\externals\joblib\parallel.py", line 136, in __init__
    self.results = func(*args, **kwargs)
  File "C:\Program Files\ilastik-1.1.6\python\lib\site-packages\sklearn\ensemble\forest.py", line 82, in _parallel_build_trees
    tree = forest._make_estimator(append=False)
  File "C:\Program Files\ilastik-1.1.6\python\lib\site-packages\sklearn\ensemble\base.py", line 57, in _make_estimator
    estimator = clone(self.base_estimator)
  File "C:\Program Files\ilastik-1.1.6\python\lib\site-packages\sklearn\base.py", line 49, in clone
    params_set = new_object.get_params(deep=False)
  File "C:\Program Files\ilastik-1.1.6\python\lib\site-packages\sklearn\base.py", line 218, in get_params
    warnings.filters.pop(0)
IndexError: pop from empty list
```
</details>

**Comment by ukoethe** [comment]
Once @dagophil's new random forest implementation gets merged into vigra, it might be easiest to switch to that, as it supports thread-safe training on the C++ side.

**Comment by stuarteberg** [comment]
>Once @dagophil's new random forest implementation gets merged into vigra, it might be easiest to switch to that

So... how's that new random forest implementation coming along?
:-)

**Comment by dagophil** [comment]
There is still some small stuff that has to be done, such as the python bindings and the import/export to hdf5. But I am working on that right now.

**Comment by stuarteberg** [comment]
Good news: A few minutes ago, scikit-learn was finally [patched](https://github.com/scikit-learn/scikit-learn/pull/9569) fix this.  We should be sure to upgrade as soon as they make their next release (0.19.1, I guess).

**Comment by FynnBe** [comment]
btw: For no obvious reason it is not in 0.19.1 yet

**Comment by k-dominik** [comment]
update: also not in 0.19.2
