### ISSUE TITLE
changing display mode for RGBA image after selecting features results in exception

### ISSUE THREAD

**Issue by svenpeter42** [ilastik/ilastik#1162]
# Exception
```
ERROR 2015-11-12 15:34:23,795 excepthooks 3845 140489613244224 Unhandled exception in thread: 'MainThread'
ERROR 2015-11-12 15:34:23,797 excepthooks 3845 140489613244224 Traceback (most recent call last):
  File "/home/speter/phd/ilastik/ilastik/ilastik/applets/featureSelection/featureSelectionGui.py", line 396, in onNewFeaturesFromFeatureDlg
    opFeatureSelection.SelectionMatrix.setValue( featureMatrix )
  File "/home/speter/miniconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "/home/speter/miniconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/graph.py", line 136, in __exit__
    sig_setup_complete()
  File "/home/speter/miniconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/utility/orderedSignal.py", line 76, in __call__
    f(*args, **kw)
  File "/home/speter/phd/ilastik/ilastik/ilastik/utility/gui/threadRouter.py", line 75, in routed
    val = func(*args, **kwargs)
  File "/home/speter/phd/ilastik/ilastik/ilastik/applets/layerViewer/layerViewerGui.py", line 406, in updateAllLayers
    newGuiLayers = self.setupLayers()
  File "/home/speter/phd/ilastik/ilastik/ilastik/applets/featureSelection/featureSelectionGui.py", line 209, in setupLayers
    layers += self.getFeatureLayers(inputSlot, featureSlot)
  File "/home/speter/phd/ilastik/ilastik/ilastik/applets/featureSelection/featureSelectionGui.py", line 248, in getFeatureLayers
    featureLayer = self.createStandardLayerFromSlot( opSubRegion.Output )
  File "/home/speter/phd/ilastik/ilastik/ilastik/applets/layerViewer/layerViewerGui.py", line 285, in createStandardLayerFromSlot
    .format( numChannels, lastChannelIsAlpha, slot.meta.axistags )
AssertionError: Unhandled combination of channels.  numChannels=1, lastChannelIsAlpha=False, axistags=AxisInfo: 'x' (type: Space)
AxisInfo: 'y' (type: Space)
AxisInfo: 'c' (type: Channels)
```

# Steps to reproduce
1. Start pixel classification workflow
2. Load RGBA png file and select "Default" for "Display mode"
3. Switch to Feature Selection tab and select at least one feature
4. Go back to "Input Data" tab and change "Display mode" to RGBA
5. Go forward to "Feature Selection"

**Comment by stuarteberg** [comment]
Thanks for the clear steps to reproduce.  Was caused by 9e261cb42cfcc8bf98dcc08a8be06e9296a3886c, now fixed via ilastik/lazyflow@3853c1e.  Also fixed a closely related issue via bc235d40175fe3b3f42c47770398e79739ffae1c.
