### ISSUE TITLE
carving error saving objects

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#1164]
When trying to save a segmented object in carving:

```
ERROR 2015-11-16 16:03:34,752 excepthooks 15707 139887076386560 Traceback (most recent call last):
  File "/home/anna/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/workflows/carving/carvingGui.py", line 321, in onSaveButton
    self.topLevelOperatorView.saveObjectAs(name)
  File "/home/anna/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/workflows/carving/opCarving.py", line 599, in saveObjectAs
    self._mst.clearSegmentation()
  File "/home/anna/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/workflows/carving/watershed_segmentor.py", line 77, in clearSegmentation
    self.gridSegmentor.clearSegmentation()
AttributeError: 'GridSegmentor_3D_UInt32' object has no attribute 'clearSegmentation'
```

**Comment by akreshuk** [comment]
i get this:
ilastiktools              0.1                     d44fe27 
I have also just hit save current object

**Comment by stuarteberg** [comment]
OK, that's the problem.  I think this is a bug that was fixed in a later version of the `ilastiktools` package.  (Earlier versions of the package didn't include the "build number in the package name, so it wasn't obvious which builds were newer and which were older.)

Try updating your whole enviroment:

```
conda update --all -n ilastik-devel -c ilastik
```

**Comment by akreshuk** [comment]
Works now, thanks!
