### ISSUE TITLE
Error loading stacked 32-bit TIFs

### ISSUE THREAD

**Issue by dlogan** [ilastik/ilastik#1176]
In the release version of ilastik 1.1.8 (Windows 7) using Pixel Classification, upon loading this stacked tif with 6 channels, I get this error:
```
ArgumentError: Python argument types in
    vigra.impex.readImage(str)
did not match C++ signature:
    readImage(char const * __ptr64 filename, class boost::python::api::object dtype='FLOAT', unsigned int index=0, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > order='')
```
Here is an example of this image type:
http://www.broadinstitute.org/~dlogan/ilastik_error/N3_broad_1_component_data.tif

I can load this into FIJI without issues.

Here is the full stack trace from the ilastik log:
```
ERROR 2016-01-19 09:27:41,795 excepthooks 6528 7684 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\volumina\volumina\tiling.py", line 90, in _render
    img = self.image_req.wait()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\volumina\volumina\pixelpipeline\imagesources.py", line 149, in wait
    return self.toImage()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\volumina\volumina\pixelpipeline\imagesources.py", line 155, in toImage
    self._arrayreq.wait()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\volumina\volumina\pixelpipeline\slicesources.py", line 43, in wait
    return self._sp(self._ar.wait())
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\volumina\volumina\pixelpipeline\datasources.py", line 471, in wait
    rawData = self._rawRequest.wait()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\volumina\volumina\pixelpipeline\datasources.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\volumina\volumina\pixelpipeline\datasources.py", line 229, in wait
    a = self._req.wait()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\operators\opReorderAxes.py", line 128, in execute
    self.Input( *in_roi ).writeInto( result_input_view ).wait()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 736, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\operators\opReorderAxes.py", line 128, in execute
    self.Input( *in_roi ).writeInto( result_input_view ).wait()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 736, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\operators\valueProviders.py", line 120, in execute
    req.wait()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 736, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\operators\valueProviders.py", line 120, in execute
    req.wait()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 736, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\operators\opSplitRequestsBlockwise.py", line 100, in execute
    pool.wait()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1148, in wait
    self._clear_finishing_requests()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1229, in _clear_finishing_requests
    req.block()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 455, in block
    self._wait(timeout) # No return value. Use wait()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\operators\opUnblockedArrayCache.py", line 100, in execute
    self.Input(roi.start, roi.stop).writeInto(result).block()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 455, in block
    self._wait(timeout) # No return value. Use wait()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 736, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\operators\opCacheFixer.py", line 63, in execute
    self.Input(roi.start, roi.stop).writeInto(result).wait()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\request\request.py", line 736, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.8\ilastik-meta\lazyflow\lazyflow\operators\ioOperators\opTiffReader.py", line 139, in execute
    page_data = vigra.impex.readImage(self._filepath, dtype='NATIVE', index=tiff_page_list_index, order='C')
ArgumentError: Python argument types in
    vigra.impex.readImage(str)
did not match C++ signature:
    readImage(char const * __ptr64 filename, class boost::python::api::object dtype='FLOAT', unsigned int index=0, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > order='')
```

**Comment by stuarteberg** [comment]
I'm able to read that image using my development version of ilastik, so one of two things is happening:

- Some recent change to our code base already fixes this bug (but the fix is not in a released version yet)
- This problem is specific to the Windows build.  (@ukoethe, are you able to load the above sample image on your machine?)

BTW, @ukoethe: Once the image is loaded, the next step is to tell ilastik to change the `t` axis to `c`, so it correctly appears as a multi-channel image (not multi-time-step).  There is one small bug related to that feature that currently affects the released version, but fixed in the (unreleased) master branch (specifically, of the lazyflow repo).

**Comment by dlogan** [comment]
Thanks for the quick reply @stuarteberg . It appears to be a Windows-related issue at some level, as I just loaded this image on a Mac with the compiled 1.1.8 version just fine. So for now, it's a fine workaround for us to use the Mac build.  I could get Windows to build from source as we would rather use a Windows machine for training, but I guess I will wait until the "new-and-improved" conda Windows instructions are ready.

And secondarily, thanks for the tip about manually changing the t -> c axis metadata.

**Comment by stuarteberg** [comment]
I just tried out the latest Windows packages from @ukoethe's anaconda channel, and they also seem to work with your data.  So I suppose the priority now is just for us to make a new release based on our latest code.

**Comment by JosephKM** [comment]
Is there a workaround for this? Thanks.

**Comment by stuarteberg** [comment]
Apparently I was wrong when I wrote this:

>I just tried out the latest Windows packages from @ukoethe's anaconda channel, and they also seem to work with your data.

The files on that channel are old.  I was effectively using an old version of ilastik, which apparently does not have this bug.

You can try the last two versions with these links:
http://files.ilastik.org/ilastik-1.1.7-win64.exe (17-Aug-2015)
http://files.ilastik.org/ilastik-1.1.6-win64.exe (10-Oct-2015)

There have been various performance/stability enhancements made since then, so it is definitely recommended to upgrade to version 1.1.9 once it is released.  (It sounds like that probably won't be until the end of the month, unfortunately.)

**Comment by JosephKM** [comment]
Thank you for the response. I have been able to successfully open my data with 1.1.7 linked above.

**Comment by ukoethe** [comment]
Apparently, boost::python is unable to convert variable `tiff_page_list_index` to `unsigned int` on Windows. I added an explicit cast on the Python side which seems to resolve this issue.
