### ISSUE TITLE
(Animal?) Tracking - Size Filtering breaks setLabel2color method

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1199]
If one uses a binary segmentation mask or does not apply a size-filter in thresholding, there is another size filter option in Tracking to get rid of very small or large objects so that they do not confuse the tracking algorithm. It looks like there is a bug in the setLabel2color method, which I guess could be due to a missing mapping of the indices between `pgmlink` and ilastik.

I only encountered in the animal tracking workflow right now, but will investigate whether this also applies to Conservation Tracking.

```
ERROR 2016-03-17 14:47:46,854 log_exception 74649 5067882496 Traceback (most recent call last):
  File "/Users/chaubold/opt/miniconda/envs/ilastik-master/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/conservationTrackingGui.py", line 234, in _track
    force_build_hypotheses_graph = False
  File "/Users/chaubold/opt/miniconda/envs/ilastik-master/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 297, in track
    self.EventsVector.setValue(events, check_changed=False)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-master/ilastik-meta/lazyflow/lazyflow/slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-master/ilastik-meta/lazyflow/lazyflow/slot.py", line 1123, in setValue
    self.partner.setValue(value, notify, check_changed)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-master/ilastik-meta/lazyflow/lazyflow/slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-master/ilastik-meta/lazyflow/lazyflow/slot.py", line 1189, in setValue
    self.setDirty(slice(None))
  File "/Users/chaubold/opt/miniconda/envs/ilastik-master/ilastik-meta/lazyflow/lazyflow/slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-master/ilastik-meta/lazyflow/lazyflow/slot.py", line 936, in setDirty
    c.setDirty(roi)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-master/ilastik-meta/lazyflow/lazyflow/slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-master/ilastik-meta/lazyflow/lazyflow/slot.py", line 942, in setDirty
    self.operator.propagateDirty(self, (), roi)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-master/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 311, in propagateDirty
    super(OpConservationTracking, self).propagateDirty(inputSlot, subindex, roi)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-master/ilastik-meta/ilastik/ilastik/applets/tracking/base/opTrackingBase.py", line 189, in propagateDirty
    self._setLabel2Color()
  File "/Users/chaubold/opt/miniconda/envs/ilastik-master/ilastik-meta/ilastik/ilastik/applets/tracking/base/opTrackingBase.py", line 345, in _setLabel2Color
    assert l not in label2color[int(i) + time_range[0]]
```

**Comment by JaimeIvanCervantes** [comment]
@chaubold how can we activate this filter and recreate this error? Can we do it from within the GUI or we have to do it directly in the code?

**Comment by chaubold** [comment]
I get the error when I try to track the first 500 frames of the project you gave me.

![screen shot 2016-03-17 at 16 00 55](https://cloud.githubusercontent.com/assets/16854/13850304/a90356ca-ec59-11e5-83f1-e05048542921.png)

**Comment by JaimeIvanCervantes** [comment]
Yeah, I just found the size filter. 

Did you changed anything in the file besides setting the time range to 500? Because I just opened the file and was able to process the first 500 frames without problem.

**Comment by chaubold** [comment]
No, I set the min size to 30 and then the error above pops up

**Comment by JaimeIvanCervantes** [comment]
Ok, I was able to recreate the error. 

Also, if I set the `time_range` to [30, 500] I get the following error:

```
ERROR 2016-03-17 11:08:53,340 log_exception 17341 140011162253056 Traceback (most recent call last):
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/conservationTrackingGui.py", line 234, in _track
    force_build_hypotheses_graph = False
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 290, in track
    raise Exception, 'Tracking terminated unsuccessfully: ' + str(e)
Exception: Tracking terminated unsuccessfully: index 21 is out of bounds for axis 0 with size 20
```
