### ISSUE TITLE
Error when generating export of manual tracking

### ISSUE THREAD

**Issue by burgerga** [ilastik/ilastik#1220]
Seems to happen when none of the tracks continue into the last time frame (I am exporting partial results).

```
ERROR 2016-05-11 16:33:46,833 log_exception 5156 139797527570176 Traceback (most recent call last):
  File "/home/gerhard/Downloads/ilastik/ilastik-1.1.9-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 293, in _execute
    self._result = self.fn()
  File "/home/gerhard/Downloads/ilastik/ilastik-1.1.9-Linux/ilastik-meta/ilastik/ilastik/applets/tracking/manual/opManualTracking.py", line 234, in do_export
    max_tracks = max(max(map(len, i.values())) for i in oid2tid.values())
  File "/home/gerhard/Downloads/ilastik/ilastik-1.1.9-Linux/ilastik-meta/ilastik/ilastik/applets/tracking/manual/opManualTracking.py", line 234, in <genexpr>
    max_tracks = max(max(map(len, i.values())) for i in oid2tid.values())
ValueError: max() arg is an empty sequence

ERROR 2016-05-11 16:33:46,834 log_exception 5156 139797527570176 Export failed
ERROR 2016-05-11 16:33:46,834 log_exception 5156 139796189689600 Traceback (most recent call last):
  File "/home/gerhard/Downloads/ilastik/ilastik-1.1.9-Linux/ilastik-meta/ilastik/ilastik/applets/dataExport/dataExportGui.py", line 388, in exportSlots
    self.parentApplet.post_process_lane_export(lane_index)
  File "/home/gerhard/Downloads/ilastik/ilastik-1.1.9-Linux/ilastik-meta/ilastik/ilastik/workflows/tracking/manual/manualTrackingWorkflow.py", line 141, in post_process_lane_export
    req.wait()
  File "/home/gerhard/Downloads/ilastik/ilastik-1.1.9-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 449, in wait
    return self._wait(timeout)
  File "/home/gerhard/Downloads/ilastik/ilastik-1.1.9-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/home/gerhard/Downloads/ilastik/ilastik-1.1.9-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 293, in _execute
    self._result = self.fn()
  File "/home/gerhard/Downloads/ilastik/ilastik-1.1.9-Linux/ilastik-meta/ilastik/ilastik/applets/tracking/manual/opManualTracking.py", line 234, in do_export
    max_tracks = max(max(map(len, i.values())) for i in oid2tid.values())
  File "/home/gerhard/Downloads/ilastik/ilastik-1.1.9-Linux/ilastik-meta/ilastik/ilastik/applets/tracking/manual/opManualTracking.py", line 234, in <genexpr>
    max_tracks = max(max(map(len, i.values())) for i in oid2tid.values())
ValueError: max() arg is an empty sequence

ERROR 2016-05-11 16:33:46,834 log_exception 5156 139796189689600 Failed to generate export file: 
/home/gerhard/ownCloud/ilastik_tracking_test_20121120_p08/Manual Tracking_conservative.h5/exported_data
max() arg is an empty sequence
```

**Comment by JaimeIvanCervantes** [comment]
Is the last frame of your video empty? It looks like `max()` is receiving an empty list of IDs when the workflow is trying to export the table. 

Do you have any suggestions on how to recreate the problem? It looks like adding a check for an empty list of IDs would solve the issue.

**Comment by burgerga** [comment]
It is quite easy to reproduce, I've attached a tracking workflow with just 2 frames. When I start a track in frame 0, but don't continue in frame 1, I get the export error. If I continue the track in frame 1 no error. Let me know if you have any further questions!

[manual_tracking_issue_1220_reproduction.zip](https://github.com/ilastik/ilastik/files/259821/manual_tracking_issue_1220_reproduction.zip)

**Comment by burgerga** [comment]
Oh by the way, if you mean with "empty" "no tracked objects, then yes!

**Comment by JaimeIvanCervantes** [comment]
Thanks for sending the files! I'll look into it in the next few days,

**Comment by JaimeIvanCervantes** [comment]
I fixed the issue: https://github.com/ilastik/ilastik/pull/1222
You can already pull the latest changes for ilastik and lazyflow in order to fix the issue, or alternatively you can wait for the next official release.

**Comment by burgerga** [comment]
Nice, thank you, will try!
