### ISSUE TITLE
Error message when using Object Classification - Click on objects inside time series data set

### ISSUE THREAD

**Issue by sebi06** [ilastik/ilastik#1221]
HI guys,

whenever I click on an object I get those errors shown inside the screenshot. I attached the last part of the error log:

ERROR 2016-05-12 08:38:58,382 excepthooks 4008 5192 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\volumina\volumina\tiling.py", line 90, in _render
    img = self.image_req.wait()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\volumina\volumina\pixelpipeline\imagesources.py", line 262, in wait
    return self.toImage()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\volumina\volumina\pixelpipeline\imagesources.py", line 268, in toImage
    self._arrayreq.wait()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\volumina\volumina\pixelpipeline\slicesources.py", line 43, in wait
    return self._sp(self._ar.wait())
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\volumina\volumina\pixelpipeline\datasources.py", line 471, in wait
    rawData = self._rawRequest.wait()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\volumina\volumina\pixelpipeline\datasources.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\volumina\volumina\pixelpipeline\datasources.py", line 229, in wait
    a = self._req.wait()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\operators\opReorderAxes.py", line 128, in execute
    self.Input( *in_roi ).writeInto( result_input_view ).wait()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 736, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\operators\opSlicedBlockedArrayCache.py", line 180, in execute
    op.outputs["Output"][key].writeInto(result).wait()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 736, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\operators\opBlockedArrayCache.py", line 102, in execute
    self._opSplitRequestsBlockwise.Output(roi.start, roi.stop).writeInto(result).wait()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 736, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\operators\opSplitRequestsBlockwise.py", line 103, in execute
    pool.wait()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1148, in wait
    self._clear_finishing_requests()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1229, in _clear_finishing_requests
    req.block()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 455, in block
    self._wait(timeout) # No return value. Use wait()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 472, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 736, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\operators\opUnblockedArrayCache.py", line 103, in execute
    self.Input(roi.start, roi.stop).writeInto(result).block()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 455, in block
    self._wait(timeout) # No return value. Use wait()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 736, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\operators\opCacheFixer.py", line 63, in execute
    self.Input(roi.start, roi.stop).writeInto(result).wait()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 736, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\ilastik\ilastik\applets\objectClassification\opObjectClassification.py", line 1284, in execute
    map_ = self.ObjectMap([t]).wait()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\slot.py", line 1530, in execute
    return self.operator.execute(self, totalIndex, roi, result)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\ilastik\ilastik\applets\objectClassification\opObjectClassification.py", line 1100, in execute
    classifier = self.Classifier.value
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\slot.py", line 1067, in value
    temp = self[:].wait()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\operators\valueProviders.py", line 292, in execute
    value = request.wait()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 449, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\ilastik\ilastik\applets\objectClassification\opObjectClassification.py", line 984, in execute
    pool.wait()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1148, in wait
    self._clear_finishing_requests()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1229, in _clear_finishing_requests
    req.block()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 455, in block
    self._wait(timeout) # No return value. Use wait()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 475, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\lazyflow\lazyflow\request\request.py", line 293, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\ilastik\ilastik\applets\objectClassification\opObjectClassification.py", line 961, in fetch_features
    featstmp, row_names, col_names, labelstmp = make_feature_array(feats, selected, labels_image_filtered)
  File "C:\Program Files\ilastik-1.1.9\ilastik-meta\ilastik\ilastik\applets\objectClassification\opObjectClassification.py", line 843, in make_feature_array
    for plugin in sorted(feats[t].keys()):
AttributeError: 'int' object has no attribute 'keys'
![ilastik_bug_object_classification](https://cloud.githubusercontent.com/assets/3833249/15206217/ad7df8dc-181d-11e6-9cbc-5c5cb80d5a30.png)

**Comment by stuarteberg** [comment]
What object features have you selected?  If you're able to share a copy of your project file (.ilp) along with the data files you're using, I can try to reproduce the problem on my own machine.  Please send the files to `team @ ilastik.org`
