### ISSUE TITLE
Crash in new feature selection UI

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik#1249]
I get the following error from volumina when I attempt to use the feature selection UI (2D data, uint8 grayscale).  Is it possible that I'm missing some volumina commits?

```pytb
ERROR 2016-07-07 21:41:33,831 excepthooks 12290 4946354176 Unhandled exception in thread: 'Worker #1'
ERROR 2016-07-07 21:41:33,831 excepthooks 12290 4946354176 Traceback (most recent call last):
  File "/magnetic/workspace/ilastik-meta/volumina/volumina/tiling.py", line 768, in _fetch_tile_layer
    img = ims_req.wait()
  File "/magnetic/workspace/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 380, in wait
    return self.toImage()
  File "/magnetic/workspace/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 415, in toImage
    raise NotImplementedError()
NotImplementedError
```

**Comment by akreshuk** [comment]
I can't reproduce that. Are you on master? Could it be your vector-graphics branch of volumina?

**Comment by akreshuk** [comment]
I see the same error when running nosetests of the latest volumina:
FAILURE: Uncaught exception in non-main thread during test: imagesources_test.ColortableImageSourceTest.testRequest
E.Traceback (most recent call last):
  File "/data/ilastik-1.1.10a1.post4-Linux/ilastik-meta/volumina/tests/imagesources_test.py", line 60, in run
    run_old(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/volumina-0.6a-py2.7.egg/volumina/pixelpipeline/datasources.py", line 77, in _doNotify
    callback(result, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/volumina-0.6a-py2.7.egg/volumina/pixelpipeline/imagesources.py", line 487, in _onNotify
    img = self.toImage()
  File "/usr/local/lib/python2.7/dist-packages/volumina-0.6a-py2.7.egg/volumina/pixelpipeline/imagesources.py", line 464, in toImage
    raise NotImplementedError()
NotImplementedError

**Comment by akreshuk** [comment]
I tried with the current release candidate and I still can't reproduce it. Does is still not work for you?

**Comment by stuarteberg** [comment]
OK, the problem seems to be my branch of volumina.  Will investigate for a couple more minutes before giving up.

**Comment by stuarteberg** [comment]
Fixed via d80366a53bc3587b6e3663af3e95e24b53855f96

**Comment by dlogan** [comment]
I am seeing this error in OSX 1.2.0rc7.  Is the above fix in this release, or will it be on the next release candidate?  (And how can I tell what's in rc7?)

**Comment by dlogan** [comment]
Oh, and I get this error when exporting a "Simple Segmentation", not in the feature selection.

**Comment by stuarteberg** [comment]
>I am seeing this error in OSX 1.2.0rc7. Is the above fix in this release

Yes, it's supposed to be fixed in that version.  Would you mind posting the traceback you saw (even if it's nearly identical to the one above)?

>And how can I tell what's in rc7?

There's no explicit method.  But as a rule-of-thumb, you can assume that all issues closed prior to the release date stamp (as listed on the download page) are supposed to be in the release.

**Comment by dlogan** [comment]
Thanks for the quick response!  Here it is (with some other similar "Worker #" messages suppressed:
```
...
ERROR 2016-08-02 11:08:13,012 excepthooks 23846 123145314549760 Unhandled exception in thread: 'Worker #0'
ERROR 2016-08-02 11:08:13,014 excepthooks 23846 123145314549760 Traceback (most recent call last):
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/tiling.py", line 768, in _fetch_tile_layer
    img = ims_req.wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 380, in wait
    return self.toImage()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 415, in toImage
    raise NotImplementedError()
NotImplementedError

ERROR 2016-08-02 11:08:13,027 excepthooks 23846 123145322962944 Unhandled exception in thread: 'Worker #2'
ERROR 2016-08-02 11:08:13,028 excepthooks 23846 123145322962944 Traceback (most recent call last):
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/tiling.py", line 768, in _fetch_tile_layer
    img = ims_req.wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 380, in wait
    return self.toImage()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 415, in toImage
    raise NotImplementedError()
NotImplementedError
```

And thanks for the info on the release includes, too.

**Comment by stuarteberg** [comment]
Can you take a screenshot of the "Export Settings" window you're using on the Data Export page?

**Comment by dlogan** [comment]
I clicked the Export button in the upper right for the first file and got this error:

![image](https://cloud.githubusercontent.com/assets/1225595/17335214/2a4920fc-58a7-11e6-8e49-7e2f4eedbd75.png)

**Comment by dlogan** [comment]
My Export Settings are to hdf5 (which is the only format that seems to work, but that's another issue -- I think I won't press my luck today! 😄 )

![image](https://cloud.githubusercontent.com/assets/1225595/17335336/95355e58-58a7-11e6-9018-747260fb55c8.png)

**Comment by stuarteberg** [comment]
OK, thanks.  Hopefully this will help me reproduce the issue.
