### ISSUE TITLE
Tracking headless test failure

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik#1255]
@JaimeIvanCervantes:
1. Thanks for adding this test.  It caught a problem with project deserialization that would have sneaked into the release otherwise
2. It still isn't passing for me.  Here's what I see:

```
$ cd ilastik/tests
$ python test_applets/conservationTracking/testConservationTrackingHeadless.py
/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py:6: RuntimeWarning: to-Python converter for std::vector<unsigned long, std::allocator<unsigned long> > already registered; second conversion method ignored.
  import pgmlink
/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py:6: RuntimeWarning: to-Python converter for std::vector<double, std::allocator<double> > already registered; second conversion method ignored.
  import pgmlink
INFO ilastik_main: Starting ilastik from "/Users/bergs/Documents/workspace".
Starting ilastik from "/Users/bergs/Documents/workspace".
INFO ilastik.shell.projectManager: Opening Project: data/inputdata/smallVideoConservationTracking.ilp
WARNING 2016-07-08 12:38:15,828 conservationTrackingWorkflow 28356 140735165293312 Unused command-line args: ['--export_source=Tracking-Result']
WARNING arraytypes.py(1263): VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
WARNING slot.py(1156): DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
WARNING dataset.py(76): DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
INFO ilastik.workflows.tracking.conservation.conservationTrackingWorkflow: Beginning Batch Processing
INFO ilastik.applets.tracking.base.opTrackingBase: generating traxels
INFO ilastik.applets.tracking.base.opTrackingBase: fetching region features and division probabilities
INFO ilastik.applets.tracking.base.opTrackingBase: filling traxelstore
- 12:38:16.944 INFO: FeatureStore created
INFO ilastik.applets.tracking.base.opTrackingBase: median object size = 3585.0
INFO ilastik.applets.tracking.conservation.opConservationTracking: median_obj_size = [3585.0]
INFO ilastik.applets.tracking.conservation.opConservationTracking: fov = 0.0,0.0,0.0,0.0,2.0,407.0,407.0,0.0
make new graph
- 12:38:16.945 INFO: using border-aware appearance and disappearance costs, with absolute margin: 10
- 12:38:16.945 INFO: Using classifier prior
- 12:38:16.946 INFO: ConservationTracking::perturbedInference: generating tracklet graph
- 12:38:16.946 INFO: ConservationTracking::perturbedInference: number of iterations: 1
- 12:38:16.946 INFO: ConservationTracking::perturbedInference: perturb using method with Id 1
- 12:38:16.946 INFO: number_of_transition_nodes_ = 5
- 12:38:16.946 INFO: number_of_appearance_nodes_ = 6
- 12:38:16.946 INFO: number_of_disappearance_nodes_ = 6
- 12:38:16.946 INFO: number_of_division_nodes_ = 0
- 12:38:16.950 INFO: [ConsTrackingInferenceModel] add_constraints
- 12:38:16.950 INFO: [ConstraintPool]: Adding 6 hard constraints for Incoming
- 12:38:16.950 INFO: [ConstraintPool]: Adding 0 hard constraints for Outgoing
- 12:38:16.950 INFO: [ConstraintPool]: Adding 6 hard constraints for Outgoing
- 12:38:16.950 INFO: [ConstraintPool]: Adding 6 hard constraints for Detection
- 12:38:16.950 INFO: [ConstraintPool]: Adding 0 hard constraints for FixNodeValue
- 12:38:16.950 INFO: [ConsTrackingInferenceModel] add_constraints
Tried aggregator 2 times.
MIP Presolve eliminated 3 rows and 10 columns.
Aggregator did 4 substitutions.
Reduced MIP has 82 rows, 121 columns, and 313 nonzeros.
Reduced MIP has 43 binaries, 0 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.00 sec. (0.32 ticks)
Found incumbent of value 5096.831232 after 0.00 sec. (0.66 ticks)
Probing fixed 0 vars, tightened 12 bounds.
Probing time = 0.00 sec. (0.09 ticks)
Tried aggregator 1 time.
MIP Presolve eliminated 4 rows and 16 columns.
Reduced MIP has 78 rows, 105 columns, and 277 nonzeros.
Reduced MIP has 39 binaries, 1 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.00 sec. (0.25 ticks)
Probing time = 0.00 sec. (0.07 ticks)
Tried aggregator 1 time.
Reduced MIP has 78 rows, 105 columns, and 277 nonzeros.
Reduced MIP has 39 binaries, 1 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.00 sec. (0.16 ticks)
Probing time = 0.00 sec. (0.07 ticks)
Clique table members: 70.
MIP emphasis: balance optimality and feasibility.
MIP search method: dynamic search.
Parallel mode: none, using 1 thread.
Root relaxation solution time = 0.00 sec. (0.09 ticks)

        Nodes                                         Cuts/
   Node  Left     Objective  IInf  Best Integer    Best Bound    ItCnt     Gap

*     0+    0                         5096.8312        0.0000       18  100.00%
      0     0       54.9280     2     5096.8312       54.9280       18   98.92%
*     0+    0                          226.6045       54.9280       18   75.76%
*     0     0      integral     0       59.4587      Cuts: 16       19    0.00%
      0     0        cutoff             59.4587       59.4587       19    0.00%
Elapsed time = 0.01 sec. (2.60 ticks, tree = 0.00 MB, solutions = 3)

GUB cover cuts applied:  4
Clique cuts applied:  4
Cover cuts applied:  1
Implied bound cuts applied:  4
Zero-half cuts applied:  1
Lift and project cuts applied:  1
Gomory fractional cuts applied:  1

Root node processing (before b&c):
  Real time             =    0.01 sec. (2.61 ticks)
Sequential b&c:
  Real time             =    0.00 sec. (0.00 ticks)
                          ------------
Total (root+branch&cut) =    0.01 sec. (2.61 ticks)
- 12:38:16.957 INFO: conclude MAP
ILP model eval: 59.4587
-> storing state of detection vars
-> constructing unresolved events
- 12:38:16.963 INFO: -> resolving mergers
- 12:38:16.963 INFO: -> creating a copy of hypotheses graph
- 12:38:17.066 INFO: resolve_graph() entered
- 12:38:17.066 INFO: adding node_originated_from to destination hypotheses graph
- 12:38:17.067 INFO: duplicate_division_nodes(): enter
- 12:38:17.067 INFO: resolve_graph(): calling conservation tracking
- 12:38:17.067 INFO: ConservationTracking::perturbedInference: generating tracklet graph
- 12:38:17.067 INFO: ConservationTracking::perturbedInference: number of iterations: 1
- 12:38:17.067 INFO: ConservationTracking::perturbedInference: perturb using method with Id 0
- 12:38:17.067 INFO: number_of_transition_nodes_ = 12
- 12:38:17.067 INFO: number_of_appearance_nodes_ = 8
- 12:38:17.067 INFO: number_of_disappearance_nodes_ = 8
- 12:38:17.067 INFO: number_of_division_nodes_ = 0
- 12:38:17.068 INFO: [ConsTrackingInferenceModel] add_constraints
- 12:38:17.068 INFO: [ConstraintPool]: Adding 8 hard constraints for Incoming
- 12:38:17.068 INFO: [ConstraintPool]: Adding 0 hard constraints for Outgoing
- 12:38:17.068 INFO: [ConstraintPool]: Adding 8 hard constraints for Outgoing
- 12:38:17.068 INFO: [ConstraintPool]: Adding 8 hard constraints for Detection
- 12:38:17.069 INFO: [ConstraintPool]: Adding 0 hard constraints for FixNodeValue
- 12:38:17.069 INFO: [ConsTrackingInferenceModel] add_constraints
Tried aggregator 2 times.
MIP Presolve eliminated 91 rows and 86 columns.
Aggregator did 19 substitutions.
All rows and columns eliminated.
Presolve time = 0.00 sec. (0.08 ticks)

Root node processing (before b&c):
  Real time             =    0.00 sec. (0.10 ticks)
Sequential b&c:
  Real time             =    0.00 sec. (0.00 ticks)
                          ------------
Total (root+branch&cut) =    0.00 sec. (0.10 ticks)
- 12:38:17.069 INFO: conclude MAP
ILP model eval: 11.8146
- 12:38:17.070 INFO: -> constructing resolved events
- 12:38:17.070 INFO: -> done resolving mergers
INFO ilastik.applets.batchProcessing.batchProcessingApplet: Exporting to /Users/bergs/Documents/workspace/ilastik-meta/ilastik/tests/data/inputdata/smallVideo_Tracking-Result.h5/exported_data
INFO lazyflow.operators.ioOperators.ioOperators.OpH5WriterBigDataset: Data shape: (3, 408, 408, 1, 1)
INFO lazyflow.utility.bigRequestStreamer: Estimated RAM usage per pixel is 4.0B * safety factor (2.0)
INFO lazyflow.utility.bigRequestStreamer: determining blockshape assuming available_ram is 4.0GiB, split between 8 threads
INFO lazyflow.utility.bigRequestStreamer: Chose blockshape: (3, 408, 408, 1, 1)
INFO lazyflow.utility.bigRequestStreamer: Estimated RAM usage per block is 3.8MiB
Export Progress [1/2]
0 ERROR 2016-07-08 12:38:17,161 log_exception 28356 4592816128 Traceback (most recent call last):
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 517, in do_export
    self._do_export_impl(settings, selected_features, progress_slot, object_feature_slot, label_image, lane_index, filename_suffix)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/tracking/base/opTrackingBase.py", line 636, in _do_export_impl
    {"selection": selected_features})
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 270, in add_columns
    columns = flatten_ilastik_feature_table(col_data, extra["selection"], self.InsertionProgress)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 61, in flatten_ilastik_feature_table
    computed_feature.update(request.wait())
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opRelabeledMergerFeatureExtraction.py", line 197, in execute
    result[t][name][k] = self._merge_features(result[t][name][k], v, mapping[t])
KeyError: 0

ERROR 2016-07-08 12:38:17,161 log_exception 28356 4592816128 Export failed
ERROR 2016-07-08 12:38:17,312 log_exception 28356 140735165293312 Traceback (most recent call last):
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 443, in _loadProject
    self.workflow.onProjectLoaded( self )
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 423, in onProjectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 59, in run_export_from_parsed_args
    return self.run_export(role_path_dict, parsed_args.input_axes)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 120, in run_export
    export_to_array=export_to_array )
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 236, in _run_export_with_empty_batch_lane
    self.dataExportApplet.post_process_lane_export(batch_lane_index)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 386, in post_process_lane_export
    req.wait()
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/request/request.py", line 503, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 517, in do_export
    self._do_export_impl(settings, selected_features, progress_slot, object_feature_slot, label_image, lane_index, filename_suffix)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/tracking/base/opTrackingBase.py", line 636, in _do_export_impl
    {"selection": selected_features})
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 270, in add_columns
    columns = flatten_ilastik_feature_table(col_data, extra["selection"], self.InsertionProgress)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 61, in flatten_ilastik_feature_table
    computed_feature.update(request.wait())
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opRelabeledMergerFeatureExtraction.py", line 197, in execute
    result[t][name][k] = self._merge_features(result[t][name][k], v, mapping[t])
KeyError: 0

ERROR 2016-07-08 12:38:17,312 log_exception 28356 140735165293312 Project could not be loaded due to the exception shown above.
Aborting Project Open Action
E
======================================================================
ERROR: testConservationTrackingHeadless.TestConservationTrackingHeadless.testTrackingHeadless
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/miniconda/envs/ilastik-1.2-dev/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 142, in wrapper
    return func(*args, **kwargs)
  File "/Users/bergs/Documents/workspace/ilastik-meta/ilastik/tests/test_applets/conservationTracking/testConservationTrackingHeadless.py", line 103, in testTrackingHeadless
    self.ilastik_startup.main()
  File "/Users/bergs/Documents/workspace/ilastik-meta/ilastik/ilastik/../ilastik.py", line 104, in main
    ilastik_main.main(parsed_args, workflow_cmdline_args)
  File "/Users/bergs/Documents/workspace/ilastik-meta/ilastik/ilastik_main.py", line 102, in main
    f(shell)
  File "/Users/bergs/Documents/workspace/ilastik-meta/ilastik/ilastik_main.py", line 317, in loadProject
    shell.openProjectFile(path, parsed_args.readonly)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/shell/headless/headlessShell.py", line 112, in openProjectFile
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 142, in wrapper
    return func(*args, **kwargs)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 443, in _loadProject
    self.workflow.onProjectLoaded( self )
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 423, in onProjectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 59, in run_export_from_parsed_args
    return self.run_export(role_path_dict, parsed_args.input_axes)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 120, in run_export
    export_to_array=export_to_array )
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 236, in _run_export_with_empty_batch_lane
    self.dataExportApplet.post_process_lane_export(batch_lane_index)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 386, in post_process_lane_export
    req.wait()
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/request/request.py", line 503, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 517, in do_export
    self._do_export_impl(settings, selected_features, progress_slot, object_feature_slot, label_image, lane_index, filename_suffix)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/tracking/base/opTrackingBase.py", line 636, in _do_export_impl
    {"selection": selected_features})
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 270, in add_columns
    columns = flatten_ilastik_feature_table(col_data, extra["selection"], self.InsertionProgress)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 61, in flatten_ilastik_feature_table
    computed_feature.update(request.wait())
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/magnetic/workspace/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opRelabeledMergerFeatureExtraction.py", line 197, in execute
    result[t][name][k] = self._merge_features(result[t][name][k], v, mapping[t])
KeyError: 0

----------------------------------------------------------------------
Ran 1 test in 2.547s

FAILED (errors=1)
```

**Comment by JaimeIvanCervantes** [comment]
I am looking into this right now. It's interesting because the test was passing this morning, so it must be an error introduced in a recent commit.

**Comment by k-dominik** [comment]
this test passes!
