### ISSUE TITLE
After reloading a previously loaded an ilp, switching the export settings fails

### ISSUE THREAD

**Issue by mmorehea** [ilastik/ilastik#1279]
I had a simple Pixel Classification project, saved with Probabilities as the export setting. Upon reloading and attempting to switch to simple segmentation, list index out of range.

INFO 2016-07-13 08:26:32,512 ilastik_main 9204 139997723657984 Starting ilastik from "/home/mdm/ilastik-1.2.0rc5-Linux".
WARNING 2016-07-13 08:26:32,969 httplib 9204 139997723657984 httplib.py(1179): ImportWarning: Not importing directory '/home/mdm/ilastik-1.2.0rc5-Linux/ssl': missing __init__.py
WARNING 2016-07-13 08:26:33,419 edge_coords 9204 139997723657984 edge_coords.py(11): UserWarning: pandas not available. edge_coords functions will be slower.
INFO 2016-07-13 08:26:33,730 opThresholdTwoLevels 9204 139997723657984 Using 'vigra' labeling implemetation
WARNING 2016-07-13 08:26:33,764 __init__ 9204 139997723657984 Failed to import automatic tracking workflow (conservation tracking). For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: No module named pgmlinkNoIlpSolver
WARNING 2016-07-13 08:26:33,767 __init__ 9204 139997723657984 Failed to import structured learning tracking workflow. For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: libconcert.so: cannot open shared object file: No such file or directory
INFO 2016-07-13 08:26:36,783 projectManager 9204 139997723657984 Opening Project: /home/mdm/code/ilastik_batch/batchtest.ilp
WARNING 2016-07-13 08:26:38,112 dataset 9204 139997723657984 dataset.py(76): DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
WARNING 2016-07-13 08:26:38,426 tiling 9204 139997723657984 tiling.py(351): UserWarning: FIXME: This is a slow way to look for the items we want.
_TilesCache._layerCache should be a dict-of-dict-of-dict for faster lookup!
ERROR 2016-07-13 08:26:41,097 excepthooks 9204 139997723657984 Unhandled exception in thread: 'MainThread'
ERROR 2016-07-13 08:26:41,098 excepthooks 9204 139997723657984 Traceback (most recent call last):
  File "/home/mdm/ilastik-1.2.0rc5-Linux/ilastik-meta/volumina/volumina/layerstack.py", line 270, in data
    return self._layerStack[index.row()]
IndexError: list index out of range

ERROR 2016-07-13 08:26:41,098 excepthooks 9204 139997723657984 Unhandled exception in thread: 'MainThread'
ERROR 2016-07-13 08:26:41,098 excepthooks 9204 139997723657984 Traceback (most recent call last):
  File "/home/mdm/ilastik-1.2.0rc5-Linux/ilastik-meta/volumina/volumina/layerstack.py", line 270, in data
    return self._layerStack[index.row()]
IndexError: list index out of range

ERROR 2016-07-13 08:26:41,098 excepthooks 9204 139997723657984 Unhandled exception in thread: 'MainThread'
ERROR 2016-07-13 08:26:41,099 excepthooks 9204 139997723657984 Traceback (most recent call last):
  File "/home/mdm/ilastik-1.2.0rc5-Linux/ilastik-meta/volumina/volumina/layerstack.py", line 270, in data
    return self._layerStack[index.row()]
IndexError: list index out of range

ERROR 2016-07-13 08:26:41,099 excepthooks 9204 139997723657984 Unhandled exception in thread: 'MainThread'
ERROR 2016-07-13 08:26:41,099 excepthooks 9204 139997723657984 Traceback (most recent call last):
  File "/home/mdm/ilastik-1.2.0rc5-Linux/ilastik-meta/volumina/volumina/layerstack.py", line 270, in data
    return self._layerStack[index.row()]
IndexError: list index out of range

ERROR 2016-07-13 08:26:41,102 excepthooks 9204 139997723657984 Unhandled exception in thread: 'MainThread'
ERROR 2016-07-13 08:26:41,102 excepthooks 9204 139997723657984 Traceback (most recent call last):
  File "/home/mdm/ilastik-1.2.0rc5-Linux/ilastik-meta/volumina/volumina/layerstack.py", line 270, in data
    return self._layerStack[index.row()]
IndexError: list index out of range

ERROR 2016-07-13 08:26:41,102 excepthooks 9204 139997723657984 Unhandled exception in thread: 'MainThread'
ERROR 2016-07-13 08:26:41,102 excepthooks 9204 139997723657984 Traceback (most recent call last):
  File "/home/mdm/ilastik-1.2.0rc5-Linux/ilastik-meta/volumina/volumina/layerstack.py", line 270, in data
    return self._layerStack[index.row()]
IndexError: list index out of range

ERROR 2016-07-13 08:26:41,102 excepthooks 9204 139997723657984 Unhandled exception in thread: 'MainThread'
ERROR 2016-07-13 08:26:41,102 excepthooks 9204 139997723657984 Traceback (most recent call last):
  File "/home/mdm/ilastik-1.2.0rc5-Linux/ilastik-meta/volumina/volumina/layerstack.py", line 270, in data
    return self._layerStack[index.row()]
IndexError: list index out of range

ERROR 2016-07-13 08:26:41,102 excepthooks 9204 139997723657984 Unhandled exception in thread: 'MainThread'
ERROR 2016-07-13 08:26:41,103 excepthooks 9204 139997723657984 Traceback (most recent call last):
  File "/home/mdm/ilastik-1.2.0rc5-Linux/ilastik-meta/volumina/volumina/layerstack.py", line 270, in data
    return self._layerStack[index.row()]
IndexError: list index out of range

**Comment by k-dominik** [comment]
can't reproduce this, it's most likely fixed (or a more involved click path than the one described).
