### ISSUE TITLE
Headless mode error 

### ISSUE THREAD

**Issue by Fritze** [ilastik/ilastik#1299]
When I try to run a test project with one image as input in headless mode I get this error message:

```pytb
INFO 2016-07-21 10:23:34,840 ilastik_main 902 140735118721024 Starting ilastik from "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release".
ERROR 2016-07-21 10:23:35,220 excepthooks 902 140735118721024 Unhandled exception in thread: 'MainThread'
ERROR 2016-07-21 10:23:35,223 excepthooks 902 140735118721024 Traceback (most recent call last):
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik.py", line 111, in <module>
    main()
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik.py", line 104, in main
    ilastik_main.main(parsed_args, workflow_cmdline_args)
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik_main.py", line 102, in main
    f(shell)
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik_main.py", line 317, in loadProject
    shell.openProjectFile(path, parsed_args.readonly)
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/shell/headless/headlessShell.py", line 84, in openProjectFile
    import ilastik.workflows
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/workflows/__init__.py", line 28, in <module>
    import pixelClassification
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/workflows/pixelClassification/__init__.py", line 21, in <module>
    from pixelClassificationWorkflow import PixelClassificationWorkflow
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/workflows/pixelClassification/pixelClassificationWorkflow.py", line 34, in <module>
    from ilastik.applets.pixelClassification import PixelClassificationApplet, PixelClassificationDataExportApplet
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/pixelClassification/__init__.py", line 21, in <module>
    from pixelClassificationApplet import *
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/pixelClassification/pixelClassificationApplet.py", line 22, in <module>
    from opPixelClassification import OpPixelClassification
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/pixelClassification/opPixelClassification.py", line 36, in <module>
    import ilastik_feature_selection
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/lib/python2.7/site-packages/ilastik_feature_selection/__init__.py", line 5, in <module>
    import filter_feature_selection
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/lib/python2.7/site-packages/ilastik_feature_selection/filter_feature_selection.py", line 3, in <module>
    from sklearn.metrics import mutual_info_score
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/lib/python2.7/site-packages/sklearn/__init__.py", line 56, in <module>
    from . import __check_build
ImportError: cannot import name __check_build
```
ideas?

**Comment by stuarteberg** [comment]
Thanks for the report.

Last week, @chaubold also ran into this issue with our OSX binary.  He determined that the root cause is due to an incorrect build of the `scipy` package that we're shipping.  I reported the issue here:

https://github.com/ContinuumIO/anaconda-issues/issues/899

Until that is fixed on Anaconda's servers, we'll need to downgrade to scipy 0.17.0.

**Comment by stuarteberg** [comment]
@Fritze: A temporary workaround (discovered by @chaubold), is to edit `ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/run_ilastik.sh` to replace this line:

```bash
export DYLD_FALLBACK_LIBRARY_PATH=""
```

with this line:

```bash
export DYLD_FALLBACK_LIBRARY_PATH=${PREFIX}/lib
```

**Comment by Fritze** [comment]
Thanks for the quick answer! I replaced the line, now the error changed to this one:
```

INFO 2016-07-21 11:43:45,138 ilastik_main 1122 140735118721024 Starting ilastik from "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release".
ERROR 2016-07-21 11:43:45,975 excepthooks 1122 140735118721024 Unhandled exception in thread: 'MainThread'
ERROR 2016-07-21 11:43:45,979 excepthooks 1122 140735118721024 Traceback (most recent call last):
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik.py", line 111, in <module>
    main()
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik.py", line 104, in main
    ilastik_main.main(parsed_args, workflow_cmdline_args)
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik_main.py", line 102, in main
    f(shell)
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik_main.py", line 317, in loadProject
    shell.openProjectFile(path, parsed_args.readonly)
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/shell/headless/headlessShell.py", line 84, in openProjectFile
    import ilastik.workflows
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/workflows/__init__.py", line 28, in <module>
    import pixelClassification
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/workflows/pixelClassification/__init__.py", line 21, in <module>
    from pixelClassificationWorkflow import PixelClassificationWorkflow
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/workflows/pixelClassification/pixelClassificationWorkflow.py", line 34, in <module>
    from ilastik.applets.pixelClassification import PixelClassificationApplet, PixelClassificationDataExportApplet
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/pixelClassification/__init__.py", line 21, in <module>
    from pixelClassificationApplet import *
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/pixelClassification/pixelClassificationApplet.py", line 22, in <module>
    from opPixelClassification import OpPixelClassification
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/pixelClassification/opPixelClassification.py", line 46, in <module>
    from PyQt4.QtCore import pyqtRemoveInputHook, pyqtRestoreInputHook
  File "/Applications/ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/headless_dummy_modules/PyQt4/__init__.py", line 9, in <module>
    raise Exception("Developer error: When ilastik is running in headless mode, you aren't allowed to import PyQt4.")
Exception: Developer error: When ilastik is running in headless mode, you aren't allowed to import PyQt4.


```

**Comment by stuarteberg** [comment]
Ouch.  Please remove the following line from `ilastik-1.2.0rc6-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/pixelClassification/opPixelClassification.py`.

```python
from PyQt4.QtCore import pyqtRemoveInputHook, pyqtRestoreInputHook
````

(That's line 46).

Sorry about that.  Our test suite is supposed to catch such bugs -- I don't know why it isn't failing on my own machine.

**Comment by Fritze** [comment]
Works perfectly thanks a lot!

**Comment by stuarteberg** [comment]
Good to hear; thanks for letting us know. I'm going to leave this issue open until we fix the scipy dependency in our build.

**Comment by stuarteberg** [comment]
@ Fritze: I've uploaded a new binary (rc7).  If you'd like to try it out and verify that this issue is resolved, I'd appreciate it.  Here's the link:
http://files.ilastik.org/ilastik-1.2.0rc7-OSX.app.zip

**Comment by Fritze** [comment]
Works nicely!
