### ISSUE TITLE
Conservation Tracking: Error when exporting .h5 and .csv files on headless mode

### ISSUE THREAD

**Issue by JaimeIvanCervantes** [ilastik/ilastik#1307]
Error when exporting `.h5` and `.csv` files on headless mode. The error might be related to the changes in the available and selected features on the conservation tracking workflow:

```
ERROR 2016-07-26 17:42:28,879 log_exception 11161 140430717273856 Project could not be loaded due to the exception shown above.
Aborting Project Open Action
ERROR 2016-07-26 17:42:29,651 excepthooks 11161 140430717273856 Unhandled exception in thread: 'MainThread'
ERROR 2016-07-26 17:42:29,654 excepthooks 11161 140430717273856 Traceback (most recent call last):
  File "/opt/local/miniconda/envs/ilastik-devel/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/local/miniconda/envs/ilastik-devel/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/local/miniconda/envs/ilastik-devel/lib/python2.7/cProfile.py", line 199, in <module>
    main()
  File "/opt/local/miniconda/envs/ilastik-devel/lib/python2.7/cProfile.py", line 192, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/opt/local/miniconda/envs/ilastik-devel/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/opt/local/miniconda/envs/ilastik-devel/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik.py", line 110, in <module>
    main()
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik.py", line 103, in main
    ilastik_main.main(parsed_args, workflow_cmdline_args)
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik_main.py", line 102, in main
    f(shell)
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik_main.py", line 283, in loadProject
    shell.openProjectFile(path, parsed_args.readonly)
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/shell/headless/headlessShell.py", line 112, in openProjectFile
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 142, in wrapper
    return func(*args, **kwargs)
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 443, in _loadProject
    self.workflow.onProjectLoaded( self )
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 427, in onProjectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 59, in run_export_from_parsed_args
    return self.run_export(role_path_dict, parsed_args.input_axes)
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 120, in run_export
    export_to_array=export_to_array )
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 236, in _run_export_with_empty_batch_lane
    self.dataExportApplet.post_process_lane_export(batch_lane_index)
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 390, in post_process_lane_export
    req.wait()
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 503, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 454, in do_export
    self._do_export_impl(settings, selected_features, progress_slot, object_feature_slot, label_image, lane_index, filename_suffix)
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/base/opTrackingBase.py", line 616, in _do_export_impl
    {"selection": selected_features})
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 270, in add_columns
    columns = flatten_ilastik_feature_table(col_data, extra["selection"], self.InsertionProgress)
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 61, in flatten_ilastik_feature_table
    computed_feature.update(request.wait())
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/opt/local/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opRelabeledMergerFeatureExtraction.py", line 197, in execute
    result[t][name][k] = self._merge_features(result[t][name][k], v, mapping[t])
KeyError: 'Coord<Principal<Kurtosis>>'

```

**Comment by JaimeIvanCervantes** [comment]
I just realized that @chaubold stumbled upon this problem previously. Related to issue #975 and commit  de4b3d2.
