### ISSUE TITLE
Autocontext can not handle uint16 data

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1308]
Select features:

Can't provide a destination array of the wrong dtype.  Slot generates <type 'numpy.uint16'>, but you gave uint8

```pytb
ERROR 2016-07-27 14:55:19,797 excepthooks 5893 140000460158720 Unhandled exception in thread: 'TileProvider-140000460158720'
ERROR 2016-07-27 14:55:19,798 excepthooks 5893 140000460158720 Traceback (most recent call last):
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/volumina/volumina/tiling.py", line 90, in _render
    img = self.image_req.wait()
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 149, in wait
    return self.toImage()
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 155, in toImage
    self._arrayreq.wait()
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/volumina/volumina/pixelpipeline/slicesources.py", line 43, in wait
    return self._sp(self._ar.wait())
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 471, in wait
    rawData = self._rawRequest.wait()
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 229, in wait
    a = self._req.wait()
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/request/request.py", line 503, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/operators/opReorderAxes.py", line 131, in execute
    self.Input( *in_roi ).writeInto( result_input_view ).wait()
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/request/request.py", line 503, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/request/request.py", line 769, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/operators/generic.py", line 416, in execute
    pool.wait()
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1181, in wait
    self._clear_finishing_requests()
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1262, in _clear_finishing_requests
    req.block()
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/request/request.py", line 486, in block
    self._wait(timeout) # No return value. Use wait()
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/request/request.py", line 503, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/request/request.py", line 769, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/home/jales/software/miniconda/envs/learning/ilastik-meta/lazyflow/lazyflow/slot.py", line 836, in __call__
    "Slot generates {}, but you gave {}".format( self.slot.meta.dtype, destination.dtype )
AssertionError: Can't provide a destination array of the wrong dtype.  Slot generates <type 'numpy.uint16'>, but you gave uint8
```

**Comment by stuarteberg** [comment]
Ah, right, this error was discovered during the workshop, but I forgot to open an issue.  Thanks for opening this.

**Comment by stuarteberg** [comment]
After thinking about it for a bit, I'm declaring this item WONTFIX.  Instead, I added a `DatasetConstraintError` to tell the user not to load any non-`uint8` images.  (See 960345e.)

My justification:

The autocontext workflow is a big hog when it comes to RAM.  To use as little RAM as possible, all predictions from stages 0..N-1 are converted to uint8 before they are used during classification in stages 1..N, respectively.  But we also append the raw data to the input for each stage, which means it needs to be converted to uint8, too.  There is no easy way to guess how the user wants to normalize her data from uint16 (or float32, etc.) into uint8.  Therefore, it's easier just to tell her to convert it separately before she loads it into ilastik.
