### ISSUE TITLE
"Suggest features" error

### ISSUE THREAD

**Issue by dlogan** [ilastik/ilastik#1315]
A single RGB .png input image using OSX build 1.2.0rc7, then trained and tried the new "Suggest features" (cool!).  It returned without error when I chose 7 features, but then with 0 (auto) features it errored.  ilastik_log.txt tail below:

```
...
INFO 2016-08-02 09:54:05,499 filter_feature_selection 20303 140735091453952 Best feature found was 2 with J_eval= -38.157497. Feature set was [5, 18, 145, 56, 52, 132, 54, 118, 44, 53, 51, 36, 112, 42, 128, 110, 47, 55, 103, 116, 48, 126, 109, 136, 41, 114, 98, 49, 45, 124, 50, 105, 139, 77, 76, 99, 104, 91, 146, 79, 120, 107, 95, 80, 96, 81, 97, 92, 85, 72, 130, 101, 78, 122, 87, 40, 86, 94, 75, 134, 143, 39, 90, 138, 83, 102, 59, 84, 93, 89, 108, 22, 140, 46, 82, 100, 21, 142, 88, 23, 106, 43, 57, 135, 115, 144, 58, 38, 137, 111, 113, 74, 26, 133, 141, 37, 62, 65, 24, 73, 69, 27, 61, 121, 33, 19, 28, 123, 15, 60, 29, 127, 12, 64, 71, 63, 129, 20, 119, 35, 30, 125, 66, 3, 32, 17, 131, 25, 70, 68, 117, 9, 34, 16, 6, 13, 31, 14, 67, 10, 0, 7, 4, 1, 11, 8]
INFO 2016-08-02 09:54:05,500 filter_feature_selection 20303 140735091453952 Filter feature selection done. Final set is: [5, 18, 145, 56, 52, 132, 54, 118, 44, 53, 51, 36, 112, 42, 128, 110, 47, 55, 103, 116, 48, 126, 109, 136, 41, 114, 98, 49, 45, 124, 50, 105, 139, 77, 76, 99, 104, 91, 146, 79, 120, 107, 95, 80, 96, 81, 97, 92, 85, 72, 130, 101, 78, 122, 87, 40, 86, 94, 75, 134, 143, 39, 90, 138, 83, 102, 59, 84, 93, 89, 108, 22, 140, 46, 82, 100, 21, 142, 88, 23, 106, 43, 57, 135, 115, 144, 58, 38, 137, 111, 113, 74, 26, 133, 141, 37, 62, 65, 24, 73, 69, 27, 61, 121, 33, 19, 28, 123, 15, 60, 29, 127, 12, 64, 71, 63, 129, 20, 119, 35, 30, 125, 66, 3, 32, 17, 131, 25, 70, 68, 117, 9, 34, 16, 6, 13, 31, 14, 67, 10, 0, 7, 4, 1, 11, 8, 2]
INFO 2016-08-02 09:54:50,489 parallelVigraRfLazyflowClassifier 20303 123145314013184 Training took, 0.128139 seconds
INFO 2016-08-02 09:54:50,490 parallelVigraRfLazyflowClassifier 20303 123145314013184 Training complete. Average OOB: 0.000904704463209
INFO 2016-08-02 09:54:55,894 parallelVigraRfLazyflowClassifier 20303 140735091453952 Training took, 0.081968 seconds
INFO 2016-08-02 09:54:55,894 parallelVigraRfLazyflowClassifier 20303 140735091453952 Training complete. Average OOB: 0.000904704463209
ERROR 2016-08-02 09:54:56,439 excepthooks 20303 140735091453952 Unhandled exception in thread: 'MainThread'
ERROR 2016-08-02 09:54:56,441 excepthooks 20303 140735091453952 Traceback (most recent call last):
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/pixelClassification/FeatureSelectionDialog.py", line 858, in _run_selection
    feature_calc_time=new_time)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/pixelClassification/FeatureSelectionDialog.py", line 37, in __init__
    self.name = self._create_name()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/pixelClassification/FeatureSelectionDialog.py", line 47, in _create_name
    name = "%%d features(auto), %s selection" % ( numpy.sum(self.feature_matrix), self.selection_method)
TypeError: not all arguments converted during string formatting
```

**Comment by akreshuk** [comment]
Thanks for the report! I fixed the first problem, but can't reproduce the second one. Is it still with a single RGB .png? No time, not stacking?

**Comment by k-dominik** [comment]
another one that hasn't resurfaced in years. I consider this closed. Please reopen if you run into this again.
