### ISSUE TITLE
too many indices for array error

### ISSUE THREAD

**Issue by Fritze** [ilastik/ilastik#1320]
After having added more images to my pixel + object classification workflow, I get now an error message stating "too many indices for array" whenever I check the Live Update box in the object classification mode. I use ilastik-1.2.0rc7-OSX.

Log file:
`
ERROR 2016-08-12 11:15:00,241 excepthooks 4168 123145322962944 Traceback (most recent call last):
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/tiling.py", line 768, in _fetch_tile_layer
    img = ims_req.wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 263, in wait
    return self.toImage()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 269, in toImage
    self._arrayreq.wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/slicesources.py", line 43, in wait
    return self._sp(self._ar.wait())
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 464, in wait
    rawData = self._rawRequest.wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 201, in wrapper
    return func(*args, **kwargs)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 225, in wait
    a = self._req.wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opReorderAxes.py", line 143, in execute
    self.Input( *in_roi ).writeInto( result_input_view ).wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 769, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opSlicedBlockedArrayCache.py", line 180, in execute
    op.outputs["Output"][key].writeInto(result).wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 769, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opBlockedArrayCache.py", line 104, in execute
    self._opSimpleBlockedArrayCache.Output(roi.start, roi.stop).writeInto(result).wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 769, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 81, in execute
    self._execute_Output(slot, subindex, roi, result)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opSimpleBlockedArrayCache.py", line 84, in _execute_Output
    pool.wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1181, in wait
    self._clear_finishing_requests()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1262, in _clear_finishing_requests
    req.block()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 486, in block
    self._wait(timeout) # No return value. Use wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opSimpleBlockedArrayCache.py", line 60, in copy_block
    self._execute_Output_impl( clipped_block_roi, result[roiToSlice(*output_roi)] )
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 106, in _execute_Output_impl
    self._fetch_and_store_block(request_roi, out=result)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 144, in _fetch_and_store_block
    block_data = req.wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 769, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opCacheFixer.py", line 63, in execute
    self.Input(roi.start, roi.stop).writeInto(result).wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 769, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1285, in execute
    map_ = self.ObjectMap([t]).wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1538, in execute
    return self.operator.execute(self, totalIndex, roi, result)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1104, in execute
    classifier = self.Classifier.value
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1067, in value
    temp = self[:].wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/valueProviders.py", line 296, in execute
    value = request.wait()[0]
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 988, in execute
    pool.wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1174, in wait
    self.submit()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1213, in submit
    self._clear_finishing_requests()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1262, in _clear_finishing_requests
    req.block()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 486, in block
    self._wait(timeout) # No return value. Use wait()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 965, in fetch_features
    featstmp, row_names, col_names, labelstmp = make_feature_array(feats, selected, labels_image_filtered)
  File "/Applications/ilastik-1.2.0rc7-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 856, in make_feature_array
    ft = ft[index]
IndexError: too many indices for array
`

**Comment by stuarteberg** [comment]
I would like to reproduce this issue somehow. Would it be possible for you to share the project file and data with us?  If so, email it to team@ilastik.org
