### ISSUE TITLE
Exception ('NoneType') in Tracking workflow

### ISSUE THREAD

**Issue by imagejan** [ilastik/ilastik#1325]
When loading the example project `conservationTracking.ilp` from the [Drosophila 3D+t](http://data.ilastik.org/drosophila.zip) dataset and then clicking the **Track!** button, I get the following error message:

![ilastiktrackingexception-1](https://cloud.githubusercontent.com/assets/2033938/17886575/beb7d414-6922-11e6-9e1e-ab292046504d.png)

This is the stack trace (tested with ilastik-1.2.0rc10 on Windows 7):

```
ERROR 2016-08-23 11:10:49,908 log_exception 5400 6256 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\tracking\conservation\conservationTrackingGui.py", line 263, in _track
    solverName=solver
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\tracking\conservation\opConservationTracking.py", line 220, in track
    if not self.DetectionProbabilities.ready() or len(self.DetectionProbabilities([0]).wait()[0]) == 0:
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 480, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 305, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\objectClassification\opObjectClassification.py", line 1127, in execute
    tmpfeats = self.Features(times_not_cached).wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 480, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 305, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\objectExtraction\opObjectExtraction.py", line 214, in execute
    val = self.Input(start, stop).wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 480, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 305, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\operators\opArrayCache.py", line 355, in execute
    return self._executeOutput(slot, subindex, roi, result)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\operators\opArrayCache.py", line 469, in _executeOutput
    dirtyPool.wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1181, in wait
    self._clear_finishing_requests()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1262, in _clear_finishing_requests
    req.block()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 486, in block
    self._wait(timeout) # No return value. Use wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 305, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 769, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\objectExtraction\opObjectExtraction.py", line 585, in execute
    pool.wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1181, in wait
    self._clear_finishing_requests()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1262, in _clear_finishing_requests
    req.block()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 486, in block
    self._wait(timeout) # No return value. Use wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 305, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\objectExtraction\opObjectExtraction.py", line 575, in compute_features_for_time_slice
    acc = self._extract(rawVolume, labelVolume)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\objectExtraction\opObjectExtraction.py", line 655, in _extract
    global_features[plugin_name] = plugin.plugin_object.compute_global(image, labels, feature_dict, axes)
AttributeError: 'NoneType' object has no attribute 'plugin_object'
```

**Comment by imagejan** [comment]
Maybe that's related: when going back to the _Division Detection (optional)_ tab, I get the following exception:
```
ERROR 2016-08-23 11:20:16,839 excepthooks 5400 6420 Unhandled exception in thread: 'MainThread'
ERROR 2016-08-23 11:20:16,842 excepthooks 5400 6420 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 936, in handleAppletBarItemExpanded
    self.setSelectedAppletDrawer(drawerIndex)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 957, in setSelectedAppletDrawer
    self.showCentralWidget(applet_index)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 972, in showCentralWidget
    centralWidget = self._applets[applet_index].getMultiLaneGui().centralWidget()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\base\singleToMultiGuiAdapter.py", line 64, in centralWidget
    if self.currentGui() is None:
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\base\singleToMultiGuiAdapter.py", line 44, in currentGui
    self._guis[self._imageLaneIndex] = self.singleImageGuiFactory( self._imageLaneIndex )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\base\standardApplet.py", line 142, in __createSingleLaneGui
    return self.singleLaneGuiClass( self, singleLaneOperator )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\layerViewer\layerViewerGui.py", line 67, in __call__
    instance = super(LayerViewerGuiMetaclass, cls).__call__(*args,**kwargs)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\objectClassification\objectClassificationGui.py", line 174, in __init__
    cfn = self.op.ComputedFeatureNames[:].wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 480, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 503, in _wait
    self._wait_within_foreign_thread( timeout )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 305, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\trackingFeatureExtraction\opTrackingFeatureExtraction.py", line 218, in execute
    assert plugin_name not in feat_names_div, "feature name dictionaries must be mutually exclusive"
AssertionError: feature name dictionaries must be mutually exclusive
```

**Comment by chaubold** [comment]
I think yes, they are related. We have added more features recently, and some of them were renamed. 

**TODO** for us:
* [ ] update the example project files
* [ ] make the new ilastik backward compatible -> update list of selected features appropriately
