### ISSUE TITLE
example tracking projects don't work

### ISSUE THREAD

**Issue by svenpeter42** [ilastik/ilastik#1340]
loading any of the two projects and clicking on "Track" results in the following error message on the consoles:

```
INFO 2016-09-08 16:22:54,071 ilastik_main 24618 140239416751872 Starting ilastik from "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux".
WARNING 2016-09-08 16:22:54,510 httplib 24618 140239416751872 httplib.py(1179): ImportWarning: Not importing directory '/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ssl': missing __init__.py
INFO 2016-09-08 16:22:55,607 opThresholdTwoLevels 24618 140239416751872 Using 'vigra' labeling implemetation
INFO 2016-09-08 16:22:57,790 projectManager 24618 140239416751872 Opening Project: /home/speter/ilastik_demo/drosophila_3d+t/conservationTracking.ilp
WARNING 2016-09-08 16:22:58,964 slot 24618 140239416751872 slot.py(1087): UserWarning: FIXME: Slot.value for slot FeatureNamesVigra is {'2D Skeleton Features': {'Skeleton Center': {}, 'Diameter': {}, 'Total Length': {}, 'Euclidean Diameter': {}, 'Terminal 1': {}, 'Hole Count': {}, 'Average Length': {}, 'Branch Count': {}, 'Terminal 2': {}}, 'Standard Object Features': {'Count': {}, 'Skewness in neighborhood': {}, 'Skewness': {}, 'Variance in neighborhood': {}, 'Kurtosis in neighborhood': {}, 'Minimum in neighborhood': {}, 'Mean in neighborhood': {}, 'Sum': {}, 'Maximum': {}, 'RegionCenter': {}, 'RegionAxes': {}, 'RegionRadii': {}, 'Maximum in neighborhood': {}, 'Minimum': {}, 'Sum in neighborhood': {}, 'Variance': {}, 'Coord<Minimum>': {}, 'Mean': {}, 'Kurtosis': {}, 'Coord<Maximum>': {}}, '2D Convex Hull Features': {'Perimeter': {}, 'Defect Area Kurtosis': {}, 'Defect Area Variance': {}, 'Area': {}, 'Defect Count': {}, 'Defect Mean Displacement': {}, 'Input Perimeter': {}, 'Defect Area Mean': {}, 'Defect Area List': {}, 'Defect Area Skewness': {}, 'Rugosity': {}, 'Hull Center': {}, 'Input Center': {}, 'Input Count': {}, 'Convexity': {}, 'Input Area': {}}}, which should be wrapped in an ndarray.
WARNING 2016-09-08 16:22:58,992 arraytypes 24618 140239416751872 arraytypes.py(1263): VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
WARNING 2016-09-08 16:23:06,112 dataset 24618 140239416751872 dataset.py(76): DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
WARNING 2016-09-08 16:23:06,372 slot 24618 140239416751872 slot.py(1160): DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
WARNING 2016-09-08 16:23:09,012 tiling 24618 140239416751872 tiling.py(351): UserWarning: FIXME: This is a slow way to look for the items we want.
_TilesCache._layerCache should be a dict-of-dict-of-dict for faster lookup!
ERROR 2016-09-08 16:23:10,872 log_exception 24618 140238705514240 Traceback (most recent call last):
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/conservationTrackingGui.py", line 263, in _track
    solverName=solver
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 220, in track
    if not self.DetectionProbabilities.ready() or len(self.DetectionProbabilities([0]).wait()[0]) == 0:
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1127, in execute
    tmpfeats = self.Features(times_not_cached).wait()
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/ilastik/ilastik/applets/objectExtraction/opObjectExtraction.py", line 214, in execute
    val = self.Input(start, stop).wait()
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/operators/opArrayCache.py", line 355, in execute
    return self._executeOutput(slot, subindex, roi, result)
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/operators/opArrayCache.py", line 469, in _executeOutput
    dirtyPool.wait()
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1181, in wait
    self._clear_finishing_requests()
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1262, in _clear_finishing_requests
    req.block()
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 486, in block
    self._wait(timeout) # No return value. Use wait()
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 769, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/ilastik/ilastik/applets/objectExtraction/opObjectExtraction.py", line 585, in execute
    pool.wait()
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1181, in wait
    self._clear_finishing_requests()
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1262, in _clear_finishing_requests
    req.block()
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 486, in block
    self._wait(timeout) # No return value. Use wait()
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/ilastik/ilastik/applets/objectExtraction/opObjectExtraction.py", line 575, in compute_features_for_time_slice
    acc = self._extract(rawVolume, labelVolume)
  File "/home/speter/ilastik_demo/ilastik-1.2.0rc10-Linux/ilastik-meta/ilastik/ilastik/applets/objectExtraction/opObjectExtraction.py", line 655, in _extract
    global_features[plugin_name] = plugin.plugin_object.compute_global(image, labels, feature_dict, axes)
AttributeError: 'NoneType' object has no attribute 'plugin_object'

ERROR 2016-09-08 16:23:10,873 log_exception 24618 140238705514240 Error during tracking.  See above error traceback.

```

**Comment by imagejan** [comment]
See also https://github.com/ilastik/ilastik/issues/1325.

**Comment by JaimeIvanCervantes** [comment]
The problem seem to be related to the object features and this might have changed when we added the new convexity and skeleton features. We will look into this, and make sure that Ilastik is backward compatible with the old tracking projects.

**Comment by chaubold** [comment]
Still not fixed...

**Comment by k-dominik** [comment]
fixed in #1872
