### ISSUE TITLE
hytra-integration for tracking: Right-click in result view raises error

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1373]
Using the current code in #1363, when one right clicks on an object in the tracking result view, the following error pops up. It looks to me like the state of the mergerResolver is not preserved.
Before, we could investigate object, track and lineage IDs, and I believe this did work already in the `Hytra-Integration` branch.

This error does **not** show up in frames or datasets without mergers.

```
ERROR 2016-11-18 14:00:55,079 excepthooks 3656 140736010675136 Unhandled exception in thread: 'MainThread'
ERROR 2016-11-18 14:00:55,079 excepthooks 3656 140736010675136 Traceback (most recent call last):
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/ilastik/ilastik/applets/layerViewer/layerViewerGui.py", line 651, in _handleEditorRightClick
    self.handleEditorRightClick(dataPosition, globalWindowCoordinate)
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/conservationTrackingGui.py", line 344, in handleEditorRightClick
    obj, time = self.get_object(position5d)
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/conservationTrackingGui.py", line 331, in get_object
    label = self.mainOperator.RelabeledImage(slicing).wait()
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/lazyflow/lazyflow/request/request.py", line 503, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 216, in execute
    self.mergerResolver.relabelMergers(result[t-roi.start[0],...,0], t)
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/lib/python2.7/site-packages/hytra/core/mergerresolver.py", line 502, in relabelMergers
    self.mergerResolverPlugin.updateLabelImage(labelImage, idx, fits, newIds)
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/lib/python2.7/site-packages/hytra/plugins/merger_resolver/gmm_merger_resolver.py", line 77, in updateLabelImage
    responsibilities = gmm.predict(coordinates)
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/lib/python2.7/site-packages/sklearn/mixture/gmm.py", line 364, in predict
    logprob, responsibilities = self.score_samples(X)
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/lib/python2.7/site-packages/sklearn/mixture/gmm.py", line 321, in score_samples
    X = check_array(X)
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/lib/python2.7/site-packages/sklearn/utils/validation.py", line 407, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required.
```

**Comment by JaimeIvanCervantes** [comment]
See 94e661645d72e0ced6ca9795176fb58e3808b7fe and https://github.com/chaubold/hytra/commit/fdd87d284d14fc2ae60161e12399d28b485a2947 on HyTra.
