### ISSUE TITLE
Object Classification on Tracking Workflow is Crashing (Detection Classifier)

### ISSUE THREAD

**Issue by JaimeIvanCervantes** [ilastik/ilastik#1380]
The object classification operator, used to classify detections, is crashing when I try to preview the count predictions. This seem to be happening only on tracking, since I didn't get the error on the object classification workflow. Here's the log:

```pytb
ERROR 2016-12-05 11:55:13,637 excepthooks 17457 140337452414720 Traceback (most recent call last):
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/volumina/volumina/tiling.py", line 768, in _fetch_tile_layer
    img = ims_req.wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 266, in wait
    return self.toImage()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 272, in toImage
    self._arrayreq.wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/volumina/volumina/pixelpipeline/slicesources.py", line 43, in wait
    return self._sp(self._ar.wait())
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 464, in wait
    rawData = self._rawRequest.wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 201, in wrapper
    return func(*args, **kwargs)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 225, in wait
    a = self._req.wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 481, in wait
    return self._wait(timeout)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/operators/opReorderAxes.py", line 143, in execute
    self.Input( *in_roi ).writeInto( result_input_view ).wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 481, in wait
    return self._wait(timeout)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 770, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/operators/opSlicedBlockedArrayCache.py", line 180, in execute
    op.outputs["Output"][key].writeInto(result).wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 481, in wait
    return self._wait(timeout)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 770, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/operators/opBlockedArrayCache.py", line 104, in execute
    self._opSimpleBlockedArrayCache.Output(roi.start, roi.stop).writeInto(result).wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 481, in wait
    return self._wait(timeout)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 770, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 82, in execute
    self._execute_Output(slot, subindex, roi, result)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/operators/opSimpleBlockedArrayCache.py", line 84, in _execute_Output
    pool.wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1289, in wait
    self._clear_finishing_requests()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1366, in _clear_finishing_requests
    req.block()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 487, in block
    self._wait(timeout) # No return value. Use wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/operators/opSimpleBlockedArrayCache.py", line 60, in copy_block
    self._execute_Output_impl( clipped_block_roi, result[roiToSlice(*output_roi)] )
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 107, in _execute_Output_impl
    self._fetch_and_store_block(request_roi, out=result)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 145, in _fetch_and_store_block
    block_data = req.wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 481, in wait
    return self._wait(timeout)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 770, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/operators/opCacheFixer.py", line 63, in execute
    self.Input(roi.start, roi.stop).writeInto(result).wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 481, in wait
    return self._wait(timeout)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 770, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1303, in execute
    map_ = self.ObjectMap([t]).wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 481, in wait
    return self._wait(timeout)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 1542, in execute
    return self.operator.execute(self, totalIndex, roi, result)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1122, in execute
    classifier = self.Classifier.value
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 1071, in value
    temp = self[:].wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 481, in wait
    return self._wait(timeout)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/operators/valueProviders.py", line 297, in execute
    value = request.wait()[0]
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 481, in wait
    return self._wait(timeout)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1006, in execute
    pool.wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1289, in wait
    self._clear_finishing_requests()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1366, in _clear_finishing_requests
    req.block()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 487, in block
    self._wait(timeout) # No return value. Use wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 983, in fetch_features
    featstmp, row_names, col_names, labelstmp = make_feature_array(feats, selected, labels_image_filtered)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 895, in make_feature_array
    assert labelsMatrix.shape[0] == featMatrix.shape[0]
AssertionError
```

**Comment by akreshuk** [comment]
Are you opening an existing project or starting from scratch?

**Comment by JaimeIvanCervantes** [comment]
@akreshuk I'm starting from scratch. I was testing the division classifier right now, and I get the following error:

```
ERROR 2016-12-05 13:19:48,995 excepthooks 25643 140388421359360 Unhandled exception in thread: 'MainThread'
ERROR 2016-12-05 13:19:49,000 excepthooks 25643 140388421359360 Traceback (most recent call last):
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/volumina/volumina/eventswitch.py", line 95, in eventFilter
    return self._interpreter.eventFilter(watched.parent(), event)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/volumina/volumina/interpreter.py", line 107, in eventFilter
    self._onClick(self._layer, tuple(pos), event.pos())
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/objectClassification/objectClassificationGui.py", line 720, in onClick
    self.topLevelOperatorView.assignObjectLabel(imageIndex, pos5d, label)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 443, in assignObjectLabel
    labelslot.setDirty([(timeCoord, objIndex)])
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 940, in setDirty
    c.setDirty(roi)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 940, in setDirty
    c.setDirty(roi)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 946, in setDirty
    self.operator.propagateDirty(self, (), roi)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1354, in propagateDirty
    feats = self.Features(ts).wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 481, in wait
    return self._wait(timeout)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 504, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/trackingFeatureExtraction/opTrackingFeatureExtraction.py", line 231, in execute
    feat_div = self.RegionFeaturesDivision(roi).wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 481, in wait
    return self._wait(timeout)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 504, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/objectExtraction/opObjectExtraction.py", line 217, in execute
    val = self.Input(start, stop).wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 481, in wait
    return self._wait(timeout)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 504, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/operators/opArrayCache.py", line 356, in execute
    return self._executeOutput(slot, subindex, roi, result)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/operators/opArrayCache.py", line 489, in _executeOutput
    req.wait()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 481, in wait
    return self._wait(timeout)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 504, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/request/request.py", line 770, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/trackingFeatureExtraction/opTrackingFeatureExtraction.py", line 91, in execute
    res = self.featureManager.computeFeatures_at(feats_cur, feats_next, img_next, divisionFeatNames)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/trackingFeatureExtraction/trackingFeatures.py", line 213, in computeFeatures_at
    feat_dim = len(feats_cur[name_split[1]][0])
KeyError: 'RegionCenter'
```
