### ISSUE TITLE
Conservation tracking Parameters is empty when projects are loaded for the first time

### ISSUE THREAD

**Issue by JaimeIvanCervantes** [ilastik/ilastik#1384]
`Parameters` dict is empty when the project is loaded for the first time, which becomes apparent when the user tries to export data from the `Tracking Result Export` applet without running tracking first. Here's the log:

```pytb
ERROR 2016-12-06 17:45:02,757 log_exception 2904 140574011160320 Traceback (most recent call last):
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/dataExport/dataExportGui.py", line 386, in exportSlots
    self.parentApplet.prepare_lane_for_export(lane_index)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 329, in prepare_lane_for_export
    size_range = parameters['size_range'],
KeyError: 'size_range'

ERROR 2016-12-06 17:45:02,758 log_exception 2904 140574011160320 Failed to generate export file: 
/groups/branson/home/cervantesj/workspace/trackingTests/unitTest/smallVideo_Object-Identities.h5/exported_data
'size_range'
```

**Comment by akreshuk** [comment]
I believe @ilastikdev has also been having problems with serialization of this slot in tracking with learning.

**Comment by ilastikdev** [comment]
this is not an issue of serialization, it is an issue of design - check the comments in the track method code of opConservationTracking - the code does what the comments says - it is assumed track method populates Parameters slot

however, parameters slot should be populated from gui, if there is one, or else form default values (without the need to run tracking first)

(my issue was that Parameters did not serialize properly because it was not broadcasted, this is solved)

**Comment by Ian-Brettell** [comment]
Hi, 

I'm trying to use Ilastik-1.3.2 to process a batch of videos in `--headless` mode, following the animal tracking workflow described here: [https://www.ilastik.org/documentation/animaltracking/animaltracking](url), but I'm getting an error message similar to the one above.

Here's an example command:
`/nfs/software/birney/ilastik-1.3.2post1-Linux/run_ilastik.sh --headless \
        --project=video_analysis/pilot/train/track_clean.ilp \
        --raw_data=video_analysis/pilot/train/divided/20190611_1331_icab_icab_R_no_q3.h5 \
        --prediction_maps=video_analysis/pilot/train/divided/20190611_1331_icab_icab_R_no_q3_Probabilities.h5 \
        --export_source="Plugin" \
        --export_plugin="CSV-Table"`

And here's the full error message:
`Warning: Ignoring your non-empty LD_LIBRARY_PATH
Warning: Ignoring your non-empty QT_PLUGIN_PATH
INFO lazyflow.operators.filterOperators: Using fast filters.
WARNING __init__.py(11): UserWarning: init: Could not import tiktorch classifier
INFO ilastik_main: Starting ilastik from "/nfs/software/birney/ilastik-1.3.2post1-Linux".
Starting ilastik from "/nfs/software/birney/ilastik-1.3.2post1-Linux".
WARNING 2019-06-25 19:45:29,686 opConservationTracking 21585 47743684574848 Could not find any ILP solver
WARNING 2019-06-25 19:45:29,747 opStructuredTracking 21585 47743684574848 Could not find any ILP solver
WARNING 2019-06-25 19:45:29,751 structuredTrackingWorkflow 21585 47743684574848 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
INFO ilastik.shell.projectManager: Opening Project: video_analysis/pilot/train/track_clean.ilp
WARNING stype.py(181): UserWarning: ArrayLike.isCompatible: FIXME here
WARNING 2019-06-25 19:45:32,490 conservationTrackingWorkflow 21585 47743684574848 Unused command-line args: ['--export_source=Plugin', '--export_plugin=CSV-Table']
INFO ilastik.workflows.tracking.conservation.conservationTrackingWorkflow: Beginning Batch Processing
ERROR 2019-06-25 19:51:26,664 log_exception 21585 47743684574848 Traceback (most recent call last):
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 441, in _loadProject
    self.workflow.onProjectLoaded( self )
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 402, in onProjectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 66, in run_export_from_parsed_args
    return self.run_export(role_path_dict, parsed_args.input_axes, sequence_axis=parsed_args.stack_along)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 131, in run_export
    export_to_array=export_to_array)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 252, in _run_export_with_empty_batch_lane
    self.dataExportApplet.prepare_lane_for_export(batch_lane_index)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 334, in prepare_lane_for_export
    size_range = parameters['size_range'],
KeyError: 'size_range'

ERROR 2019-06-25 19:51:26,665 log_exception 21585 47743684574848 Project could not be loaded due to the exception shown above.
Aborting Project Open Action
ERROR 2019-06-25 19:51:28,921 excepthooks 21585 47743684574848 Unhandled exception in thread: 'MainThread'
ERROR 2019-06-25 19:51:28,935 excepthooks 21585 47743684574848 Traceback (most recent call last):
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik.py", line 123, in <module>
    main()
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik.py", line 108, in main
    hShell = ilastik_main.main(parsed_args, workflow_cmdline_args)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik_main.py", line 138, in main
    f(shell)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik_main.py", line 373, in loadProject
    shell.openProjectFile(path, parsed_args.readonly)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/shell/headless/headlessShell.py", line 117, in openProjectFile
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 146, in wrapper
    return func(*args, **kwargs)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 441, in _loadProject
    self.workflow.onProjectLoaded( self )
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 402, in onProjectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 66, in run_export_from_parsed_args
    return self.run_export(role_path_dict, parsed_args.input_axes, sequence_axis=parsed_args.stack_along)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 131, in run_export
    export_to_array=export_to_array)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 252, in _run_export_with_empty_batch_lane
    self.dataExportApplet.prepare_lane_for_export(batch_lane_index)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 334, in prepare_lane_for_export
    size_range = parameters['size_range'],
KeyError: 'size_range'`

The `Batch processing` applet in the GUI works fine for the same project and file, but I want to send the jobs to a cluster to process in parallel.

I'd be very grateful for any guidance.

Cheers,

Ian

**Comment by k-dominik** [comment]
Hi @Ian-Brettell,

thanks for already conveniently locating a relevant past issue to add your comment. I quickly tried to reproduce the problem but couldn't. Do you know the ilastik version the project was created with?

Cheers
Dominik

**Comment by Ian-Brettell** [comment]
> Hi,
> 
> I'm trying to use Ilastik-1.3.2 to process a batch of videos in `--headless` mode, following the animal tracking workflow described here: [https://www.ilastik.org/documentation/animaltracking/animaltracking](url), but I'm getting an error message similar to the one above.
> 
> Here's an example command:
> 
> ```
> /nfs/software/birney/ilastik-1.3.2post1-Linux/run_ilastik.sh --headless \
>         --project=video_analysis/pilot/train/track_clean.ilp \
>         --raw_data=video_analysis/pilot/train/divided/20190611_1331_icab_icab_R_no_q3.h5 \
>         --prediction_maps=video_analysis/pilot/train/divided/20190611_1331_icab_icab_R_no_q3_Probabilities.h5 \
>         --export_source="Plugin" \
>         --export_plugin="CSV-Table"
> ```
> 
> And here's the full error message:
> 
> ```
> Warning: Ignoring your non-empty LD_LIBRARY_PATH
> Warning: Ignoring your non-empty QT_PLUGIN_PATH
> INFO lazyflow.operators.filterOperators: Using fast filters.
> WARNING __init__.py(11): UserWarning: init: Could not import tiktorch classifier
> INFO ilastik_main: Starting ilastik from "/nfs/software/birney/ilastik-1.3.2post1-Linux".
> Starting ilastik from "/nfs/software/birney/ilastik-1.3.2post1-Linux".
> WARNING 2019-06-25 19:45:29,686 opConservationTracking 21585 47743684574848 Could not find any ILP solver
> WARNING 2019-06-25 19:45:29,747 opStructuredTracking 21585 47743684574848 Could not find any ILP solver
> WARNING 2019-06-25 19:45:29,751 structuredTrackingWorkflow 21585 47743684574848 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
> INFO ilastik.shell.projectManager: Opening Project: video_analysis/pilot/train/track_clean.ilp
> WARNING stype.py(181): UserWarning: ArrayLike.isCompatible: FIXME here
> WARNING 2019-06-25 19:45:32,490 conservationTrackingWorkflow 21585 47743684574848 Unused command-line args: ['--export_source=Plugin', '--export_plugin=CSV-Table']
> INFO ilastik.workflows.tracking.conservation.conservationTrackingWorkflow: Beginning Batch Processing
> ERROR 2019-06-25 19:51:26,664 log_exception 21585 47743684574848 Traceback (most recent call last):
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 441, in _loadProject
>     self.workflow.onProjectLoaded( self )
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 402, in onProjectLoaded
>     self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 66, in run_export_from_parsed_args
>     return self.run_export(role_path_dict, parsed_args.input_axes, sequence_axis=parsed_args.stack_along)
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 131, in run_export
>     export_to_array=export_to_array)
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 252, in _run_export_with_empty_batch_lane
>     self.dataExportApplet.prepare_lane_for_export(batch_lane_index)
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 334, in prepare_lane_for_export
>     size_range = parameters['size_range'],
> KeyError: 'size_range'
> 
> ERROR 2019-06-25 19:51:26,665 log_exception 21585 47743684574848 Project could not be loaded due to the exception shown above.
> Aborting Project Open Action
> ERROR 2019-06-25 19:51:28,921 excepthooks 21585 47743684574848 Unhandled exception in thread: 'MainThread'
> ERROR 2019-06-25 19:51:28,935 excepthooks 21585 47743684574848 Traceback (most recent call last):
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik.py", line 123, in <module>
>     main()
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik.py", line 108, in main
>     hShell = ilastik_main.main(parsed_args, workflow_cmdline_args)
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik_main.py", line 138, in main
>     f(shell)
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik_main.py", line 373, in loadProject
>     shell.openProjectFile(path, parsed_args.readonly)
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/shell/headless/headlessShell.py", line 117, in openProjectFile
>     self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 146, in wrapper
>     return func(*args, **kwargs)
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 441, in _loadProject
>     self.workflow.onProjectLoaded( self )
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 402, in onProjectLoaded
>     self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 66, in run_export_from_parsed_args
>     return self.run_export(role_path_dict, parsed_args.input_axes, sequence_axis=parsed_args.stack_along)
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 131, in run_export
>     export_to_array=export_to_array)
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 252, in _run_export_with_empty_batch_lane
>     self.dataExportApplet.prepare_lane_for_export(batch_lane_index)
>   File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 334, in prepare_lane_for_export
>     size_range = parameters['size_range'],
> KeyError: 'size_range'
> ```
> 
> Also note that it's not recognising the `--export_source="Plugin"` or `--export_plugin="CSV-Table"` arguments.
> 
> The `Batch processing` applet in the GUI works fine for the same project and file, but I want to send the jobs to a cluster to process in parallel.
> 
> I'd be very grateful for any guidance.
> 
> Cheers,
> 
> Ian

This was solved by saving the project _after_ it had done a tracking run on the GUI.

**Comment by Ian-Brettell** [comment]
> Hi @Ian-Brettell,
> 
> thanks for already conveniently locating a relevant past issue to add your comment. I quickly tried to reproduce the problem but couldn't. Do you know the ilastik version the project was created with?
> 
> Cheers
> Dominik

Hi Dominik, thanks for the prompt reply. FYI I had created the project on the same version: 1.3.2post1.

I'm also experiencing another problem with `--headless` mode where if I submit say 600 separate jobs to the cluster using the same project file, all fail except for around 60 to 70. The data files that the jobs operate successfully on are random – all complete eventually if I keep submitting them. Here's the error message from one of the failed jobs:

```
Warning: Ignoring your non-empty LD_LIBRARY_PATH
Warning: Ignoring your non-empty QT_PLUGIN_PATH
WARNING __init__.py(11): UserWarning: init: Could not import tiktorch classifier
WARNING 2019-06-25 21:13:37,556 opConservationTracking 58981 47332231947328 Could not find any ILP solver
WARNING 2019-06-25 21:13:37,579 opStructuredTracking 58981 47332231947328 Could not find any ILP solver
WARNING 2019-06-25 21:13:37,583 structuredTrackingWorkflow 58981 47332231947328 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
ERROR 2019-06-25 21:13:38,095 excepthooks 58981 47332231947328 Unhandled exception in thread: 'MainThread'
ERROR 2019-06-25 21:13:38,098 excepthooks 58981 47332231947328 Traceback (most recent call last):
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 139, in openProjectFile
    hdf5File = h5py.File(projectFilePath, mode)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/lib/python3.6/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/lib/python3.6/site-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik.py", line 123, in <module>
    main()
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik.py", line 108, in main
    hShell = ilastik_main.main(parsed_args, workflow_cmdline_args)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik_main.py", line 138, in main
    f(shell)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik_main.py", line 373, in loadProject
    shell.openProjectFile(path, parsed_args.readonly)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/shell/headless/headlessShell.py", line 92, in openProjectFile
    hdf5File, workflow_class, readOnly = ProjectManager.openProjectFile(projectFilePath, force_readonly)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 142, in openProjectFile
    hdf5File = h5py.File(projectFilePath, 'r')
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/lib/python3.6/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/nfs/software/birney/ilastik-1.3.2post1-Linux/lib/python3.6/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
```

Thanks in advance.

Ian

**Comment by k-dominik** [comment]
Hi Ian,

if you are accessing the same file with all your instances, then you have to add the  `--readonly` command line flag. `h5py` does not allow for concurrent read/_write_ access. Sorry, we need to update our docs.

**Comment by Ian-Brettell** [comment]
Thank you!

**Comment by k-dominik** [comment]
no problem, please let us know if this resolves your problem!
