### ISSUE TITLE
out_edges(parent) fails

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1386]
parent is NOT a NetworkX node

Looking at in edge ((8, 78), (9, 78)) of node (9, 78), searching for (8,78)
ERROR 2016-12-09 11:47:48,065 excepthooks 4264 140728827692864 Unhandled exception in thread: 'MainThread'
ERROR 2016-12-09 11:47:48,066 excepthooks 4264 140728827692864 Traceback (most recent call last):
  File "/home/jales/software/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/structured/structuredTrackingGui.py", line 366, in _onRunStructuredLearningButtonPressed
    withBatchProcessing)
  File "/home/jales/software/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/structured/opStructuredTracking.py", line 296, in _runStructuredLearning
    outEdges = hypothesesGraph._graph.out_edges(parent)
  File "/home/jales/software/miniconda/envs/ilastik-devel/lib/python2.7/site-packages/networkx/classes/graph.py", line 1050, in edges
    return list(self.edges_iter(nbunch, data))
  File "/home/jales/software/miniconda/envs/ilastik-devel/lib/python2.7/site-packages/networkx/classes/digraph.py", line 744, in edges_iter
    for n,nbrs in nodes_nbrs:
  File "/home/jales/software/miniconda/envs/ilastik-devel/lib/python2.7/site-packages/networkx/classes/digraph.py", line 738, in <genexpr>
    nodes_nbrs=((n,self.adj[n]) for n in self.nbunch_iter(nbunch))
  File "/home/jales/software/miniconda/envs/ilastik-devel/lib/python2.7/site-packages/networkx/classes/graph.py", line 1811, in bunch_iter
    "nbunch is not a node or a sequence of nodes.")
NetworkXError: nbunch is not a node or a sequence of nodes.

**Comment by ilastikdev** [comment]
fixed in hytra-learning
