### ISSUE TITLE
export fails if a division only has one child

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1387]
```
[====================] 100%
[====================] 100%
[====================] 100%
	contains 7366 segmentation hypotheses
	contains 17302 linking hypotheses
Log: Initializing Residual Graph ...
Log:  done in 0.474798 secs
Log: Beginning tracking ...
Log: 	Cycle returned to source with negative cost -0.796828 in iteration 1
Log: 	Cycle returned to source with negative cost -1.11022e-16 in iteration 2
Log: Tracking took 1.49085 secs and 314 iterations
Log: Final energy: -241652
	contains 189 segmentation hypotheses
	contains 316 linking hypotheses
Log: Running min cost max flow on a graph with 380 nodes and 567 edges
Log: Found MaxFlow value: 31
Log: MaxFlow Tracking took 0.000416 secs
ERROR 2016-12-09 11:57:31,106 log_exception 4322 139728917706496 Traceback (most recent call last):
  File "/home/jales/software/miniconda/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/home/jales/software/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 665, in do_export
    self._do_export_impl(settings, selected_features, progress_slot, object_feature_slot, label_image, lane_index, filename_suffix)
  File "/home/jales/software/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 729, in _do_export_impl
    assert len(hypothesesGraph._graph.out_edges(node)) != 2, "Division node {}, does not contain 2 children".format(node)
AssertionError: Division node (4, 41), does not contain 2 children

ERROR 2016-12-09 11:57:31,107 log_exception 4322 139728917706496 Export failed
ERROR 2016-12-09 11:57:31,108 log_exception 4322 139726689896192 Traceback (most recent call last):
  File "/home/jales/software/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/dataExport/dataExportGui.py", line 392, in exportSlots
    self.parentApplet.post_process_lane_export(lane_index)
  File "/home/jales/software/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py", line 409, in post_process_lane_export
    req.wait()
  File "/home/jales/software/miniconda/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 481, in wait
    return self._wait(timeout)
  File "/home/jales/software/miniconda/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 504, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/home/jales/software/miniconda/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/home/jales/software/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 665, in do_export
    self._do_export_impl(settings, selected_features, progress_slot, object_feature_slot, label_image, lane_index, filename_suffix)
  File "/home/jales/software/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 729, in _do_export_impl
    assert len(hypothesesGraph._graph.out_edges(node)) != 2, "Division node {}, does not contain 2 children".format(node)
AssertionError: Division node (4, 41), does not contain 2 children

ERROR 2016-12-09 11:57:31,108 log_exception 4322 139726689896192 Failed to generate export file: 
/home/jales/data/mitocheck_2d+t/mitocheck_94570_2D+t_01-53_Tracking-Result.h5/exported_data
Division node (4, 41), does not contain 2 children
```

**Comment by chaubold** [comment]
@ilastikdev, please put triple backticks (these: `) around console log or code.

**Comment by chaubold** [comment]
See for a fix suggestion. The assertion is wrong because there could be more than 2 outgoing edges in the hypotheses graph at a dividing node, but only two of the edges should be used by the solution. Could you please test that fix (by checking out `fix-wrong-division-assertion`) with the same dataset as you used when that problem appeared?

**Comment by chaubold** [comment]
@ilastikdev is this fixed?

**Comment by ilastikdev** [comment]
fixed
