### ISSUE TITLE
Object Classification fails if there are no objects in empty frame

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1395]
@letiP and I noticed it in tracking, I'm not sure whether this also shows up in a plain Object Classification workflow, but I guess so:

iastik tries to predict the object classifier for every frame of the time sequence, but if a frame was empty, then no probabilities can be retrieved.

```
ERROR 2016-12-20 13:07:51,852 log_exception 20557 139761224369920 Error during tracking.  See above error traceback.
No hypotheses graph
ERROR 2016-12-20 13:08:37,270 log_exception 20557 139760978880256 Traceback (most recent call last):
 File "/net/hciserver03/storage/lparcala/anaconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/conservationTrackingGui.py", line 350, in _track
   solverName=solver
 File "/net/hciserver03/storage/lparcala/anaconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 424, in track
   hypothesesGraph = self._createHypothesesGraph()
 File "/net/hciserver03/storage/lparcala/anaconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 242, in _createHypothesesGraph
   with_classifier_prior=withClassifierPrior)
 File "/net/hciserver03/storage/lparcala/anaconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 885, in _generate_traxelstore
   detProbs = self.DetectionProbabilities(time_range).wait()
 File "/net/hciserver03/storage/lparcala/anaconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 481, in wait
   return self._wait(timeout)
 File "/net/hciserver03/storage/lparcala/anaconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 507, in _wait
   self._wait_within_request( current_request )
 File "/net/hciserver03/storage/lparcala/anaconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
   self._result = self.fn()
 File "/net/hciserver03/storage/lparcala/anaconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/slot.py", line 850, in __call__
   result_op = self.operator.execute(self.slot, (), self.roi, destination)
 File "/net/hciserver03/storage/lparcala/anaconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1180, in execute
   pool.wait()
 File "/net/hciserver03/storage/lparcala/anaconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1270, in wait
   self._clear_finishing_requests()
 File "/net/hciserver03/storage/lparcala/anaconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1366, in _clear_finishing_requests
   req.block()
 File "/net/hciserver03/storage/lparcala/anaconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 487, in block
   self._wait(timeout) # No return value. Use wait()
 File "/net/hciserver03/storage/lparcala/anaconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 507, in _wait
   self._wait_within_request( current_request )
 File "/net/hciserver03/storage/lparcala/anaconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
   self._result = self.fn()
 File "/net/hciserver03/storage/lparcala/anaconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1171, in predict_forest
   prob_predictions[_t] = classifier.predict_probabilities(feats[_t].astype(numpy.float32))
KeyError: 1
```

**Comment by ilastikdev** [comment]
ilastik's tracking "standard" to solve this problem (labels) was to populate the super-dictionary with empty dictionaries for all the time keys that did not exist in the super-dictionary
this creates redundant data, but it is easy to code

a better solution is to actually check which times exist in the dict.keys()
whenever accessing the culprit and react accordingly for non-existing "keys"

**Comment by k-dominik** [comment]
this issue still exists, closing this in favor of https://github.com/ilastik/ilastik/issues/2019
