### ISSUE TITLE
Error when user selectes time range that doesn't start from 0

### ISSUE THREAD

**Issue by JaimeIvanCervantes** [ilastik/ilastik#1398]
On the conservation tracking wokflow, The following error shows up when the user tries to process a time range that doesn't starts from 0 (see screenshot):

![errortimerange](https://cloud.githubusercontent.com/assets/5825034/21366017/0739bb98-c6c6-11e6-91f7-787ff336f633.png)
 

```pytb
ERROR 2016-12-20 14:48:05,219 log_exception 2675 140421353154304 Traceback (most recent call last):
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/conservationTrackingGui.py", line 307, in _track
    solverName=solver
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 423, in track
    hypothesesGraph = self._createHypothesesGraph()
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 264, in _createHypothesesGraph
    divisionThreshold=divThreshold
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/hytra/hytra/core/ilastikhypothesesgraph.py", line 51, in __init__
    divisionThreshold=divisionThreshold)
  File "/opt/local/miniconda/envs/ilastik-tracking/ilastik-meta/hytra/hytra/core/hypothesesgraph.py", line 190, in buildFromProbabilityGenerator
    kdTreeThisFrame = self._buildFrameKdTree(probabilityGenerator.TraxelsPerFrame[frame])
KeyError: 0
```

**Comment by ilastikdev** [comment]
to properly fix this we need https://github.com/chaubold/hytra/pull/20

**Comment by sc65** [comment]
Can you clarify what we need to do to track from not t0?
I'm facing the same problem.
