### ISSUE TITLE
multicut workflow crashes on windows 

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#1399]
I loaded a small gray value 3D volume and upon proceeding to DT watershed, obtained this: 

```
INFO 2016-12-21 17:47:59,753 ilastik_main 8364 4036 Starting ilastik from "C:\Program Files\ilastik-1.2.0".
WARNING 2016-12-21 17:48:00,989 vigraOperators 8364 4036 Failed to import fast filters: No module named fastfilters
INFO 2016-12-21 17:48:03,144 opThresholdTwoLevels 8364 4036 Using 'vigra' labeling implemetation
INFO 2016-12-21 17:48:03,269 conservationTrackingApplet 8364 4036 Using old conservation tracking workflow (PgmLink)
WARNING 2016-12-21 17:49:28,003 tiling 8364 4036 tiling.py(351): UserWarning: FIXME: This is a slow way to look for the items we want.
_TilesCache._layerCache should be a dict-of-dict-of-dict for faster lookup!
ERROR 2016-12-21 17:49:44,081 excepthooks 8364 4036 Unhandled exception in thread: 'MainThread'
ERROR 2016-12-21 17:49:44,096 excepthooks 8364 4036 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 1039, in handleAppletBarItemExpanded
    self.setSelectedAppletDrawer(drawerIndex)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 1060, in setSelectedAppletDrawer
    self.showCentralWidget(applet_index)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 1075, in showCentralWidget
    centralWidget = self._applets[applet_index].getMultiLaneGui().centralWidget()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\base\singleToMultiGuiAdapter.py", line 64, in centralWidget
    if self.currentGui() is None:
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\base\singleToMultiGuiAdapter.py", line 44, in currentGui
    self._guis[self._imageLaneIndex] = self.singleImageGuiFactory( self._imageLaneIndex )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\base\standardApplet.py", line 142, in __createSingleLaneGui
    return self.singleLaneGuiClass( self, singleLaneOperator )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\layerViewer\layerViewerGui.py", line 68, in __call__
    instance = super(LayerViewerGuiMetaclass, cls).__call__(*args,**kwargs)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\wsdt\wsdtGui.py", line 68, in __init__
    super(WsdtGui, self).__init__( parentApplet, topLevelOperatorView )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\layerViewer\layerViewerGui.py", line 178, in __init__
    self.initAppletDrawerUi() # Default implementation loads a blank drawer from drawer.ui.
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\wsdt\wsdtGui.py", line 104, in initAppletDrawerUi
    set_channel_box_range()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\wsdt\wsdtGui.py", line 103, in set_channel_box_range
    channel_box.setMaximum( op.Input.meta.getTaggedShape()['c']-1 )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\metaDict.py", line 141, in getTaggedShape
    assert self.axistags is not None
AssertionError 
```

**Comment by stuarteberg** [comment]
Crap. Thanks for the traceback. If the volume is small enough to share, please upload it here. Otherwise: what is the file format and data dimensions?

**Comment by FredHamprecht** [comment]
https://db.tt/QWfXG8tLyP

-----Original Message-----

**Comment by k-dominik** [comment]
I've tried to reproduce this on windows, with ilastik 1.3.2 but couldn't. Multicut just worked fine using the provided image plus a prob map generated in ilastik. Thanks for keeping it available that long @FredHamprecht
