### ISSUE TITLE
crash in in 3D pixel / object classification on windows 

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#1409]
Possible causes include 
- an ilastik project was saved, moved on disk from one folder to another, loaded again. 
- possibly there was a different project of the same name in the target folder beforehand 
- class display colors were changed. 

I have not managed to reproduce the crash (but given the audience it was an embarrassing one...) 

```
INFO 2017-01-23 11:43:20,664 parallelVigraRfLazyflowClassifier 12716 13068 Training complete. Average OOB: 0.0384615384615
INFO 2017-01-23 11:43:30,832 parallelVigraRfLazyflowClassifier 12716 12840 Training took, 0.0 seconds
INFO 2017-01-23 11:43:30,832 parallelVigraRfLazyflowClassifier 12716 12840 Training complete. Average OOB: 0.030487804878
INFO 2017-01-23 11:43:32,437 parallelVigraRfLazyflowClassifier 12716 12840 Training took, 0.016 seconds
INFO 2017-01-23 11:43:32,437 parallelVigraRfLazyflowClassifier 12716 12840 Training complete. Average OOB: 0.0340909090909
INFO 2017-01-23 13:59:17,036 projectManager 12716 11860 Opening Project: C:/Users/fhamprec/cellwall.ilp
ERROR 2017-01-23 13:59:19,101 log_exception 12716 9028 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\operators\cacheMemoryManager.py", line 178, in _cleanup
    first_class_caches = self._first_class_caches.copy()
  File "C:\Program Files\ilastik-1.2.0rc10\lib\_weakrefset.py", line 94, in copy
    return self.__class__(self)
  File "C:\Program Files\ilastik-1.2.0rc10\lib\_weakrefset.py", line 50, in __init__
    self.update(data)
  File "C:\Program Files\ilastik-1.2.0rc10\lib\_weakrefset.py", line 121, in update
    for element in other:
  File "C:\Program Files\ilastik-1.2.0rc10\lib\_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration

ERROR 2017-01-23 14:00:18,990 log_exception 12716 11860 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\applets\labeling\labelingGui.py", line 634, in _addNewLabel
    self._labelingSlots.labelNames.setValue( operator_names, check_changed=False )
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1201, in setValue
    self.setDirty(slice(None))
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 943, in setDirty
    self._sig_dirty(self, roi)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\utility\orderedSignal.py", line 76, in __call__
    f(*args, **kw)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\applets\pixelClassification\opPixelClassification.py", line 169, in _updateNumClasses
    self.opPredictionPipeline.NumClasses.setValue( numClasses )
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1181, in setValue
    s.setValue(self._value)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1195, in setValue
    self._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1401, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1415, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\operator.py", line 450, in _setupOutputs
    self.setupOutputs()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\operators\classifierOperators.py", line 378, in setupOutputs
    self.PMaps.connect( self._prediction_op.PMaps )
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 520, in connect
    self._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1401, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1415, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\operator.py", line 467, in _setupOutputs
    oslot._setReady()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1314, in _setReady
    self._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1384, in _changed
    self._sig_ready(self)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\utility\orderedSignal.py", line 76, in __call__
    f(*args, **kw)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\utility\bind.py", line 64, in __call__
    self.f(*(self.bound_args + args[0:self.numUnboundArgs]))
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\utility\gui\threadRouter.py", line 75, in routed
    val = func(*args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\applets\thresholdTwoLevels\thresholdTwoLevelsGui.py", line 141, in _updateGuiFromOperator
    pm.fill(input_channel_colors[ichannel])
IndexError: list index out of range

ERROR 2017-01-23 14:00:19,020 log_exception 12716 11860 Logged the above exception just in case PyQt loses it.
ERROR 2017-01-23 14:00:19,052 excepthooks 12716 11860 Unhandled exception in thread: 'MainThread'
ERROR 2017-01-23 14:00:19,052 excepthooks 12716 11860 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\utility\bind.py", line 64, in __call__
    self.f(*(self.bound_args + args[0:self.numUnboundArgs]))
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\applets\labeling\labelingGui.py", line 634, in _addNewLabel
    self._labelingSlots.labelNames.setValue( operator_names, check_changed=False )
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1201, in setValue
    self.setDirty(slice(None))
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 943, in setDirty
    self._sig_dirty(self, roi)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\utility\orderedSignal.py", line 76, in __call__
    f(*args, **kw)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\applets\pixelClassification\opPixelClassification.py", line 169, in _updateNumClasses
    self.opPredictionPipeline.NumClasses.setValue( numClasses )
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1181, in setValue
    s.setValue(self._value)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1195, in setValue
    self._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1401, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1415, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\operator.py", line 450, in _setupOutputs
    self.setupOutputs()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\operators\classifierOperators.py", line 378, in setupOutputs
    self.PMaps.connect( self._prediction_op.PMaps )
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 520, in connect
    self._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1401, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1415, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\operator.py", line 467, in _setupOutputs
    oslot._setReady()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1314, in _setReady
    self._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1384, in _changed
    self._sig_ready(self)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\utility\orderedSignal.py", line 76, in __call__
    f(*args, **kw)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\utility\bind.py", line 64, in __call__
    self.f(*(self.bound_args + args[0:self.numUnboundArgs]))
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\utility\gui\threadRouter.py", line 75, in routed
    val = func(*args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\applets\thresholdTwoLevels\thresholdTwoLevelsGui.py", line 141, in _updateGuiFromOperator
    pm.fill(input_channel_colors[ichannel])
IndexError: list index out of range

ERROR 2017-01-23 14:00:19,571 log_exception 12716 11860 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\applets\labeling\labelingGui.py", line 634, in _addNewLabel
    self._labelingSlots.labelNames.setValue( operator_names, check_changed=False )
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1201, in setValue
    self.setDirty(slice(None))
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 943, in setDirty
    self._sig_dirty(self, roi)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\utility\orderedSignal.py", line 76, in __call__
    f(*args, **kw)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\applets\pixelClassification\opPixelClassification.py", line 169, in _updateNumClasses
    self.opPredictionPipeline.NumClasses.setValue( numClasses )
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1181, in setValue
    s.setValue(self._value)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1195, in setValue
    self._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1401, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1415, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\operator.py", line 477, in _setupOutputs
    oslot._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1401, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1415, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\operator.py", line 467, in _setupOutputs
    oslot._setReady()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1314, in _setReady
    self._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1384, in _changed
    self._sig_ready(self)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\utility\orderedSignal.py", line 76, in __call__
    f(*args, **kw)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\utility\bind.py", line 64, in __call__
    self.f(*(self.bound_args + args[0:self.numUnboundArgs]))
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\utility\gui\threadRouter.py", line 75, in routed
    val = func(*args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\applets\thresholdTwoLevels\thresholdTwoLevelsGui.py", line 141, in _updateGuiFromOperator
    pm.fill(input_channel_colors[ichannel])
IndexError: list index out of range

ERROR 2017-01-23 14:00:19,634 log_exception 12716 11860 Logged the above exception just in case PyQt loses it.
ERROR 2017-01-23 14:00:19,641 excepthooks 12716 11860 Unhandled exception in thread: 'MainThread'
ERROR 2017-01-23 14:00:19,655 excepthooks 12716 11860 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\utility\bind.py", line 64, in __call__
    self.f(*(self.bound_args + args[0:self.numUnboundArgs]))
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\applets\labeling\labelingGui.py", line 634, in _addNewLabel
    self._labelingSlots.labelNames.setValue( operator_names, check_changed=False )
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1201, in setValue
    self.setDirty(slice(None))
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 943, in setDirty
    self._sig_dirty(self, roi)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\utility\orderedSignal.py", line 76, in __call__
    f(*args, **kw)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\applets\pixelClassification\opPixelClassification.py", line 169, in _updateNumClasses
    self.opPredictionPipeline.NumClasses.setValue( numClasses )
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1181, in setValue
    s.setValue(self._value)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1195, in setValue
    self._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1401, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1415, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\operator.py", line 477, in _setupOutputs
    oslot._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1401, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1415, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\operator.py", line 467, in _setupOutputs
    oslot._setReady()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1314, in _setReady
    self._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1395, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\slot.py", line 1384, in _changed
    self._sig_ready(self)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\lazyflow\lazyflow\utility\orderedSignal.py", line 76, in __call__
    f(*args, **kw)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\utility\bind.py", line 64, in __call__
    self.f(*(self.bound_args + args[0:self.numUnboundArgs]))
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\utility\gui\threadRouter.py", line 75, in routed
    val = func(*args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0rc10\ilastik-meta\ilastik\ilastik\applets\thresholdTwoLevels\thresholdTwoLevelsGui.py", line 141, in _updateGuiFromOperator
    pm.fill(input_channel_colors[ichannel])
IndexError: list index out of range
```

**Comment by stuarteberg** [comment]
Were you using the combined Pixel + Object workflow, or were you using the other Object classification worklflow (starting from previously saved pixel probabilities)?

If the latter, I can think of one possible way this occurred, if you moved the project file to a folder that "accidentally" contained a pixel probability volume with the "right" name, but the wrong number of channels.

If that's not what happened, then I'm unsure what happened.  One other theory could be related to unsaved changes in the project file before it was closed and related, but I'd have to experiment with it to be sure.

**Comment by FredHamprecht** [comment]
On 23-Jan-17 15:03, Stuart Berg wrote:
> Were you using the combined Pixel + Object workflow, or were you using
> the other Object classification worklflow (starting from previously
> saved pixel probabilities)?

combined.

> If the latter, I can think of one possible way this occurred, if you
> moved the project file to a folder that "accidentally" contained a pixel
> probability volume with the "right" name, but the wrong number of channels.
>
> If that's not what happened, then I'm unsure what happened. One other
> theory could be related to unsaved changes in the project file before it
> was closed and related, but I'd have to experiment with it to be sure.

That could be. I assumed that I can do whatever in ilastik and it will 
not affect the project file unless I press the "save" button. Is that 
false?

**Comment by FredHamprecht** [comment]
I cannot reliably reproduce the error, but I have now observed an occurrence of this crash without renaming classes, and without moving files. 

Does the attached log help? I think it features this problem only. 

[ilastik_log-crash.txt](https://github.com/ilastik/ilastik/files/757413/ilastik_log-crash.txt)
