### ISSUE TITLE
Weird closing behavior of read-only projects

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1435]
I just opened ilastik with a project for which I had no write permissions.
The `File->Save` menu entry was grayed out appropriately. But when I closed the project again ilastik asked whether I want to save the changes. Knowing that I cannot save the project I clicked "yes", and the ilastik window disappeared quietly. Yet on the command line it showed the error below. So it was aware that it couldn't save, but for a user who is not checking the logs we should also pop up a message box about that (and perhaps give him/her the chance to save to a different file instead?). 

```py
ERROR 2017-03-22 10:19:41,786 excepthooks 34105 140380058150656 Traceback (most recent call last):
  File "/home/chaubold/miniconda-2.7/envs/ilastik12/ilastik-meta/ilastik/ilastik/excepthooks.py", line 109, in run
    run_old(*args, **kwargs)
  File "/home/chaubold/miniconda-2.7/envs/ilastik12/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/chaubold/miniconda-2.7/envs/ilastik12/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 1609, in save
    self.projectManager.saveProject()
  File "/home/chaubold/miniconda-2.7/envs/ilastik12/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 264, in saveProject
    assert not self.currentProjectIsReadOnly, "Can't save a read-only project"
AssertionError: Can't save a read-only project
```

**Comment by imagejan** [comment]
Just stumbled across this issue as well. This can lead to data loss when users aren't aware that they work from a read-only location.

The process of quitting should be interrupted in case any IO errors occur during saving.
