### ISSUE TITLE
Progressbar error when running tracking workflow on Mac

### ISSUE THREAD

**Issue by JaimeIvanCervantes** [ilastik/ilastik#1438]
I have seen this error twice when running tracking on Mac:

```
INFO 2017-03-24 10:29:41,535 conservationTrackingGui 65395 140735178985472 global name 'mht' is not defined
INFO 2017-03-24 10:30:08,235 opObjectClassification 65395 123145335132160 training on matrix of shape (4, 25)
INFO 2017-03-24 10:30:08,250 parallelVigraRfLazyflowClassifier 65395 123145335132160 Training took, 0.014376 seconds
INFO 2017-03-24 10:30:08,250 parallelVigraRfLazyflowClassifier 65395 123145335132160 Training complete. Average OOB: 0.0
INFO 2017-03-24 10:30:08,251 opObjectClassification 65395 123145335132160 training finished, average out-of-bag error: 0.0
INFO 2017-03-24 10:31:23,254 opObjectClassification 65395 123145410850816 training on matrix of shape (7, 25)
INFO 2017-03-24 10:31:23,259 parallelVigraRfLazyflowClassifier 65395 123145410850816 Training took, 0.00423 seconds
INFO 2017-03-24 10:31:23,259 parallelVigraRfLazyflowClassifier 65395 123145410850816 Training complete. Average OOB: 0.0
INFO 2017-03-24 10:31:23,259 opObjectClassification 65395 123145410850816 training finished, average out-of-bag error: 0.0
INFO 2017-03-24 10:31:23,270 opConservationTracking 65395 123145410850816 generating traxels
INFO 2017-03-24 10:31:23,270 opConservationTracking 65395 123145410850816 fetching region features and division probabilities
INFO 2017-03-24 10:31:27,271 opConservationTracking 65395 123145410850816 filling traxelstore
ERROR 2017-03-24 10:31:27,333 log_exception 65395 123145410850816 Traceback (most recent call last):
  File "/Users/robitscheke/Downloads/ilastik-1.2.0-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/conservationTrackingGui.py", line 307, in _track
    solverName=solver
  File "/Users/robitscheke/Downloads/ilastik-1.2.0-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 423, in track
    hypothesesGraph = self._createHypothesesGraph()
  File "/Users/robitscheke/Downloads/ilastik-1.2.0-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 264, in _createHypothesesGraph
    divisionThreshold=divThreshold
  File "/Users/robitscheke/Downloads/ilastik-1.2.0-OSX.app/Contents/Resources/lib/python2.7/site-packages/hytra/core/ilastikhypothesesgraph.py", line 51, in __init__
    divisionThreshold=divisionThreshold)
  File "/Users/robitscheke/Downloads/ilastik-1.2.0-OSX.app/Contents/Resources/lib/python2.7/site-packages/hytra/core/hypothesesgraph.py", line 227, in buildFromProbabilityGenerator
    progressBar.show()
  File "/Users/robitscheke/Downloads/ilastik-1.2.0-OSX.app/Contents/Resources/lib/python2.7/site-packages/hytra/util/progressbar.py", line 22, in show
    sys.stdout.flush()
IOError: [Errno 32] Broken pipe
```
@chaubold this seems to be related to the progressbar.

**Comment by chaubold** [comment]
This was fixed by just not throwing the error a long time ago in [hytra](https://github.com/chaubold/hytra/commit/5786596018810a72e97e08f21156877214e51b5a). 

And on the other hand @ilastikdev is cleaning this part up to provide a GUI progress bar in ilastik.

Once we update the hytra version this should be fixed.

**Comment by ilastikdev** [comment]
to try the latest with a commandline triggered (--gui_progress_bar or --command_line_progress_bar)
for tracking in the learning workflow
the pull from 
ilastik/hytra-learning
and
hytra/master
