### ISSUE TITLE
Tracking - NotImplementedError in get_exporting_operator

### ISSUE THREAD

**Issue by Confusezius** [ilastik/ilastik#1451]
```
ERROR 2017-03-31 11:06:52,173 excepthooks 19717 140118287963968 Traceback (most recent call last):
  File "/home/kroth/miniconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/utility/exportingOperator.py", line 151, in show_export_dialog
    op = self.get_exporting_operator()
  File "/home/kroth/miniconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/utility/exportingOperator.py", line 134, in get_exporting_operator
    raise NotImplementedError
NotImplementedError

```

**Comment by LetiP** [comment]
So I guess you used:
![screenshot from 2017-03-31 11-27-32](https://cloud.githubusercontent.com/assets/16118202/24544844/1fb22140-1605-11e7-9751-ca31e0041c68.png)
I do not know yet, what this button is intended for.

But for tracking result export, you should click in this area:
![screenshot from 2017-03-31 11-26-52](https://cloud.githubusercontent.com/assets/16118202/24544868/3838ac02-1605-11e7-9230-d63d6beeb6b9.png)

:)
What t

**Comment by chaubold** [comment]
Thanks @LetiP for finding that relict. That was a very old implementation of exporting a CSV table of features (even before it ever made it into the **Tracking Export Applet**). So that button should just not be there at all.

@Confusezius yup, what @LetiP said 😉

**Comment by k-dominik** [comment]
menu entry is gone..
