### ISSUE TITLE
mamutexport

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1453]
conda loads outdated mamutexport
(which does not have mamutexport/raw_input.xml file)

Note: Cloning this 
https://github.com/Beinabih/MaMutConverter
into ...../site-packages
and moving MaMutConverter/mamutexport
one level up works.

```
ERROR 2017-03-31 12:00:46,129 log_exception 29757 140195375879936 Traceback (most recent call last):
  File "/home/jales/software/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/dataExport/dataExportGui.py", line 396, in exportSlots
    exportStatus = self.parentApplet.post_process_lane_export(lane_index, checkOverwriteFiles=True)
  File "/home/jales/software/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py", line 509, in post_process_lane_export
    exportStatus = self.trackingApplet.topLevelOperator.getLane(lane_index).exportPlugin(filename, exportPlugin, checkOverwriteFiles)
  File "/home/jales/software/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 650, in exportPlugin
    if not plugin.export(filename, hypothesesGraph, object_feature_slot, label_image, self.RawImage):
  File "/home/jales/software/miniconda/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/plugins_default/tracking_mamut_export.py", line 65, in export
    builder = MamutXmlBuilder()
  File "/home/jales/software/miniconda/envs/ilastik-devel/lib/python2.7/site-packages/mamutexport/mamutxmlbuilder.py", line 12, in __init__
    self.tree = ET.parse(os.path.join(path,'raw_input.xml'))
  File "/home/jales/software/miniconda/envs/ilastik-devel/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/home/jales/software/miniconda/envs/ilastik-devel/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: '/home/jales/software/miniconda/envs/ilastik-devel/lib/python2.7/site-packages/mamutexport/raw_input.xml'

ERROR 2017-03-31 12:00:46,129 log_exception 29757 140195375879936 Failed to generate export file: 
/home/jales/sfb1129/karstenRoth/mamutExport/rawDataUint8YFP_02_Tracking-Result.h5/exported_data
[Errno 2] No such file or directory: '/home/jales/software/miniconda/envs/ilastik-devel/lib/python2.7/site-packages/mamutexport/raw_input.xml'


```

**Comment by chaubold** [comment]
Thanks for catching that. Mamutexport was not outdated, it simply didn't copy the xml file into the site-packages folder. Fixed in https://github.com/Beinabih/MaMutConverter/commit/06eecb1d1609332f9cd8b494a8c82f754c3028cb

Please next time also report the error in the repository that causes it.

@stuarteberg: I've pushed a new version tag for `MaMutConverter` (0.2.1) and updated `ilastik-build-conda`, but that still means you need to rebuild the package... Thanks!
