### ISSUE TITLE
Error on tracking_csv_export when running tracking on headless mode

### ISSUE THREAD

**Issue by JaimeIvanCervantes** [ilastik/ilastik#1470]
One of my users got this error when running tracking on headless mode:

```
WARNING httplib.py(1245): ImportWarning: Not importing directory '/Applications/ilastik-1.2.1b2-OSX.app/Contents/ilastik-release/ssl': missing __init__.py
INFO lazyflow.operators.vigraOperators: Using fast filters.
INFO ilastik_main: Starting ilastik from "/Applications/ilastik-1.2.1b2-OSX.app/Contents/ilastik-release".
Starting ilastik from "/Applications/ilastik-1.2.1b2-OSX.app/Contents/ilastik-release".
WARNING cross_validation.py(44): DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
WARNING 2017-04-13 17:02:25,319 opConservationTracking 1537 140735168634880 Could not find any ILP solver
WARNING 2017-04-13 17:02:25,430 __init__ 1537 140735168634880 Failed to import structured learning tracking workflow. For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: Could not find any ILP solver
WARNING pkgutil.py(186): ImportWarning: Not importing directory '/Applications/ilastik-1.2.1b2-OSX.app/Contents/ilastik-release/lib/python2.7/site-packages/mpl_toolkits': missing __init__.py
INFO ilastik.shell.projectManager: Opening Project: /Users/robiea/Desktop/FlyBowl/FlyBubble_animaltrackingv4.ilp
WARNING 2017-04-13 17:02:31,280 conservationTrackingWorkflow 1537 140735168634880 Unused command-line args: ['--export_source=Plugin', '--export_plugin=CSV-Table']
WARNING transition_feature_multiplication.py(4): DeprecationWarning: The compiler package is deprecated and removed in Python 3.x.
WARNING slot.py(1186): DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
INFO ilastik.workflows.tracking.conservation.conservationTrackingWorkflow: Beginning Batch Processing
INFO ilastik.applets.tracking.conservation.opConservationTracking: generating traxels
INFO ilastik.applets.tracking.conservation.opConservationTracking: fetching region features and division probabilities
INFO ilastik.applets.tracking.conservation.opConservationTracking: filling traxelstore
INFO hytra.core.hypothesesgraph: generating tracklet graph...
INFO hytra.core.hypothesesgraph: tracklet graph has 65 nodes and 80 edges (before 172721,172736)
contains 65 segmentation hypotheses
contains 80 linking hypotheses
Log: Initializing Residual Graph ...
Log:  done in 0.002708 secs
Log: Beginning tracking ...
Log: Tracking took 0.001303 secs and 5 iterations
Log: Final energy: -1.32008e+07
INFO ilastik.applets.tracking.conservation.opConservationTracking: Resolving mergers.
INFO ilastik.applets.tracking.conservation.opConservationTracking: Computing full graph on merger resolver (Only enabled on animal tracking workflow)
INFO ilastik.applets.tracking.conservation.opConservationTracking: Graph contains no mergers. Skipping merger resolving.
INFO ilastik.applets.tracking.conservation.opConservationTracking: Computing hypotheses graph lineages
INFO ilastik.applets.batchProcessing.batchProcessingApplet: Exporting to /Volumes/MyPassport/Test_Ilastik/grooming2_Line1_Unknown_RigA_20161213T224309/movie_Object-Identities.h5/exported_data
INFO ilastik.workflows.tracking.conservation.conservationTrackingWorkflow: Export source is: Plugin
INFO ilastik.workflows.tracking.conservation.conservationTrackingWorkflow: Export source plugin selected!
INFO ilastik.workflows.tracking.conservation.conservationTrackingWorkflow: Exporting tracking result using CSV-Table
ERROR 2017-04-13 19:37:52,662 log_exception 1537 140735168634880 Traceback (most recent call last):
  File "/Applications/ilastik-1.2.1b2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 443, in _loadProject
    self.workflow.onProjectLoaded( self )
  File "/Applications/ilastik-1.2.1b2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 490, in onProjectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "/Applications/ilastik-1.2.1b2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 60, in run_export_from_parsed_args
    return self.run_export(role_path_dict, parsed_args.input_axes)
  File "/Applications/ilastik-1.2.1b2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 123, in run_export
    export_to_array=export_to_array )
  File "/Applications/ilastik-1.2.1b2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 239, in _run_export_with_empty_batch_lane
    self.dataExportApplet.post_process_lane_export(batch_lane_index)
  File "/Applications/ilastik-1.2.1b2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 409, in post_process_lane_export
    exportStatus = self.trackingApplet.topLevelOperator.getLane(lane_index).exportPlugin(filename, exportPlugin, checkOverwriteFiles)
  File "/Applications/ilastik-1.2.1b2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 618, in exportPlugin
    if not plugin.export(filename, hypothesesGraph, object_feature_slot, label_image, self.RawImage):
  File "/Applications/ilastik-1.2.1b2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/plugins_default/tracking_csv_export.py", line 115, in export
    np.savetxt(filename + '.csv', table, header=headerLine, delimiter=',', comments='', fmt=formats)
  File "/Applications/ilastik-1.2.1b2-OSX.app/Contents/ilastik-release/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1219, in savetxt
    % (str(X.dtype), format))
TypeError: Mismatch between array dtype ('float64') and format specifier ('%d,%d,%d,%d,%d,%d,%f,%f,%f,%f,%f,%f,%f,%d,%d,%d,%d,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%d,%f,%f,%f,%f,%f,%f,%d,%d,%d,%d,%d,%d')
```
@chaubold it appears to be related to the plugin system

**Comment by chaubold** [comment]
Indeed, I didn't know that numpy complains about the format specifier if it is decimal and the value is `NaN`. But this is already fixed in https://github.com/ilastik/ilastik/commit/a3fea41d66334926a3c91fd6d18cd998d4cb4041, so from version ilastik 1.2.1b3 on.
