### ISSUE TITLE
Error when running the structured learning tests

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik#1472]
When I try to run the structured learning tests (e.g. `testStructuredLearningTrackingHytraWithDivisions.py`, `testStructuredLearningTrackingHytraFluo-N2DH-SIM-01.py`), I encounter a failure due to the deserialization of a `IlastikHypothesesGraph` object.  I guess the format of that data structure has changed?

What I'm not sure about is if the test project files need to be updated, or if my version of `hytra` needs to be updated.  (I'm still using version `1.1.3`.)

Suggestions?
@chaubold @ilastikdev 

```pytb
ilastik_main: INFO: Starting ilastik in debug mode from "/Users/bergs/Documents/workspace".
ilastik.shell.projectManager: INFO: Opening Project: data/inputdata/mitocheckStructuredLearningTrackingHytraWithDivisions.ilp
ilastik.workflows.tracking.structured.structuredTrackingWorkflow: WARNING: Unused command-line args: ['--testFullAnnotations', '--export_source=Tracking-Result']
ilastik.shell.projectManager: ERROR: Traceback (most recent call last):
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 435, in _loadProject
    serializer.deserializeFromHdf5(self.currentProjectFile, projectFilePath)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 1012, in deserializeFromHdf5
    ss.deserialize(topGroup)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 243, in deserialize
    self._deserialize(group[self.name], self.inslot)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 280, in _deserialize
    self._deserialize(subgroup[key], subslot)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 258, in _deserialize
    self._getValue(subgroup, slot)
  File "/magnetic/workspace/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 630, in _getValue
    slot.setValue(pickle.loads(val))
  File "/miniconda2/envs/test-release/lib/python2.7/site-packages/hytra/core/ilastikhypothesesgraph.py", line 101, in __setstate__
    = state
ValueError: need more than 16 values to unpack

ilastik.shell.projectManager: ERROR: Project could not be loaded due to the exception shown above.
Aborting Project Open Action```

**Comment by chaubold** [comment]
I think this is because the hypotheses graph format has changed in `hytra`, and we store that graph by using `pickle`, with some special member handling in `hytra.hypothesesGraph.__set/getstate__()`. 

We should adjust the deserialization to `try` unpickling and, as fallback if that doesn't work, return `None` so that the user has to run tracking again after reopening an old project with the new ilastik version.

**Comment by chaubold** [comment]
@ilastikdev could you do that, please?
