### ISSUE TITLE
circleCi build is not working

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#1480]
With #1479 the tests are actually attempted to run on circleCi. However There somehow seems to be a mismatch of versions that I cannot explain.
While I have verified that the package versions are the same as on my (local) linux machine. However there is the following error:
```python
Running ./bin/generate_test_data.py
Traceback (most recent call last):
  File "./nose_single.py", line 46, in <module>
    from helpers import mainThreadHelpers
  File "/home/ubuntu/ilastik/tests/helpers/__init__.py", line 21, in <module>
    from shellGuiTestCaseBase import ShellGuiTestCaseBase
  File "/home/ubuntu/ilastik/tests/helpers/shellGuiTestCaseBase.py", line 34, in <module>
    from ilastik.utility.gui.threadRouter import ThreadRouter
  File "/home/ubuntu/miniconda/envs/test-env/ilastik-meta/ilastik/ilastik/utility/__init__.py", line 24, in <module>
    from operatorSubView import OperatorSubView
  File "/home/ubuntu/miniconda/envs/test-env/ilastik-meta/ilastik/ilastik/utility/operatorSubView.py", line 21, in <module>
    from lazyflow.graph import OperatorWrapper, InputDict, OutputDict
  File "/home/ubuntu/miniconda/envs/test-env/ilastik-meta/lazyflow/lazyflow/__init__.py", line 32, in <module>
    import operators
  File "/home/ubuntu/miniconda/envs/test-env/ilastik-meta/lazyflow/lazyflow/operators/__init__.py", line 41, in <module>
    import classifierOperators
  File "/home/ubuntu/miniconda/envs/test-env/ilastik-meta/lazyflow/lazyflow/operators/classifierOperators.py", line 34, in <module>
    from lazyflow.classifiers import LazyflowVectorwiseClassifierABC, LazyflowVectorwiseClassifierFactoryABC, \
  File "/home/ubuntu/miniconda/envs/test-env/ilastik-meta/lazyflow/lazyflow/classifiers/__init__.py", line 11, in <module>
    from iiboostLazyflowClassifier import IIBoostLazyflowClassifier, IIBoostLazyflowClassifierFactory
  File "/home/ubuntu/miniconda/envs/test-env/ilastik-meta/lazyflow/lazyflow/classifiers/iiboostLazyflowClassifier.py", line 31, in <module>
    import iiboost
  File "/home/ubuntu/miniconda/envs/test-env/lib/python2.7/site-packages/iiboost/__init__.py", line 1, in <module>
    from booster import Booster, EigenVectorsOfHessianImage, computeEigenVectorsOfHessianImage, computeIntegralImage, ROICoordinates
  File "/home/ubuntu/miniconda/envs/test-env/lib/python2.7/site-packages/iiboost/booster.py", line 32, in <module>
    libPtr = ctypes.CDLL( libName )
  File "/home/ubuntu/miniconda/envs/test-env/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libjpeg.so.9: cannot open shared object file: No such file or directory
```

**Comment by stuarteberg** [comment]
Now that `ilastik-everything-no-solvers` is up-to-date on our channel, try re-starting the CI build "without cache" to ensure that the conda environment is updated.

**Comment by k-dominik** [comment]
closed via https://github.com/ilastik/ilastik-build-conda/issues/29.

Thank you Stuart for the quick help!
