### ISSUE TITLE
Multicut: changing superpix after multicut crashes next applets

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#1488]
Here is what I did:
- make some superpixels
- label some edges, run edge prediction, run multicut (by "run now", not "live update")
- clear the edge labels, turn off all layers besides raw data
- go back to superpixels, change a setting (note, that all "live update" is off in the Training applet)
- crash:

```pytb
ERROR 2017-05-05 15:31:29,668 excepthooks 4579 140702080575232 Traceback (most recent call last):
  File "/home/akreshuk/miniconda2/envs/ilastik-devel-new/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/home/akreshuk/miniconda2/envs/ilastik-devel-new/ilastik-meta/ilastik/ilastik/applets/multicut/multicutGui.py", line 224, in _impl
    edge_disagreements = op.EdgeLabelDisagreementDict.value
  File "/home/akreshuk/miniconda2/envs/ilastik-devel-new/ilastik-meta/lazyflow/lazyflow/slot.py", line 1097, in value
    temp = self[:].wait()
  File "/home/akreshuk/miniconda2/envs/ilastik-devel-new/ilastik-meta/lazyflow/lazyflow/request/request.py", line 481, in wait
    return self._wait(timeout)
  File "/home/akreshuk/miniconda2/envs/ilastik-devel-new/ilastik-meta/lazyflow/lazyflow/request/request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "/home/akreshuk/miniconda2/envs/ilastik-devel-new/ilastik-meta/lazyflow/lazyflow/request/request.py", line 306, in _execute
    self._result = self.fn()
  File "/home/akreshuk/miniconda2/envs/ilastik-devel-new/ilastik-meta/lazyflow/lazyflow/slot.py", line 876, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/home/akreshuk/miniconda2/envs/ilastik-devel-new/ilastik-meta/ilastik/ilastik/applets/multicut/opMulticut.py", line 196, in execute
    edge_labels_from_nodes = (node_labels[rag.edge_ids[:,0]] != node_labels[rag.edge_ids[:,1]]).view(np.uint8)
IndexError: index 2323 is out of bounds for axis 0 with size 2322```

Apparently, something of the old superpixels still remains, and it tries to re-apply some old settings to them.

**Comment by snajder-r** [comment]
I got a different error message at a different point today, but I think it is most likely caused by the same thing. See below.

Got a message box with "AssertionError" today while updating Multicut. 

Here is what I was doing: I created a multicut project, loaded raw data, edge probabilities and ground truth, applied watershed (with "preserve thin structures"), performed auto-labeling of edges, updated multicut, then went back to watershed, changed some settings and ran watershed again. At this point I didn't get an error yet. Only when I went back to multicut and updated multiut again, did I get this error.

In the log I had this error:

```
ERROR 2018-09-12 13:42:55,123 excepthooks 54819 140640329627392 Unhandled exception in thread: 'Worker #5'
ERROR 2018-09-12 13:42:55,124 excepthooks 54819 140640329627392 Traceback (most recent call last):
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/volumina/volumina/tiling.py", line 773, in _fetch_tile_layer
    img = ims_req.wait()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 718, in wait
    array_data = self._arrayreq.wait()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/volumina/volumina/pixelpipeline/slicesources.py", line 46, in wait
    return self._sp(self._ar.wait())
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 204, in wrapper
    return func(*args, **kwargs)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 228, in wait
    a = self._req.wait()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/operators/opReorderAxes.py", line 145, in execute
    self.Input( *in_roi ).writeInto( result_input_view ).wait()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 793, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 83, in execute
    self._execute_Output(slot, subindex, roi, result)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/operators/opSimpleBlockedArrayCache.py", line 100, in _execute_Output
    pool.wait()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1313, in wait
    self._clear_finishing_requests()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1390, in _clear_finishing_requests
    req.block()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in block
    self._wait(timeout) # No return value. Use wait()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 609, in _wait_within_request
    raise_with_traceback(exc_type(exc_value), exc_tb)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/operators/opSimpleBlockedArrayCache.py", line 87, in copy_block
    self._execute_Output_impl( full_block_roi, full_block_data )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 108, in _execute_Output_impl
    self._fetch_and_store_block(request_roi, out=result)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 146, in _fetch_and_store_block
    block_data = req.wait()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 793, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/operators/opCacheFixer.py", line 63, in execute
    self.Input(roi.start, roi.stop).writeInto(result).wait()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 793, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/multicut/opMulticut.py", line 167, in execute
    mapping_index_array = self.NodeLabels.value
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1105, in value
    temp = self[:].wait()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/operators/valueProviders.py", line 301, in execute
    value = request.wait()[0]
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 609, in _wait_within_request
    raise_with_traceback(exc_type(exc_value), exc_tb)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/multicut/opMulticut.py", line 264, in execute
    rag, edge_probabilities, beta, solver_name)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/multicut/opMulticut.py", line 309, in agglomerate_with_multicut
    assert edge_weights.shape == (rag.num_edges,)
AssertionError
```

**Comment by k-dominik** [comment]
okay, multicut is really overdue for an overhaul :)
