### ISSUE TITLE
Structured learning tests not skipped on machine without CPLEX or GUROBI

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#1492]
When running the tests with the current master, the following headless tests are run and fail because neither `multiHypoTracking_with_cplex` nor `multiHypoTracking_with_gurobi` is available.

```
./test_applets/structuredLearningTracking/testStructuredLearningTrackingHytraWithDivisions.py
./test_applets/structuredLearningTracking/testStructuredLearningTrackingHytraFluo-N2DH-SIM-01.py
./test_applets/structuredLearningTracking/testStructuredLearningTrackingHytraWithMergers.py
```

in each of the test line [374](https://github.com/ilastik/ilastik/blob/master/ilastik/applets/tracking/structured/opStructuredTracking.py#L374) in [opStructuredTracking](https://github.com/ilastik/ilastik/blob/master/ilastik/applets/tracking/structured/opStructuredTracking.py#L374) is run

here is some exemplary output
```
ilastik.shell.projectManager: ERROR: Traceback (most recent call last):
  File "....../miniconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 443, in _loadProject
    self.workflow.onProjectLoaded( self )
  File "....../miniconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py", line 591, in onProjectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "....../miniconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 60, in run_export_from_parsed_args
    return self.run_export(role_path_dict, parsed_args.input_axes)
  File "....../miniconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 123, in run_export
    export_to_array=export_to_array )
  File "....../miniconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 225, in _run_export_with_empty_batch_lane
    self.dataExportApplet.prepare_lane_for_export(batch_lane_index)
  File "....../miniconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py", line 416, in prepare_lane_for_export
    self.result = runLearningAndTracking(withMergerResolution=False)
  File "....../miniconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py", line 376, in runLearningAndTracking
    withBatchProcessing=True)
  File "....../miniconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/tracking/structured/opStructuredTracking.py", line 374, in _runStructuredLearning
    mht.trainWithWeightInitialization(model,gt, initialWeights)
NameError: global name 'mht' is not defined
```

@ilastikdev should we check whether one of the solvers is installed prior to running the tests?

**Comment by ilastikdev** [comment]
done in b7ac9f1b17b2b14e5b77d718c231d6d19750eecc

**Comment by ilastikdev** [comment]
see https://github.com/ilastik/ilastik/pull/1495

**Comment by k-dominik** [comment]
thanks, that fixes it!

**Comment by chaubold** [comment]
@ilastikdev: usually we only close those issues once they make it into **master** (and that even happens automatically if you mentioned the issue in your commit message)
