### ISSUE TITLE
Structured Learning cannot be run in headless mode due to QtGui import

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1494]
We should only import the **GUI** part of the progress bar for tracking when we are not running in headless mode. The easy way to reproduce that error is to run the following:

```
nosetests test_applets/structuredLearningTracking/testStructuredLearningTrackingHytraWithDivisions.py
```

Gives that error:

```pytb
======================================================================
ERROR: testStructuredLearningTrackingHytraWithDivisions.TestStructuredLearningTrackingHeadless.testStructuredLearningTrackingHeadless
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 142, in wrapper
    return func(*args, **kwargs)
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/ilastik/tests/test_applets/structuredLearningTracking/testStructuredLearningTrackingHytraWithDivisions.py", line 87, in testStructuredLearningTrackingHeadless
    import ilastik.workflows.tracking.structured
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/ilastik/ilastik/workflows/__init__.py", line 59, in <module>
    import tracking.conservation
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/__init__.py", line 4, in <module>
    from conservationTrackingWorkflow import ConservationTrackingWorkflowFromPrediction, ConservationTrackingWorkflowFromBinary
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 6, in <module>
    from ilastik.applets.tracking.conservation.conservationTrackingApplet import ConservationTrackingApplet
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/conservationTrackingApplet.py", line 14, in <module>
    from ilastik.applets.tracking.conservation.opConservationTracking import OpConservationTracking
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 29, in <module>
    from ilastik.utility.gui.progress import DefaultProgressVisitor, CommandLineProgressVisitor
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/ilastik/ilastik/utility/gui/__init__.py", line 21, in <module>
    from thunkEvent import ThunkEvent, ThunkEventHandler
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/ilastik/ilastik/utility/gui/thunkEvent.py", line 21, in <module>
    from PyQt4.QtCore import QObject, QEvent
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/ilastik/ilastik/headless_dummy_modules/PyQt4/__init__.py", line 9, in <module>
    raise Exception("Developer error: When ilastik is running in headless mode, you aren't allowed to import PyQt4.")
Exception: Developer error: When ilastik is running in headless mode, you aren't allowed to import PyQt4.

----------------------------------------------------------------------
```

**Comment by chaubold** [comment]
Oops, @akreshuk filed the same thing, duplicate of #1493

**Comment by ilastikdev** [comment]
I will move non-gui progress bar methods one directory up
however, I can not reproduce the error
this ran through on three different machines, so the logic of checks for non-allowed gui imports should be revisited

**Comment by ilastikdev** [comment]
see https://github.com/ilastik/ilastik/pull/1495
