### ISSUE TITLE
No gurobi wrapper found

### ISSUE THREAD

**Issue by vothx042** [ilastik/ilastik#1502]
Hello,

I am using the cell density counter to count labelled nuclei. Currently, I get two error messages, either the "RuntimeError: No gurobi wrapper found", or "pop from empty list". I am trying to process large images (GBs in size), which causes Ilastik to crash using the batch feature. So, I cut the images into pieces and run it through the batch processing feature of Ilastik. However, this time around, every time I try to export any image (either the training images or the batch processing images) it returns the No gurobi wrapper found error.

Here is the error log:

ERROR 2017-05-16 14:25:31,858 excepthooks 4956 6408 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\volumina\volumina\tiling.py", line 768, in _fetch_tile_layer
    img = ims_req.wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\volumina\volumina\pixelpipeline\imagesources.py", line 383, in wait
    return self.toImage()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\volumina\volumina\pixelpipeline\imagesources.py", line 389, in toImage
    self._arrayreq.wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\volumina\volumina\pixelpipeline\slicesources.py", line 43, in wait
    return self._sp(self._ar.wait())
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\volumina\volumina\pixelpipeline\datasources.py", line 464, in wait
    rawData = self._rawRequest.wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\volumina\volumina\pixelpipeline\datasources.py", line 201, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\volumina\volumina\pixelpipeline\datasources.py", line 225, in wait
    a = self._req.wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 481, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 306, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\operators\opReorderAxes.py", line 143, in execute
    self.Input( *in_roi ).writeInto( result_input_view ).wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 481, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 306, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 770, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\counting\opCounting.py", line 152, in execute
    data = self.inputs["Input"][key].wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 481, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 306, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\operators\opArrayCache.py", line 356, in execute
    return self._executeOutput(slot, subindex, roi, result)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\operators\opArrayCache.py", line 471, in _executeOutput
    dirtyPool.wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1289, in wait
    self._clear_finishing_requests()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1366, in _clear_finishing_requests
    req.block()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 487, in block
    self._wait(timeout) # No return value. Use wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 306, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 770, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\counting\countingOperators.py", line 387, in execute
    forests=self.inputs["Classifier"][:].wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 481, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 306, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\operators\valueProviders.py", line 299, in execute
    value = request.wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 481, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 306, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\slot.py", line 850, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\counting\countingOperators.py", line 307, in execute
    pool.wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1289, in wait
    self._clear_finishing_requests()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1366, in _clear_finishing_requests
    req.block()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 487, in block
    self._wait(timeout) # No return value. Use wait()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 507, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\lazyflow\lazyflow\request\request.py", line 306, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\counting\countingOperators.py", line 303, in train_and_store
    = self.numRegressors, trainAll = False)
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\counting\countingsvr.py", line 573, in fitPrepared
    raise err
RuntimeError: No gurobi wrapper found

**Comment by akreshuk** [comment]
Thanks for the report, we'll take a look. I thought the "pop from empty list" problem has been solved already, can you say something about your steps to reproduce it? Does it happen when adding files to batch processing? Are you trying to remove files as well or just add?

**Comment by vothx042** [comment]
So the "pop from empty list" happens when I use the live update feature, then either add training data or turn the live update off and try to turn it back on. It is an easy fix though. All I have to do is save the project, close it, and reopen it.

**Comment by vothx042** [comment]
Also, thank you for the quick response. I am trying to process these images ASAP, so any advice or solutions would be fantastic.

**Comment by akreshuk** [comment]
Do you have "RandomForest" selected in the Algorithm dropdown menu? If not, can you change it to Random Forest? I can't reproduce it on Linux with the latest release, but these outside libraries sometimes cause different problems on different platforms.

**Comment by vothx042** [comment]
I run on Windows 10, and RandomForest is the only option I have. I am using the cell density counting function, by the way.

**Comment by akreshuk** [comment]
Can you try our latest version, I just announced it on the website? We have solved some issues with outside solvers, perhaps it will go away by itself. If not, we'll debug on Windows.

**Comment by vothx042** [comment]
Starting ilastik from "C:\Program Files\ilastik-1.2.0".
ERROR 2017-05-17 11:44:12,089 excepthooks 8424 9864 Unhandled exception in thread: 'MainThread'
ERROR 2017-05-17 11:44:12,094 excepthooks 8424 9864 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\shell\gui\startShellGui.py", line 91, in launchShell
    from ilastik.shell.gui.ilastikShell import IlastikShell
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 83, in <module>
    import ilastik.workflows
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\workflows\__init__.py", line 45, in <module>
    import objectClassification
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\workflows\objectClassification\__init__.py", line 27, in <module>
    from objectClassificationWorkflow import \
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\workflows\objectClassification\objectClassificationWorkflow.py", line 37, in <module>
    from ilastik.applets.thresholdTwoLevels import ThresholdTwoLevelsApplet, OpThresholdTwoLevels
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\thresholdTwoLevels\__init__.py", line 21, in <module>
    from thresholdTwoLevelsApplet import ThresholdTwoLevelsApplet
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\thresholdTwoLevels\thresholdTwoLevelsApplet.py", line 23, in <module>
    from opThresholdTwoLevels import OpThresholdTwoLevels
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\thresholdTwoLevels\opThresholdTwoLevels.py", line 35, in <module>
    from _OpGraphCut import segmentGC
  File "C:\Program Files\ilastik-1.2.0\ilastik-meta\ilastik\ilastik\applets\thresholdTwoLevels\_OpGraphCut.py", line 34, in <module>
    import opengm
  File "C:\Program Files\ilastik-1.2.0\lib\site-packages\opengm\__init__.py", line 27, in <module>
    for infClass,infName in _inject_interface(_solverDicts):
  File "C:\Program Files\ilastik-1.2.0\lib\site-packages\opengm\_inference_interface_generator.py", line 797, in _inject_interface
    result.append(classGenerator(algName, a, adhp, ec))
  File "C:\Program Files\ilastik-1.2.0\lib\site-packages\opengm\_inference_interface_generator.py", line 661, in classGenerator
    """ % (generateParamHelp(),)
  File "C:\Program Files\ilastik-1.2.0\lib\site-packages\opengm\_inference_interface_generator.py", line 473, in generateParamHelp
    exampleParam = inferenceClasses.anyParameterClass()
  File "C:\Program Files\ilastik-1.2.0\lib\site-packages\opengm\_inference_parameter_injector.py", line 32, in newInit
    baseInit(self_proxy)
  File "C:\Program Files\ilastik-1.2.0\lib\site-packages\opengm\_inference_parameter_injector.py", line 33, in newInit
    self_proxy._after_init(*args[1:len(args)],**kwargs)
  File "C:\Program Files\ilastik-1.2.0\lib\site-packages\opengm\_inference_parameter_injector.py", line 52, in _after_init
    self.set()
ArgumentError: Python argument types in
    _Icm.set(_Icm)
did not match C++ signature:
    set(class opengm::ICM<class opengm::GraphicalModel<double,struct opengm::Adder,struct opengm::meta::TypeList<class opengm::ExplicitFunction<double,unsigned __int64,unsigned __int64>,struct opengm::meta::TypeList<class opengm::PottsFunction<double,unsigned __int64,unsigned __int64>,struct opengm::meta::TypeList<class opengm::PottsNFunction<double,unsigned __int64,unsigned __int64>,struct opengm::meta::TypeList<class opengm::PottsGFunction<double,unsigned __int64,unsigned __int64>,struct opengm::meta::TypeList<class opengm::TruncatedAbsoluteDifferenceFunction<double,unsigned __int64,unsigned __int64>,struct opengm::meta::TypeList<class opengm::TruncatedSquaredDifferenceFunction<double,unsigned __int64,unsigned __int64>,struct opengm::meta::TypeList<class opengm::SparseFunction<double,unsigned __int64,unsigned __int64,class std::map<unsigned __int64,double,struct std::less<unsigned __int64>,class std::allocator<struct std::pair<unsigned __int64 const ,double> > > >,struct opengm::meta::TypeList<class opengm::functions::learnable::LPotts<double,unsigned __int64,unsigned __int64>,struct opengm::meta::TypeList<class opengm::functions::learnable::LUnary<double,unsigned __int64,unsigned __int64>,struct opengm::meta::ListEnd> > > > > > > > >,class opengm::DiscreteSpace<unsigned __int64,unsigned __int64> >,struct opengm::Maximizer>::Parameter {lvalue}, enum opengm::python::pyenums::IcmMoveType moveType=opengm.opengmcore._opengmcore.IcmMoveType.variable)

**Comment by vothx042** [comment]
Just downloaded the new version (sorry the ilastik program file says 1.2.0) and it can't open.

**Comment by akreshuk** [comment]
Oh my, looks like we have more testing to do...
Ok, new try to pin it down (in the old version you can still run): have you defined any box constraints? That is, have you typed in the right count number for any box?

**Comment by vothx042** [comment]
I tried updating my C++ in case that was the issue, but that did not change the error message. Also, I did not know you can type in the right count number into a box I make, so I am not sure.  If I draw a box and click "live update", I get a decimal number in the upper left corner. Are you saying I can edit that count to be the number I count by eye?

**Comment by akreshuk** [comment]
Yes, you can edit it if you have those solvers installed. But you don't, and it still behaves as if you do. Your C++ is not a problem, it's something on our side. If you need it resolved quickly, the best way would be to try a non-Windows machine. You should still be able to open the project you created, but the batch processing should work. If you are in academia, another option is to actually get a gurobi license, it's free for academic use: http://www.gurobi.com/academia/for-universities. But I have to admit I don't know if this will resolve your problem, since it shouldn't have asked for the license to begin with.

**Comment by vothx042** [comment]
I will try obtaining the gurobi license and see if that works. When the error " RuntimeError: No gurobi wrapper found" occurs, is that saying I do not have the proper license?

**Comment by vothx042** [comment]
I cannot find the ilastik 1.2.0 edition on the website... The 1.2.0rc10 edition wasn't the one I had before...

**Comment by vothx042** [comment]
Getting the gurobi license seemed to bypass the problem. I am attempting to run the batch process right now to see if that works.

**Comment by vothx042** [comment]
Batch Processing works. Thank you for your help!

**Comment by FynnBe** [comment]
I was trying to reproduce this on the current version 1.2.2rc3. The "pop from empty list" pops up a lot when playing around with the Counting applet.
However, when using Batch Processing I get a different Error: Python crashes with 
```
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QTextDocument(0xc7887f00), parent's thread is QThread(0x1253f100), current thread is QThread(0x6ac7c610)
```

**Comment by FynnBe** [comment]
without CPLEX I get the same error:
```
 Python argument types in
    _Icm.set(_Icm)
did not match C++ signature:
...
```

**Comment by vothx042** [comment]
Just letting you know, the "No gurobi wrapper found" error is still happening.

**Comment by vothx042** [comment]
This cell density counting has given me the "No gurobi wrapper found" in both Windows and Linux. I downloaded linux Ubuntu and ran it through Oracle VM VirtualBox using my same project, and it gave the same error. It seems it is an error in the project itself... But when I start an entirely new project I get the same error message. I am using the same training images... Is there a problem with them? I am getting frustrated as this is the only software I can use for this project...

**Comment by akreshuk** [comment]
Sorry it's giving you so much trouble. Can you send us a complete project, with the raw data copied inside (you can do that by double-clicking on the dataset in the Input Data applet and choosing "Copy to project file" in the Storage dropdown menu)? Perhaps it will be easier to reproduce then. Also, does it only happen in batch mode? Can you update the total image density interactively without crashes?

**Comment by vothx042** [comment]
Can you email me at vothx042@umn.edu so I can send you the project? It is too big to upload here.

**Comment by akreshuk** [comment]
I am really mystified by this problem. I can run your project file without any error messages. What i did: opened MyProject.ilp, clicked "Update total density", waited for a long time, proceeded to prediction export, then to batch processing, all worked. In the csv file I get the following total densities: 16.32, 16.32, 4842.91, 8387.3, no idea if it makes sense. I don't have gurobi installed on this machine. We'll try on a blanc test machine, perhaps something is still helping in my environment.

**Comment by vothx042** [comment]
Interesting, I have not clicked "Update total density" before... Maybe that is my problem. Let me try that and get back to you.

**Comment by vothx042** [comment]
That is all it takes to bypass the problem. I clicked on that and it worked. So, to recreate the problem, you need to open the project and go directly to export. This should give the "No gurobi wrapper found" error.

**Comment by sneuner** [comment]
I am getting similar errors and trying to work through both the "No gurobi wrapper found" and "pop from empty list errors". I have only loaded a single image and can't even get through training, so I am still struggling with that to even try. I did want to ask - @akreshuk, can you expand on how to manually enter the correct number of objects into each box? I have not seen that mentioned anywhere else.
