### ISSUE TITLE
ilastik-1.2.2rc3: dataset's provided axistags (yxc) do not have the correct dimensionality

### ISSUE THREAD

**Issue by AVKazak** [ilastik/ilastik#1524]
Greetings!

  I created a project, trained classifier, saved the project and try to go headless with on Windows:
`C:\Program Files\ilastik-1.2.2rc3>run-ilastik.bat --headless --project="C:\Users\A.Kazak\Desktop\iTest\GeraniumFlowerUnfurl2.ilp" "C:\Users\A.Kazak\Desktop\iTest\Input\*.tif"`

  However it fails with the following error.
  What is my mistake?
  Thank you.

Loading ilastik from "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta"
WARNING 2017-05-30 08:46:37,711 vigraOperators 18388 7796 Failed to import fast filters: No module named fastfilters
INFO ilastik_main: Starting ilastik from "C:\Program Files\ilastik-1.2.2rc3".
Starting ilastik from "C:\Program Files\ilastik-1.2.2rc3".
WARNING 2017-05-30 08:46:40,174 tracking_h5_event_export 18388 7796 Could not load hytra. Event exporting plugin not loaded.
WARNING 2017-05-30 08:46:40,456 __init__ 18388 7796 Failed to import automatic tracking workflow (conservation tracking). For this workflow, see the i
nstallationinstructions on our website ilastik.org; check dependencies: No module named pgmlinkNoIlpSolver
WARNING 2017-05-30 08:46:40,516 __init__ 18388 7796 Failed to import structured learning tracking workflow. For this workflow, see the installationins
tructions on our website ilastik.org; check dependencies: DLL load failed: The specified module could not be found.
WARNING 2017-05-30 08:46:42,710 __init__ 18388 7796 Failed to import 'Edge Training With Multicut' workflow; check dependencies: Can't import OpMultic
ut: No solver libraries detected!
INFO ilastik.shell.projectManager: Opening Project: C:/Users/A.Kazak/Desktop/iTest/GeraniumFlowerUnfurl2.ilp
WARNING dataset.py(70): DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function
instead.
INFO ilastik.workflows.pixelClassification.pixelClassificationWorkflow: Beginning Batch Processing
ERROR 2017-05-30 08:46:43,644 log_exception 18388 7796 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 443, in _loadProject
    self.workflow.onProjectLoaded( self )
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik\workflows\pixelClassification\pixelClassificationWorkflow.py", line 334, in onP
rojectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 60, in run_export_from_
parsed_args
    return self.run_export(role_path_dict, parsed_args.input_axes)
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 123, in run_export
    export_to_array=export_to_array )
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 213, in _run_export_wit
h_empty_batch_lane
    opDataSelectionBatchLaneView.DatasetGroup[role_index].setValue(info)
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\slot.py", line 1221, in setValue
    self._changed()
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\slot.py", line 1421, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\slot.py", line 1421, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\slot.py", line 1421, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\slot.py", line 1427, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\slot.py", line 1441, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\operator.py", line 450, in _setupOutputs
    self.setupOutputs()
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik\applets\dataSelection\opDataSelection.py", line 361, in setupOutputs
    .format( "".join(tag.key for tag in datasetInfo.axistags), len(providerSlot.meta.shape) ) )
Exception: Your dataset's provided axistags (yxc) do not have the correct dimensionality for your dataset, which has 4 dimensions.

ERROR 2017-05-30 08:46:43,645 log_exception 18388 7796 Project could not be loaded due to the exception shown above.
Aborting Project Open Action
ERROR 2017-05-30 08:46:43,851 excepthooks 18388 7796 Unhandled exception in thread: 'MainThread'
ERROR 2017-05-30 08:46:43,854 excepthooks 18388 7796 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik.py", line 122, in <module>
    main()
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik.py", line 108, in main
    ilastik_main.main(parsed_args, workflow_cmdline_args)
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik_main.py", line 107, in main
    f(shell)
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik_main.py", line 303, in loadProject
    shell.openProjectFile(path, parsed_args.readonly)
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik\shell\headless\headlessShell.py", line 116, in openProjectFile
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\utility\timer.py", line 142, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 443, in _loadProject
    self.workflow.onProjectLoaded( self )
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik\workflows\pixelClassification\pixelClassificationWorkflow.py", line 334, in onP
rojectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 60, in run_export_from_
parsed_args
    return self.run_export(role_path_dict, parsed_args.input_axes)
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 123, in run_export
    export_to_array=export_to_array )
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 213, in _run_export_wit
h_empty_batch_lane
    opDataSelectionBatchLaneView.DatasetGroup[role_index].setValue(info)
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\slot.py", line 1221, in setValue
    self._changed()
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\slot.py", line 1421, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\slot.py", line 1421, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\slot.py", line 1421, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\slot.py", line 1427, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\slot.py", line 1441, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\lazyflow\lazyflow\operator.py", line 450, in _setupOutputs
    self.setupOutputs()
  File "C:\Program Files\ilastik-1.2.2rc3\ilastik-meta\ilastik\ilastik\applets\dataSelection\opDataSelection.py", line 361, in setupOutputs
    .format( "".join(tag.key for tag in datasetInfo.axistags), len(providerSlot.meta.shape) ) )
**Exception: Your dataset's provided axistags (yxc) do not have the correct dimensionality for your dataset, which has 4 dimensions.**

**Comment by k-dominik** [comment]
Hi @AVKazak ,

really unfortunate, that you are experiencing problems with ilastik. I can see that you are trying to do pixel classification. Thanks for including it right away! Is it correct to assume, that you have trained on a stack of colored 2d-slices? And the testing data is in the same form?

**Comment by AVKazak** [comment]
Dear Dominik,

  Yes, I try to do pixel classification. Yes I trained the classifier with one test color image and try to apply it to do pixel classification for the rest. I done all in the GUI using exactly the same format of test and target images and even ran Batch Processing in GUI quite successfully. Now I want to learn how to do the same headlessly.

  Where could I get wrong?

Thank you.

**Comment by AVKazak** [comment]
Dear Dominik,
  Can you an update for the topic please?
Thank you.

**Comment by k-dominik** [comment]
Dear @AVKazak, would you mind sending us an example image? That would make it easier to reproduce the problem.

**Comment by AVKazak** [comment]
Dear @k-dominik, 
Please download an archive with original image and its mask used to train the image with all features:
http://dropmefile.com/N6LVZ

**Comment by k-dominik** [comment]
Thanks for the data! I have tried it on linux and it doesn't present me with the described problem. @FynnBe will try it on Windows and we'll get back to you with our findings.

**Comment by k-dominik** [comment]
Hey @AVKazak , not having copy-pasted your command being on linux and not on windows, I have just realized that you might have passed your input file as a stack by enclosing it in quotation marks ```"C:\Users\A.Kazak\Desktop\iTest\Input\*.tif" ```. Ilastik will interpret the ```*``` character and try to assemble a stack (with one more dimension). You could try removing the quotation marks when running the command:

```dos
C:\Program Files\ilastik-1.2.2rc3>run-ilastik.bat --headless --project="C:\Users\A.Kazak\Desktop\iTest\GeraniumFlowerUnfurl2.ilp" C:\Users\A.Kazak\Desktop\iTest\Input\*.tif
```

or list the images explicitly, e.g.:

```dos
C:\Program Files\ilastik-1.2.2rc3>run-ilastik.bat --headless --project="C:\Users\A.Kazak\Desktop\iTest\GeraniumFlowerUnfurl2.ilp" C:\Users\A.Kazak\Desktop\iTest\Input\01.tif C:\Users\A.Kazak\Desktop\iTest\Input\02.tif ...
```

**Comment by FynnBe** [comment]
I can reproduce the issue and specifying the images explicitly works for me. 
Leaving out the quotation marks does not.
Side note: I'm having trouble when the project file and the data are not in the same location.

**Comment by AVKazak** [comment]
OK, I see.
If I drop the quotation marks, then what how to handle whitespaces in my directory/file names?
Can I use escape sequence **"\ "** in this case?

**Comment by FynnBe** [comment]
If you specify each image explicitly you can use quotation marks.

**Comment by AVKazak** [comment]
I am sorry for a long delay.
I have tested the same with ilastik-1.2.2rc4 for Windows and should report that the following commands give the error (see below):
`C:\Program Files\ilastik-1.2.2rc4>run-ilastik.bat --headless --project="C:\Users\A.Kazak\Desktop\iTest\GeraniumFlowerUnfurl2.ilp" C:\Users\A.Kazak\Desktop\iTest\Input\*.tif`
`C:\Program Files\ilastik-1.2.2rc4>run-ilastik.bat --headless --project="C:\Users\A.Kazak\Desktop\iTest\GeraniumFlowerUnfurl2.ilp" "C:\Users\A.Kazak\Desktop\iTest\Input\*.tif"`

Good news that listing the target images explicitly works fine. However I have quite a few of target images and it seems that explicit listing option is not viable.

How else can I try overcoming ***.tif** issue?
Thank you.

> Loading ilastik from "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta"
> WARNING 2017-08-17 22:13:16,575 vigraOperators 11348 2420 Failed to import fast filters: No module named 
> fastfilters
> INFO ilastik_main: Starting ilastik from "C:\Program Files\ilastik-1.2.2rc4".
> Starting ilastik from "C:\Program Files\ilastik-1.2.2rc4".
> WARNING 2017-08-17 22:13:18,155 tracking_h5_event_export 11348 2420 Could not load hytra. Event exporting 
> plugin not loaded.
> WARNING 2017-08-17 22:13:18,305 __init__ 11348 2420 Failed to import automatic tracking workflow (
> conservation tracking). For this workflow, see the installationinstructions on our website ilastik.org; check 
> dependencies: No module named pgmlinkNoIlpSolver
> WARNING 2017-08-17 22:13:18,345 __init__ 11348 2420 Failed to import structured learning tracking workflow. 
> For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: DLL load 
> failed: The specified module could not be found.
> WARNING 2017-08-17 22:13:19,796 __init__ 11348 2420 Failed to import 'Edge Training With Multicut' workflow; 
> check dependencies: Can't import OpMulticut: No solver libraries detected!
> INFO ilastik.shell.projectManager: Opening Project: C:/Users/A.Kazak/Desktop/iTest/GeraniumFlowerUnfurl2.ilp
> WARNING dataset.py(70): DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `
> ~` operator or the logical_not function instead.
> INFO ilastik.workflows.pixelClassification.pixelClassificationWorkflow: Beginning Batch Processing
> ERROR 2017-08-17 22:13:20,676 log_exception 11348 2420 Traceback (most recent call last):
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 443, in 
> _loadProject
>     self.workflow.onProjectLoaded( self )
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik\workflows\pixelClassification\
> pixelClassificationWorkflow.py", line 334, in onProjectLoaded
>     self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik\applets\batchProcessing\
> batchProcessingApplet.py", line 60, in run_export_from_parsed_args
>     return self.run_export(role_path_dict, parsed_args.input_axes)
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik\applets\batchProcessing\
> batchProcessingApplet.py", line 123, in run_export
>     export_to_array=export_to_array )
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik\applets\batchProcessing\
> batchProcessingApplet.py", line 213, in _run_export_with_empty_batch_lane
>     opDataSelectionBatchLaneView.DatasetGroup[role_index].setValue(info)
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in 
> call_in_setup_context
>     return func(self, *args, **kwargs)
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\slot.py", line 1221, in setValue
>     self._changed()
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\slot.py", line 1421, in _changed
>     c._changed()
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\slot.py", line 1421, in _changed
>     c._changed()
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\slot.py", line 1421, in _changed
>     c._changed()
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\slot.py", line 1427, in _changed
>     self._configureOperator(self)
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\slot.py", line 1441, in 
> _configureOperator
>     self.operator._setupOutputs()
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\operator.py", line 450, in 
> _setupOutputs
>     self.setupOutputs()
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik\applets\dataSelection\opDataSelection.
> py", line 361, in setupOutputs
>     .format( "".join(tag.key for tag in datasetInfo.axistags), len(providerSlot.meta.shape) ) )
> Exception: Your dataset's provided axistags (yxc) do not have the correct dimensionality for your dataset, 
> which has 4 dimensions.
> 
> ERROR 2017-08-17 22:13:20,676 log_exception 11348 2420 Project could not be loaded due to the exception shown 
> above.
> Aborting Project Open Action
> ERROR 2017-08-17 22:13:20,875 excepthooks 11348 2420 Unhandled exception in thread: 'MainThread'
> ERROR 2017-08-17 22:13:20,885 excepthooks 11348 2420 Traceback (most recent call last):
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik.py", line 122, in <module>
>     main()
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik.py", line 108, in main
>     ilastik_main.main(parsed_args, workflow_cmdline_args)
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik_main.py", line 107, in main
>     f(shell)
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik_main.py", line 270, in loadProject
>     shell.openProjectFile(path, parsed_args.readonly)
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik\shell\headless\headlessShell.py", line 
> 116, in openProjectFile
>     self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\utility\timer.py", line 142, in 
> wrapper
>     return func(*args, **kwargs)
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 443, in 
> _loadProject
>     self.workflow.onProjectLoaded( self )
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik\workflows\pixelClassification\
> pixelClassificationWorkflow.py", line 334, in onProjectLoaded
>     self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik\applets\batchProcessing\
> batchProcessingApplet.py", line 60, in run_export_from_parsed_args
>     return self.run_export(role_path_dict, parsed_args.input_axes)
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik\applets\batchProcessing\
> batchProcessingApplet.py", line 123, in run_export
>     export_to_array=export_to_array )
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik\applets\batchProcessing\
> batchProcessingApplet.py", line 213, in _run_export_with_empty_batch_lane
>     opDataSelectionBatchLaneView.DatasetGroup[role_index].setValue(info)
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\slot.py", line 110, in 
> call_in_setup_context
>     return func(self, *args, **kwargs)
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\slot.py", line 1221, in setValue
>     self._changed()
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\slot.py", line 1421, in _changed
>     c._changed()
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\slot.py", line 1421, in _changed
>     c._changed()
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\slot.py", line 1421, in _changed
>     c._changed()
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\slot.py", line 1427, in _changed
>     self._configureOperator(self)
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\slot.py", line 1441, in 
> _configureOperator
>     self.operator._setupOutputs()
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\lazyflow\lazyflow\operator.py", line 450, in 
> _setupOutputs
>     self.setupOutputs()
>   File "C:\Program Files\ilastik-1.2.2rc4\ilastik-meta\ilastik\ilastik\applets\dataSelection\opDataSelection.
> py", line 361, in setupOutputs
>     .format( "".join(tag.key for tag in datasetInfo.axistags), len(providerSlot.meta.shape) ) )
> Exception: Your dataset's provided axistags (yxc) do not have the correct dimensionality for your dataset, 
> which has 4 dimensions.

**Comment by jwindhager** [comment]
I can confirm this for rc3. Makes running large Ilastik batch processes in headless mode impossible on Windows machines.
