### ISSUE TITLE
Axes reordering: switching from 3D to 2D+t without X gives weird error

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1528]
I guess we should simply tell the user that this is not allowed, right?

Currently, this is the error message we spit out:
```pytb
ERROR 2017-05-31 15:56:18,489 excepthooks 27482 123145580716032 Traceback (most recent call last):
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/volumina/volumina/tiling.py", line 768, in _fetch_tile_layer
    img = ims_req.wait()
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 158, in wait
    return self.toImage()
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 164, in toImage
    self._arrayreq.wait()
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/volumina/volumina/pixelpipeline/slicesources.py", line 43, in wait
    return self._sp(self._ar.wait())
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 464, in wait
    rawData = self._rawRequest.wait()
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 201, in wrapper
    return func(*args, **kwargs)
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 225, in wait
    a = self._req.wait()
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/lazyflow/lazyflow/request/request.py", line 487, in wait
    return self._wait(timeout)
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/lazyflow/lazyflow/request/request.py", line 513, in _wait
    self._wait_within_request( current_request )
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/lazyflow/lazyflow/request/request.py", line 312, in _execute
    self._result = self.fn()
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/lazyflow/lazyflow/slot.py", line 861, in __call__
    destination = self.slot.stype.allocateDestination(self.roi)
  File "/Users/chaubold/opt/miniconda/envs/ilastik12/ilastik-meta/lazyflow/lazyflow/stype.py", line 109, in allocateDestination
    storage = numpy.ndarray(shape, dtype=self.slot.meta.dtype)
ValueError: negative dimensions are not allowed
```

**Comment by chaubold** [comment]
When stepping in with the debugger, it has indeed a negative shape: 
```
roi = Subregion: start '[0, 688, 512, 512, 0]' stop '[1, 1, 1038, 1024, 1]'
shape = [1, -687, 526, 512, 1]
```
Which looks like a completely random number, because the dataset has a size of `104` along the axis that turns negative.
