### ISSUE TITLE
No dataset description in 'tracking result export' applet and export fails

### ISSUE THREAD

**Issue by FynnBe** [ilastik/ilastik#1556]
![tracking result export bug](https://user-images.githubusercontent.com/15139589/27696402-cbb93716-5cf1-11e7-9633-799248e6dddf.png)

after clicking on 'Export All':
```
ERROR 2017-06-29 17:38:06,996 log_exception 8912 13112 Traceback (most recent call last):
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\applets\dataExport\dataExportGui.py", line 393, in exportSlots
    opLaneView.run_export()
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\applets\tracking\base\opTrackingBaseDataExport.py", line 41, in run_export
    super(OpTrackingBaseDataExport, self).run_export()
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\applets\dataExport\opDataExport.py", line 269, in run_export
    self._opFormattedExport.run_export()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\operators\ioOperators\opFormattedDataExport.py", line 242, in run_export
    self._opExportSlot.run_export()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\operators\ioOperators\opExportSlot.py", line 233, in run_export
    mkdir_p( PathComponents(self.ExportPath.value).externalDirectory )
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\slot.py", line 1100, in value
    temp =  self[:].wait()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\slot.py", line 1016, in __getitem__
    raise Slot.SlotNotReadyError(slotInfoMsg)
SlotNotReadyError: Can't get data from slot <class 'lazyflow.operators.ioOperators.opExportSlot.OpExportSlot'>.ExportPath yet. It isn't ready.First upstream problem slot is: OpExportSlot/OpExportSlot.Input : 	{_ready : False, shape : None, has_mask : None, _dirty : True}


ERROR 2017-06-29 17:38:06,996 log_exception 8912 13112 Failed to generate export file.
Can't get data from slot <class 'lazyflow.operators.ioOperators.opExportSlot.OpExportSlot'>.ExportPath yet. It isn't ready.First upstream problem slot is: OpExportSlot/OpExportSlot.Input : 	{_ready : False, shape : None, has_mask : None, _dirty : True}
```

**Comment by chaubold** [comment]
This seems to be a Windows-only problem, I was not able to reproduce it on MacOS with the current master of ilastik. I didn't try to use `pgmlink` as tracking backend on MacOS though, which could be a good check to see whether some lane connection is off.

**Comment by chaubold** [comment]
Did you try this with the python 3 version already? Should be fixed (at least the headless export tests pass which use the `run_export` method as well).
