### ISSUE TITLE
Loading project on Linux leads to SegFault

### ISSUE THREAD

**Issue by david-hoffman** [ilastik/ilastik#1563]
When I try to load a project file that works fine on the Windows version of ilastik it causes a `Segmentation fault` on the Linux version.

Print out of the error below

```
Found system libstdc++ version: 3.4.22
Found conda  libstdc++ version: 3.4.22
Starting ilastik from "/home/hoffmand/ilastik-1.2.2rc4-Linux".
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 14 (X_GetGeometry)
  Resource id:  0x3600137
OpenGL Warning: No pincher, please call crStateSetCurrentPointers() in your SPU
ERROR: In /miniconda/conda-bld/vtk_1491876129458/work/VTK5.10.1/Rendering/vtkOpenGLExtensionManager.cxx, line 393
vtkOpenGLExtensionManager (0x843fb40): Extension GL_VERSION_1_5 could not be loaded.

Fatal Python error: Segmentation fault

Thread 0x00007f01ee783700 (most recent call first):
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 359 in wait
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 614 in wait
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 1071 in run
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 801 in __bootstrap_inner
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 774 in __bootstrap

Thread 0x00007f01f5526700 (most recent call first):
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 359 in wait
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/operators/cacheMemoryManager.py", line 240 in _wait
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/operators/cacheMemoryManager.py", line 159 in run
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 801 in __bootstrap_inner
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 774 in __bootstrap

Thread 0x00007f0230bb9700 (most recent call first):
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 340 in wait
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 211 in _get_next_job
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 157 in run
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 801 in __bootstrap_inner
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 774 in __bootstrap

Thread 0x00007f02313ba700 (most recent call first):
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 340 in wait
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 211 in _get_next_job
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 157 in run
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 801 in __bootstrap_inner
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 774 in __bootstrap

Thread 0x00007f0231bbb700 (most recent call first):
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 340 in wait
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 211 in _get_next_job
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 157 in run
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 801 in __bootstrap_inner
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 774 in __bootstrap

Thread 0x00007f02323bc700 (most recent call first):
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 340 in wait
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 211 in _get_next_job
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 157 in run
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 801 in __bootstrap_inner
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 774 in __bootstrap

Thread 0x00007f0232bbd700 (most recent call first):
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 340 in wait
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 211 in _get_next_job
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 157 in run
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 801 in __bootstrap_inner
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 774 in __bootstrap

Thread 0x00007f02333be700 (most recent call first):
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 340 in wait
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 211 in _get_next_job
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 157 in run
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 801 in __bootstrap_inner
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 774 in __bootstrap

Thread 0x00007f0233bbf700 (most recent call first):
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 340 in wait
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 211 in _get_next_job
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 157 in run
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 801 in __bootstrap_inner
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 774 in __bootstrap

Thread 0x00007f024ffff700 (most recent call first):
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 340 in wait
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 211 in _get_next_job
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 157 in run
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 801 in __bootstrap_inner
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/threading.py", line 774 in __bootstrap

Current thread 0x00007f027ea49700 (most recent call first):
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/volumina/volumina/view3d/view3d.py", line 152 in update
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/volumina/volumina/view3d/view3d.py", line 228 in resizeEvent
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 1085 in showCentralWidget
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 1060 in setSelectedAppletDrawer
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 1538 in _loadProject
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 1425 in openProjectFile
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 1397 in onOpenProjectActionTriggered
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik/shell/gui/startShellGui.py", line 69 in startShellGui
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik_main.py", line 112 in main
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik.py", line 108 in main
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik.py", line 122 in <module>
./run_ilastik.sh: line 72: 15759 Segmentation fault      (core dumped) "${PREFIX}/bin/python" "${PREFIX}/ilastik-meta/ilastik/ilastik.py" "$@"
```

**Comment by stuarteberg** [comment]
If you simply delete `/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/libstdc++.so.6` from the binary, does that fix the issue?

**Comment by david-hoffman** [comment]
It stops the seg fault but another issue comes up:

```
ERROR 2017-07-20 15:39:18,986 volumeEditor 32646 140706983053120 Warning: could not import optional dependency VTK
ERROR 2017-07-20 15:40:00,500 excepthooks 32646 140706983053120 Unhandled exception in thread: 'MainThread'
ERROR 2017-07-20 15:40:00,505 excepthooks 32646 140706983053120 Traceback (most recent call last):
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 1039, in handleAppletBarItemExpanded
    self.setSelectedAppletDrawer(drawerIndex)
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 1060, in setSelectedAppletDrawer
    self.showCentralWidget(applet_index)
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 1075, in showCentralWidget
    centralWidget = self._applets[applet_index].getMultiLaneGui().centralWidget()
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik/applets/base/singleToMultiGuiAdapter.py", line 64, in centralWidget
    if self.currentGui() is None:
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik/applets/base/singleToMultiGuiAdapter.py", line 44, in currentGui
    self._guis[self._imageLaneIndex] = self.singleImageGuiFactory( self._imageLaneIndex )
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik/applets/base/standardApplet.py", line 136, in __createSingleLaneGui
    if self.singleLaneGuiClass is NotImplemented:
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik/applets/pixelClassification/pixelClassificationApplet.py", line 70, in singleLaneGuiClass
    from pixelClassificationGui import PixelClassificationGui
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/ilastik/ilastik/applets/pixelClassification/pixelClassificationGui.py", line 58, in <module>
    from volumina.view3d.volumeRendering import RenderingManager
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/volumina/volumina/view3d/volumeRendering.py", line 23, in <module>
    import vtk
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/site-packages/vtk/__init__.py", line 63, in <module>
    __helper.refine_import_err('rendering', 'vtkRenderingPython', exc)
  File "/home/hoffmand/ilastik-1.2.2rc4-Linux/lib/python2.7/site-packages/vtk/__helper.py", line 32, in refine_import_err
    raise LinkError, str(exc)
LinkError: libXss.so.1: cannot open shared object file: No such file or directory
```

Strangely, I can see the raw data, sometimes, but if I click on the training tab it raises the above exception.

**Comment by stuarteberg** [comment]
What version of Linux are you using?

**Comment by stuarteberg** [comment]
The `libXss.so.1` file is part of the X11 window system, and should provided by the OS.  (It's required by VTK and/or Qt, which we depend on.)  If you're using CentOS or Fedora, you can install it with this:

```
sudo yum install libXScrnSaver
```

If you're using ubuntu, try this:

```
sudo apt-get install libxss1
```

**Comment by david-hoffman** [comment]
```
$ uname --a
Linux hoffmand-VirtualBox 4.10.0-28-generic #32-Ubuntu SMP Fri Jun 30 05:32:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

I was also working within Windows Subsystem for linux:
```
Linux HOFFMAND-WW1 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux  
```

Removing the `libstdc++.so.6` from the binary does not remove the segfault in the Ubuntu system

**Comment by stuarteberg** [comment]
I guess somehow our 3D widget isn't cooperating with VirtualBox.  Try disabling it by editing this file:

```
/home/hoffmand/ilastik-1.2.2rc4-Linux/ilastik-meta/volumina/volumina/__init__.py
```

Set `NO3D = True`

**Comment by david-hoffman** [comment]
Looks like that did the trick

**Comment by k-dominik** [comment]
not using vtk anymore, this is hopefully gone
