### ISSUE TITLE
Live Update in Counting leads to IndexError: pop from empty list

### ISSUE THREAD

**Issue by FynnBe** [ilastik/ilastik#1577]
```
ERROR 2017-08-16 19:49:55,326 countingOperators 12460 6300 ERROR: could not learn regressor
ERROR 2017-08-16 19:49:55,328 countingOperators 12460 6300 fullFeatMatrix shape = (886L, 84L), dtype = float64
ERROR 2017-08-16 19:49:55,328 countingOperators 12460 6300 fullLabelsMatrix shape = (886L,), dtype = float64
ERROR 2017-08-16 19:49:55,342 excepthooks 12460 4808 Unhandled exception in thread: 'Worker #4'
ERROR 2017-08-16 19:49:55,349 excepthooks 12460 4808 Traceback (most recent call last):
  File "C:\Program Files\ilastik\ilastik-meta\volumina\volumina\tiling.py", line 768, in _fetch_tile_layer
    img = ims_req.wait()
  File "C:\Program Files\ilastik\ilastik-meta\volumina\volumina\pixelpipeline\imagesources.py", line 383, in wait
    return self.toImage()
  File "C:\Program Files\ilastik\ilastik-meta\volumina\volumina\pixelpipeline\imagesources.py", line 389, in toImage
    self._arrayreq.wait()
  File "C:\Program Files\ilastik\ilastik-meta\volumina\volumina\pixelpipeline\slicesources.py", line 43, in wait
    return self._sp(self._ar.wait())
  File "C:\Program Files\ilastik\ilastik-meta\volumina\volumina\pixelpipeline\datasources.py", line 464, in wait
    rawData = self._rawRequest.wait()
  File "C:\Program Files\ilastik\ilastik-meta\volumina\volumina\pixelpipeline\datasources.py", line 201, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\ilastik\ilastik-meta\volumina\volumina\pixelpipeline\datasources.py", line 225, in wait
    a = self._req.wait()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 487, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 513, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 312, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\slot.py", line 876, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\operators\opReorderAxes.py", line 143, in execute
    self.Input( *in_roi ).writeInto( result_input_view ).wait()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 487, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 513, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 312, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 776, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\slot.py", line 876, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\applets\counting\opCounting.py", line 152, in execute
    data = self.inputs["Input"][key].wait()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 487, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 513, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 312, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\slot.py", line 876, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\operators\opArrayCache.py", line 356, in execute
    return self._executeOutput(slot, subindex, roi, result)
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\operators\opArrayCache.py", line 471, in _executeOutput
    dirtyPool.wait()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1295, in wait
    self._clear_finishing_requests()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1372, in _clear_finishing_requests
    req.block()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 493, in block
    self._wait(timeout) # No return value. Use wait()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 513, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 312, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 776, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\slot.py", line 876, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\applets\counting\countingOperators.py", line 387, in execute
    forests=self.inputs["Classifier"][:].wait()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 487, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 513, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 312, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\slot.py", line 876, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\operators\valueProviders.py", line 299, in execute
    value = request.wait()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 487, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 513, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 312, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\slot.py", line 876, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\applets\counting\countingOperators.py", line 307, in execute
    pool.wait()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1295, in wait
    self._clear_finishing_requests()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1372, in _clear_finishing_requests
    req.block()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 493, in block
    self._wait(timeout) # No return value. Use wait()
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 513, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 312, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\applets\counting\countingOperators.py", line 303, in train_and_store
    = self.numRegressors, trainAll = False)
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\applets\counting\countingsvr.py", line 569, in fitPrepared
    regressor = self._fit(img[indices, :], dot[indices], newTags, newBoxConstraints)
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\applets\counting\countingsvr.py", line 593, in _fit
    regressor.fit(img, dot)
  File "C:\Program Files\ilastik\lib\site-packages\sklearn\ensemble\forest.py", line 261, in fit
    tree.set_params(random_state=random_state.randint(MAX_INT))
  File "C:\Program Files\ilastik\lib\site-packages\sklearn\base.py", line 241, in set_params
    valid_params = self.get_params(deep=True)
  File "C:\Program Files\ilastik\lib\site-packages\sklearn\base.py", line 217, in get_params
    warnings.filters.pop(0)
IndexError: pop from empty list
```

**Comment by k-dominik** [comment]
Hy @FynnBe , if you have time, you could check if you still encounter this error in the current version. Thx

**Comment by FynnBe** [comment]
It's gone in 1.2.2post1

**Comment by k-dominik** [comment]
This seems to still be an issue in v1.3.0 :/

**Comment by hannekeo** [comment]
Any progress on this error? I am trying to do density counting and I get "pop from empty list" when i try to run a batch of images.

**Comment by sneuner** [comment]
Any update? Still getting this error 09-14-2018 with ilastik 1.3.0, trying to do density counting (currently only have a single image loaded to begin training). I am able to set some parameters but eventually always get this error: "pop from empty list"

**Comment by k-dominik** [comment]
@hannekeo @sneuner this should be gone with https://github.com/ilastik/ilastik/pull/1810 . The fix will be available in the next release.

**Comment by sneuner** [comment]
@k-dominik any idea when the release will be available?

**Comment by k-dominik** [comment]
Oh, hey, I forgot to inform you, it already is. You can get `1.3.2rc1` on our [website](http://ilastik.org/download.html)
