### ISSUE TITLE
No module name distutils.versio

### ISSUE THREAD

**Issue by nickholway** [ilastik/ilastik#1593]
When running Ilastik 1.2.2 on RHEL 6.7 I get the following error when starting Ilastik:
```
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named distutils.version
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named distutils.version
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named distutils.version
Found system libstdc++ version: 
Found conda  libstdc++ version: 
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named distutils.version
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named distutils.version
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named distutils.version
```

**Comment by k-dominik** [comment]
Hi @nickholway,

how do you start ilastik? do you start it using `/your/ilastik/folder/run_ilastik.sh`?

**Comment by nickholway** [comment]
Hi, That's correct

**Comment by k-dominik** [comment]
Hi again,

i do not have the chance to try it on a rhel system here. We're all on Ubuntu.
Did you paste all output when starting ilastik there? I don't suppose there is a logfile `~/ilastik_log.txt` created, as the error is appearing so early in the startup. But could you still have a look there and paste possible contents? But in anyway it would already help if you pasted the whole command line from start to finish.

Cheers

**Comment by k-dominik** [comment]
Ok thank you. ilastik seems to be starting though. Have you tried the gui mode (no `--headless`)?

**Comment by nickholway** [comment]
This was starting the GUI and quitting immediately:
```
~/ilastik-1.2.2-Linux/run_ilastik.sh 
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named distutils.version
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named distutils.version
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named distutils.version
Found system libstdc++ version: 
Found conda  libstdc++ version: 
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named distutils.version
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named distutils.version
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named distutils.version
Starting ilastik from "/home/holwani1/ilastik-1.2.2-Linux".
```

**Comment by k-dominik** [comment]
Sorry for not getting back to you earlier.

So, just so that I understand the problem right; is the ilastik gui starting for you, despite these errors, and is it then usable, or is it closing as a result of these errors?

**Comment by k-dominik** [comment]
so, I think I might have been running into the same issue lately. Could you confirm, that `which python` gives you something that looks like it's python3 ?

**Comment by nickholway** [comment]
On our RHEL 6.x cluster there's only the standard python in /usr/bin

**Comment by k-dominik** [comment]
closing this - please reopen if anyone runs into this with `1.2.2post2`
