### ISSUE TITLE
 Object Classification: 2D Convex Hull Features not found in available (computed) object features

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1624]
Error thrown:

```
  File "/home/jales/software/miniconda/envs/p3-ilastik/ilastik-meta/ilastik/ilastik/applets/objectClassification/objectClassificationGui.py", line 339, in handleSubsetFeaturesClicked
    assert pluginInfo.name in list(computedFeatures.keys()), 'Object Classification: {} not found in available (computed) object features'.format(pluginInfo.name)
AssertionError: Object Classification: 2D Convex Hull Features not found in available (computed) object features
```

this is suposed to be already addressed in non-merged PR:
 https://github.com/ilastik/ilastik/pull/1615

**Comment by chaubold** [comment]
Could you please try again now that #1615 is merged?

**Comment by akreshuk** [comment]
@ilastikdev, is it fixed now?

**Comment by k-dominik** [comment]
Ran into this again in `1.4.2`

```pytb
ERROR 2026-06-17 12:04:54,623 excepthooks 29490 8458251328 Unhandled exception in thread: 'MainThread'
ERROR 2026-06-17 12:04:54,626 excepthooks 29490 8458251328 Traceback (most recent call last):
  File "/private/var/folders/_g/bwdf9cs14c98wt0r68blcd8c0000gp/T/AppTranslocation/8E673076-8403-421A-9F7C-481A96474CA9/d/ilastik-1.4.2-arm64-OSX.app/Contents/ilastik-release/lib/python3.11/site-packages/ilastik/applets/objectClassification/objectClassificationGui.py", line 448, in handleSubsetFeaturesClicked
    assert pluginInfo.name in list(
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Object Classification: 2D Skeleton Features not found in available (computed) object features
```

seems to happen with old projects? I encountered it with the mitocheck example from our website. Does not happen if I create a new project. Probably related to added / renamed features - which tracking should be able to deal with (as long as features are not missing, which is an error).
