### ISSUE TITLE
Tracking with Learning tests fail

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1648]
@ilastikdev: No matter whether I use ilastik `master` or the `tracking_annotations` (PR #1643) branch, using the latest `hytra` version and with solvers (`multi-hypotheses-tracking-with-cplex` or `multi-hypotheses-tracking-with-gurobi`) installed, the structured learning tracking tests fail. 
Calculating the weights works fine in the GUI with `master`, but in PR #1643 it gets stuck in the learning step and just doesn't proceed without any CPU usage.

```
ERROR: tests.test_applets.structuredLearningTracking.testStructuredLearningTrackingHytraWithDivisions.TestStructuredLearningTrackingHeadless.testStructuredLearningTrackingHeadless
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chaubold/opt/miniconda/envs/ilastik-py3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-py3/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 146, in wrapper
    return func(*args, **kwargs)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-py3/ilastik-meta/ilastik/tests/test_applets/structuredLearningTracking/testStructuredLearningTrackingHytraWithDivisions.py", line 141, in testStructuredLearningTrackingHeadless
    self.ilastik_startup.main()
  File "/Users/chaubold/opt/miniconda/envs/ilastik-py3/ilastik-meta/ilastik/ilastik/../ilastik.py", line 108, in main
    ilastik_main.main(parsed_args, workflow_cmdline_args)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-py3/ilastik-meta/ilastik/ilastik_main.py", line 108, in main
    f(shell)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-py3/ilastik-meta/ilastik/ilastik_main.py", line 271, in loadProject
    shell.openProjectFile(path, parsed_args.readonly)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-py3/ilastik-meta/ilastik/ilastik/shell/headless/headlessShell.py", line 116, in openProjectFile
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-py3/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 146, in wrapper
    return func(*args, **kwargs)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-py3/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 443, in _loadProject
    self.workflow.onProjectLoaded( self )
  File "/Users/chaubold/opt/miniconda/envs/ilastik-py3/ilastik-meta/ilastik/ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py", line 525, in onProjectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-py3/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 62, in run_export_from_parsed_args
    return self.run_export(role_path_dict, parsed_args.input_axes)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-py3/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 125, in run_export
    export_to_array=export_to_array )
  File "/Users/chaubold/opt/miniconda/envs/ilastik-py3/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 227, in _run_export_with_empty_batch_lane
    self.dataExportApplet.prepare_lane_for_export(batch_lane_index)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-py3/ilastik-meta/ilastik/ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py", line 389, in prepare_lane_for_export
    hypothesesGraph.insertSolution(self.result)
  File "/Users/chaubold/opt/miniconda/envs/ilastik-py3/lib/python3.6/site-packages/hytra/core/hypothesesgraph.py", line 584, in insertSolution
    traxelgraph._graph.edge[source][dest]['value'] = link["value"]
KeyError: (4, 3)
```

**Comment by ilastikdev** [comment]
fixed in
https://github.com/ilastik/ilastik/pull/1643

needs hytra
https://github.com/chaubold/hytra/pull/32
