### ISSUE TITLE
AssertionError during creation of MultiCut project

### ISSUE THREAD

**Issue by holstgr-kaust** [ilastik/ilastik#1653]
Running ilastik-1.3.0b2-Linux (installed via tarball) on CentOS 7:

AssertionError during process of creating a Boundary-based Segmentation with MultiCut project (finished loading images, click on DT Watershed tab):

```
ERROR 2017-11-22 11:39:26,748 excepthooks 5369 140118885762880 Unhandled exception in thread: 'MainThread'
ERROR 2017-11-22 11:39:26,794 excepthooks 5369 140118885762880 Traceback (most recent call last):
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 1063, in handleAppletBarItemExpanded
    self.setSelectedAppletDrawer(drawerIndex)
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 1084, in setSelectedAppletDrawer
    self.showCentralWidget(applet_index)
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 1099, in showCentralWidget
    centralWidget = self._applets[applet_index].getMultiLaneGui().centralWidget()
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/applets/base/singleToMultiGuiAdapter.py", line 64, in centralWidget
    if self.currentGui() is None:
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/applets/base/singleToMultiGuiAdapter.py", line 44, in currentGui
    self._guis[self._imageLaneIndex] = self.singleImageGuiFactory( self._imageLaneIndex )
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/applets/base/standardApplet.py", line 142, in __createSingleLaneGui
    return self.singleLaneGuiClass( self, singleLaneOperator )
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/applets/layerViewer/layerViewerGui.py", line 71, in __call__
    instance = super(LayerViewerGuiMetaclass, cls).__call__(*args,**kwargs)
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/applets/wsdt/wsdtGui.py", line 70, in __init__
    super(WsdtGui, self).__init__( parentApplet, topLevelOperatorView )
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/applets/layerViewer/layerViewerGui.py", line 181, in __init__
    self.initAppletDrawerUi() # Default implementation loads a blank drawer from drawer.ui.
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/applets/wsdt/wsdtGui.py", line 115, in initAppletDrawerUi
    populate_channel_menu()
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/applets/wsdt/wsdtGui.py", line 109, in populate_channel_menu
    for ch in range(op.Input.meta.getTaggedShape()['c']):
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/lazyflow/lazyflow/metaDict.py", line 147, in getTaggedShape
    assert self.axistags is not None
AssertionError
```
Dataset was a stack of PNG images, ordered along Z axis (this style of import worked for Carving)

Workflow wasn't functional after that (Watershed pane was blank)

**Comment by chaubold** [comment]
Hi @holstgr-kaust! Could it be that you didn't load a probability map or segmentation together with the raw data? We've seen this assertion before, and are aware that we should face the user with a meaningful error message instead of this failure. But for now, the quick fix should be to load a boundary probability map as described in the docs: http://ilastik.org/documentation/multicut/multicut

**Comment by holstgr-kaust** [comment]
Thanks @chaubold, that was the issue.  Sorry to bother. 

+1 for a notification dialog (or unavailable DT Watershed pane). ;-)

**Comment by k-dominik** [comment]
done in #1732
