### ISSUE TITLE
AssertionError during creation of Watershed Over Distance Transform project

### ISSUE THREAD

**Issue by holstgr-kaust** [ilastik/ilastik#1654]
Running ilastik-1.3.0b2-Linux (installed via tarball) on CentOS 7:

AssertionError during creation of Watershed Over Distance Transform project (finished loading images, clicked on Watershed pane):

```
ERROR 2017-11-22 12:23:47,589 excepthooks 7345 140434909869888 Unhandled exception in thread: 'MainThread'
ERROR 2017-11-22 12:23:47,618 excepthooks 7345 140434909869888 Traceback (most recent call last):
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 1063, in handleAppletBarItemExpanded
    self.setSelectedAppletDrawer(drawerIndex)
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 1084, in setSelectedAppletDrawer
    self.showCentralWidget(applet_index)
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 1099, in showCentralWidget
    centralWidget = self._applets[applet_index].getMultiLaneGui().centralWidget()
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/applets/base/singleToMultiGuiAdapter.py", line 64, in centralWidget
    if self.currentGui() is None:
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/applets/base/singleToMultiGuiAdapter.py", line 44, in currentGui
    self._guis[self._imageLaneIndex] = self.singleImageGuiFactory( self._imageLaneIndex )
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/applets/base/standardApplet.py", line 142, in __createSingleLaneGui
    return self.singleLaneGuiClass( self, singleLaneOperator )
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/applets/layerViewer/layerViewerGui.py", line 71, in __call__
    instance = super(LayerViewerGuiMetaclass, cls).__call__(*args,**kwargs)
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/applets/wsdt/wsdtGui.py", line 70, in __init__
    super(WsdtGui, self).__init__( parentApplet, topLevelOperatorView )
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/applets/layerViewer/layerViewerGui.py", line 181, in __init__
    self.initAppletDrawerUi() # Default implementation loads a blank drawer from drawer.ui.
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/applets/wsdt/wsdtGui.py", line 115, in initAppletDrawerUi
    populate_channel_menu()
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/ilastik/ilastik/applets/wsdt/wsdtGui.py", line 109, in populate_channel_menu
    for ch in range(op.Input.meta.getTaggedShape()['c']):
  File "$HOME/Downloads/ilastik/ilastik-1.3.0b2-Linux/ilastik-meta/lazyflow/lazyflow/metaDict.py", line 147, in getTaggedShape
    assert self.axistags is not None
AssertionError
```
Dataset was a stack of PNG images, ordered along Z axis (this style of import worked for Carving)

Workflow wasn't functional after that (Watershed pane was blank)

**Comment by snajder-r** [comment]
I just want to add to this report: I am seeing a lot of this error as well. Right now I got it after removing the probability map from one lane and replacing it with the other. After clicking OK in the error message, Ilastik became unresponsive for about a minute and then crashed with a segmentation fault.
