### ISSUE TITLE
Fix problematic tracks with user input

### ISSUE THREAD

**Issue by dfberenson** [ilastik/ilastik#1679]
I am using ilastik to segment and track a complicated image series with highly motile cells and many divisions. I find that ilastik's automatic tracking is mostly correct, but occasionally makes mistakes in the tracking assignments that are easily visible by eye. I wish there were an option for ilastik to ask the user for input while tracking especially difficult regions, or allow the user to fix erroneous assignments after ilastik's automatic tracking completes.

**Comment by ilastikdev** [comment]
Hi dfberenson,

You should use Tracking with Learning workflow, where in addition to  
the applets in Automatic tracking you also input training for tracking  
and then run structured learning to obtain unique tracking weights for  
given classifiers and tracking training.
If you train for tracking in the questionable areas you will get a  
better result with these custom weights.

There is a MaMuT export option in the export plugin dialog which  
exports the necessary files for you to import the tracking result into  
MaMuT - there you can manually correct any track you find incorrect.

Janez.




Quoting dfberenson <notifications@github.com>:

**Comment by dfberenson** [comment]
Hi Janez,

Thank you for this helpful suggestion. I am having trouble getting MaMuT to work properly with the ilastik output files and would appreciate some guidance. After I run the export plugin, I get three files: myimage_raw.h5, myimage_bdv.xml, and myimage_mamut.xml.

First, I "Launch new MaMuT annotation" and choose myimage_bdv.xml. This loads the untracked image into MaMuT. Second, in MaMuT I go to "Actions" and select "Merge another annotation," choosing myimage_mamut.xml. Now I have loaded the tracking information to go along with the image. All good so far.

The issue comes when I try to Save the combined file as myimage_bdv-mamut.xml because I get the errors below. I have tried to make some manual annotations on the myimage_bdv.xml file and I can successfully save the manually annotated one. Similarly, if I open only the annotation file myimage_mamut.xml, I can save just that file. I only experience the saving issue when I have loaded the bdv file and then merged the mamut file.

I greatly appreciate your help. Here are the errors that occur when I try to save the merged file:

In the Log: "Something wrong happened while saving to myimage_bdv-mamut.xml; null."

In the MaMuT save file dump: "A problem occured when saving to a file. To recuperate your work, ust copy/paste the text below the line and save it to an XML file.
__________________________
<?xml version="1.0" encoding="UTF-8"?>
<TrackMate version="3.5.1-SNAPSHOT" />
"

In the ImageJ console: "
ava.lang.NullPointerException
	at fiji.plugin.trackmate.io.TmXmlWriter.marshalSpot(TmXmlWriter.java:728)
	at fiji.plugin.trackmate.io.TmXmlWriter.echoSpots(TmXmlWriter.java:548)
	at fiji.plugin.trackmate.io.TmXmlWriter.appendModel(TmXmlWriter.java:216)
	at fiji.plugin.mamut.MaMuT.save(MaMuT.java:1139)
	at fiji.plugin.mamut.MaMuT.access$600(MaMuT.java:137)
	at fiji.plugin.mamut.MaMuT$2.actionPerformed(MaMuT.java:428)
	at fiji.plugin.trackmate.gui.panels.ActionListenablePanel.fireAction(ActionListenablePanel.java:42)
	at fiji.plugin.mamut.gui.MamutControlPanel.access$100(MamutControlPanel.java:16)
	at fiji.plugin.mamut.gui.MamutControlPanel$2.actionPerformed(MamutControlPanel.java:73)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
"
