### ISSUE TITLE
Fiji/MaMut export - import into MaMut fails

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1698]
Fiji with plugins is updated, but loading mamut.xml file into Fiji/MaMuT fails:

java.lang.NoClassDefFoundError: Could not initialize class org.ilastik.bdvextension.XmlIoIlastikImageLoader
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at mpicbg.spim.data.generic.sequence.ImgLoaders.createXmlIoForFormat(ImgLoaders.java:76)
	at mpicbg.spim.data.generic.sequence.XmlIoAbstractSequenceDescription.fromXml(XmlIoAbstractSequenceDescription.java:110)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.fromXml(XmlIoAbstractSpimData.java:153)
	at bdv.spimdata.XmlIoSpimDataMinimal.load(XmlIoSpimDataMinimal.java:86)
	at fiji.plugin.mamut.MaMuT.prepareSources(MaMuT.java:618)
	at fiji.plugin.mamut.MaMuT.launch(MaMuT.java:352)
	at fiji.plugin.mamut.MaMuT.<init>(MaMuT.java:271)
	at fiji.plugin.mamut.LoadMamutAnnotationPlugin.load(LoadMamutAnnotationPlugin.java:125)
	at fiji.plugin.mamut.LoadMamutAnnotationPlugin.run(LoadMamutAnnotationPlugin.java:82)
	at ij.IJ.runUserPlugIn(IJ.java:221)
	at ij.IJ.runPlugIn(IJ.java:185)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)

**Comment by chaubold** [comment]
You must install the ilastik fiji plugin first, which provides the `org.ilastik.bdvextension.XmlIoIlastikImageLoader` class so that BigDataViewer can read our HDF5 format: http://ilastik.org/documentation/fiji_export/plugin

**Comment by ilastikdev** [comment]
I did have ilastik fiji plugin installed.
I also updated everything last week and it still did not work.

A restart and another update made this work.

**Comment by k-dominik** [comment]
good to know, can we consider this issue resolved @ilastikdev ?
