### ISSUE TITLE
object classification export fail (uint16 input image)

### ISSUE THREAD

**Issue by Steffen-Wolf** [ilastik/ilastik#1711]
When exporting the result of object classification on a uint16 image ilastik crashed with the error message below. An empty output file is created. (project file will be sent to team@ilastik)

Error message:
```
0 ERROR 2018-02-13 15:10:08,125 log_exception 22119 139877572122368 Traceback (most recent call last):
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 416, in _make_h5_dataset
    dset = fout.create_dataset(table_name, table.shape, data=table, **compression)
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/lib/python3.6/site-packages/h5py/_hl/group.py", line 108, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 97, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1543, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:18118)
  File "h5py/h5t.pyx", line 1565, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:17938)
  File "h5py/h5t.pyx", line 1587, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:17416)
  File "h5py/h5t.pyx", line 1492, in h5py.h5t._c_compound (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:16251)
  File "h5py/h5t.pyx", line 1565, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:17938)
  File "h5py/h5t.pyx", line 1626, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:17897)
TypeError: No conversion path for dtype: dtype('<U')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 825, in do_export
    export_file.write_all(settings["file type"], settings["compression"])
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 383, in write_all
    compression if compression is not None else {})
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 418, in _make_h5_dataset
    dset = fout.create_dataset(table_name, table.shape, data=table)
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/lib/python3.6/site-packages/h5py/_hl/group.py", line 108, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 97, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1543, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:18118)
  File "h5py/h5t.pyx", line 1565, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:17938)
  File "h5py/h5t.pyx", line 1587, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:17416)
  File "h5py/h5t.pyx", line 1492, in h5py.h5t._c_compound (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:16251)
  File "h5py/h5t.pyx", line 1565, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:17938)
  File "h5py/h5t.pyx", line 1626, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:17897)
TypeError: No conversion path for dtype: dtype('<U')

ERROR 2018-02-13 15:10:08,125 log_exception 22119 139877572122368 Export failed
ERROR 2018-02-13 15:10:08,126 log_exception 22119 139875735037696 Traceback (most recent call last):
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 416, in _make_h5_dataset
    dset = fout.create_dataset(table_name, table.shape, data=table, **compression)
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/lib/python3.6/site-packages/h5py/_hl/group.py", line 108, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 97, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1543, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:18118)
  File "h5py/h5t.pyx", line 1565, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:17938)
  File "h5py/h5t.pyx", line 1587, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:17416)
  File "h5py/h5t.pyx", line 1492, in h5py.h5t._c_compound (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:16251)
  File "h5py/h5t.pyx", line 1565, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:17938)
  File "h5py/h5t.pyx", line 1626, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:17897)
TypeError: No conversion path for dtype: dtype('<U')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/dataExport/dataExportGui.py", line 408, in exportSlots
    self.parentApplet.post_process_lane_export(lane_index)
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/workflows/objectClassification/objectClassificationWorkflow.py", line 360, in post_process_lane_export
    req.wait()
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 523, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 579, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 825, in do_export
    export_file.write_all(settings["file type"], settings["compression"])
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 383, in write_all
    compression if compression is not None else {})
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 418, in _make_h5_dataset
    dset = fout.create_dataset(table_name, table.shape, data=table)
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/lib/python3.6/site-packages/h5py/_hl/group.py", line 108, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/astubbusch/Desktop/ilastik-1.3.0-Linux/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 97, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1543, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:18118)
  File "h5py/h5t.pyx", line 1565, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:17938)
  File "h5py/h5t.pyx", line 1587, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:17416)
  File "h5py/h5t.pyx", line 1492, in h5py.h5t._c_compound (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:16251)
  File "h5py/h5t.pyx", line 1565, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:17938)
  File "h5py/h5t.pyx", line 1626, in h5py.h5t.py_create (/feedstock_root/build_artefacts/h5py_1491365196274/work/h5py-2.7.0/h5py/h5t.c:17897)
TypeError: No conversion path for dtype: dtype('<U')

ERROR 2018-02-13 15:10:08,127 log_exception 22119 139875735037696 Failed to generate export file: 
/media/hdb/astubbusch/data_12_02_18/EGF_Object Predictions.h5/exported_data
No conversion path for dtype: dtype('<U')
```

**Comment by Xqua** [comment]
I have the same issue, using H5 uint16 data as input

**Comment by k-dominik** [comment]
I tried to reproduce this without luck - this probably "just works" now (maybe related to changes in OC that would allow for uint16 input #1961)
