### ISSUE TITLE
Unhandled exception in thread: 'Worker #1'

### ISSUE THREAD

**Issue by guermonprez** [ilastik/ilastik#1712]
hello

Trying to do a pixel then object classification. got this error at the classification step.

ERROR 2018-02-13 15:05:50,192 excepthooks 26420 123145433337856 Unhandled exception in thread: 'Worker #1'
ERROR 2018-02-13 15:05:50,197 excepthooks 26420 123145433337856 Traceback (most recent call last):
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/tiling.py", line 773, in _fetch_tile_layer
    img = ims_req.wait()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 270, in wait
    return self.toImage()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 276, in toImage
    self._arrayreq.wait()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/slicesources.py", line 46, in wait
    return self._sp(self._ar.wait())
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 473, in wait
    rawData = self._rawRequest.wait()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 204, in wrapper
    return func(*args, **kwargs)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 228, in wait
    a = self._req.wait()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/Resources/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opReorderAxes.py", line 145, in execute
    self.Input( *in_roi ).writeInto( result_input_view ).wait()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/Resources/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 793, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opSlicedBlockedArrayCache.py", line 178, in execute
    op.outputs["Output"][key].writeInto(result).wait()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/Resources/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 793, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 83, in execute
    self._execute_Output(slot, subindex, roi, result)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opSimpleBlockedArrayCache.py", line 100, in _execute_Output
    pool.wait()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1313, in wait
    self._clear_finishing_requests()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1390, in _clear_finishing_requests
    req.block()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in block
    self._wait(timeout) # No return value. Use wait()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 609, in _wait_within_request
    raise_with_traceback(exc_type(exc_value), exc_tb)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/Resources/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opSimpleBlockedArrayCache.py", line 76, in copy_block
    self._execute_Output_impl( clipped_block_roi, result[roiToSlice(*output_roi)] )
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 108, in _execute_Output_impl
    self._fetch_and_store_block(request_roi, out=result)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 146, in _fetch_and_store_block
    block_data = req.wait()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/Resources/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 793, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opCacheFixer.py", line 63, in execute
    self.Input(roi.start, roi.stop).writeInto(result).wait()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/Resources/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 793, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1296, in execute
    map_ = self.ObjectMap([t]).wait()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/Resources/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1577, in execute
    return self.operator.execute(self, totalIndex, roi, result)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1134, in execute
    classifier = self.Classifier.value
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1105, in value
    temp = self[:].wait()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/Resources/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/valueProviders.py", line 301, in execute
    value = request.wait()[0]
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 609, in _wait_within_request
    raise_with_traceback(exc_type(exc_value), exc_tb)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/Resources/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1012, in execute
    pool.wait()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1313, in wait
    self._clear_finishing_requests()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1390, in _clear_finishing_requests
    req.block()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in block
    self._wait(timeout) # No return value. Use wait()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 609, in _wait_within_request
    raise_with_traceback(exc_type(exc_value), exc_tb)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/Resources/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 989, in fetch_features
    featstmp, row_names, col_names, labelstmp = make_feature_array(feats, selected, labels_image_filtered)
  File "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 901, in make_feature_array
    assert labelsMatrix.shape[0] == featMatrix.shape[0]
AssertionError

**Comment by akreshuk** [comment]
Thanks for the report! Could it be that you started to predict in the object classification stage without selecting any object-level features? It should fail more gracefully in any case. Would you be willing to share your ilastik project file with us, that would really help debugging? If so, please e-mail it to team@ilastik.org. Even if it produced an assertion error, you should still be able to save the project.

**Comment by k-dominik** [comment]
maybe related: https://github.com/ilastik/ilastik/issues/1902
