### ISSUE TITLE
Error using pixel classification with 2D h5 files

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#1749]
### Observed behavior

If a 2D `h5` file is loaded into Pixelclassification, the following exception is thrown when adding a label:

```
ERROR 2018-04-26 11:48:12,897 excepthooks 19657 139812857657088 Traceback (most recent call last):
  File ".../ilastik-meta/ilastik/ilastik/applets/dataExport/dataExportGui.py", line 344, in handleTableSelectionChange
    self.showSelectedDataset()
  File ".../ilastik-meta/ilastik/ilastik/applets/dataExport/dataExportGui.py", line 516, in showSelectedDataset
    layerViewer = self.createLayerViewer(opLane)
  File ".../ilastik-meta/ilastik/ilastik/applets/pixelClassification/pixelClassificationDataExportGui.py", line 40, in createLayerViewer
    return PixelClassificationResultsViewer(self.parentApplet, opLane)
  File ".../ilastik-meta/ilastik/ilastik/applets/layerViewer/layerViewerGui.py", line 72, in __call__
    instance._after_init()
  File ".../ilastik-meta/ilastik/ilastik/applets/layerViewer/layerViewerGui.py", line 192, in _after_init
    self.updateAllLayers()
  File ".../ilastik-meta/ilastik/ilastik/utility/gui/threadRouter.py", line 76, in routed
    val = func(*args, **kwargs)
  File ".../ilastik-meta/ilastik/ilastik/applets/layerViewer/layerViewerGui.py", line 427, in updateAllLayers
    newGuiLayers = self.setupLayers()
  File ".../ilastik-meta/ilastik/ilastik/applets/pixelClassification/pixelClassificationDataExportGui.py", line 70, in setupLayers
    previewLayers = self._initPredictionLayers(opLane.ImageToExport)
  File ".../ilastik-meta/ilastik/ilastik/applets/pixelClassification/pixelClassificationDataExportGui.py", line 164, in _initPredictionLayers
    num_channels = predictionSlot.meta.getTaggedShape()['c']
KeyError: 'c'
```

### Expected behaviour

There is no reason why this shouldn't work as with other data. Maybe a channel has to be added to the shape

### Steps to reproduce

1. Open a new PixelClassification project
1. Load a 2D `.h5` file
1. go to Training
1. add a label

### Context

* **OS**: should be an issue in all, tested on Linux
* **Workflows**: tested in PixelClassification
* **Ilastik Version**: 1.3.1
* **Data**: `.h5` 2D file (so `len(shape)=2`)

You can generate suitable data with:
```Python
import h5py
import numpy

data = numpy.random.randint(0, 256, (1000, 500), dtype=numpy.uint8)
with h5py.File('/tmp/random2d.h5', 'w') as f:
    f.add_dataset('random', data=data)
```

Todo:

- [ ] check if this is still an issue after @FynnBe's wonderful PRs...

**Comment by k-dominik** [comment]
this issue has been resolved (cannot reproduce it in 1.4.0)
