### ISSUE TITLE
Remove the error popup while changing the file destination in the Image Export Options

### ISSUE THREAD

**Issue by wolny** [ilastik/ilastik#1761]
When the use tries to change/remove the placeholder in the Image Export Option, the validation kicks in and shows the popup on every keystroke.
![exporterror](https://user-images.githubusercontent.com/706781/40174297-f56eb852-59d4-11e8-834e-33aae95eab74.png)

```
ERROR 2018-05-17 13:14:42,366 excepthooks 3944 139994220934912 Traceback (most recent call last):
  File "/opt/ilastik-1.3.1b1-Linux/ilastik-meta/volumina/volumina/widgets/hdf5ExportFileOptionsWidget.py", line 43, in <lambda>
    self.filepathEdit.textEdited.connect( lambda: self._handleTextEdited(self.filepathEdit) )
  File "/opt/ilastik-1.3.1b1-Linux/ilastik-meta/volumina/volumina/widgets/hdf5ExportFileOptionsWidget.py", line 87, in _handleTextEdited
    self._applyFilepath()
  File "/opt/ilastik-1.3.1b1-Linux/ilastik-meta/volumina/volumina/widgets/hdf5ExportFileOptionsWidget.py", line 80, in _applyFilepath
    self._filepathSlot.setValue( filepath )
  File "/opt/ilastik-1.3.1b1-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 118, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "/opt/ilastik-1.3.1b1-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1229, in setValue
    self._changed()
  File "/opt/ilastik-1.3.1b1-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1436, in _changed
    self._configureOperator(self)
  File "/opt/ilastik-1.3.1b1-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1450, in _configureOperator
    self.operator._setupOutputs()
  File "/opt/ilastik-1.3.1b1-Linux/ilastik-meta/lazyflow/lazyflow/operator.py", line 459, in _setupOutputs
    self.setupOutputs()
  File "/opt/ilastik-1.3.1b1-Linux/ilastik-meta/lazyflow/lazyflow/operators/ioOperators/opFormattedDataExport.py", line 231, in setupOutputs
    partially_formatted_path = format_known_keys( name_format, known_keys )
  File "/opt/ilastik-1.3.1b1-Linux/ilastik-meta/lazyflow/lazyflow/utility/format_known_keys.py", line 42, in format_known_keys
    for i in it:
ValueError: expected '}' before end of string

```

**Comment by k-dominik** [comment]
closing this as it is basically fixed with https://github.com/ilastik/lazyflow/pull/276
continuation of improvements here: https://github.com/ilastik/ilastik/issues/1919
