### ISSUE TITLE
Running pixel classification in headless mode requires the old dataset

### ISSUE THREAD

**Issue by wolny** [ilastik/ilastik#1775]
When running pixel classification in a headless mode on new data, `dataSelectionSerializer` throws an error if the old dataset is not present:
```
File "/home/adrian/opt/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/dataSelection/dataSelectionSerializer.py", line 436, in _readDatasetInfo
    raise RuntimeError("Could not find data at " + filePath)
RuntimeError: Could not find data at MuviSPIM/2017-08-02_17.49.34_stPVB003-2-2xDR5v2_F3_nb25_Marvelous_fused_cropped_for_Arivis_InViewR_export_stacked.h5
```
Even when faking the old dataset, we still get the issue from the label serializer if the size of the fake data is different from the original old dataset:
```
ERROR 2018-05-25 15:01:18,000 excepthooks 30291 139785581119232 Traceback (most recent call last):
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik.py", line 122, in <module>
    main()
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik.py", line 108, in main
    ilastik_main.main(parsed_args, workflow_cmdline_args)
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik_main.py", line 146, in main
    f(shell)
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik_main.py", line 352, in loadProject
    shell.openProjectFile(path, parsed_args.readonly)
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/shell/headless/headlessShell.py", line 116, in openProjectFile
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 146, in wrapper
    return func(*args, **kwargs)
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 435, in _loadProject
    serializer.deserializeFromHdf5(self.currentProjectFile, projectFilePath)
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 1052, in deserializeFromHdf5
    ss.deserialize(topGroup)
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 256, in deserialize
    self._deserialize(group[self.name], self.inslot)
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 146, in wrapper
    return func(*args, **kwargs)
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 545, in _deserialize
    self.inslot[index][slicing] = blockArray
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1064, in __setitem__
    p[key] = value
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1064, in __setitem__
    p[key] = value
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1064, in __setitem__
    p[key] = value
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1060, in __setitem__
    self.operator.setInSlot(self, (), roi, value)
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/operators/opCompressedUserLabelArray.py", line 373, in setInSlot
    self._setInSlotInput(slot, subindex, roi, new_pixels)
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/operators/opCompressedUserLabelArray.py", line 397, in _setInSlotInput
    (roi.start, roi.stop) )
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/roi.py", line 538, in getIntersectingRois
    block_rois = list(map( partial(getBlockBounds, dataset_shape, blockshape), block_starts ))
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/roi.py", line 564, in getBlockBounds
    block_bounds = getIntersection( block_bounds, entire_dataset_roi )
  File "/home/adrianwolny/opt/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/roi.py", line 318, in getIntersection
    assert ((stop - start) > 0).all(), "Rois do not intersect: {} and {}".format( roiA, roiB )
```
The fix should be to move all this reading to only when `--retrain` flag is passed.

**Comment by wolny** [comment]
Duplicates https://github.com/ilastik/ilastik/issues/1441
