### ISSUE TITLE
index x is out of bounds

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1776]
When exporting with Ilastik in Object classification, we sometimes get this mistake: 

index x is out of bounds for axis 0 with size x

![failedtoexport](https://user-images.githubusercontent.com/9413215/40924184-eabe2c44-6816-11e8-8ac3-4ade7157836f.png)

**Comment by BIDCatUCSF** [comment]
Hello, 

I also get the same issue when doing Pixel Classification + Object Classification. This happens both when I try to export, or when I try to do a 'Prediction - Preview' under export settings with Object Predictions selected.

Has any progress been made on this? I think I've actually made a good object classifier, but can't apply it to anything.

Thanks

![image](https://user-images.githubusercontent.com/26391996/42197770-39e1f7dc-7e39-11e8-8673-7acc5239416c.png)

**Comment by nznmol** [comment]
Hi,
Any results in here?
I am experiencing the same problem (#1328).

**Comment by akreshuk** [comment]
@k-dominik will be back next week and we will fix it.

**Comment by boazmohar** [comment]
Hi, 
Sorry to bug you again, but is there any progress regurding this?

**Comment by awedwards** [comment]
I'm also experiencing this issue. Has anyone found any work-around?

**Comment by stuarteberg** [comment]
I've done some preliminary investigation.  It appears that when `make_feature_array()` is called, the arrays in `feats` are not of the same length as the arrays in `labels`.  Somehow the `labels` array has more items (and not just by 1).

Here's an example traceback:

```pytb
/applets/objectClassification/opObjectClassification.py", line 989, in fetch_features
    featstmp, row_names, col_names, labelstmp = make_feature_array(feats, selected, labels_image_filtered)
  File "/Applications/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 880, in make_feature_array
    ft = ft[index]
IndexError: index 406 is out of bounds for axis 1 with size 405
```

<br>

It took me a while, but I was able to reproduce the issue in a fresh project.  I haven't completely tracked down the exact problem, but I'm close.  The problem seems to be related to the fact that the thresholding applet outputs a label image whose labels are not consecutive.  This is easy to reproduce by setting restrictive "min size" and "max size" options in the thresholding applet.  I've attached a project file that exhibits the issue.  Just open it up and hit "Live Update" on the Object Classification page.

[issue-1776.ilp.zip](https://github.com/ilastik/ilastik/files/2738917/issue-1776.ilp.zip)

In `opObjectClassification.py` the `assignObjectLabel()` function seems to assume that object labels are contiguous.  Does the entire `OpObjectExtraction` and `OpObjectClassification` pipeline assume that?  If so, we need to add a post-processing step to `OpThresholdTwoLevels` to "consecutivize" the labels in the output before it is passed downstream.

**Comment by boazmohar** [comment]
So a work around might be to set the min to 0 and max to a very large number, right?

**Comment by stuarteberg** [comment]
I think so, yes.

**Comment by awedwards** [comment]
I don't know if this is helpful, and it might just be pure coincidence, but I only get this error when my input images are .png. If I use .bmp, I don't get the error at all. (This is on Windows)

**Comment by mayaucsf** [comment]
I am experiencing the same issue. I am unable to change the thresholding parameters as they are important for my analysis.

**Comment by k-dominik** [comment]
Hey @stuarteberg thank you for the detective work! Could you maybe share the data along with the project? I haven't succeeded in reproducing this issue, yet :/

**Comment by stuarteberg** [comment]
Oops.  Here's an updated zip file that contains the data along with the project file.
[issue-1776.zip](https://github.com/ilastik/ilastik/files/2803533/issue-1776.zip)

**Comment by k-dominik** [comment]
awesome, this works perfectly! Thank you very much!

**Comment by k-dominik** [comment]
So this is the guide to reproduce the issue:

* choose a object classification workflow that involves thresholding, for simplicity with a 2D image
* threshold with some vanilla settings, e.g. `0.5`
* Select features
* In object classification, label one object in the  lower right corner
* go back to thresholding, modify settings so that you have less objects left
* back to object classification: live update...

**Comment by akreshuk** [comment]
TransferLabels has been disabled for a while now. But my guess would also be it's somewhere around there, some object array is not reset when dirty.

**Comment by k-dominik** [comment]
So, what is the current deal, we just discard the labels after changing threshold levels? I think the missing bit is just the flushing of the `Labels`.

**Comment by akreshuk** [comment]
Generally speaking, I like the possibility to transfer labels. This functionality was turned off as it failed in some cases at a time-critical moment and we never re-enabled it. So I think the proper thing to do now would be to flush the labels and reset completely, but hope to one day bring the transfer back.

**Comment by jandoG** [comment]
> So this is the guide to reproduce the issue:
> 
> * choose a object classification workflow that involves thresholding, for simplicity with a 2D image
> * threshold with some vanilla settings, e.g. `0.5`
> * Select features
> * In object classification, label one object in the  lower right corner (high objectID)
> * go back to thresholding, modify settings so that you have less objects left
> * back to object classification: live update...
> 
> so my guess is, that it's somewhere in transferlabels... let's see

Hello everyone, I am running into the same index out of bounds on one of the projects I am working on using pixel + object classification workflow. To try to get to the root cause, I tried the steps described above but nothing happened and I could export the predictions without any errors popping up. 
- pipeline:
    1. select data, features, draw labels, train, get probability maps - pixel classification
    2. smooth and threshold the probability maps, select a subset of features for object classification, add labels and do object prediction - object classification
- if object classification step is performed and then features in pixel classfication part or object classification part are modified, an error is produced but somehow the behaviour is quite random. Sometimes the export prediction works, sometimes gives index out of bounds error. So I believe it has nothing to do with feature selections? I felt the error is due to something happening after the thresholding step but I am at a complete loss now. 
- Now I am also getting an error on opening the project itself which says `NotImplementedError()`
Traceback:

```python
ERROR 2019-03-11 13:38:25,284 excepthooks 72917 123145460879360 Unhandled exception in thread: 'Worker #5'
ERROR 2019-03-11 13:38:25,288 excepthooks 72917 123145460879360 Traceback (most recent call last):
  File "/Applications/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/tiling.py", line 773, in _fetch_tile_layer
    img = ims_req.wait()
  File "/Applications/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 387, in wait
    return self.toImage()
  File "/Applications/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 425, in toImage
    raise NotImplementedError()
NotImplementedError
```

Traceback for out of bounds error:

```python
ERROR 2019-03-11 13:39:04,544 request 72917 123145466134528 Encountered exception while processing roi: (array([0, 0, 0, 0]), array([ 51, 116, 225,   1]))
ERROR 2019-03-11 13:39:04,570 log_exception 72917 123145426665472 Traceback (most recent call last):
  File "/Applications/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/utility/roiRequestBatch.py", line 167, in execute
    self._activateNewRequest()
  File "/Applications/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/utility/roiRequestBatch.py", line 210, in _activateNewRequest
    roi = next(self._roiIter)
StopIteration

During handling of the above exception, another exception occurred:
...
File "/Applications/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 989, in fetch_features
    featstmp, row_names, col_names, labelstmp = make_feature_array(feats, selected, labels_image_filtered)
  File "/Applications/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 880, in make_feature_array
    ft = ft[index]
IndexError: index 13 is out of bounds for axis 1 with size 13
```

Any help or lead is appreciated!

**Comment by k-dominik** [comment]
hi @jandoG,

from your traceback I can see that you are using version `1.3.2rc2`. The fix to this issue was not yet included there. If you get the latest version from [our website](https://www.ilastik.org/download.html) (`1.3.2post1` at the time of writing), the index error should be gone.

as for the other error I am not sure, maybe try the new version and report back if it solves the index error problem (and maybe the other one, too).

Just a general note on using the combined pixel + object classification workflow: it's very memory-intensive. We don't recommend it for serious use. It's really better to split the project in two: one for pixel classification, one for object classification and use the output from the former (probability map) in the latter one.

**Comment by jandoG** [comment]
@k-dominik thank you for the input. I will definitely give it a try! 👍

**Comment by vzickus** [comment]
Using 1.3.2post1 and have this issue

**Comment by alexlenail** [comment]
I am seeing this error in 1.4.1b6 for apple silicon.

**Comment by sven-lange** [comment]
Same error here with 1.4.1b7 on MacOs Venturo 13.6

**Comment by k-dominik** [comment]
Hi @sven-lange,

it would be really helpful to see the traceback for your error - would you mind posting it?

Best
Dominik

**Comment by sven-lange** [comment]
Of course, see below. This occurred when exporting Object Predictions from a Pix+Obj classification pipeline. I have now switched to separate pix and obj classifications, where I don't get this problem. 

`ERROR 2023-11-06 09:54:36,299 request 3548 10771050496 Traceback (most recent call last):
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/slot.py", line 870, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/operator.py", line 601, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/operators/opReorderAxes.py", line 171, in execute
    self.Input(*in_roi).writeInto(result_input_view).wait()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/future/utils/__init__.py", line 449, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 860, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/slot.py", line 870, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/operator.py", line 601, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/operators/opReorderAxes.py", line 171, in execute
    self.Input(*in_roi).writeInto(result_input_view).wait()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/future/utils/__init__.py", line 449, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 860, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/slot.py", line 870, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/operator.py", line 601, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/operators/generic.py", line 574, in execute
    matrix = req.wait()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/future/utils/__init__.py", line 449, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 860, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/slot.py", line 870, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/operator.py", line 601, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/operators/valueProviders.py", line 130, in execute
    req.wait()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/future/utils/__init__.py", line 449, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 860, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/slot.py", line 870, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/operator.py", line 601, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/operators/generic.py", line 422, in execute
    self.Input(*input_roi).writeInto(result).wait()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/future/utils/__init__.py", line 449, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 860, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/slot.py", line 870, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/operator.py", line 601, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/objectClassification/opObjectClassification.py", line 1386, in execute
    map_ = self.ObjectMap([t]).wait()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/future/utils/__init__.py", line 449, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/slot.py", line 870, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/operator.py", line 601, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/objectClassification/opObjectClassification.py", line 1223, in execute
    classifier = self.Classifier.value
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/slot.py", line 1041, in value
    temp = self[:].wait()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/future/utils/__init__.py", line 449, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/slot.py", line 870, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/operator.py", line 601, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/operators/valueProviders.py", line 310, in execute
    value = request.wait()[0]
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 654, in _wait_within_request
    raise_with_traceback(exc_type(exc_value), exc_tb)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/future/utils/__init__.py", line 449, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/slot.py", line 870, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/operator.py", line 601, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/objectClassification/opObjectClassification.py", line 1098, in execute
    pool.wait()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 1403, in wait
    self._clear_finishing_requests()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 1478, in _clear_finishing_requests
    req.block()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 547, in block
    self._wait(timeout)  # No return value. Use wait()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 654, in _wait_within_request
    raise_with_traceback(exc_type(exc_value), exc_tb)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/future/utils/__init__.py", line 449, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/objectClassification/opObjectClassification.py", line 1075, in fetch_features
    featstmp, row_names, col_names, labelstmp = make_feature_array(feats, selected, labels_image_filtered)
  File "/Applications/ilastik-1.4.1b7-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/objectClassification/opObjectClassification.py", line 965, in make_feature_array
    ft = ft[index]
IndexError: index 5 is out of bounds for axis 0 with size 5

ERROR 2023-11-06 09:54:36,299 request 3548 10771050496 Encountered exception while processing roi: ((0, 12, 0, 0, 0), (1, 13, 1, 570, 785))`

**Comment by alexlenail** [comment]
@k-dominik has there been a fix?

**Comment by alexlenail** [comment]
I installed 1.4.1b13 just to check, but I'm still getting an error. The message has changed from:

<img width="313" alt="image" src="https://github.com/ilastik/ilastik/assets/2761597/13cbad17-1173-47e6-9dc1-4e03dfed9091">

to 

<img width="413" alt="image" src="https://github.com/ilastik/ilastik/assets/2761597/133b2ef0-5ace-4bba-a2e2-58184bd0cd90">

but I'm assuming that's the same error. This is just for object prediction (not segmentation + object prediction pipeline). And I only get this error message when trying to export a subset of my inputs, which is strange. 

Is there a way to not export an image when I'm exporting object predictions? All I want is the csv. Maybe that would fix it?

**Comment by alexlenail** [comment]
Reading the log, it is still the same error: 

```
ERROR 2023-12-31 10:48:51,567 log_exception 5860 6260617216 Traceback (most recent call last):
  File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/objectClassification/opObjectClassification.py", line 143, in do_export
    prediction_label = predictions[t][object_id]
IndexError: index 224445 is out of bounds for axis 0 with size 224445
```

The error comes from here: 
https://github.com/ilastik/ilastik/blob/5116115c08091ccbe1c80412186ac34f7a3937f4/ilastik/applets/objectClassification/opObjectClassification.py#L142-L143

id's is defined here: 
https://github.com/ilastik/ilastik/blob/5116115c08091ccbe1c80412186ac34f7a3937f4/ilastik/applets/objectClassification/opObjectClassification.py#L119-L120

My guess is the error is in here somewhere: 

https://github.com/ilastik/ilastik/blob/5116115c08091ccbe1c80412186ac34f7a3937f4/ilastik/utility/exportFile.py#L157-L164

**Comment by alexlenail** [comment]
@k-dominik Does it make sense to re-open this issue or start a new one?

**Comment by k-dominik** [comment]
Hi @alexlenail,

yes, thank you for checking and also for tracing the error to a possible source!! I opened a new issue here to follow up: https://github.com/ilastik/ilastik/issues/2790.

Cheers
Dominik
