### ISSUE TITLE
 '>' not supported between instances of 'NoneType' and 'float'

### ISSUE THREAD

**Issue by snajder-r** [ilastik/ilastik#1837]
Hi,

I have this reproducible error message. What I did is:

* I started a multicut workflow, loaded raw files, probabilities, and ground truth
* Saved the project and closed ilastik
* Re-opened the project
* Update Watershed
* Auto-Label
* Live Multicut

Then I get this error message:

```
ERROR 2018-09-17 14:07:10,123 excepthooks 32212 140208585692928 Unhandled exception in thread: 'Worker #2'
ERROR 2018-09-17 14:07:10,141 excepthooks 32212 140208585692928 Traceback (most recent call last):
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/multicut/multicutGui.py", line 225, in _impl
    edge_disagreements = op.EdgeLabelDisagreementDict.value
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1105, in value
    temp = self[:].wait()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/multicut/opMulticut.py", line 228, in execute
    edge_labels_from_probabilities = edge_probabilities > 0.5
TypeError: '>' not supported between instances of 'NoneType' and 'float'
```

I don't know whether it is specific to my file, as I haven't tried to reproduce it from the beginning. But if I repeat the steps after re-opening the file, I can reproduce it.

**Comment by snajder-r** [comment]
Having the same problem with a different project and different input files (although the same kind of data) now, so it's not specific to that one project.
