### ISSUE TITLE
Multicut error: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by snajder-r** [ilastik/ilastik#1839]
Hi! 

This is how I got the error:

* Start new multicut workflow
* Load several 3d volumes from h5 files, including probabilities and ground truth
* Selected one of the 3d volumes and ran watershed
* Changed some parameters and updated watershed (not sure if relevant)
* Ran Auto-Label
* Switched "Current view" to a different dataset 

That's when I got the error. 

Environment:

* Centos 7
* Ilastik 1.3.0

In the log I found the following traceback:

```
ERROR 2018-09-18 10:25:06,142 excepthooks 130573 139769694639872 Traceback (most recent call last):
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/edgeTraining/edgeTrainingGui.py", line 270, in _impl
    edge_probs = op.EdgeProbabilitiesDict.value
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1105, in value
    temp = self[:].wait()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/operators/valueProviders.py", line 301, in execute
    value = request.wait()[0]
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/edgeTraining/opEdgeTraining.py", line 376, in execute
    rag = self.Rag.value
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1105, in value
    temp = self[:].wait()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/operators/valueProviders.py", line 301, in execute
    value = request.wait()[0]
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/edgeTraining/opEdgeTraining.py", line 211, in execute
    result[0] = ilastikrag.Rag(superpixels)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/ilastikrag/rag.py", line 160, in __init__
    self._init_sp_attributes()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/ilastikrag/rag.py", line 376, in _init_sp_attributes
    self._max_sp = self._sp_ids.max()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by k-dominik** [comment]
closing this in favor of https://github.com/ilastik/ilastik/issues/2117
