### ISSUE TITLE
KeyError in cacheMemoryManager.py in 1.3.2b3

### ISSUE THREAD

**Issue by snajder-r** [ilastik/ilastik#1860]
This actually didn't affect the user experience, because I didn't get any error in the user interface, but I find multiple occurrences of it on the console:

```
ERROR 2018-10-10 13:56:13,751 log_exception 114253 140086932043520 Traceback (most recent call last):
  File "/g/kreshuk/snajder/ilastik-1.3.2b3-Linux/ilastik-meta/lazyflow/lazyflow/operators/cacheMemoryManager.py", line 218, in _cleanup
    mem = cleanupFun()
  File "/g/kreshuk/snajder/ilastik-1.3.2b3-Linux/ilastik-meta/lazyflow/lazyflow/operators/opBlockedArrayCache.py", line 127, in freeBlock
    return self._opSimpleBlockedArrayCache.freeBlock(key)
  File "/g/kreshuk/snajder/ilastik-1.3.2b3-Linux/ilastik-meta/lazyflow/lazyflow/operators/opUnblockedArrayCache.py", line 257, in freeBlock
    block = self._block_data[key]
KeyError: ((256, 100, 256, 0), (362, 101, 325, 2))
```

This was using the version 1.3.2b3 (2018-09-25), while working with the autocontext workflow.

**Comment by k-dominik** [comment]
Hey @snajder-r thank you very much for the report! Was that a one-off occurrence, or do you see it on a regular basis? Also, which workflow did you see that happening in?

Btw. If you're into it, there is a new version of ilastik out :)) `1.3.2rc1` http://ilastik.org/download.html

**Comment by snajder-r** [comment]
Hi! I only encountered it once, but it repeated about 4 or 5 times in the log. I didn't use ilastik much after that, though, so I can't really say whether it would have re-occurred.  I believe it was in the multicut workflow.

**Comment by k-dominik** [comment]
can't say that this issue was brought to our attention ever again. I also checked my ~300k lines of ilastik logs and didn't find it. Not saying that it won't occur again, but I don't see anything actionable here right now.
