### ISSUE TITLE
Error starting Ilastik

### ISSUE THREAD

**Issue by eenerait** [ilastik/ilastik#1877]
From the command prompt window:

```
Starting ilastik from "C:\Program Files\ilastik-1.3.2rc1".
ERROR 2018-10-30 10:46:15,988 excepthooks 16700 11208 Unhandled exception in thread: 'MainThread'
ERROR 2018-10-30 10:46:15,990 excepthooks 16700 11208 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.3.2rc1\ilastik-meta\ilastik\ilastik\shell\gui\startShellGui.py", line 90, in launchShell
    shell = IlastikShell(None, workflow_cmdline_args)
  File "C:\Program Files\ilastik-1.3.2rc1\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 346, in __init__
    self._loaduifile()
  File "C:\Program Files\ilastik-1.3.2rc1\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 602, in _loaduifile
    self._replaceLogo(localDir)
  File "C:\Program Files\ilastik-1.3.2rc1\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 585, in _replaceLogo
    z.extract(filename, localDir)
  File "C:\Program Files\ilastik-1.3.2rc1\lib\zipfile.py", line 1484, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Program Files\ilastik-1.3.2rc1\lib\zipfile.py", line 1555, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\ilastik-1.3.2rc1\\ilastik-meta\\ilastik\\ilastik\\shell\\gui\\ilastik-halloween.png'
```

I haven't tried running Ilastik in a while, so I am unsure if this is due to something that has changed on my end or due to Ilastik. I reinstalled and this still happened. I think it could be from Ilastik though because it is throwing error on opening a Halloween .png (last line) :/

**Comment by k-dominik** [comment]
thanks for the report! We're working on a solution, stay tuned ;)

**Comment by k-dominik** [comment]
Here is the release that fixes it: http://files.ilastik.org/ilastik-1.3.2rc2-win64.exe

**Comment by eenerait** [comment]
Works great! I'm glad the theme made it in ;)
