### ISSUE TITLE
Autocontext not working due to missing 'featureSelectionApplet'

### ISSUE THREAD

**Issue by FynnBe** [ilastik/ilastik#1897]
## Describe the bug
'Select Features' in Autocontext workflow leads to error popup

## Screenshots
![autocontextbug](https://user-images.githubusercontent.com/15139589/49081625-b51d5b80-f247-11e8-8549-e898978a5de8.jpeg)

## Desktop:
 - ilastik version: 1.3.2
 - OS: Mac 10.14

## Error message/traceback
```
INFO 2018-11-27 09:20:25,880 ilastik_main 3289 4517828032 Starting ilastik from "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release".
INFO 2018-11-27 09:20:26,786 filterOperators 3289 4517828032 Using fast filters.
WARNING 2018-11-27 09:20:26,790 warnings 3289 4517828032 __init__.py(11): UserWarning: init: Could not import tiktorch classifier
WARNING 2018-11-27 09:20:27,720 warnings 3289 4517828032 cross_validation.py(41): DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
WARNING 2018-11-27 09:20:28,032 opConservationTracking 3289 4517828032 Could not find any ILP solver
WARNING 2018-11-27 09:20:28,040 opStructuredTracking 3289 4517828032 Could not find any ILP solver
WARNING 2018-11-27 09:20:28,043 structuredTrackingWorkflow 3289 4517828032 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
WARNING 2018-11-27 09:20:54,782 warnings 3289 4517828032 stype.py(181): UserWarning: ArrayLike.isCompatible: FIXME here
INFO 2018-11-27 09:21:43,147 ilastik_main 3303 4451505600 Starting ilastik from "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release".
INFO 2018-11-27 09:21:44,024 filterOperators 3303 4451505600 Using fast filters.
WARNING 2018-11-27 09:21:44,029 warnings 3303 4451505600 __init__.py(11): UserWarning: init: Could not import tiktorch classifier
WARNING 2018-11-27 09:21:44,932 warnings 3303 4451505600 cross_validation.py(41): DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
WARNING 2018-11-27 09:21:45,238 opConservationTracking 3303 4451505600 Could not find any ILP solver
WARNING 2018-11-27 09:21:45,247 opStructuredTracking 3303 4451505600 Could not find any ILP solver
WARNING 2018-11-27 09:21:45,250 structuredTrackingWorkflow 3303 4451505600 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
WARNING 2018-11-27 09:22:07,513 warnings 3303 4451505600 stype.py(181): UserWarning: ArrayLike.isCompatible: FIXME here
INFO 2018-11-27 09:22:07,607 acceleratesupport 3303 4451505600 No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
WARNING 2018-11-27 09:22:58,727 warnings 3303 4451505600 tiling.py(356): UserWarning: FIXME: This is a slow way to look for the items we want.
_TilesCache._layerCache should be a dict-of-dict-of-dict for faster lookup!
ERROR 2018-11-27 09:23:28,371 excepthooks 3303 4451505600 Unhandled exception in thread: 'MainThread'
ERROR 2018-11-27 09:23:28,377 excepthooks 3303 4451505600 Traceback (most recent call last):
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/featureSelection/featureSelectionGui.py", line 374, in onNewFeaturesFromFeatureDlg
    opFeatureSelection.SelectionMatrix.setValue(self.featureDlg.selectionMatrix)
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 118, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1232, in setValue
    self._changed()
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1433, in _changed
    c._changed()
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1439, in _changed
    self._configureOperator(self)
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1453, in _configureOperator
    self.operator._setupOutputs()
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operator.py", line 455, in _setupOutputs
    self.setupOutputs()
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/featureSelection/opFeatureSelection.py", line 246, in setupOutputs
    super().setupOutputs()
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/featureSelection/opFeatureSelection.py", line 174, in setupOutputs
    if self.parent.parent.featureSelectionApplet._gui is None:
AttributeError: 'AutocontextTwoStage' object has no attribute 'featureSelectionApplet'

ERROR 2018-11-27 09:24:49,203 excepthooks 3303 4451505600 Unhandled exception in thread: 'MainThread'
ERROR 2018-11-27 09:24:49,206 excepthooks 3303 4451505600 Traceback (most recent call last):
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/featureSelection/featureSelectionGui.py", line 300, in onFeatureButtonClicked
    slot.disconnect()
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 118, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 660, in disconnect
    self._changed()
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1433, in _changed
    c._changed()
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1439, in _changed
    self._configureOperator(self)
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1453, in _configureOperator
    self.operator._setupOutputs()
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operator.py", line 455, in _setupOutputs
    self.setupOutputs()
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/featureSelection/opFeatureSelection.py", line 246, in setupOutputs
    super().setupOutputs()
  File "/private/var/folders/k4/z9m1p9713pg4sv1dgyq9kwqr0000gp/T/AppTranslocation/0957A02E-543D-4103-9941-8B86AEE254B6/d/ilastik-1.3.2rc2-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/featureSelection/opFeatureSelection.py", line 174, in setupOutputs
    if self.parent.parent.featureSelectionApplet._gui is None:
AttributeError: 'AutocontextTwoStage' object has no attribute 'featureSelectionApplet'
```

**Comment by k-dominik** [comment]
Okay this happens if you select a scale that exceeds the z-depth and the fancy chain of dialogs is supposed to pop up to help you correct it.

So in order to reproduce, you need a narrow 3D stack. Quick workaround: use 2D features :/
