### ISSUE TITLE
Tracking, export image broken when explicitly selecting something in source drop-down

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#1971]
## Describe the bug
In tracking when going to the export applet, if one doesn't trigger the _source_ drop-down, the state between gui and export operator seems to be out of sync.

## Expected behavior
When changing to the export applet, I'd expect everything to work, with the default export source `object identities`.

## To Reproduce
You can use the mitocheck example from our website
0. Load the conservation tracking example
1. Go to export applet and choose "configure export settings" without touching anything else
-> boom

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
ERROR 2019-03-04 13:58:59,762 excepthooks 8456 139756753446720 Unhandled exception in thread: 'MainThread'
ERROR 2019-03-04 13:58:59,767 excepthooks 8456 139756753446720 Traceback (most recent call last):
  File ".../ilastik-versions/ilastik-1.3.2-Linux/ilastik-meta/ilastik/ilastik/applets/tracking/base/trackingBaseDataExportGui.py", line 107, in _chooseSettings
    if self.topLevelOperator.SelectedExportSource.value != OpTrackingBaseDataExport.PluginOnlyName:
  File ".../ilastik-versions/ilastik-1.3.2-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1111, in value
    temp =  self[:].wait()
  File ".../ilastik-versions/ilastik-1.3.2-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1027, in __getitem__
    raise Slot.SlotNotReadyError(slotInfoMsg)
lazyflow.slot.Slot.SlotNotReadyError: Can't get data from slot <class 'ilastik.utility.opMultiLaneWrapper.OpMultiLaneWrapper'>.SelectedExportSource yet. It isn't ready.First upstream problem slot is: Wrapped OpTrackingBaseDataExport/Wrapped OpTrackingBaseDataExport.SelectedExportSource :    {_ready : False, shape : None, has_mask : None, _dirty : True}


```

## Desktop (please complete the following information):
 - ilastik version: `1.3.2`
 - OS: Ubuntu 18.04

**Comment by k-dominik** [comment]
closed in #1963
