### ISSUE TITLE
Project file cannot be saved with custom classifiers

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#1997]
## Describe the bug
When choosing a "custom" classifier (e.g. the scikit-learn ones), saving the project results in an error.

## Expected behavior
Classifiers should obviously be serialized properly

## To Reproduce
Within the Pixel Classification workflow
1. Add some [2d/3d/4d/5d] data in the data selection applet
2. Add some features
3. Go to the _training_ applet, make some annotations
4. Choose _Advanced -> Classifiers_ ... and select any of the scikit learn ones
5. hit save -> boom

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
ERROR 2019-04-25 08:16:05,983 log_exception 16228 140687278286592 Project Save Action failed due to the exception shown above.
ERROR 2019-04-25 08:16:29,540 log_exception 16228 140687260985088 Traceback (most recent call last):
  File ".../sources/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 279, in saveProject
    serializer.serializeToHdf5(self.currentProjectFile, self.currentProjectPath)
  File ".../sources/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 1023, in serializeToHdf5
    ss.serialize(topGroup)
  File ".../sources/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 205, in serialize
    self._serialize(group, self.name, self.slot)
  File ".../sources/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 613, in _serialize
    classifier.serialize_hdf5( classifier_group )
  File ".../miniconda3/envs/idev-py37/ilastik-meta/lazyflow/lazyflow/classifiers/sklearnLazyflowClassifier.py", line 102, in serialize_hdf5
    h5py_group["pickled_classifier"] = pickle.dumps(self, 0)
  File ".../miniconda3/envs/idev-py37/lib/python3.7/site-packages/h5py/_hl/group.py", line 385, in __setitem__
    ds = self.create_dataset(None, data=obj, dtype=base.guess_dtype(obj))
  File ".../miniconda3/envs/idev-py37/lib/python3.7/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File ".../miniconda3/envs/idev-py37/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 170, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 221, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 163, in h5py._proxy.dset_rw
  File "h5py/defs.pyx", line 3405, in h5py.defs.H5Tconvert
  File "h5py/_conv.pyx", line 449, in h5py._conv.str2vlen
  File "h5py/_conv.pyx", line 113, in h5py._conv.generic_converter
  File "h5py/_conv.pyx", line 259, in h5py._conv.conv_str2vlen
ValueError: VLEN strings do not support embedded NULLs

```

## Screenshots
If applicable, please add screenshots to help explain your problem.

## Desktop (please complete the following information):
 - ilastik 1.3.3b1
 - OS: Ubuntu 18.04
 
ilastik ilastik/ilastik@d60f515f1d43d9f7f73274ebcf386353622390af
lazyflow ilastik/lazyflow@8c2d40b0c38a9abcdee6c2f165d9e0d2913482ff
volumina ilastik/volumina@d505e92ac378011280d87342e62aecb1302355dc

**Comment by emilmelnikov** [comment]
If you try to save the project _before_ hitting the "Live Update" button (but after adding some annotations and changing the classifier type), the following exception occurs:

```pytb
ERROR 2019-09-20 16:34:51,277 excepthooks 1291 139945419802432 Unhandled exception in thread: 'MainThread'
ERROR 2019-09-20 16:34:51,278 excepthooks 1291 139945419802432 Traceback (most recent call last):
  File "/home/em/local/miniconda3/envs/ilastik-devel/ilastik-meta/volumina/volumina/widgets/layerwidget.py", line 382, in handleRemovedRows
    layer = itemData[Qt.EditRole]
KeyError: 2

QObject::connect: Cannot queue arguments of type 'QItemSelection'
(Make sure 'QItemSelection' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QItemSelection'
(Make sure 'QItemSelection' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QItemSelection'
(Make sure 'QItemSelection' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
```

**Comment by emilmelnikov** [comment]
> If you try to save the project _before_ hitting the "Live Update" button (but after adding some annotations and changing the classifier type), the following exception occurs:
>  ...

The precise sequence of steps to reproduce the error described above:

1. Start ilastik
2. `Create New Project -> Pixel Classification` and save the initial project file `MyProject.ilp`
3. `1. Input Data -> Add New... -> Add separate image(s)...` and select [`2d_cells_apoptotic_1channel.png`](http://files.ilastik.org/2d_cells_apoptotic_1channel.png)
4. `2. Feature Selection -> Select Features...` and select `Color/Intensity` at `Sigma = 0.70`
5. `3. Training` and add a single stroke for both `Label 1` and `Label 2`
6. Press `Live Update`
7. `Advanced -> Classifier... -> Gaussian Naive Bayes (scikit-learn)`
8. `Project -> Save Project As...` and save a project file `MyProject_2.ilp`
