### ISSUE TITLE
Tracking fails if one frame does not contain any objects

### ISSUE THREAD

**Issue by bobfRT1** [ilastik/ilastik#2019]
## Describe the bug
If there no objects in a given frame the Tracking fails. 

## To Reproduce
run attached Project
[Trackingbug2.zip](https://github.com/ilastik/ilastik/files/3173766/Trackingbug2.zip)

## Error message/traceback
ERROR 2019-05-13 17:40:01,033 log_exception 15104 10960 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\ilastik\ilastik\applets\tracking\conservation\conservationTrackingGui.py", line 346, in _track
    progressVisitor=self.progressVisitor
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\ilastik\ilastik\applets\tracking\conservation\opConservationTracking.py", line 457, in track
    hypothesesGraph = self._createHypothesesGraph()
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\ilastik\ilastik\applets\tracking\conservation\opConservationTracking.py", line 248, in _createHypothesesGraph
    with_classifier_prior=withClassifierPrior)
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\ilastik\ilastik\applets\tracking\conservation\opConservationTracking.py", line 731, in _generate_traxelstore
    detProbs = self.DetectionProbabilities(time_range).wait()
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 531, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 559, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 688, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.3.3b1\lib\site-packages\future\utils\__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 350, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\lazyflow\lazyflow\slot.py", line 928, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\ilastik\ilastik\applets\objectClassification\opObjectClassification.py", line 1236, in execute
    pool.wait()
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1344, in wait
    self._clear_finishing_requests()
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1439, in _clear_finishing_requests
    req.block()
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 537, in block
    self._wait(timeout)  # No return value. Use wait()
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 559, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 644, in _wait_within_request
    raise_with_traceback(exc_type(exc_value), exc_tb)
  File "C:\Program Files\ilastik-1.3.3b1\lib\site-packages\future\utils\__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 350, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.3.3b1\ilastik-meta\ilastik\ilastik\applets\objectClassification\opObjectClassification.py", line 1227, in predict_forest
    prob_predictions[_t] = classifier.predict_probabilities(feats[_t].astype(numpy.float32))
KeyError: KeyError(13)

## Desktop (please complete the following information):
 - ilastik version: all, 1.3.3b1
 - OS:  Win 10

**Comment by bobfRT1** [comment]
sorry wrong zip
