### ISSUE TITLE
AssertionError when trying to select features during Pixel+Object classification

### ISSUE THREAD

**Issue by VolkerH** [ilastik/ilastik#2026]
## Describe the bug

Ilastik crashes with an assertion error when clicking "Select features" 
during a "Pixel + Object Classification" workflow. 

When just using just the "Pixel Classification" workflow on the same dataset, no assertion error occurs.

Same ilastik version and dataset as in issue #2025 

## Expected behavior
Select features dialog window would show up.

## To Reproduce
Within the ... workflow
1. Create a new project "Pixel + Object classifcation"
2. Add a single file: https://www.dropbox.com/s/bkbeskgd7gsiiz7/1643%20%20Glom%201.tif?dl=0
3. Go to feature selection, click on "select features"

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
tarting ilastik from "C:\Program Files\ilastik-1.3.2post1".
QWindowsWindow::setGeometry: Unable to set geometry 0x0+13+13 on QWidgetWindow/'viewWindow'. Resulting geometry:  2x2+13+13 (frame: 0, 0, 0, 0, custom margin: 0, 0, 0, 0, minimum size: 0x0, maximum size: 16777215x16777215).
ERROR 2019-05-21 10:46:20,722 excepthooks 33480 8092 Unhandled exception in thread: 'MainThread'
ERROR 2019-05-21 10:46:20,724 excepthooks 33480 8092 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\ilastik\ilastik\applets\featureSelection\featureSelectionGui.py", line 305, in onFeatureButtonClicked
    self.topLevelOperatorView.SelectionMatrix.setValue(self.topLevelOperatorView.MinimalFeatures)
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 118, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 1232, in setValue
    self._changed()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 1433, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 1433, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 1439, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 1453, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\operator.py", line 455, in _setupOutputs
    self.setupOutputs()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\operators\opPixelFeaturesPresmoothed.py", line 102, in setupOutputs
    self.parent.ComputeIn2d.setValue([False] * len(self.Scales.value))
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 118, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 1168, in setValue
    self.upstream_slot.setValue(value, notify, check_changed)
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 118, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 1232, in setValue
    self._changed()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 1433, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 1439, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 1453, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\operator.py", line 455, in _setupOutputs
    self.setupOutputs()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\ilastik\ilastik\applets\featureSelection\opFeatureSelection.py", line 246, in setupOutputs
    super().setupOutputs()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\ilastik\ilastik\applets\featureSelection\opFeatureSelection.py", line 184, in setupOutputs
    self.OutputImage.connect(self.opReorderOut.Output)
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 118, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 557, in connect
    self._changed()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 1433, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 1433, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 1433, in _changed
    c._changed()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 1439, in _changed
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 1453, in _configureOperator
    self.operator._setupOutputs()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\operator.py", line 455, in _setupOutputs
    self.setupOutputs()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\operators\opFeatureMatrixCache.py", line 96, in setupOutputs
    assert self.FeatureImage.meta.getAxisKeys()[-1] == 'c'
AssertionError
```

**Comment by k-dominik** [comment]
okay, this is fixed in the current master. We'll do a new release this week that will make it work again.

**Comment by VolkerH** [comment]
Thanks for looking into it.
Any chance for the new release this week or otherwise which version could I go back to in the mean time?
