### ISSUE TITLE
Error encountered during bath processing

### ISSUE THREAD

**Issue by mawelti** [ilastik/ilastik#2031]
## Describe the bug
I prepared a pixel classification and objects classification project. When I used it for batch analysis and it seems to work at the first attempt but I did not specify correctly the output file. I tried to rerun it on the same images but I had this message “Error encountered during bath processing: index 1 is out of bounds for axis 0 with size 0”
I did try with other pictures but I always get the same message. 
Could you please help me. Thanks a lot.

## Expected behavior
I would expect the protol to run and to obtain the images and the CVS files.

## To Reproduce
Runn several times a batch processing on the workflow

## Error message/traceback

If applicable, please add tracebacks with formatting, such as
Starting ilastik from "C:\Program Files\ilastik-1.3.2post1".
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
ERROR 2019-06-05 14:49:45,938 log_exception 13076 13852 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 324, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\ilastik\ilastik\applets\objectClassification\opObjectClassification.py", line 832, in do_export
    prediction_label = predictions[t][object_id]
IndexError: index 1 is out of bounds for axis 0 with size 0

ERROR 2019-06-05 14:49:45,938 log_exception 13076 13852 Export failed
ERROR 2019-06-05 14:49:46,483 log_exception 13076 8940 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 324, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 131, in run_export
    export_to_array=export_to_array)
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 267, in _run_export_with_empty_batch_lane
    self.dataExportApplet.post_process_lane_export(batch_lane_index)
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\ilastik\ilastik\workflows\objectClassification\objectClassificationWorkflow.py", line 360, in post_process_lane_export
    req.wait()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 500, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.3.2post1\lib\site-packages\future\utils\__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 324, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.3.2post1\ilastik-meta\ilastik\ilastik\applets\objectClassification\opObjectClassification.py", line 832, in do_export
    prediction_label = predictions[t][object_id]
IndexError: index 1 is out of bounds for axis 0 with size 0

ERROR 2019-06-05 14:49:46,486 log_exception 13076 8940 Error encountered during batch processing:
index 1 is out of bounds for axis 0 with size 0

## Desktop (please complete the following information):
 - ilastik version: 1.3.2
 - OS: [Windows 10]
 
 <!---
[ilastick workflow.pptx](https://github.com/ilastik/ilastik/files/3257273/ilastick.workflow.pptx)

**Comment by BioinfoTongLI** [comment]
Hi, 
Is there any update about this?
I am also experiencing the same issue with 1.3.3 post2, ubuntu 18.01/win10.
Thx!
Tong

**Comment by BioinfoTongLI** [comment]
Problem solved for my case.
Briefly, my training datas had different axes orders, a subset is `tzcyx` while another subset is `tzyxc`. Keep using the same images shape during training and prediction removed this error in my case.
Hope that helps
