### ISSUE TITLE
Watershed in Multicud randomly fails

### ISSUE THREAD

**Issue by paulhfu** [ilastik/ilastik#2044]
## Describe the bug
I could not relieably reproduce this error. It happens randomly after hitting update Watershed. Happens with Multicut on "smallFibStack" from Ilastik web page. This error never happened with 2-dim data. Also, never happend on Linux.

## Logfile
```pytb
INFO 2019-06-28 08:49:03,363 ilastik_main 4520 16312 Starting ilastik in debug mode from "C:\Users\hiltp_000\Anaconda3\envs\ilastik-devel".
INFO 2019-06-28 08:49:06,227 filterOperators 4520 16312 Using fast filters.
WARNING 2019-06-28 08:49:06,242 warnings 4520 16312 __init__.py(20): UserWarning: init: Could not import tiktorch classifier
INFO 2019-06-28 08:49:06,542 ilastik_main 4520 16312 Resetting lazyflow thread pool with 10 threads.
WARNING 2019-06-28 08:49:11,028 opConservationTracking 4520 16312 Could not find any ILP solver
WARNING 2019-06-28 08:49:11,058 opStructuredTracking 4520 16312 Could not find any ILP solver
WARNING 2019-06-28 08:49:11,062 structuredTrackingWorkflow 4520 16312 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
WARNING 2019-06-28 08:49:24,590 warnings 4520 16312 stype.py(187): UserWarning: ArrayLike.isCompatible: FIXME here
INFO 2019-06-28 08:49:31,298 acceleratesupport 4520 16312 No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
WARNING 2019-06-28 08:49:33,286 warnings 4520 16312 tiling.py(366): UserWarning: FIXME: This is a slow way to look for the items we want.
_TilesCache._layerCache should be a dict-of-dict-of-dict for faster lookup!
WARNING 2019-06-28 08:49:38,501 warnings 4520 16312 opSimpleBlockedArrayCache.py(43): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
INFO 2019-06-28 08:50:04,119 wsDtSegmentation 4520 11596 wsDtSegmentation...
DEBUG 2019-06-28 08:50:04,133 wsDtSegmentation 4520 11596 signed_distance_transform...
DEBUG 2019-06-28 08:50:05,190 wsDtSegmentation 4520 11596 remove_wrongly_sized_connected_components...
DEBUG 2019-06-28 08:50:05,191 wsDtSegmentation 4520 11596 remove_wrongly_sized_connected_components took (0.00 seconds)
DEBUG 2019-06-28 08:50:05,192 wsDtSegmentation 4520 11596 positive distance transform...
DEBUG 2019-06-28 08:50:06,836 wsDtSegmentation 4520 11596 negative distance transform...
DEBUG 2019-06-28 08:50:08,422 wsDtSegmentation 4520 11596 signed_distance_transform took (4.29 seconds)
DEBUG 2019-06-28 08:50:08,423 wsDtSegmentation 4520 11596 binary_seeds_from_distance_transform...
DEBUG 2019-06-28 08:50:09,319 wsDtSegmentation 4520 11596 localMaximaND...
DEBUG 2019-06-28 08:50:11,922 wsDtSegmentation 4520 11596 localMaximaND took (2.60 seconds)
DEBUG 2019-06-28 08:50:11,945 wsDtSegmentation 4520 11596 binary_seeds_from_distance_transform took (3.52 seconds)
DEBUG 2019-06-28 08:50:12,453 wsDtSegmentation 4520 11596 iterative_inplace_watershed...
DEBUG 2019-06-28 08:50:19,039 wsDtSegmentation 4520 11596 Max Watershed Label: 2274
DEBUG 2019-06-28 08:50:19,041 wsDtSegmentation 4520 11596 iterative_inplace_watershed took (6.59 seconds)
INFO 2019-06-28 08:50:19,050 wsDtSegmentation 4520 11596 wsDtSegmentation took (14.93 seconds)
ERROR 2019-06-28 08:50:20,303 excepthooks 4520 18468 Unhandled exception in thread: 'Thread-9'
ERROR 2019-06-28 08:50:20,686 excepthooks 4520 18468 Traceback (most recent call last):
  File "C:\Users\hiltp_000\Anaconda3\envs\ilastik-devel\ilastik-meta\ilastik\ilastik\excepthooks.py", line 115, in run
    run_old(*args, **kwargs)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\hiltp_000\Anaconda3\envs\ilastik-devel\ilastik-meta\ilastik\ilastik\applets\wsdt\wsdtGui.py", line 260, in updateThread
    self.topLevelOperatorView.FreezeCache.setValue(False)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 125, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1251, in setValue
    self._changed()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1437, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1432, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1463, in _changed_impl
    c._changed()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1437, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1432, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1463, in _changed_impl
    c._changed()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1437, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1432, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1463, in _changed_impl
    c._changed()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1437, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1432, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1470, in _changed_impl
    self._configureOperator(self)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1483, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1432, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\operator.py", line 510, in _setupOutputs
    oslot._changed()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1437, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1432, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1463, in _changed_impl
    c._changed()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1437, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1432, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1470, in _changed_impl
    self._configureOperator(self)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1483, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1432, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\operator.py", line 510, in _setupOutputs
    oslot._changed()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1437, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1432, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1463, in _changed_impl
    c._changed()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1437, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1432, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1463, in _changed_impl
    c._changed()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1437, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1432, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1463, in _changed_impl
    c._changed()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1437, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1432, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1463, in _changed_impl
    c._changed()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1437, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1432, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1470, in _changed_impl
    self._configureOperator(self)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1483, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1432, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\operator.py", line 481, in _setupOutputs
    self.setupOutputs()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\operators\opReorderAxes.py", line 49, in setupOutputs
    if "c" not in self.AxisOrder.value:
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1129, in value
    temp = self[:].wait()
  File "C:\Users\hiltp_000\Anaconda3\envs\idev_test2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1052, in __getitem__
    raise Slot.SlotNotReadyError(slotInfoMsg)
lazyflow.slot.Slot.SlotNotReadyError: Can't get data from slot <class 'lazyflow.operators.opReorderAxes.OpReorderAxes'>.AxisOrder yet. It isn't ready.First upstream problem slot is: OpReorderAxes/OpReorderAxes.Input : 	{_ready : False, has_mask : None, _dirty : False}

```

## Desktop (please complete the following information):

 - ilastik ilastik/ilastik@0b94ea8104e38bda5eb17b1b23df9ed54f689a8f
 - lazyflow ilastik/lazyflow@55858dd85af8c08be30fe4da018b8651cbeb7803
 - volumina ilastik/volumina@33c44d7b441556efed345de671189cae0a8afe8f

 - OS: Windows 10

**Comment by k-dominik** [comment]
I'm pretty sure this should be gone - we changed the watershed quite a bit, using elf now.
