### ISSUE TITLE
pixel classification, suggest features seems broken in multi-lane context

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2068]
## Describe the bug
[Per user report](https://forum.image.sc/t/ilastik-rois-do-not-intersect-assertionerror/27997) suggest features doesn't properly work with multiple lanes. Especially when triggering the suggest features functionality not from the first lane.

## Expected behavior
should work no matter what lane you are on

## To Reproduce
Within the Pixel Classification workflow
1. Add at least 2 datasets
2. Select some features
3. Do a bit of trainining
4. Trigger suggest features while not being on the first lane

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
ERROR 2019-07-24 19:19:22,336 excepthooks 4756 3532 Unhandled exception in thread: 'MainThread'
ERROR 2019-07-24 19:19:22,337 excepthooks 4756 3532 Traceback (most recent call last):
  File "...ilastik-1.3.2post1\ilastik-meta\ilastik\ilastik\applets\pixelClassification\pixelClassificationGui.py", line 499, in show_feature_selection_dialog
    self.featSelDlg.exec_()
  File "...ilastik-1.3.2post1\ilastik-meta\ilastik\ilastik\applets\pixelClassification\FeatureSelectionDialog.py", line 229, in exec_
    self.raw_xy_slice = numpy.squeeze(self.opPixelClassification.InputImages[total_slicing].wait())
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 500, in wait
    return self._wait(timeout)
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 523, in _wait
    self._wait_within_foreign_thread( timeout )
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 579, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File "...ilastik-1.3.2post1\lib\site-packages\future\utils\__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 324, in _execute
    self._result = self.fn()
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 887, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\operators\opReorderAxes.py", line 160, in execute
    self.Input( *in_roi ).writeInto( result_input_view ).wait()
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 500, in wait
    return self._wait(timeout)
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 523, in _wait
    self._wait_within_foreign_thread( timeout )
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 579, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File "...ilastik-1.3.2post1\lib\site-packages\future\utils\__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 324, in _execute
    self._result = self.fn()
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 793, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 887, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\operators\valueProviders.py", line 125, in execute
    req.wait()
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 500, in wait
    return self._wait(timeout)
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 523, in _wait
    self._wait_within_foreign_thread( timeout )
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 579, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File "...ilastik-1.3.2post1\lib\site-packages\future\utils\__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 324, in _execute
    self._result = self.fn()
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 793, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 887, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\operators\valueProviders.py", line 125, in execute
    req.wait()
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 500, in wait
    return self._wait(timeout)
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 523, in _wait
    self._wait_within_foreign_thread( timeout )
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 579, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File "...ilastik-1.3.2post1\lib\site-packages\future\utils\__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 324, in _execute
    self._result = self.fn()
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 793, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\slot.py", line 887, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\operators\opUnblockedArrayCache.py", line 83, in execute
    self._execute_Output(slot, subindex, roi, result)
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\operators\opSimpleBlockedArrayCache.py", line 93, in _execute_Output
    clipped_block_rois = getIntersectingRois( self.Input.meta.shape, self._blockshape, (roi.start, roi.stop), True )
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\roi.py", line 540, in getIntersectingRois
    block_rois = list(map( partial(getBlockBounds, dataset_shape, blockshape), block_starts ))
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\roi.py", line 566, in getBlockBounds
    block_bounds = getIntersection( block_bounds, entire_dataset_roi )
  File "...ilastik-1.3.2post1\ilastik-meta\lazyflow\lazyflow\roi.py", line 318, in getIntersection
    assert ((stop - start) > 0).all(), "Rois do not intersect: {} and {}".format( roiA, roiB )
AssertionError: Rois do not intersect: (array([ 42,   0, 369]), array([ 43, 373, 738])) and ([0, 0, 0], [106, 373, 369])
```

## Desktop (please complete the following information):
 - ilastik version: 11.3.2post11
 - OS: Windows

**Comment by CXxx1103** [comment]
I have encountered the same problem. Additionally, the previous work where I used ilastik to export tiff files, I could see shapes in the exported files. However, now the exported files are black and only 1kb in size.
