### ISSUE TITLE
ValueError when updating watershed on two channels

### ISSUE THREAD

**Issue by boykovdn** [ilastik/ilastik#2117]
## Describe the bug
When pressing "Update Watershed" under the Boundary Based Segmentation with Multicut workflow with two channels selected, the following error appears: 

## Expected behavior
A more descriptive error message if this behaviour is unexpected from the user, else I expect to get superpixels and carry on with the workflow.

## To Reproduce
Within the Boundary-Based Segmentation with Multicut workflow
1. Add 3d2c test data in the data selection applet
2. Go to DT Watershed applet, select both 0,1 channels in Input Channel
3. Click "Update Watershed"

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
ERROR 2019-09-20 21:50:34,094 excepthooks 13471 140018340787968 Unhandled exception in thread: 'Worker #1'
ERROR 2019-09-20 21:50:34,143 excepthooks 13471 140018340787968 Traceback (most recent call last):
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/applets/edgeTraining/edgeTrainingGui.py", line 270, in _impl
    edge_probs = op.EdgeProbabilitiesDict.value
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1108, in value
    temp = self[:].wait()
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/boyko/ilastik-1.3.2post1-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 887, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/operators/valueProviders.py", line 301, in execute
    value = request.wait()[0]
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/boyko/ilastik-1.3.2post1-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 887, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/applets/edgeTraining/opEdgeTraining.py", line 376, in execute
    rag = self.Rag.value
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1108, in value
    temp = self[:].wait()
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/boyko/ilastik-1.3.2post1-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 887, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/operators/valueProviders.py", line 301, in execute
    value = request.wait()[0]
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/boyko/ilastik-1.3.2post1-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 887, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/home/boyko/ilastik-1.3.2post1-Linux/ilastik-meta/ilastik/ilastik/applets/edgeTraining/opEdgeTraining.py", line 211, in execute
    result[0] = ilastikrag.Rag(superpixels)
  File "/home/boyko/ilastik-1.3.2post1-Linux/lib/python3.6/site-packages/ilastikrag/rag.py", line 160, in __init__
    self._init_sp_attributes()
  File "/home/boyko/ilastik-1.3.2post1-Linux/lib/python3.6/site-packages/ilastikrag/rag.py", line 376, in _init_sp_attributes
    self._max_sp = self._sp_ids.max()
  File "/home/boyko/ilastik-1.3.2post1-Linux/lib/python3.6/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity

```

## Screenshots
![image](https://user-images.githubusercontent.com/18038288/65354407-bf05b600-dbef-11e9-8ffc-15e55845bc77.png)

## Desktop (please complete the following information):
 - ilastik version: [e.g. 1.3.2b1]
 - OS: Ubuntu 18.04, 16.04

**Comment by k-dominik** [comment]
Update: a user on the forum.image.sc could reproduce this with a prob map with all pixels being predicted as boundaries. I assume the cause for the issue here was that _all_ (in  this instance 2) channels were selected which results in the same output: a probability map where all pixels are foreground.
