### ISSUE TITLE
Multicut: Saving multicut projects broken with pandas >=0.24

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2147]
## Describe the bug
Once a classifier is trained, saving the project results in failure. Project file is corrupted, cannot be loaded again.

The problem is related to a change in pandas 0.25, see https://github.com/ilastik/ilastik-conda-recipes/issues/77

Right now this is mitigated by pinning pandas to 0.24.x, however, this will bubble up again

## Expected behavior
This should work!

## To Reproduce
Within the Multicut workflow
1. Add some 2d/3d along with a probability map
2. Do preprocessing
3. Click one edge and do _live predict_
4. CTRL-s (or save) -> :boom:

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
ERROR 2019-10-24 14:03:47,144 log_exception 32529 140473003927296 Project Save Action failed due to the exception shown above.
ERROR 2019-10-24 14:03:51,171 log_exception 32529 140473003927296 Traceback (most recent call last):
  File ".../ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 291, in saveProject
    serializer.serializeToHdf5(self.currentProjectFile, self.currentProjectPath)
  File ".../ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 1089, in serializeToHdf5
    ss.serialize(topGroup)
  File ".../ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 211, in serialize
    self._serialize(group, self.name, self.slot)
  File ".../ilastik-meta/ilastik/ilastik/applets/edgeTraining/edgeTrainingSerializer.py", line 132, in _serialize
    self._serialize(subgroup, subname, slot[i])
  File ".../ilastik-meta/ilastik/ilastik/applets/edgeTraining/edgeTrainingSerializer.py", line 127, in _serialize
    dataframe_to_hdf5(df_group, dataframe)
  File ".../miniconda3/envs/idev/lib/python3.7/site-packages/ilastikrag/util.py", line 268, in dataframe_to_hdf5
    h5py_group['row_index'] = df.index.values
  File ".../miniconda3/envs/idev/lib/python3.7/site-packages/h5py/_hl/group.py", line 385, in __setitem__
    ds = self.create_dataset(None, data=obj, dtype=base.guess_dtype(obj))
  File ".../miniconda3/envs/idev/lib/python3.7/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File ".../miniconda3/envs/idev/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1630, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1652, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1707, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```

## Desktop (please complete the following information):
 - ilastik version: 1.3.3
 - OS: seen on win and ubuntu

related to https://github.com/ilastik/ilastik-conda-recipes/issues/77

**Comment by k-dominik** [comment]
Saving project works now in multicut, also with pandas 1.x
