### ISSUE TITLE
1.3.2 -> 1.3.3 Project Failed to Load

### ISSUE THREAD

**Issue by JulianIST** [ilastik/ilastik#2152]
## Describe the bug
I installed the latest Ilastik and tried to open a Pixel Classification and Object Classification project I created with the 1.3.2 version. When trying to open the file, the new version cannot open it anymore. 

## Expected behavior
To open the old project file. Old 1.3.2 version can still open it.

## To Reproduce
Tried multiple times to open it and it does not work. 

## Error message/traceback
"Failed to Load
Could not load project file. 
too many indices for array" 

```


## Screenshots
If applicable, please add screenshots to help explain your problem.


## Desktop (please complete the following information):
 - ilastik version: 1.3.2 & 1.3.3
 - OS: Windows 10

**Comment by Tomaz-Vieira** [comment]
Hello, Julian

I can't reproduce the error on my end. Could you send us your log file? It should be in your home folder, something like `C:\Users\<YOUR USER NAME>\ilastik_log.txt`

If you wish, you can anonimize paths to data with sensitive file or folder names in the logfile.

**Comment by JulianIST** [comment]
Hey Tomaz-Vieira,

As said, my old Ilastik can open it. I actually saved it fresh etc. but the new version cannot open it.

Would you need more? 

[ilastik_log.txt](https://github.com/ilastik/ilastik/files/3784607/ilastik_log.txt)

**Comment by JulianIST** [comment]
Any news so far? Would be bad to do all that "painting" again - at least with the newer version ;)

**Comment by k-dominik** [comment]
Hi @JulianIST,

since we have problems reproducing the problem, would you be able to share this project file (and the data) with us?

**Comment by Tomaz-Vieira** [comment]
I'm taking a look at it. This might be the same problem, so I'll add it here just in case someone takes over later:

I've tried creating a Pixel+Object workflow on a 3d image in ilastik 1.3.2, add two pixel label strokes, save and quit. Then try to open that with ilastik 1.3.3 and it breaks with the exception
```pytb
ERROR 2019-11-12 15:39:54,731 log_exception 12360 140352292157248 Traceback (most recent call last):
  File "/home/tomaz/source/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 454, in _loadProject
    serializer.deserializeFromHdf5(self.currentProjectFile, projectFilePath, self._headless)
  File "/home/tomaz/source/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 1130, in deserializeFromHdf5
    ss.deserialize(topGroup)
  File "/home/tomaz/source/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 262, in deserialize
    self._deserialize(group[self.name], self.inslot)
  File "/home/tomaz/source/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "/home/tomaz/source/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 601, in _deserialize
    self.inslot[index][slicing] = blockArray
  File "/home/tomaz/source/ilastik-meta/lazyflow/lazyflow/slot.py", line 992, in __setitem__
    p[key] = value
  File "/home/tomaz/source/ilastik-meta/lazyflow/lazyflow/slot.py", line 992, in __setitem__
    p[key] = value
  File "/home/tomaz/source/ilastik-meta/lazyflow/lazyflow/slot.py", line 992, in __setitem__
    p[key] = value
  File "/home/tomaz/source/ilastik-meta/lazyflow/lazyflow/slot.py", line 988, in __setitem__
    self.operator.setInSlot(self.top_level_slot, self.subindex, roi, value)
  File "/home/tomaz/source/ilastik-meta/lazyflow/lazyflow/operators/opCompressedUserLabelArray.py", line 394, in setInSlot
    self._setInSlotInput(slot, subindex, roi, new_pixels)
  File "/home/tomaz/source/ilastik-meta/lazyflow/lazyflow/operators/opCompressedUserLabelArray.py", line 416, in _setInSlotInput
    block_rois = getIntersectingRois(self.Output.meta.shape, self._blockshape, (roi.start, roi.stop))
  File "/home/tomaz/source/ilastik-meta/lazyflow/lazyflow/roi.py", line 639, in getIntersectingRois
    block_rois = list(map(partial(getBlockBounds, dataset_shape, blockshape), block_starts))
  File "/home/tomaz/source/ilastik-meta/lazyflow/lazyflow/roi.py", line 667, in getBlockBounds
    block_bounds = getIntersection(block_bounds, entire_dataset_roi)
  File "/home/tomaz/source/ilastik-meta/lazyflow/lazyflow/roi.py", line 402, in getIntersection
    assert ((stop - start) > 0).all(), "Rois do not intersect: {} and {}".format(roiA, roiB)
AssertionError: Rois do not intersect: (array([  0, 504, 506,   0,   1]), array([  1, 756, 759,   1,   2])) and ([0, 0, 0, 0, 0], [104, 1600, 1200, 1, 1])
```

Doesn't seem to happen on a 2D dataset, though.
