### ISSUE TITLE
Multicut breaks when superpixels change

### ISSUE THREAD

**Issue by boykovdn** [ilastik/ilastik#2154]
## Describe the bug
Get one of two errors when try to re-evaluate MC on updated superpixels.
## Expected behavior
Updated Multicut (new blue contours in viewer)
## To Reproduce
Within the Edge Training With Multicut workflow
1. Add the 3d1c raw and probability test data in the Data Selection applet
2. Do Watershed and proceed to Training and Multicut
3. Select some edges in viewer, click 'Live Predict' under Training and 'Update Now' under Multicut
4. When the Multicut results are visualised, go back to Watershed, change a parameter and update.
5. Go to Training and Multicut and click 'Update Now' under Multicut.
6. Error to do with number of edges or failed assertions.

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
ERROR 2019-11-01 20:29:21,754 excepthooks 20166 140007111001856 Unhandled exception in thread: 'Worker #6'
ERROR 2019-11-01 20:29:21,759 excepthooks 20166 140008859813632 Unhandled exception in thread: 'Thread-6'
ERROR 2019-11-01 20:29:21,770 excepthooks 20166 140007111001856 Traceback (most recent call last):
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/boykov/sources/ilastik-meta/ilastik/ilastik/applets/multicut/multicutGui.py", line 247, in _impl
    edge_disagreements = op.EdgeLabelDisagreementDict.value
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/slot.py", line 1015, in value
    temp = self[:].wait()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/boykov/sources/ilastik-meta/ilastik/ilastik/applets/multicut/opMulticut.py", line 213, in execute
    node_labels = self.NodeLabels.value
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/slot.py", line 1015, in value
    temp = self[:].wait()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operators/valueProviders.py", line 310, in execute
    value = request.wait()[0]
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 654, in _wait_within_request
    raise_with_traceback(exc_type(exc_value), exc_tb)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/boykov/sources/ilastik-meta/ilastik/ilastik/applets/multicut/opMulticut.py", line 259, in execute
    node_labeling = self.agglomerate_with_multicut(rag, edge_probabilities, beta, solver_name)
  File "/home/boykov/sources/ilastik-meta/ilastik/ilastik/applets/multicut/opMulticut.py", line 303, in agglomerate_with_multicut
    assert edge_weights.shape == (rag.num_edges,)
AssertionError

ERROR 2019-11-01 20:29:21,772 excepthooks 20166 140008859813632 Traceback (most recent call last):
  File "/home/boykov/sources/ilastik-meta/ilastik/ilastik/excepthooks.py", line 129, in run
    run_old(*args, **kwargs)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/boykov/sources/ilastik-meta/ilastik/ilastik/applets/multicut/multicutGui.py", line 323, in updateThread
    self.topLevelOperatorView.Output((0,) * ndim, (1,) * ndim).wait()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 564, in _wait
    self._wait_within_foreign_thread(timeout)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 624, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operators/opUnblockedArrayCache.py", line 87, in execute
    self._execute_Output(slot, subindex, roi, result)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operators/opSimpleBlockedArrayCache.py", line 106, in _execute_Output
    pool.wait()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 1373, in wait
    self._clear_finishing_requests()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 1449, in _clear_finishing_requests
    req.block()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 547, in block
    self._wait(timeout)  # No return value. Use wait()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 564, in _wait
    self._wait_within_foreign_thread(timeout)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 624, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operators/opSimpleBlockedArrayCache.py", line 92, in copy_block
    self._execute_Output_impl(full_block_roi, full_block_data)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operators/opUnblockedArrayCache.py", line 112, in _execute_Output_impl
    self._fetch_and_store_block(request_roi, out=result)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operators/opUnblockedArrayCache.py", line 150, in _fetch_and_store_block
    block_data = req.wait()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operators/opCacheFixer.py", line 65, in execute
    self.Input(roi.start, roi.stop).writeInto(result).wait()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/boykov/sources/ilastik-meta/ilastik/ilastik/applets/multicut/opMulticut.py", line 167, in execute
    mapping_index_array = self.NodeLabels.value
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/slot.py", line 1015, in value
    temp = self[:].wait()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operators/valueProviders.py", line 310, in execute
    value = request.wait()[0]
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 654, in _wait_within_request
    raise_with_traceback(exc_type(exc_value), exc_tb)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/boykov/sources/ilastik-meta/ilastik/ilastik/applets/multicut/opMulticut.py", line 259, in execute
    node_labeling = self.agglomerate_with_multicut(rag, edge_probabilities, beta, solver_name)
  File "/home/boykov/sources/ilastik-meta/ilastik/ilastik/applets/multicut/opMulticut.py", line 303, in agglomerate_with_multicut
    assert edge_weights.shape == (rag.num_edges,)
AssertionError

```
OR 

```pytb
ERROR 2019-11-01 20:22:00,955 excepthooks 17970 140191742285568 Unhandled exception in thread: 'Worker #0'
ERROR 2019-11-01 20:22:00,955 excepthooks 17970 140192137950976 Unhandled exception in thread: 'Worker #7'
ERROR 2019-11-01 20:22:00,999 excepthooks 17970 140191742285568 Traceback (most recent call last):
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/boykov/sources/ilastik-meta/ilastik/ilastik/applets/multicut/multicutGui.py", line 247, in _impl
    edge_disagreements = op.EdgeLabelDisagreementDict.value
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/slot.py", line 1015, in value
    temp = self[:].wait()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/boykov/sources/ilastik-meta/ilastik/ilastik/applets/multicut/opMulticut.py", line 225, in execute
    edge_labels_from_nodes = (node_labels[rag.edge_ids[:, 0]] != node_labels[rag.edge_ids[:, 1]]).view(np.uint8)
IndexError: index 44 is out of bounds for axis 0 with size 44

ERROR 2019-11-01 20:22:01,002 excepthooks 17970 140192137950976 Traceback (most recent call last):
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/boykov/sources/ilastik-meta/ilastik/ilastik/applets/multicut/multicutGui.py", line 247, in _impl
    edge_disagreements = op.EdgeLabelDisagreementDict.value
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/slot.py", line 1015, in value
    temp = self[:].wait()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/boykov/miniconda3/envs/idev/lib/python3.7/site-packages/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/boykov/sources/ilastik-meta/ilastik/ilastik/applets/multicut/opMulticut.py", line 225, in execute
    edge_labels_from_nodes = (node_labels[rag.edge_ids[:, 0]] != node_labels[rag.edge_ids[:, 1]]).view(np.uint8)
IndexError: index 44 is out of bounds for axis 0 with size 44

```
## Screenshots
If applicable, please add screenshots to help explain your problem.

## Desktop (please complete the following information):
 - ilastik version: [e.g. 1.3.2b1]
 - OS: Ubuntu 16.04 LTS

**Comment by k-dominik** [comment]
Adding to that:

with version 1.4.0b9:

```pytb
ERROR 2020-12-02 14:03:29,284 excepthooks 12886 123145353281536 Traceback (most recent call last):
  File "/Applications/ilastik-1.4.0b9-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.4.0b9-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/multicut/multicutGui.py", line 270, in _impl
    edge_disagreements = op.EdgeLabelDisagreementDict.value
  File "/Applications/ilastik-1.4.0b9-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/lazyflow/slot.py", line 1015, in value
    temp = self[:].wait()
  File "/Applications/ilastik-1.4.0b9-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.4.0b9-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/Applications/ilastik-1.4.0b9-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/Applications/ilastik-1.4.0b9-OSX.app/Contents/Resources/lib/python3.7/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.4.0b9-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.4.0b9-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/Applications/ilastik-1.4.0b9-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/Applications/ilastik-1.4.0b9-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/multicut/opMulticut.py", line 230, in execute
    conflicts = np.where(edge_labels_from_nodes != edge_labels_from_probabilities)
  File "/Applications/ilastik-1.4.0b9-OSX.app/Contents/Resources/lib/python3.7/site-packages/pandas/core/ops.py", line 1745, in wrapper
    raise ValueError('Lengths must match to compare')
ValueError: Lengths must match to compare
```
