### ISSUE TITLE
Autocontext: crashing in headless mode

### ISSUE THREAD

**Issue by KarishmaVal** [ilastik/ilastik#2162]
## Describe the bug
We have developed an autmated image segmentation pipeline where we combine several cellprofiler .cppipe and ilastik .ilp files. The output from cellprofiler is a 6-channel 16bit composite image in h5 format, and I put this into an ilastik autocontext workflow that I have pretrained with several images. Batch processing using this works smoothly on the local GUI version of ilastik1.3.3b1-OSX, but when I try to run this using headless mode using ilastik docker containers it fails and shoots up an error saying to convert data into UNIT8. When I do this (and double check in fiji-imagej that the file is indeed 8-bit), it still throws up the same error.

## Expected behavior
To run autocontext workflow in headless mode using 16bit images.

## To Reproduce

In this zip folder I have included the command used, error message, ilastik .ilp file and the .h5 input file used to reproduce this error.

[ilastik_test.zip](https://github.com/ilastik/ilastik/files/3917724/ilastik_test.zip)

Docker container = 'ilastik/ilastik-from-binary:1.3.2b3'

## Error message/traceback

```pytb
Error executing process > 'Ilastik (20190930_KV_HypM_BRAC3539.2c.roi_1)'

Caused by:
  Process `Ilastik (20190930_KV_HypM_BRAC3539.2c.roi_1)` terminated with an error exit status (1)

Command executed:

  cp ilastik_training_params.ilp ilastik_params.ilp
  
  /ilastik-release/run_ilastik.sh \
      --headless \
      --project=ilastik_params.ilp \
      --output_format="tiff sequence" \
      --output_filename_format=./{nickname}_{result_type}_{slice_index}.tiff \
      --logfile ./ilastik_log.txt \
      composite_.h5
  rm  ilastik_params.ilp
  
  /ilastik-release/bin/python -c "import ilastik; print(ilastik.__version__)" > ilastik_version.txt

Command exit status:
  1

Command output:
  INFO lazyflow.operators.filterOperators: Using fast filters.
  INFO ilastik_main: Starting ilastik from "/ilastik-release".
  Starting ilastik from "/ilastik-release".
  INFO ilastik.shell.projectManager: Opening Project: ilastik_params.ilp

Command error:
      shell.openProjectFile(path, parsed_args.readonly)
    File "/ilastik-release/ilastik-meta/ilastik/ilastik/shell/headless/headlessShell.py", line 117, in openProjectFile
      self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 146, in wrapper
      return func(*args, **kwargs)
    File "/ilastik-release/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 433, in _loadProject
      serializer.deserializeFromHdf5(self.currentProjectFile, projectFilePath, self._headless)
    File "/ilastik-release/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 1055, in deserializeFromHdf5
      self._deserializeFromHdf5(topGroup, groupVersion, hdf5File, projectFilePath, headless)
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 146, in wrapper
      return func(*args, **kwargs)
    File "/ilastik-release/ilastik-meta/ilastik/ilastik/applets/dataSelection/dataSelectionSerializer.py", line 366, in _deserializeFromHdf5
      self.topLevelOperator.WorkingDirectory.setValue( working_dir )
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 118, in call_in_setup_context
      return func(self, *args, **kwargs)
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1232, in setValue
      self._changed()
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1433, in _changed
      c._changed()
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1433, in _changed
      c._changed()
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1433, in _changed
      c._changed()
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1439, in _changed
      self._configureOperator(self)
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1453, in _configureOperator
      self.operator._setupOutputs()
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/operator.py", line 455, in _setupOutputs
      self.setupOutputs()
    File "/ilastik-release/ilastik-meta/ilastik/ilastik/applets/dataSelection/opDataSelection.py", line 487, in setupOutputs
      self.Image.connect(providerSlot)
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 118, in call_in_setup_context
      return func(self, *args, **kwargs)
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 557, in connect
      self._changed()
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1433, in _changed
      c._changed()
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1433, in _changed
      c._changed()
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1433, in _changed
      c._changed()
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1422, in _changed
      self._sig_ready(self)
    File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/utility/orderedSignal.py", line 77, in __call__
      f(*args, **kw)
    File "/ilastik-release/ilastik-meta/ilastik/ilastik/workflows/newAutocontext/newAutocontextWorkflow.py", line 250, in checkConstraints
      raise DatasetConstraintError( "Autocontext Workflow", msg, unfixable=True )
  ilastik.applets.base.applet.DatasetConstraintError: Constraint of 'Autocontext Workflow' applet was violated: The Autocontext Workflow only supports 8-bit images (UINT8 pixel type).
  Your image has a pixel type of uint16.  Please convert your data to UINT8 and try again.

```

## Desktop (please complete the following information):
 - ilastik version: [1.3.3b1-OSX]
 - OS: [macOS 10.12.6: Sierra]

**Comment by KarishmaVal** [comment]
@drpatelh

**Comment by k-dominik** [comment]
Hi @KarishmaVal,

in version 1.3.3b1 we didn't support 16 bit images in autocontext yet. I created a [new docker container (1.3.3post1)](https://hub.docker.com/layers/ilastik/ilastik-from-binary/1.3.3post1/images/sha256-24710665919fb87d0979bc9cad7f28e696f5f9e2f8444ccc5df1d341c77fd7ba), could you check it out, whether this resolves your issue?

**Comment by drpatelh** [comment]
Great! Thanks for updating the Docker image @k-dominik 👍 That was the first thing we checked yesterday. @KarishmaVal can you replace the line below in the `test` directory I created:
https://github.com/nf-core/imcyto/blob/2e830372779df115b11871f58259d780c1ba02ac/conf/base.config#L47

to 
`container = 'ilastik/ilastik-from-binary:1.3.3post1'`

Maybe run before and after the changes to make sure this solves the issue.

**Comment by KarishmaVal** [comment]
Hi @k-dominik thank you for updating the docker container! 
I tried to run again but it still doesn't resolve the issue - this time a new error pops up:

```pytb
Warning: Ignoring your non-empty LD_LIBRARY_PATH
2019-12-06 14:12:15,415 __main__-ERROR: An unexpected error occurred. Your installation might be corrupt!
Traceback (most recent call last):
  File "/ilastik-release/lib/python3.7/site-packages/ilastik_install/cli.py", line 114, in <module>
    main()
  File "/ilastik-release/lib/python3.7/site-packages/ilastik_install/cli.py", line 108, in main
    args.root / "conda-meta", args.root, prefix_config.prefix, args.root
  File "/ilastik-release/lib/python3.7/site-packages/ilastik_install/core.py", line 58, in replace_prefixes
    mode,
  File "/ilastik-release/lib/python3.7/site-packages/ilastik_install/external/_constructor.py", line 157, in update_prefix
    exp_backoff_fn(os.unlink, path)
  File "/ilastik-release/lib/python3.7/site-packages/ilastik_install/external/_constructor.py", line 46, in exp_backoff_fn
    return fn(*args)
PermissionError: [Errno 13] Permission denied: '/ilastik-release/lib/libatk-1.0.so.0.23209.1'
WARNING __init__.py(20): UserWarning: init: Could not import tiktorch classifier
WARNING 2019-12-06 14:12:19,923 opConservationTracking 22278 140636913444672 Could not find any ILP solver
WARNING 2019-12-06 14:12:19,940 opStructuredTracking 22278 140636913444672 Could not find any ILP solver
WARNING 2019-12-06 14:12:19,943 structuredTrackingWorkflow 22278 140636913444672 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
WARNING dataset.py(313): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING opSimpleBlockedArrayCache.py(43): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
WARNING opSlicedBlockedArrayCache.py(141): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
ERROR 2019-12-06 14:12:22,389 log_exception 22278 140636913444672 Traceback (most recent call last):
  File "/ilastik-release/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 454, in _loadProject
    serializer.deserializeFromHdf5(self.currentProjectFile, projectFilePath, self._headless)
  File "/ilastik-release/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 1130, in deserializeFromHdf5
    ss.deserialize(topGroup)
  File "/ilastik-release/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 262, in deserialize
    self._deserialize(group[self.name], self.inslot)
  File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "/ilastik-release/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 601, in _deserialize
    self.inslot[index][slicing] = blockArray
  File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 992, in __setitem__
    p[key] = value
  File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 992, in __setitem__
    p[key] = value
  File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 992, in __setitem__
    p[key] = value
  File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 988, in __setitem__
    self.operator.setInSlot(self.top_level_slot, self.subindex, roi, value)
  File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opCompressedUserLabelArray.py", line 394, in setInSlot
    self._setInSlotInput(slot, subindex, roi, new_pixels)
  File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opCompressedUserLabelArray.py", line 423, in _setInSlotInput
    new_block_pixels = new_pixels[roiToSlice(*roi_within_data)]
IndexError: too many indices for array
ERROR 2019-12-06 14:12:22,389 log_exception 22278 140636913444672 Project could not be loaded due to the exception shown above.
Aborting Project Open Action
ERROR 2019-12-06 14:12:22,464 excepthooks 22278 140636913444672 Unhandled exception in thread: 'MainThread'
ERROR 2019-12-06 14:12:22,466 excepthooks 22278 140636913444672 Traceback (most recent call last):
  File "/ilastik-release/ilastik-meta/ilastik/ilastik.py", line 134, in <module>
    main()
  File "/ilastik-release/ilastik-meta/ilastik/ilastik.py", line 128, in main
    hShell = ilastik_main.main(parsed_args, workflow_cmdline_args)
  File "/ilastik-release/ilastik-meta/ilastik/ilastik_main.py", line 165, in main
    f(shell)
  File "/ilastik-release/ilastik-meta/ilastik/ilastik_main.py", line 338, in loadProject
    shell.openProjectFile(path, parsed_args.readonly)
  File "/ilastik-release/ilastik-meta/ilastik/ilastik/shell/headless/headlessShell.py", line 125, in openProjectFile
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "/ilastik-release/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 454, in _loadProject
    serializer.deserializeFromHdf5(self.currentProjectFile, projectFilePath, self._headless)
  File "/ilastik-release/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 1130, in deserializeFromHdf5
    ss.deserialize(topGroup)
  File "/ilastik-release/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 262, in deserialize
    self._deserialize(group[self.name], self.inslot)
  File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "/ilastik-release/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 601, in _deserialize
    self.inslot[index][slicing] = blockArray
  File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 992, in __setitem__
    p[key] = value
  File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 992, in __setitem__
    p[key] = value
  File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 992, in __setitem__
    p[key] = value
  File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 988, in __setitem__
    self.operator.setInSlot(self.top_level_slot, self.subindex, roi, value)
  File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opCompressedUserLabelArray.py", line 394, in setInSlot
    self._setInSlotInput(slot, subindex, roi, new_pixels)
  File "/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opCompressedUserLabelArray.py", line 423, in _setInSlotInput
    new_block_pixels = new_pixels[roiToSlice(*roi_within_data)]
IndexError: too many indices for array
```
Do you have any suggestions how to resolve this?

**Comment by k-dominik** [comment]
closing this due to inactivity.
