### ISSUE TITLE
Animal tracking on headless mode doesn't recognise --export_source="Plugin"

### ISSUE THREAD

**Issue by Ian-Brettell** [ilastik/ilastik#2168]
## Describe the bug

When I run this bash code with Ilastik v1.3.3 on headless mode:
```bash
./ilastik-1.3.3-Linux/run_ilastik.sh --headless \
  --project=<animal_tracking_project>.ilp \
  --readonly \
  --raw_data=<video_file>.h5 \
  --prediction_maps=<prediction_map>.h5 \
  --export_source="Plugin" \
  --export_plugin="CSV-Table"
```
I get the following error:
```bash
Unused command-line args: ['--export_source=Plugin', '--export_plugin=CSV-Table']  
```

Then when I escape the quotes as follows:
```bash
./ilastik-1.3.3-Linux/run_ilastik.sh --headless \
  --project=<animal_tracking_project>.ilp \
  --readonly \
  --raw_data=<video_file>.h5 \
  --prediction_maps=<prediction_map>.h5 \
  --export_source=\"Plugin\" \
  --export_plugin=\"CSV-Table\"
```
It gives me this error:
```bash
export_plugin should only be specified if export_source is set to Plugin.
```
Even though it appears to recognise the arguments (as set out elsewhere in the error message):
```bash
args   = (<ilastik.shell.headless.headlessShell.HeadlessShell object at 0x2b7ed822dc88>, True, ['--raw_data=<video_file>.h5', '--prediction_maps=<prediction_map>.h5', '--export_source="Plugin"', '--export_plugin="CSV-Table"'], [])
```

## Expected behaviour

- The code should generate a CSV file in the same folder as the `<video_file>.h5`.
- The CSV can be successfully generated via the GUI.
- Similar code to that of the first chunk worked for Ilastik v1.3.2.

## To Reproduce

1. Within the `Animal Tracking [Inputs: Raw Data, Pixel Prediction Map]` workflow:
2. Follow the steps set out in the `Automatic Tracking` section here: [https://www.ilastik.org/documentation/animaltracking/animaltracking](url).
3. Export the results as a CSV table.
4. Save the project.
5. Run this code:

```bash
./ilastik-1.3.3-Linux/run_ilastik.sh --headless \
  --project=<animal_tracking_project>.ilp \
  --readonly \
  --raw_data=<video_file>.h5 \
  --prediction_maps=<prediction_map>.h5 \
  --export_source="Plugin" \
  --export_plugin="CSV-Table"
```

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```bash
Warning: Ignoring your non-empty LD_LIBRARY_PATH
Warning: Ignoring your non-empty QT_PLUGIN_PATH
Could not find /nfs/software/birney/ilastik-1.3.3-Linux/python-scripts/ilastik-install. ignoring.
INFO lazyflow.operators.filterOperators: Using fast filters.
WARNING __init__.py(20): UserWarning: init: Could not import tiktorch classifier
INFO ilastik_main: Starting ilastik from "/nfs/software/birney/ilastik-1.3.3-Linux".
Starting ilastik from "/nfs/software/birney/ilastik-1.3.3-Linux".
WARNING 2020-01-04 18:07:37,578 opConservationTracking 318628 47544041971392 Could not find any ILP solver
WARNING 2020-01-04 18:07:37,613 opStructuredTracking 318628 47544041971392 Could not find any ILP solver
WARNING 2020-01-04 18:07:37,617 structuredTrackingWorkflow 318628 47544041971392 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
INFO ilastik.shell.projectManager: Opening Project: ilastik/projects/20191224_antrack.ilp
WARNING dataset.py(313): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
ERROR 2020-01-04 18:07:39,388 excepthooks 318628 47544041971392 Unhandled exception in thread: 'MainThread'
ERROR 2020-01-04 18:07:39,389 excepthooks 318628 47544041971392 Traceback (most recent call last):
  File "/nfs/software/birney/ilastik-1.3.3-Linux/ilastik-meta/lazyflow/lazyflow/operator.py", line 118, in __call__
    instance = ABCMeta.__call__(cls, *args, **kwargs)
  File "/nfs/software/birney/ilastik-1.3.3-Linux/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/animalConservationTrackingWorkflow.py", line 27, in __init__
    shell, headless, workflow_cmdline_args, *args, **kwargs
  File "/nfs/software/birney/ilastik-1.3.3-Linux/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 168, in __init__
    self._data_export_args, unused_args = self.dataExportApplet.parse_known_cmdline_args(workflow_cmdline_args)
  File "/nfs/software/birney/ilastik-1.3.3-Linux/ilastik-meta/ilastik/ilastik/applets/tracking/base/trackingBaseDataExportApplet.py", line 151, in parse_known_cmdline_args
    raise Exception(msg)
Exception: Error parsing command-line arguments for tracking data export applet.
export_plugin should only be specified if export_source is set to Plugin.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/software/birney/ilastik-1.3.3-Linux/ilastik-meta/ilastik/ilastik.py", line 134, in <module>
    main()
  File "/nfs/software/birney/ilastik-1.3.3-Linux/ilastik-meta/ilastik/ilastik.py", line 128, in main
    hShell = ilastik_main.main(parsed_args, workflow_cmdline_args)
  File "/nfs/software/birney/ilastik-1.3.3-Linux/ilastik-meta/ilastik/ilastik_main.py", line 165, in main
    f(shell)
  File "/nfs/software/birney/ilastik-1.3.3-Linux/ilastik-meta/ilastik/ilastik_main.py", line 338, in loadProject
    shell.openProjectFile(path, parsed_args.readonly)
  File "/nfs/software/birney/ilastik-1.3.3-Linux/ilastik-meta/ilastik/ilastik/shell/headless/headlessShell.py", line 123, in openProjectFile
    project_creation_args=project_creation_args,
  File "/nfs/software/birney/ilastik-1.3.3-Linux/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 239, in __init__
    self.workflow = workflowClass(shell, headless, self._workflow_cmdline_args, self._project_creation_args)
  File "/nfs/software/birney/ilastik-1.3.3-Linux/ilastik-meta/lazyflow/lazyflow/operator.py", line 140, in __call__
    raise RuntimeError(err)
RuntimeError: Could not create instance of '<class 'ilastik.workflows.tracking.conservation.animalConservationTrackingWorkflow.AnimalConservationTrackingWorkflowFromPrediction'>'
args   = (<ilastik.shell.headless.headlessShell.HeadlessShell object at 0x2b3de0446048>, True, ['--raw_data=ilastik/20191213_training_vids/20191117_1529_72-2_L_B_q3_no_f16001-18000.h5', '--prediction_maps=ilastik/20191213_training_probabilities/20191117_1529_72-2_L_B_q3_no_f16001-18000_Probabilities.h5', '--export_source="Plugin"', '--export_plugin="CSV-Table"'], [])
kwargs = {}
The exception was:
Error parsing command-line arguments for tracking data export applet.
export_plugin should only be specified if export_source is set to Plugin.
Traceback:
Traceback (most recent call last):
  File "/nfs/software/birney/ilastik-1.3.3-Linux/ilastik-meta/lazyflow/lazyflow/operator.py", line 118, in __call__
    instance = ABCMeta.__call__(cls, *args, **kwargs)
  File "/nfs/software/birney/ilastik-1.3.3-Linux/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/animalConservationTrackingWorkflow.py", line 27, in __init__
    shell, headless, workflow_cmdline_args, *args, **kwargs
  File "/nfs/software/birney/ilastik-1.3.3-Linux/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 168, in __init__
    self._data_export_args, unused_args = self.dataExportApplet.parse_known_cmdline_args(workflow_cmdline_args)
  File "/nfs/software/birney/ilastik-1.3.3-Linux/ilastik-meta/ilastik/ilastik/applets/tracking/base/trackingBaseDataExportApplet.py", line 151, in parse_known_cmdline_args
    raise Exception(msg)
Exception: Error parsing command-line arguments for tracking data export applet.
export_plugin should only be specified if export_source is set to Plugin.
```

## Screenshots
N/A

## Desktop (please complete the following information):
 - ilastik version: 1.3.3
 - OS: Red Hat Enterprise Linux Server release 7.4 (Maipo)

**Comment by Ian-Brettell** [comment]
## Resolution

This error was a red herring:
```
Unused command-line args: ['--export_source=Plugin', '--export_plugin=CSV-Table']  
```
When left undisturbed, the process eventually finished as expected.
