### ISSUE TITLE
importing projects

### ISSUE THREAD

**Issue by reinat168** [ilastik/ilastik#2176]
## Describe the bug
I have saved an ilastik project with h5 data set. I am trying to open it in different computer and it ask for the images (training set). However I get an error massage that the link to the images can not be created as the name already exist.

**Comment by nieder** [comment]
Ditto. I was given an .ilp file by a collaborator. We are using the same image files, but his mountpoint for the imagestore is different than mine, so the full path to the images doesn't match.
When trying to open the project, ilastik says that it can't find image file X:
![image](https://user-images.githubusercontent.com/1105137/74468295-361e3e00-4e60-11ea-9e5e-c3fa00fa7329.png)

After searching out the image in my filesystem, ilastik pops up this error:
![image](https://user-images.githubusercontent.com/1105137/74468217-138c2500-4e60-11ea-9d19-6d9e5fbf5853.png)

**Comment by k-dominik** [comment]
Hi @reinat168 @nieder,

thank you for reporting this. This is a bug in 1.3.3 that has been fixed in #2173. We'll do a new release by the end of this week, that includes this fix.

Cheers
Dominik

**Comment by alecrimi** [comment]
Hi,
we have the same problem.
we are on Windows and we used the exe installer, if we remove the software and we download a new one and re-install it, is it going to solve this?

**Comment by k-dominik** [comment]
Hi @alecrimi, no, this will unfortunately not solve it. We're a little behind on the release, but will have a new beta early next week. I'll post an update here!

**Comment by alecrimi** [comment]
Hi,
I downloaded the beta, it is kindo of running, but when I do via the command line:
`run-ilastik.bat --headless -project:myproject.ilp test.tif` the process got stucked after a while with no error. Should I open another issue?

**Comment by Tomaz-Vieira** [comment]
Hello, alecrimi

Did you run exactly that line? If so, then it should be
`--project myproject.ilp` or `--project=myproject.ilp`
as opposed to
`--project:myproject.ilp`

Do let us know if that's the case; if it's not, we can go hunting for bugs. Still, ilastik should in the future produce meaningful error messages on wrong command line parameters, but that's a lesser issue.

**Comment by k-dominik** [comment]
> Hi,
> I downloaded the beta, it is kindo of running, but when I do via the command line:
> `run-ilastik.bat --headless -project:myproject.ilp test.tif` the process got stucked after a while with no error. Should I open another issue?

just out of curiosity, which beta version are you referring to?

**Comment by alecrimi** [comment]
sorry for the mess, yes I use the "=" character and still having problem with the beta but not the stable version

**Comment by k-dominik** [comment]
Hi @alecrimi,

We have a new beta (`1.4.0b1`) online since yesterday. You can download it from [our download site](https://www.ilastik.org/download.html#beta).

**Comment by nieder** [comment]
1.4.0b1 (win64) works for me. I can now load and run an ilp file the collaborator sent me that wouldn't load in 1.3.3p2.

**Comment by alecrimi** [comment]
Hi.
THanks, the file opening seems to be fixed but when I run command line on my new file  as described above, I got this:

`

ERROR 2020-03-05 18:57:13,818 log_exception 11908 3004 Project could not be loaded due to the exception shown above.
Aborting Project Open Action
ERROR 2020-03-05 18:57:14,005 excepthooks 11908 3004 Unhandled exception in thread: 'MainThread'
ERROR 2020-03-05 18:57:14,021 excepthooks 11908 3004 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\ilastik\ilastik.py", line 134, in <module>
    main()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\ilastik\ilastik.py", line 128, in main
    hShell = ilastik_main.main(parsed_args, workflow_cmdline_args)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\ilastik\ilastik_main.py", line 165, in main
    f(shell)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\ilastik\ilastik_main.py", line 338, in loadProject
    shell.openProjectFile(path, parsed_args.readonly)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\ilastik\ilastik\shell\headless\headlessShell.py", line 125, in openProjectFile
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 467, in _loadProject
    self.workflow.onProjectLoaded(self)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\ilastik\ilastik\workflows\pixelClassification\pixelClassificationWorkflow.py", line 382, in onProjectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 64, in run_export_from_parsed_args
    return self.run_export(role_path_dict, parsed_args.input_axes, sequence_axis=parsed_args.stack_along)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 118, in run_export
    progress_callback=partial(lerpProgressSignal, global_progress_start, global_progress_end),
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\ilastik\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 181, in export_dataset
    opDataExport.run_export()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\ilastik\ilastik\applets\dataExport\opDataExport.py", line 251, in run_export
    self._opFormattedExport.run_export()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\ioOperators\opFormattedDataExport.py", line 257, in run_export
    self._opExportSlot.run_export()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\ioOperators\opExportSlot.py", line 257, in run_export
    export_func()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\ioOperators\opExportSlot.py", line 380, in _export_multipage_tiff
    opExport.run_export()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\ioOperators\opExportMultipageTiff.py", line 94, in run_export
    batch.execute()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\utility\roiRequestBatch.py", line 185, in execute
    raise_with_traceback(exc_type(exc_value), exc_tb)
  File "C:\Program Files\ilastik-1.4.0b1\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\opReorderAxes.py", line 171, in execute
    self.Input(*in_roi).writeInto(result_input_view).wait()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 541, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.4.0b1\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\opReorderAxes.py", line 171, in execute
    self.Input(*in_roi).writeInto(result_input_view).wait()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 541, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.4.0b1\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\generic.py", line 592, in execute
    matrix = req.wait()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 541, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.4.0b1\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\valueProviders.py", line 130, in execute
    req.wait()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 541, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.4.0b1\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\generic.py", line 443, in execute
    self.Input(*input_roi).writeInto(result).wait()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 541, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.4.0b1\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\classifierOperators.py", line 481, in execute
    probabilities = self._calculate_probabilities(roi)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\classifierOperators.py", line 593, in _calculate_probabilities
    input_data = self.Image[newKey].wait()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 541, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.4.0b1\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\opReorderAxes.py", line 171, in execute
    self.Input(*in_roi).writeInto(result_input_view).wait()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 541, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.4.0b1\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\opPixelFeaturesPresmoothed.py", line 377, in execute
    source = req.wait()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 541, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.4.0b1\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\opReorderAxes.py", line 171, in execute
    self.Input(*in_roi).writeInto(result_input_view).wait()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 541, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.4.0b1\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\opReorderAxes.py", line 171, in execute
    self.Input(*in_roi).writeInto(result_input_view).wait()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 541, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.4.0b1\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\valueProviders.py", line 130, in execute
    req.wait()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 541, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.4.0b1\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\valueProviders.py", line 130, in execute
    req.wait()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 541, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.4.0b1\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\opUnblockedArrayCache.py", line 87, in execute
    self._execute_Output(slot, subindex, roi, result)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\opSimpleBlockedArrayCache.py", line 106, in _execute_Output
    pool.wait()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1354, in wait
    self._clear_finishing_requests()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 1449, in _clear_finishing_requests
    req.block()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 547, in block
    self._wait(timeout)  # No return value. Use wait()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 654, in _wait_within_request
    raise_with_traceback(exc_type(exc_value), exc_tb)
  File "C:\Program Files\ilastik-1.4.0b1\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\opSimpleBlockedArrayCache.py", line 81, in copy_block
    self._execute_Output_impl(clipped_block_roi, result[roiToSlice(*output_roi)])
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\opUnblockedArrayCache.py", line 112, in _execute_Output_impl
    self._fetch_and_store_block(request_roi, out=result)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\opUnblockedArrayCache.py", line 150, in _fetch_and_store_block
    block_data = req.wait()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 541, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.4.0b1\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\opCacheFixer.py", line 65, in execute
    self.Input(roi.start, roi.stop).writeInto(result).wait()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 541, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.4.0b1\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\request\request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "C:\Program Files\ilastik-1.4.0b1\ilastik-meta\lazyflow\lazyflow\operators\ioOperators\opTiffReader.py", line 159, in execute
    self._filepath, dtype="NATIVE", index=int(tiff_page_list_index), order="C"
RuntimeError:
Invalid TIFF image index
(C:\Users\kutra\miniconda3\conda-bld\vigra_1582727041550\work\src\impex\tiff.cxx:356)`

**Comment by alecrimi** [comment]
Assuming I will leave some time to have this stable which older version can I use which is known to have no issue with opening relocated files and command line?
