### ISSUE TITLE
Possible race condition in OpCompressedCache tests

### ISSUE THREAD

**Issue by m-novikov** [ilastik/ilastik#2204]
The test can occasionally fail with:
```
[00:08:24] ================================== FAILURES ===================================
[00:08:24] ________________ TestOpCompressedCache.testMultiThread_masked _________________
[00:08:24] 
[00:08:24] self = <tests.test_lazyflow.test_operators.testOpCompressedCache.TestOpCompressedCache object at 0x00000025DDFA8E10>
[00:08:24] 
[00:08:24]     def testMultiThread_masked(self):
[00:08:24]         logger.info("Generating sample data...")
[00:08:24]         sampleData = numpy.indices((3, 100, 200, 150, 2), dtype=numpy.float32).sum(0)
[00:08:24]         sampleData = sampleData.view(numpy.ma.masked_array)
[00:08:24]         sampleData.set_fill_value(numpy.float32(numpy.nan))
[00:08:24]         sampleData[0] = numpy.ma.masked
[00:08:24]     
[00:08:24]         graph = Graph()
[00:08:24]         opData = OpArrayPiper(graph=graph)
[00:08:24]         opData.Input.meta.has_mask = True
[00:08:24]         opData.Input.meta.axistags = vigra.defaultAxistags("txyzc")
[00:08:24]         opData.Input.setValue(sampleData)
[00:08:24]     
[00:08:24]         op = OpCompressedCache(parent=None, graph=graph)
[00:08:24]         # logger.debug("Setting block shape...")
[00:08:24]         op.BlockShape.setValue([1, 100, 75, 50, 2])
[00:08:24]         op.Input.connect(opData.Output)
[00:08:24]     
[00:08:24]         assert op.Output.ready()
[00:08:24]     
[00:08:24]         slicing = numpy.s_[0:2, 0:100, 50:150, 75:150, 0:1]
[00:08:24]         expectedData = sampleData[slicing]
[00:08:24]     
[00:08:24]         results = {}
[00:08:24]     
[00:08:24]         def readData(resultIndex):
[00:08:24]             results[resultIndex] = op.Output[slicing].wait()
[00:08:24]     
[00:08:24]         threads = []
[00:08:24]         for i in range(10):
[00:08:24]             threads.append(threading.Thread(target=functools.partial(readData, i)))
[00:08:24]     
[00:08:24]         for th in threads:
[00:08:24]             th.start()
[00:08:24]     
[00:08:24]         for th in threads:
[00:08:24]             th.join()
[00:08:24]     
[00:08:24] >       assert len(results) == len(threads), "Didn't get all results."
[00:08:24] E       AssertionError: Didn't get all results.
[00:08:24] E       assert 9 == 10
[00:08:24] E        +  where 9 = len({0: masked_array(\n  data=[[[[[--],\n           [--],\n           [--],\n           ...,\n           [--],\n           [--],...          ...,\n           [False],\n           [False],\n           [False]]]]],\n  fill_value=nan,\n  dtype=float32), ...})
[00:08:24] E        +  and   10 = len([<Thread(Thread-30, stopped 2620)>, <Thread(Thread-31, stopped 2252)>, <Thread(Thread-32, stopped 1432)>, <Thread(Thread-33, stopped 2200)>, <Thread(Thread-34, stopped 1104)>, <Thread(Thread-35, stopped 1360)>, ...])
[00:08:24]
```

**Comment by m-novikov** [comment]
Related  traceback from thread:
```
[00:08:15] Traceback (most recent call last):
[00:08:15]   File "C:\Miniconda37-x64\envs\test-env\lib\threading.py", line 917, in _bootstrap_inner
[00:08:15]     self.run()
[00:08:15]   File "C:\Miniconda37-x64\envs\test-env\lib\threading.py", line 865, in run
[00:08:15]     self._target(*self._args, **self._kwargs)
[00:08:15]   File "C:\ilastik\ilastik-meta\lazyflow\tests\test_lazyflow\test_operators\testOpCompressedCache.py", line 437, in readData
[00:08:15]     results[resultIndex] = op.Output[slicing].wait()
[00:08:15]   File "C:\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 541, in wait
[00:08:15]     return self._wait(timeout)
[00:08:15]   File "C:\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 564, in _wait
[00:08:15]     self._wait_within_foreign_thread(timeout)
[00:08:15]   File "C:\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 624, in _wait_within_foreign_thread
[00:08:15]     raise_with_traceback(exc_value, exc_tb)
[00:08:15]   File "C:\Miniconda37-x64\envs\test-env\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
[00:08:15]     raise exc.with_traceback(traceback)
[00:08:15]   File "C:\ilastik\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
[00:08:15]     self._result = self.fn()
[00:08:15]   File "C:\ilastik\ilastik-meta\lazyflow\lazyflow\slot.py", line 869, in __call__
[00:08:15]     result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
[00:08:15]   File "C:\ilastik\ilastik-meta\lazyflow\lazyflow\operator.py", line 591, in call_execute
[00:08:15]     return self.execute(slot, subindex, roi, result, **kwargs)
[00:08:15]   File "C:\ilastik\ilastik-meta\lazyflow\lazyflow\operators\opCompressedCache.py", line 145, in execute
[00:08:15]     return self._executeOutput(roi, destination)
[00:08:15]   File "C:\ilastik\ilastik-meta\lazyflow\lazyflow\operators\opCompressedCache.py", line 166, in _executeOutput
[00:08:15]     self._copyData(roi, destination, block_starts)
[00:08:15]   File "C:\ilastik\ilastik-meta\lazyflow\lazyflow\operators\opCompressedCache.py", line 204, in _copyData
[00:08:15]     destination.mask[destination_relative_intersection_slicing] = dataset["mask"][
[00:08:15]   File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
[00:08:15]   File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
[00:08:15]   File "C:\Miniconda37-x64\envs\test-env\lib\site-packages\h5py\_hl\group.py", line 264, in __getitem__
[00:08:15]     oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
[00:08:15]   File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
[00:08:15]   File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
[00:08:15]   File "h5py\h5o.pyx", line 190, in h5py.h5o.open
[00:08:15] ValueError: Not a location (invalid object ID)
```
