### ISSUE TITLE
Exception for multichannel, channel first images in NN workflow

### ISSUE THREAD

**Issue by FynnBe** [ilastik/ilastik#2221]
## Bug
Exception for multichannel images (with channel dimension not the last dimension)

## Expected
The NN workflow should be oblivous to axis order.

## To Reproduce
Within the NN workflow
1. Add some multichannel input with channel axis first
2.  load a model

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
INFO ilastik_main: Starting ilastik in debug mode from "C:\repos".
Starting ilastik in debug mode from "C:\repos".
INFO lazyflow.operators.filterOperators: Using fast filters.
INFO ilastik_main: Resetting lazyflow thread pool with 8 threads.
WARNING 2020-03-31 16:02:15,264 opConservationTracking 284 13208 Could not find any ILP solver
WARNING 2020-03-31 16:02:15,279 opStructuredTracking 284 13208 Could not find any ILP solver
WARNING 2020-03-31 16:02:15,282 structuredTrackingWorkflow 284 13208 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
INFO OpenGL.acceleratesupport: No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
INFO ilastik.shell.projectManager: Opening Project: C:/Users/fbeut/MyProject.ilp
WARNING slot.py(1290): UserWarning: Deprecated use slot.operator property instead
WARNING slicingtools.py(269): FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
WARNING tiling.py(366): UserWarning: FIXME: This is a slow way to look for the items we want.
_TilesCache._layerCache should be a dict-of-dict-of-dict for faster lookup!
DEBUG ilastik.applets.networkClassification.opNNclass: got training shape [0, 0, 0, 128, 128] and axisorder ['c', 'y', 'x'] => Set BlockShapeTrain to (9999, -60, -60)
DEBUG ilastik.applets.networkClassification.opNNclass: got largest valid shape [ -1   3  -1 324 324] and axis order ['c', 'y', 'x'] => Set BlockShapeInference to (9999, 324, 324)
WARNING slot.py(1033): UserWarning: FIXME: Slot.value for slot ModelSession is <lazyflow.operators.tiktorch.classifier.ModelSession object at 0x000001D23109C5C0>, which should be wrapped in an ndarray.
ERROR 2020-03-31 16:02:38,693 excepthooks 284 13208 Unhandled exception in thread: 'MainThread'
ERROR 2020-03-31 16:02:38,702 excepthooks 284 13208 Traceback (most recent call last):
  File "C:\repos\ilastik-meta\ilastik\ilastik\applets\networkClassification\nnClassGui.py", line 755, in addModel
    self.add_NN_classifiers(filename)
  File "C:\repos\ilastik-meta\ilastik\ilastik\applets\networkClassification\nnClassGui.py", line 778, in add_NN_classifiers
    success = self.topLevelOperatorView.set_model(model_f.read())
  File "C:\repos\ilastik-meta\ilastik\ilastik\applets\networkClassification\opNNclass.py", line 310, in set_model
    self.ModelBinary.setValue(model_content)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1143, in setValue
    self._changed()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1354, in _changed_impl
    c._changed()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1361, in _changed_impl
    self._configureOperator(self)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1374, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\operator.py", line 498, in _setupOutputs
    self.setupOutputs()
  File "C:\repos\ilastik-meta\ilastik\ilastik\applets\networkClassification\opNNclass.py", line 116, in setupOutputs
    self.TiktorchModel.setValue(session)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1143, in setValue
    self._changed()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1354, in _changed_impl
    c._changed()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1361, in _changed_impl
    self._configureOperator(self)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1374, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\operator.py", line 498, in _setupOutputs
    self.setupOutputs()
  File "C:\repos\ilastik-meta\ilastik\ilastik\applets\networkClassification\opNNclass.py", line 181, in setupOutputs
    self.NumClasses.setValue(numClasses)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1143, in setValue
    self._changed()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1361, in _changed_impl
    self._configureOperator(self)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1374, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\operator.py", line 498, in _setupOutputs
    self.setupOutputs()
  File "C:\repos\ilastik-meta\ilastik\ilastik\applets\networkClassification\opNNclass.py", line 182, in setupOutputs
    self.opTrain.MaxLabel.setValue(numClasses)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1143, in setValue
    self._changed()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1361, in _changed_impl
    self._configureOperator(self)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1374, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\repos\ilastik-meta\ilastik\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\operator.py", line 498, in _setupOutputs
    self.setupOutputs()
  File "C:\repos\ilastik-meta\ilastik\lazyflow\operators\tiktorch\operators.py", line 69, in setupOutputs
    ), f"This opearator assumes channel is the last axis. problem: {slot}"
AssertionError: This opearator assumes channel is the last axis. problem: OpTikTorchTrainClassifierBlocked.Images [len=1 level=1]: 	{_ready : False, has_mask : None, _dirty : False}

```
server log:
```
(tiktorch-server-env) C:\repos\tiktorch>python -m tiktorch.server
21796
Starting server on 127.0.0.1:5567
16:02:33.808 [MainProcess/ThreadPoolExecutor-0_0] INFO Created session 20b5a78591f14185bae514b47cf08f93
16:02:33.809 [MainProcess/ThreadPoolExecutor-0_0] DEBUG Registered close handler <bound method _Lease.terminate of <tiktorch.server.device_pool._Lease object at 0x000002BC0CC15358>> for session 20b5a78591f14185bae514b47cf08f93
16:02:33.811 [MainProcess/ThreadPoolExecutor-0_0] DEBUG Registered close handler <tiktorch.rpc.mp.create_client.<locals>._make_method.<locals>.MethodWrapper object at 0x000002BC0CC224A8> for session 20b5a78591f14185bae514b47cf08f93
16:02:38.650 [ModelSessionProcess/ModelThread] INFO Starting session worker
16:02:38.651 [ModelSessionProcess/ModelThread] DEBUG Set new state State.Paused
```
## Desktop:
OS: Windows 10
```
ilastik ilastik/ilastik@6c1a3dd5957b24f79f78038b0af63603bbd163c7
lazyflow ilastik/lazyflow@77b2f317c9206c51ffa48a6a01d652f3cff19188
volumina ilastik/volumina@e66ca6791b7d68b7313065f72f30ec2b7a7548d6
```

**Comment by k-dominik** [comment]
fixed in 26b908813ee3e7b8abe5f1ec7b11eb85a53a58c3
