### ISSUE TITLE
ilastik 1.4.0b5 does not start on win 10 -- No module named 'elf'

### ISSUE THREAD

**Issue by FynnBe** [ilastik/ilastik#2255]
## Error message/traceback
```pytb
INFO ilastik.app: Starting ilastik in debug mode from "C:\Program Files\ilastik-1.4.0b5\ilastik-meta".
Starting ilastik in debug mode from "C:\Program Files\ilastik-1.4.0b5\ilastik-meta".
INFO ilastik.app: Resetting lazyflow thread pool with 8 threads.
WARNING 2020-06-30 15:24:17,943 opConservationTracking 16056 23156 Could not find any ILP solver
WARNING 2020-06-30 15:24:18,019 opStructuredTracking 16056 23156 Could not find any ILP solver
WARNING 2020-06-30 15:24:18,022 structuredTrackingWorkflow 16056 23156 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
WARNING 2020-06-30 15:24:18,183 __init__ 16056 23156 Failed to import 'Edge Training With Multicut' workflow; check dependencies: No module named 'elf'
INFO OpenGL.acceleratesupport: No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
ERROR 2020-06-30 15:24:20,592 excepthooks 16056 23156 Unhandled exception in thread: 'MainThread'
ERROR 2020-06-30 15:24:20,596 excepthooks 16056 23156 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.0b5\ilastik-meta\ilastik\ilastik\shell\gui\startShellGui.py", line 100, in launchShell
    from ilastik.shell.gui.ilastikShell import IlastikShell
  File "C:\Program Files\ilastik-1.4.0b5\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 95, in <module>
    import ilastik.workflows
  File "C:\Program Files\ilastik-1.4.0b5\ilastik-meta\ilastik\ilastik\workflows\__init__.py", line 144, in <module>
    from . import wsdt
  File "C:\Program Files\ilastik-1.4.0b5\ilastik-meta\ilastik\ilastik\workflows\wsdt\__init__.py", line 2, in <module>
    from .wsdtWorkflow import WsdtWorkflow
  File "C:\Program Files\ilastik-1.4.0b5\ilastik-meta\ilastik\ilastik\workflows\wsdt\wsdtWorkflow.py", line 26, in <module>
    from ilastik.applets.wsdt import WsdtApplet
  File "C:\Program Files\ilastik-1.4.0b5\ilastik-meta\ilastik\ilastik\applets\wsdt\__init__.py", line 2, in <module>
    from .wsdtApplet import WsdtApplet
  File "C:\Program Files\ilastik-1.4.0b5\ilastik-meta\ilastik\ilastik\applets\wsdt\wsdtApplet.py", line 25, in <module>
    from .opWsdt import OpCachedWsdt
  File "C:\Program Files\ilastik-1.4.0b5\ilastik-meta\ilastik\ilastik\applets\wsdt\opWsdt.py", line 4, in <module>
    from elf.segmentation.watershed import distance_transform_watershed
ModuleNotFoundError: No module named 'elf'
```

## Desktop (please complete the following information):
 - ilastik version: 1.4.0b5
 - OS: Windows 10

**Comment by k-dominik** [comment]
guess we'll need a rebuild of the dependency package there. Will fix that later today.

**Comment by k-dominik** [comment]
hmmm, there seems to be a bigger problem with the paths in 1.4.0b5...
