### ISSUE TITLE
Failed to export object predictions

### ISSUE THREAD

**Issue by FynnBe** [ilastik/ilastik#2256]
## Describe the bug
Object probability export does not work

## To Reproduce
Within the Object classification with prediciton probabilities workflow
1. standard demo procedure... 
2. try to export the result

## Error message/traceback
```pytb
ERROR 2020-06-30 17:05:50,168 log_exception 23628 23704 Export failed
ERROR 2020-06-30 17:05:50,171 log_exception 23628 23292 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\dataExport\dataExportGui.py", line 426, in exportSync
    self.parentApplet.post_process_lane_export(lane_index)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\objectClassification\objectClassificationDataExportApplet.py", line 63, in post_process_lane_export
    req = self._tableExporter.export_object_data(lane_index, show_gui=False).wait()
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\lazyflow\lazyflow\request\request.py", line 541, in wait
    return self._wait(timeout)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\lazyflow\lazyflow\request\request.py", line 564, in _wait
    self._wait_within_foreign_thread(timeout)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\lazyflow\lazyflow\request\request.py", line 624, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File "C:\Program Files\ilastik-1.3.3post3\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\lazyflow\lazyflow\request\request.py", line 360, in _execute
    self._result = self.fn()
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\objectClassification\opObjectClassification.py", line 173, in do_export
    "table", self._op.ObjectFeatures[lane_index], Mode.IlastikFeatureTable, {"selection": selected_features}
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\utility\exportFile.py", line 331, in add_columns
    columns = flatten_ilastik_feature_table(col_data, extra["selection"], self.InsertionProgress)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\utility\exportFile.py", line 97, in flatten_ilastik_feature_table
    long_name = all_props[feat_name]["displaytext"]
KeyError: 'displaytext'

ERROR 2020-06-30 17:05:50,172 log_exception 23628 23292 Failed to generate export file:
C:/Users/fbeut/Desktop/ilastik_course/ilastik/ilastik_tutorial/01_pixel_classification/2d_cells_apoptotic_1channel_Object Predictions.h5/exported_data
'displaytext'

```

## Screenshots
![image](https://user-images.githubusercontent.com/15139589/86144235-b387d980-baf5-11ea-8053-bd9a81275716.png)

## Desktop (please complete the following information):
 - ilastik version: 1.3.3post3
 - OS: Windows 10

**Comment by k-dominik** [comment]
did you do this in debug mode? (my guess). It activates test plugins that seem not to have all required fields.
