### ISSUE TITLE
All .ilp files corrupted after moving file location - HELP?

### ISSUE THREAD

**Issue by Elw-lab** [ilastik/ilastik#2266]
I use CVL virtual desktop to run iLastik
A file became corrupt when I tried to save due to lack of storage space
So I moved old files to a separate location to free up storage
Now none of those project files (.ilp) will open
I get the warning message that they are corrupt (box appears with title Corrupted Project, then shows file location and states unable to open)
Any way to fix this and get my files to open again??
How am I supposed to store once i'm finished projects?? Do they always need to remain in the same file location to be retrievable/usable??
I don't code/understand much about the workings of the program
Would appreciate some help/troubleshooting steps/how to avoid in the future
Thanks!

**Comment by k-dominik** [comment]
Hi @Elw-lab,

first of all I understand that this situation must feel scary. it sounds like ilastik cannot find the data files associated with those projects. So when the pop-up comes and shows you the file dialog, it wants you to point to the location of the dataset.

As a background (see also the point about _storage_ in [our docs](https://www.ilastik.org/documentation/basics/dataselection#properties):
ilastik can save the data in multiple ways:
 * absolute link to a file (e.g. `C:\mydata\myimage.tif` (windows), or `/home/memyself/mydata/myimage.tif` (linux)). In priciple moving the `ilp` file should not result in problems if you are on the same machine and the data is still in the same folder.
 * relative link: when the data is in a subfolder of the project location (say project in `/home/memyself/myproject.ilp` and the data is in `/home/memyself/mydata/myimage.tif` then ilastik saves a relative link to the file (so something  like `mydata/myimage.tif), and finally. When you move the project you have to move the data along in the same hierarchy. So in this example if you have moved `myproject.ilp` to `/backups/today` then you should also move the `/mydata` folder to home`/backups/today`.
 * copied to project file: then the data is embedded in the file. When you move the `ilp` you move everything. The file can get large.

In any case, if you start ilastik with a project where the data cannot be located, it will tell you that a certain image cannot be found - in the next step you have the possibility to point to the file.

If your paths were stored relative to the project file, then moving the data, keeping the folder structure relative to the project file intact, should do the job.

On what operating system are you and how may projects are we talking about? I quickly googled CVL and it looks like linux, but could you confirm it?

Once the links to the data are restored, the projects should work again

**Comment by Elw-lab** [comment]
Hi @k-dominik 

Thanks so much for taking the time to reply!! 
I have looked at the document you linked
When i add files to the pixel classifier i'm using it shows location as an absolute link to the hdf5 files i use an input, although my project files are saved in a different folder. 
I have changed it to copy into project file instead - then when i moved that practice file into a different folder location the file opened perfectly (yay solution!)
I'll do this in future, however i still have the issue of retrieving the previous files... is it possible??

If it helps this is the error log i'm getting for the "corrupted" project files: 

ERROR 2020-07-28 16:35:32,854 projectManager 35721 140010850121536 Error opening file: /home/ewilliam/xs15_scratch/6. Creatine Ilastik/Creatine practice.ilp
ERROR 2020-07-28 16:35:32,857 log_exception 35721 140010850121536 Traceback (most recent call last):
  File "/usr/local/ilastik/1.3.3/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 1544, in _loadProject
    self.projectManager._importProject(importFromPath, hdf5File, projectFilePath)
  File "/usr/local/ilastik/1.3.3/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 503, in _importProject
    importedFile = h5py.File(importedFilePath, "r")
  File "/usr/local/ilastik/1.3.3/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/usr/local/ilastik/1.3.3/lib/python3.7/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 134217728, sblock->base_addr = 0, stored_eof = 142836960)


I have quite a lot of files (~30 each about 200 - 300 MB, saved as .ilp, HDF document format)
