### ISSUE TITLE
Pixel Classification multi-lane problems, index out of range

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2269]
Per [user-report](https://forum.image.sc/t/ilastik-list-index-out-of-range-error/40028?u=k-dominik) we have been made aware that there are problems in pixel classification in multi-lane mode. I have so far not been able to _reliably_ reproduce the problem, but for me it happened shortly after removing lanes, when saving. Interestingly I got different errors than the user (but same error message).

Summary of error messages so this can be investigated further:

1. from the forum:

<details>

```pytb
WARNING 2020-07-01 02:10:59,357 warnings 5095 140736054272896 valueRangeWidget.py(66): FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type.
ERROR 2020-07-01 02:13:10,414 excepthooks 5095 140736054272896 Unhandled exception in thread: ‘MainThread’
ERROR 2020-07-01 02:13:10,431 excepthooks 5095 140736054272896 Traceback (most recent call last):
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/featureSelection/featureSelectionGui.py”, line 390, in onNewFeaturesFromFeatureDlg
opFeatureSelection.SelectionMatrix.setValue(self.featureDlg.selectionMatrix)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 1146, in setValue
self.setDirty(slice(None))
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 906, in setDirty
c.setDirty(roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 906, in setDirty
c.setDirty(roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 912, in setDirty
self.operator.propagateDirty(self.top_level_slot, self.subindex, roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opPixelFeaturesPresmoothed.py”, line 291, in propagateDirty
self.Output.setDirty(slice(None))
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 906, in setDirty
c.setDirty(roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 912, in setDirty
self.operator.propagateDirty(self.top_level_slot, self.subindex, roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opReorderAxes.py”, line 191, in propagateDirty
self.Output.setDirty(*out_roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 906, in setDirty
c.setDirty(roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 906, in setDirty
c.setDirty(roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 906, in setDirty
c.setDirty(roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 906, in setDirty
c.setDirty(roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 906, in setDirty
c.setDirty(roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 906, in setDirty
c.setDirty(roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 906, in setDirty
c.setDirty(roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 912, in setDirty
self.operator.propagateDirty(self.top_level_slot, self.subindex, roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opFeatureMatrixCache.py”, line 239, in propagateDirty
self.LabelAndFeatureMatrix.setDirty()
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 906, in setDirty
c.setDirty(roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 906, in setDirty
c.setDirty(roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 73, in call_in_setup_context
return func(self, *args, **kwargs)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 912, in setDirty
self.operator.propagateDirty(self.top_level_slot, self.subindex, roi)
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operators/opConcatenateFeatureMatrices.py”, line 134, in propagateDirty
self._dirty_slots.add(self.FeatureMatrices[subindex])
File “/private/var/folders/3t/2zq6cr195s724s6_18961_cw0000gn/T/AppTranslocation/572F0FED-3005-4A5E-ACDB-C2AF4F2F4E6C/d/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py”, line 931, in getitem
return self._subSlots[key[0]]
IndexError: list index out of range
```

</details>

2. from me

<details>

```pytb
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/volumina/volumina/brushingcontroller.py", line 315, in _writeIntoSink
    self._dataSink.put(slicing, labels.reshape(tuple(newshape)))
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/volumina/volumina/pixelpipeline/datasources/lazyflowsource.py", line 201, in put
    self._inputSlot[transposedSlicing] = transposedArray.view(np.ndarray)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 992, in __setitem__
    p[key] = value
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 992, in __setitem__
    p[key] = value
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 992, in __setitem__
    p[key] = value
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 988, in __setitem__
    self.operator.setInSlot(self.top_level_slot, self.subindex, roi, value)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operators/opCompressedUserLabelArray.py", line 394, in setInSlot
    self._setInSlotInput(slot, subindex, roi, new_pixels)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operators/opCompressedUserLabelArray.py", line 461, in _setInSlotInput
    self.Output.setDirty(*block_roi)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 906, in setDirty
    c.setDirty(roi)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 906, in setDirty
    c.setDirty(roi)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 906, in setDirty
    c.setDirty(roi)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 906, in setDirty
    c.setDirty(roi)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 906, in setDirty
    c.setDirty(roi)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 906, in setDirty
    c.setDirty(roi)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 912, in setDirty
    self.operator.propagateDirty(self.top_level_slot, self.subindex, roi)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operators/opFeatureMatrixCache.py", line 239, in propagateDirty
    self.LabelAndFeatureMatrix.setDirty()
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 906, in setDirty
    c.setDirty(roi)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 906, in setDirty
    c.setDirty(roi)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 912, in setDirty
    self.operator.propagateDirty(self.top_level_slot, self.subindex, roi)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operators/opConcatenateFeatureMatrices.py", line 134, in propagateDirty
    self._dirty_slots.add(self.FeatureMatrices[subindex])
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 931, in __getitem__
    return self._subSlots[key[0]]
IndexError: list index out of range
```
</details>

and another one:

<details>

```pytb
ERROR 2020-07-09 16:37:59,335 log_exception 19845 140182549907200 Traceback (most recent call last):
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 293, in saveProject
    serializer.serializeToHdf5(self.currentProjectFile, self.currentProjectPath)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 1110, in serializeToHdf5
    ss.serialize(topGroup)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 213, in serialize
    self._serialize(group, self.name, self.slot)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/base/appletSerializer.py", line 542, in _serialize
    block, slicing = self.reshape_datablock_and_slicing_for_output(block, slicing, slot[index])
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/pixelClassification/pixelClassificationSerializer.py", line 93, in reshape_datablock_and_slicing_for_output
    original_axiskeys = self.get_input_image_original_axiskeys(slot)
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/pixelClassification/pixelClassificationSerializer.py", line 48, in get_input_image_original_axiskeys
    return "".join(self.get_corresponding_input_image_slot(labelSlot).meta.getOriginalAxisKeys())
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/pixelClassification/pixelClassificationSerializer.py", line 45, in get_corresponding_input_image_slot
    return labelSlot.operator.InputImages[labelSlot.subindex]
  File ".../ilastik-versions/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 931, in __getitem__
    return self._subSlots[key[0]]
IndexError: list index out of range

```

**Comment by emilmelnikov** [comment]
Steps to reproduce:

1. Create a new _Pixel Classification_ project
2. In the _Input Data_ applet, create 2 lanes by adding 2 _Raw Data_ images (I used `2d_cells_apoptotic.tif` for both)
3. Go to the _Feature Selection_ applet and select a single Gaussian Smoothing feature with sigma = 0.30
4. Go back to the _Input Data_ applet and remove **the first lane**
5. Go to the _Feature Selection_ applet again and select an additional Gaussian Smoothing feature with sigma = 0.70

Everything works if on step 4 you remove the last (second) lane.

**Comment by emilmelnikov** [comment]
The out-of-bounds error happens because [subslots are saved in a data structure](https://github.com/ilastik/ilastik/blob/d2390fee59acbc3136d8ec15537bf800b9110030/lazyflow/operators/opConcatenateFeatureMatrices.py#L38).

However, the core problem stems from the lazyflow design: OperatorWrappers keep lanes as multi-slots, and refer to lanes by their positional index, but multi-slots identify their sub-slots by [`subindex`](https://github.com/ilastik/ilastik/blob/bb91c9b9614ca6e4db39e57f556010805a9f30d4/lazyflow/slot.py#L918), which is a tuple of ints, constructed when the multi-slot is initialized. This leads to inconsistency between positional index and `subindex` when positional index changes, e.g. because a user deleted any but the last lane.

**Comment by c-morgans** [comment]
Hi there, 

I have had the same problem in pixel classification, training with multiple images. I deleted one of the training images and now am unable to train any further (the brush strokes disappear) and when I try to save the project I get a pop up stating error attempting save "list index out of range"
Anything to fix this?

Thanks!

**Comment by MeijerW** [comment]
Yep same, occured when removing one of the training images ! Has a solution been found?
