### ISSUE TITLE
Could not load old project file

### ISSUE THREAD

**Issue by leslie9121030** [ilastik/ilastik#2274]
## Describe the bug
I was training data on the version 1.3.3post3 of ilastik. At the end of the last training I saved the model. But today, when I open the project, open failed, the error is：
 "Could not load old project file: "(the path of project file)“ . Please try 'Import Project' instead.” 
So I tried the way of  'Import Project', but  error occurred again, this time the error message is:
 "RuntimeError: Unable to get link info (free block size is zero?)"
## Expected behavior
open my pixel classification project

## To Reproduce
1. My pixel classification project has been annotating and training for 10 days
2. At the end of the last training， I saved the project as usual and closed the project.
3. when I open the project again, the project load failed.
4. In order to solve the problem, I tried to install a higher version(1.4) and a lower version(1.3.2), the error still exist. 

## Error message/traceback
the log info in command line on 1.4.0和1.3.3post version
```
Starting ilastik from "C:\Users\qiaoying\ilastik-1.4.0b7\ilastik-meta".
ERROR 2020-07-14 19:34:52,989 log_exception 3256 116 Traceback (most recent call last):
  File "C:\Users\qiaoying\ilastik-1.4.0b7\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 1543, in _loadProject
    self.projectManager._importProject(importFromPath, hdf5File, projectFilePath)
  File "C:\Users\qiaoying\ilastik-1.4.0b7\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 515, in _importProject
    newProject.populateFrom(importedFile, [s.topGroupName for s in serializers])
  File "C:\Users\qiaoying\ilastik-1.4.0b7\ilastik-meta\ilastik\ilastik\__init__.py", line 69, in populateFrom
    if key in importedFile.keys():
  File "C:\Users\qiaoying\ilastik-1.4.0b7\lib\_collections_abc.py", line 717, in __contains__
    return key in self._mapping
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\qiaoying\ilastik-1.4.0b7\lib\site-packages\h5py\_hl\group.py", line 415, in __contains__
    return self._e(name) in self.id
  File "h5py\h5g.pyx", line 461, in h5py.h5g.GroupID.__contains__
  File "h5py\h5g.pyx", line 462, in h5py.h5g.GroupID.__contains__
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5g.pyx", line 531, in h5py.h5g._path_valid
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5l.pyx", line 212, in h5py.h5l.LinkProxy.exists
RuntimeError: Unable to get link info (free block size is zero?)
```

## Screenshots
1. the error info of Open Project:
on 1.3.2、1.3.3post、1.4.0 version:
![image](https://user-images.githubusercontent.com/45454642/87422129-aba65a00-c60a-11ea-9795-1c698cd28b09.png)
the error info of import project:

2. the error info of Import Project  
on 1.3.3post、1.4.0  version:
![image](https://user-images.githubusercontent.com/45454642/87422020-769a0780-c60a-11ea-95ee-f1f86abfee4b.png)
on 1.3.2 version:
![image](https://user-images.githubusercontent.com/45454642/87423907-abf42480-c60d-11ea-8e15-25c0e2234a2a.png)

## Desktop:
 - ilastik version: [1.3.3post3]
 - OS: [Windows 10]

**Comment by k-dominik** [comment]
Hi @leslie9121030,

I've never seen that one before! Thank you for trying with all those versions. Would you mind sharing the file with us? This way we could reproduce the problem and see if there is something that can be rescued from the file. (if so you could upload it [here](https://oc.embl.de/index.php/s/Rq2E5vatlUDZ6S6))

**Comment by leslie9121030** [comment]
Hi @k-dominik,

I've upload my project("leslie9121030_project.ilp") to the link you shared. Please check!

**Comment by k-dominik** [comment]
Hi @leslie9121030,

I got the file. Unfortunately I could not read anything from this file. Files that are unreadable at all are very rare and usually only seen in combination with remote storage like dropbox or one-drive. Did you have the file in such a folder?

**Comment by k-dominik** [comment]
closing this - most likely issue was a corrupt file.
