### ISSUE TITLE
Migration of ilastik_preferences crashes when there are hotkeys saved in config

### ISSUE THREAD

**Issue by m-novikov** [ilastik/ilastik#2323]
When `.ilastik_preferences` file contains user hotkey configuration migration will fail.

<details>

<summary>Traceback</summary>

<p>

```python
Traceback (most recent call last):
  File "ilastik.py", line 116, in <module>
    main()
  File "ilastik.py", line 112, in main
    main()
  File "/home/novikov/projects/ilastik-project/ilastik/ilastik/__main__.py", line 30, in main
    hShell = app.main(parsed_args, workflow_cmdline_args)
  File "/home/novikov/projects/ilastik-project/ilastik/ilastik/app.py", line 143, in main
    _init_preferences()
  File "/home/novikov/projects/ilastik-project/ilastik/ilastik/app.py", line 291, in _init_preferences
    migrate()
  File "/home/novikov/projects/ilastik-project/volumina/volumina/utility/preferences.py", line 178, in migrate
    _preferences.migrate(old_path)
  File "/home/novikov/projects/ilastik-project/volumina/volumina/utility/preferences.py", line 103, in migrate
    self.write(old_preferences)
  File "/home/novikov/projects/ilastik-project/volumina/volumina/utility/preferences.py", line 89, in write
    json.dump(data, f, indent=2, sort_keys=True)
  File "/home/novikov/tools/miniconda3/envs/ila-2020-10-07/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/novikov/tools/miniconda3/envs/ila-2020-10-07/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/novikov/tools/miniconda3/envs/ila-2020-10-07/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/novikov/tools/miniconda3/envs/ila-2020-10-07/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/novikov/tools/miniconda3/envs/ila-2020-10-07/lib/python3.7/json/encoder.py", line 376, in _iterencode_dict
    raise TypeError(f'keys must be str, int, float, bool or None, '
TypeError: keys must be str, int, float, bool or None, not tuple
```
</p>

</details>

The issue is the format in which hotkeys are stored in old preferences file. It's a map from `tuple` to `string`. JSON doesn't support `tuple` keys.

<details><summary>Relevant config section</summary>

<p>

```python
{
 'Shortcut Preferences v2': {'all_shortcuts': {('Ilastik Shell',
    'shell next image'): 'PgDown',
   ('Ilastik Shell', 'shell previous image'): 'PgUp',
   ('Labeling', 'Undo'): 'Ctrl+Z',
   ('Labeling', 'Redo'): 'Ctrl+Y',
   ('Navigation', 'Go to next time frame'): '<',
   ('Navigation', 'Go to previous time frame'): '>',
   ('Navigation', 'Minimize/Maximize x-Window'): 'X',
   ('Navigation', 'Minimize/Maximize y-Window'): 'Y',
   ('Navigation', 'Minimize/Maximize z-Window'): 'Z',
   ('Navigation', 'Zoom in'): '+',
   ('Navigation', 'Zoom out'): '-',
   ('Navigation', 'Center image'): 'C',
   ('Navigation', 'Toggle hud'): 'H',
   ('Navigation', 'Slice up'): 'Ctrl+Down',
   ('Navigation', '10 slices up'): 'Ctrl+Shift+Up',
   ('Navigation', '10 slices down'): 'Ctrl+Shift+Down',
   ('Navigation', 'Jump to first slice'): 'Shift+Up',
   ('Navigation', 'Jump to last slice'): 'Shift+Down',
   ('Navigation', 'Next channel'): 'Ctrl+N',
   ('Navigation', 'Prev channel'): 'Ctrl+P',
   ('Navigation', 'Show tiling'): 'Ctrl+D',
   ('Navigation', 'Block gui for rendering'): 'Ctrl+B',
   ('Navigation', 'Fit image on screen'): 'K',
   ('Navigation', 'Reset zoom'): 'W',
   ('Labeling', 'New Label'): 'A',
   ('Labeling', 'Navigation Cursor'): 'N',
   ('Labeling', 'Brush Cursor'): 'B',
   ('Labeling', 'Eraser Cursor'): 'E',
   ('Labeling', 'Decrease Brush Size'): ',',
   ('Labeling', 'Increase Brush Size'): '.',
   ('Labeling', 'Window Leveling'): 'T',
   ('Labeling', 'Select Label 1'): '1',
   ('Labeling', 'Select Label 2'): '2',
   ('Predictions', 'Toggle Prediction'): 'P',
   ('Predictions', 'Toggle Segmentaton'): 'S',
   ('Predictions', 'Live Prediction'): 'L',
   ('Labeling', 'LabelVisibility'): '0',
   ('Prediction Layers', 'Uncertainty'): 'U',
   ('Prediction Layers', 'Bring Input To Top/Bottom'): 'I'}},
}
```

<p>
</details>

[Preferences file attached](https://github.com/ilastik/ilastik/files/5363873/ilastik_prefs.zip)

**Comment by k-dominik** [comment]
Also, unconnected to the migration process, changing key bindings via the gui, will also result in the same error.
