### ISSUE TITLE
Unable to load OpenGL library on macOS Big Sur

### ISSUE THREAD

**Issue by jobha** [ilastik/ilastik#2369]
## Describe the bug
I get the error following error when I try to load images into Ilastik:
('Unable to load OpenGL library', 'dlopen(OpenGL, 10): image not found', 'OpenGL', None)

## To Reproduce
Within the Pixel classification workflow
1. Try to load an .h5 file

## Error message/traceback
```Traceback (most recent call last):
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/dataSelection/dataSelectionGui.py", line 284, in showFirstSelectedDataset
    self.showDataset(lanes[0], _roleIndex)
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/utility/gui/threadRouter.py", line 82, in routed
    val = func(*args, **kwargs)
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/dataSelection/dataSelectionGui.py", line 375, in showDataset
    layerViewer = DatasetViewer(self.parentApplet, opLaneView, crosshair=False)
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/layerViewer/layerViewerGui.py", line 82, in __call__
    instance = super(LayerViewerGuiMetaclass, cls).__call__(*args, **kwargs)
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/layerViewer/layerViewerGui.py", line 199, in __init__
    self._initEditor(crosshair=crosshair, is_3d_widget_visible=is_3d_widget_visible)
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/layerViewer/layerViewerGui.py", line 665, in _initEditor
    self.layerstack, parent=self, crosshair=crosshair, is_3d_widget_visible=is_3d_widget_visible
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/volumeEditor.py", line 186, in __init__
    self.view3d = self._initView3d(is_3d_widget_visible)
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/volumeEditor.py", line 285, in _initView3d
    view3d = Overview3D(is_3d_widget_visible=is_3d_widget_visible)
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/view3d/overview3d.py", line 42, in __init__
    cls, _ = loadUiType(join(split(__file__)[0], "ui/view3d.ui"))
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/PyQt5/uic/__init__.py", line 201, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "<string>", line 76, in <module>
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/ilastik-meta/volumina/volumina/view3d/glview.py", line 1, in <module>
    from pyqtgraph.opengl import GLViewWidget
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/pyqtgraph/opengl/__init__.py", line 1, in <module>
    from .GLViewWidget import GLViewWidget
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 2, in <module>
    from OpenGL.GL import *
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 36, in <module>
    _load()
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 33, in _load
    plugin.install(globals())
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 96, in install
    namespace[ name ] = getattr(self,name,None)
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 62, in GetCurrentContext
    return self.CGL.CGLGetCurrentContext
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 45, in CGL
    def CGL(self): return self.GL
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 41, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', 'dlopen(OpenGL, 10): image not found', 'OpenGL', None)

ERROR 2020-12-14 11:00:12,618 excepthooks 10717 4405214720 Unhandled exception in thread: 'MainThread'
ERROR 2020-12-14 11:00:12,618 excepthooks 10717 4405214720 Traceback (most recent call last):
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 38, in GL
    mode=ctypes.RTLD_GLOBAL
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/OpenGL/platform/ctypesloader.py", line 36, in loadLibrary
    return _loadLibraryWindows(dllType, name, mode)
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/Resources/lib/python3.7/site-packages/OpenGL/platform/ctypesloader.py", line 89, in _loadLibraryWindows
    return dllType( name, mode )
  File "/Applications/ilastik-1.3.3post3-OSX.app/Contents/ilastik-release/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ('dlopen(OpenGL, 10): image not found', 'OpenGL', None)
```

## Screenshots
<img width="1027" alt="Screenshot 2020-12-14 at 10 48 44" src="https://user-images.githubusercontent.com/5748338/102067978-219e2f80-3dfc-11eb-8466-e93353d7fb3d.png">

## Desktop
 - ilastik version: 1.3.3post3
 - OS: macOS 11.0.1

**Comment by k-dominik** [comment]
Hi @jobha,

thank you for the report! We (and many other OSS tools) struggle a bit after the OSX upgrade to BigSur. We have fixes (#2345 https://github.com/ilastik/volumina/pull/277) which we need to bake into a new release.

Related #2344 #2363

Will give you an update once that is done!

**Comment by jobha** [comment]
Thanks! I have the same problem using 1.4.0b9, so I'll wait for a new release. When do you expect it to be available?

**Comment by k-dominik** [comment]
Hi @jobha , would you mind trying our latest beta [1.4.0b11](https://files.ilastik.org/ilastik-1.4.0b11-OSX.tar.bz2)?

**Comment by jobha** [comment]
That works. Thank you very much!
