### ISSUE TITLE
Unable to save or reopen object classification file: RuntimeError: wrapped C/C++ object of type QDoubleSpinBox has been deleted

### ISSUE THREAD

**Issue by AnnCloos** [ilastik/ilastik#2376]
## Description
Whenever I close my object classification file (based on pixel prediction map) , I get the following error message. 

![image](https://user-images.githubusercontent.com/77466657/104844857-6c630980-58ca-11eb-9c34-061cac41722f.png)

I then press ok. When I then close Ilastik, this message appears. 
![image](https://user-images.githubusercontent.com/77466657/104845080-7df8e100-58cb-11eb-886f-9e45b1d81a48.png)

I press save but after this, I am no longer able to open the file and loose all the work I have done. 
![image](https://user-images.githubusercontent.com/77466657/104845183-f5c70b80-58cb-11eb-801d-f257c09b0628.png)

## Expected behavior
I expect to be able to save and close the file and reopen it. I don't have this problem with the pixel classification file.  

## To Reproduce
1. Create a new object classification file (based on pixel prediction map)
2. I add a raw image (Tiff) and probability prediction map (h5 file) (Unfortunately I can't attach them here as the file format is not supported). I then set the thresholds for object identification (used the hysteresis one), selected all object features and then labelled some of the objects
3. Saved the file and then pressed close. 
4. That's when the error happens. 

## ilastik version and OS 
 - ilastik version: ilastik-1.4.0b8
 - OS: Windows 10
 
I've included everything in the ilastik command window: I first tried to open my previous object classification file where the same error happened. Then I tried open another file which worked. I then went on to create a new object classification file to recreate the error: 

```pytb
Starting ilastik from "D:\Program Files\ilastik-1.4.0b8\ilastik-meta".
ERROR 2021-01-17 13:34:56,658 log_exception 471012 449280 Traceback (most recent call last):
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 460, in _loadProject
    serializer.deserializeFromHdf5(self.currentProjectFile, projectFilePath, self._headless)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\base\appletSerializer.py", line 1153, in deserializeFromHdf5
    self._deserializeFromHdf5(topGroup, groupVersion, hdf5File, projectFilePath, headless)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\dataSelection\dataSelectionSerializer.py", line 192, in _deserializeFromHdf5
    assert "location" in laneGroup
AssertionError

ERROR 2021-01-17 13:34:56,659 log_exception 471012 449280 Project could not be loaded due to the exception shown above.
Aborting Project Open Action
ERROR 2021-01-17 13:34:56,803 log_exception 471012 449280 Traceback (most recent call last):
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 1554, in _loadProject
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 460, in _loadProject
    serializer.deserializeFromHdf5(self.currentProjectFile, projectFilePath, self._headless)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\base\appletSerializer.py", line 1153, in deserializeFromHdf5
    self._deserializeFromHdf5(topGroup, groupVersion, hdf5File, projectFilePath, headless)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\dataSelection\dataSelectionSerializer.py", line 192, in _deserializeFromHdf5
    assert "location" in laneGroup
AssertionError

ERROR 2021-01-17 13:35:03,701 log_exception 471012 449280 Traceback (most recent call last):
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 460, in _loadProject
    serializer.deserializeFromHdf5(self.currentProjectFile, projectFilePath, self._headless)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\base\appletSerializer.py", line 1153, in deserializeFromHdf5
    self._deserializeFromHdf5(topGroup, groupVersion, hdf5File, projectFilePath, headless)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\dataSelection\dataSelectionSerializer.py", line 192, in _deserializeFromHdf5
    assert "location" in laneGroup
AssertionError

ERROR 2021-01-17 13:35:03,702 log_exception 471012 449280 Project could not be loaded due to the exception shown above.
Aborting Project Open Action
ERROR 2021-01-17 13:35:03,711 log_exception 471012 449280 Traceback (most recent call last):
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 1554, in _loadProject
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 460, in _loadProject
    serializer.deserializeFromHdf5(self.currentProjectFile, projectFilePath, self._headless)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\base\appletSerializer.py", line 1153, in deserializeFromHdf5
    self._deserializeFromHdf5(topGroup, groupVersion, hdf5File, projectFilePath, headless)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\dataSelection\dataSelectionSerializer.py", line 192, in _deserializeFromHdf5
    assert "location" in laneGroup
AssertionError

ERROR 2021-01-17 13:36:57,959 log_exception 471012 449280 Traceback (most recent call last):
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 460, in _loadProject
    serializer.deserializeFromHdf5(self.currentProjectFile, projectFilePath, self._headless)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\base\appletSerializer.py", line 1153, in deserializeFromHdf5
    self._deserializeFromHdf5(topGroup, groupVersion, hdf5File, projectFilePath, headless)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\dataSelection\dataSelectionSerializer.py", line 192, in _deserializeFromHdf5
    assert "location" in laneGroup
AssertionError

ERROR 2021-01-17 13:36:57,959 log_exception 471012 449280 Project could not be loaded due to the exception shown above.
Aborting Project Open Action
ERROR 2021-01-17 13:36:57,971 log_exception 471012 449280 Traceback (most recent call last):
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 1554, in _loadProject
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 460, in _loadProject
    serializer.deserializeFromHdf5(self.currentProjectFile, projectFilePath, self._headless)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\base\appletSerializer.py", line 1153, in deserializeFromHdf5
    self._deserializeFromHdf5(topGroup, groupVersion, hdf5File, projectFilePath, headless)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\dataSelection\dataSelectionSerializer.py", line 192, in _deserializeFromHdf5
    assert "location" in laneGroup
AssertionError

ERROR 2021-01-17 13:37:03,379 log_exception 471012 449280 Traceback (most recent call last):
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 460, in _loadProject
    serializer.deserializeFromHdf5(self.currentProjectFile, projectFilePath, self._headless)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\base\appletSerializer.py", line 1153, in deserializeFromHdf5
    self._deserializeFromHdf5(topGroup, groupVersion, hdf5File, projectFilePath, headless)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\dataSelection\dataSelectionSerializer.py", line 192, in _deserializeFromHdf5
    assert "location" in laneGroup
AssertionError

ERROR 2021-01-17 13:37:03,379 log_exception 471012 449280 Project could not be loaded due to the exception shown above.
Aborting Project Open Action
ERROR 2021-01-17 13:37:03,389 log_exception 471012 449280 Traceback (most recent call last):
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 1554, in _loadProject
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 460, in _loadProject
    serializer.deserializeFromHdf5(self.currentProjectFile, projectFilePath, self._headless)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\base\appletSerializer.py", line 1153, in deserializeFromHdf5
    self._deserializeFromHdf5(topGroup, groupVersion, hdf5File, projectFilePath, headless)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\dataSelection\dataSelectionSerializer.py", line 192, in _deserializeFromHdf5
    assert "location" in laneGroup
AssertionError

ERROR 2021-01-17 13:45:31,710 log_exception 471012 449280 Traceback (most recent call last):
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 247, in cleanUp
    self._closeCurrentProject()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 538, in _closeCurrentProject
    self.workflow.cleanUp()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\workflow.py", line 183, in cleanUp
    super(Workflow, self).cleanUp()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\operator.py", line 397, in cleanUp
    self._disconnect()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\operator.py", line 376, in _disconnect
    child._disconnect()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\operator.py", line 373, in _disconnect
    s.resize(0)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 688, in resize
    self.removeSlot(len(self) - 1, len(self) - 1, propagate=False)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 780, in removeSlot
    self._sig_removed(self, position, finalsize)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\orderedSignal.py", line 80, in __call__
    f(*args, **kw)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\operatorWrapper.py", line 211, in _callbackPostRemoved
    self._removeInnerOperator(index, size)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\operatorWrapper.py", line 285, in _removeInnerOperator
    oslot.removeSlot(index, length)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 71, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 766, in removeSlot
    self._sig_remove(self, position, finalsize)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\orderedSignal.py", line 80, in __call__
    f(*args, **kw)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\workflow.py", line 246, in _removeImageLane
    a.topLevelOperator.removeLane(index, finalLength)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\utility\opMultiLaneWrapper.py", line 44, in removeLane
    self._removeInnerOperator(laneIndex, numLanes - 1)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\operatorWrapper.py", line 289, in _removeInnerOperator
    outerSlot.removeSlot(index, length)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 71, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 769, in removeSlot
    slot.disconnect()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 71, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 650, in disconnect
    self._changed()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 1325, in maybe_call_within_transaction
    fn()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 1365, in _changed_impl
    self._sig_changed(self)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\orderedSignal.py", line 80, in __call__
    f(*args, **kw)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\utility\bind.py", line 67, in __call__
    self.f(*(self.bound_args + args[0 : self.numUnboundArgs]))
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\utility\gui\threadRouter.py", line 88, in routed
    val = func(*args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\thresholdTwoLevels\thresholdTwoLevelsGui.py", line 148, in _updateGuiFromOperator
    self._drawer.sigmaSpinBox_Z.setVisible(data_has_z_axis)
RuntimeError: wrapped C/C++ object of type QDoubleSpinBox has been deleted

ERROR 2021-01-17 13:45:31,742 excepthooks 471012 449280 Unhandled exception in thread: 'MainThread'
ERROR 2021-01-17 13:45:31,744 excepthooks 471012 449280 Traceback (most recent call last):
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 1197, in onCloseActionTriggered
    if not self.ensureNoCurrentProject():
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 1672, in ensureNoCurrentProject
    self.closeCurrentProject()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 1641, in closeCurrentProject
    self.projectManager.cleanUp()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 250, in cleanUp
    raise e
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 247, in cleanUp
    self._closeCurrentProject()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 538, in _closeCurrentProject
    self.workflow.cleanUp()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\workflow.py", line 183, in cleanUp
    super(Workflow, self).cleanUp()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\operator.py", line 397, in cleanUp
    self._disconnect()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\operator.py", line 376, in _disconnect
    child._disconnect()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\operator.py", line 373, in _disconnect
    s.resize(0)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 688, in resize
    self.removeSlot(len(self) - 1, len(self) - 1, propagate=False)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 780, in removeSlot
    self._sig_removed(self, position, finalsize)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\orderedSignal.py", line 80, in __call__
    f(*args, **kw)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\operatorWrapper.py", line 211, in _callbackPostRemoved
    self._removeInnerOperator(index, size)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\operatorWrapper.py", line 285, in _removeInnerOperator
    oslot.removeSlot(index, length)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 71, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 766, in removeSlot
    self._sig_remove(self, position, finalsize)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\orderedSignal.py", line 80, in __call__
    f(*args, **kw)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\workflow.py", line 246, in _removeImageLane
    a.topLevelOperator.removeLane(index, finalLength)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\utility\opMultiLaneWrapper.py", line 44, in removeLane
    self._removeInnerOperator(laneIndex, numLanes - 1)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\operatorWrapper.py", line 289, in _removeInnerOperator
    outerSlot.removeSlot(index, length)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 71, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 769, in removeSlot
    slot.disconnect()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 71, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 650, in disconnect
    self._changed()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 1325, in maybe_call_within_transaction
    fn()
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\slot.py", line 1365, in _changed_impl
    self._sig_changed(self)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\lazyflow\utility\orderedSignal.py", line 80, in __call__
    f(*args, **kw)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\utility\bind.py", line 67, in __call__
    self.f(*(self.bound_args + args[0 : self.numUnboundArgs]))
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\utility\gui\threadRouter.py", line 88, in routed
    val = func(*args, **kwargs)
  File "D:\Program Files\ilastik-1.4.0b8\ilastik-meta\ilastik\ilastik\applets\thresholdTwoLevels\thresholdTwoLevelsGui.py", line 148, in _updateGuiFromOperator
    self._drawer.sigmaSpinBox_Z.setVisible(data_has_z_axis)
RuntimeError: wrapped C/C++ object of type QDoubleSpinBox has been deleted
```

**Comment by k-dominik** [comment]
Thank you @AnnCloos for reporting this and providing all details.

a fix has been pushed and will be included in the next release!
