### ISSUE TITLE
ilastik fails on servers without gui libs

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2385]
https://github.com/ilastik/ilastik/blob/19d89a88817169699d61ae7979ce858b2c754772/ilastik/app.py#L286

something innocent as migrating preferences causes ilastik to fail in headless mode on servers that don't have gui libs installed :/

Any good ideas for workarounds?

<details>

```pytb
Traceback (most recent call last):
  File "/ilastik-release/ilastik-meta/ilastik/ilastik.py", line 122, in <module>
    main()
  File "/ilastik-release/ilastik-meta/ilastik/ilastik.py", line 118, in main
    main()
  File "/ilastik-release/ilastik-meta/ilastik/ilastik/__main__.py", line 30, in main
    hShell = app.main(parsed_args, workflow_cmdline_args)
  File "/ilastik-release/ilastik-meta/ilastik/ilastik/app.py", line 141, in main
    _init_preferences()
  File "/ilastik-release/ilastik-meta/ilastik/ilastik/app.py", line 287, in _init_preferences
    from volumina.utility.preferences import migrate
  File "/ilastik-release/ilastik-meta/volumina/volumina/__init__.py", line 47, in <module>
    from . import api
  File "/ilastik-release/ilastik-meta/volumina/volumina/api.py", line 25, in <module>
    from .pixelpipeline.imagepump import ImagePump
  File "/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/imagepump.py", line 30, in <module>
    from volumina.pixelpipeline.slicesources import PlanarSliceSource, SyncedSliceSources
  File "/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/slicesources.py", line 28, in <module>
    from .interface import DataSourceABC, PlanarSliceSourceABC, RequestABC
  File "/ilastik-release/ilastik-meta/volumina/volumina/pixelpipeline/interface.py", line 29, in <module>
    from volumina.utility.qabc import QABC, abstractsignal
  File "/ilastik-release/ilastik-meta/volumina/volumina/utility/__init__.py", line 25, in <module>
    from .getMainWindow import getMainWindow
  File "/ilastik-release/ilastik-meta/volumina/volumina/utility/getMainWindow.py", line 1, in <module>
    from PyQt5.QtWidgets import QApplication, QWidget, QMainWindow
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

</details>

**Comment by emilmelnikov** [comment]
This is caused by [importing `ShortcutManager` in `migrate()`](https://github.com/ilastik/volumina/blob/2b55981b56e1caba87069da3e09e94cddd93a98a/volumina/utility/preferences.py#L105) for accessing some constants; in turn, this import triggers [Qt GUI imports](https://github.com/ilastik/volumina/blob/2b55981b56e1caba87069da3e09e94cddd93a98a/volumina/utility/shortcutManager.py#L8).

We can either move these constants out into a separate module, or just hardcode them.

**Comment by k-dominik** [comment]
I'm not sure this is accurate. I mean, this would happen at some point (That's what I thought, too), but the traceback indicates, that this happens much earlier in `__init__` of `volumina`, well before the import to the shortcutmanager is reached..
