### ISSUE TITLE
Can't train neural network classifier in 1.4.0b13

### ISSUE THREAD

**Issue by nranthony** [ilastik/ilastik#2388]
**## Describe the bug**
Can't get past NN Training section.  Errors on trying to interact with TikTorch.  Also, can't add additional classes beyond 2 (not sure if this is the limit with NN).  I get an error on closing the Set Hyperparameters dialog, and opening the Create TikTorch config menu item.   Console outputs below.

**## Expected behavior**
Not sure, first time trying NNs with ilastik

**## To Reproduce**
1. Created TikTorch env and started server as detailed at https://github.com/ilastik/tiktorch 
2. Open ilastik and start NN pixel classifier.
3. Step 1. Setup server configuration.  It auto found server.  I selected the cuda checkbox and saved
(tiktorch-server-env) C:\WINDOWS\system32>tiktorch-server
138452
Starting server on 127.0.0.1:5567
4. Step 2. Input data - ~20 grayscale tifs
5. Step 3. NN Training - renamed two classes and labeled all images.
6. Wasn't able to get any further.  Nothing happening.  Tried the options in the TikTorch menu.

**## Error message/traceback**

_Setting hyperparameters dialog close:_

ERROR 2021-01-31 15:20:29,636 excepthooks 120196 147852 Unhandled exception in thread: 'MainThread'
ERROR 2021-01-31 15:20:29,636 excepthooks 120196 147852 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.0b13\ilastik-meta\ilastik\ilastik\applets\networkClassification\nnClassGui.py", line 386, in settingParameter
    self.topLevelOperatorView.update_config(dlg.hparams)
  File "C:\Program Files\ilastik-1.4.0b13\ilastik-meta\ilastik\ilastik\applets\networkClassification\opNNclass.py", line 215, in update_config
    self.ClassifierFactory.meta.hparams = partial_config
AttributeError: 'OpNNClassification' object has no attribute 'ClassifierFactory'

_Opening Create TikTorch Configuration:_

ERROR 2021-01-31 15:21:18,185 excepthooks 120196 147852 Unhandled exception in thread: 'MainThread'
ERROR 2021-01-31 15:21:18,186 excepthooks 120196 147852 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.0b13\ilastik-meta\ilastik\ilastik\applets\networkClassification\nnClassGui.py", line 392, in object_wizard
    wizard = MagicWizard()
NameError: name 'MagicWizard' is not defined

**## Screenshots**
![image](https://user-images.githubusercontent.com/16306836/106397215-32215e00-63da-11eb-9e52-63ef8593991e.png)

**## Desktop (please complete the following information):**
 - ilastik version: [1.4.0b13]
 - OS: Win 10 64bit
 
Thanks for your time.
Neil

**Comment by k-dominik** [comment]
Hi @nranthony,

unfortunately that is currently nothing we can provide in ilastik. Right now you would load a pre-trained model here. And in future, you will (hopefully) be able to fine-tune a network with annotations - but this is still a research topic and not solved.

Cheers

**Comment by nranthony** [comment]
Hi @k-dominik , thanks for the speedy reply.
Good to know.  If this section of ilastik were to be used for training/annotation, would I be correct in thinking it would need to have completely filled in regions, whereby all pixels had an overlay that indicated it's annotated class?
Just thinking out loud.  Please close and move on to more pressing things.
Thanks for your time.
Neil
