### ISSUE TITLE
Using ilastik api fails for 2d image

### ISSUE THREAD

**Issue by constantinpape** [ilastik/ilastik#2464]
I tried using the ilastik api to run prediction for a 2d image, following the example notebook https://github.com/ilastik/ilastik/tree/main/notebooks/pixel_classification_api. Prediction fails with an assertion error (see full traceback below)

Minimal reproducible example
```python
import numpy as np
from ilastik.experimental.api import from_project_file
from xarray import DataArray

# project trained on 2D image data
project = "/home/pape/Work/my_projects/shilas_data/nuclei_foreground.ilp"
ilp = from_project_file(project)
# random example data of correct shape
image = np.random.rand(2048, 2048)
pred = ilp.predict(DataArray(image, dims=("y", "x")))
```

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    pred = ilp.predict(DataArray(image, dims=("y", "x")))
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/ilastik/experimental/api/_base.py", line 61, in predict
    self._reorder_op.Input.setValue(data)
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/slot.py", line 1143, in setValue
    self._changed()
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/slot.py", line 1361, in _changed_impl
    self._configureOperator(self)
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/slot.py", line 1374, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/operator.py", line 515, in _setupOutputs
    oslot._setReady()
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/slot.py", line 1265, in _setReady
    self._changed()
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/slot.py", line 1354, in _changed_impl
    c._changed()
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/slot.py", line 1361, in _changed_impl
    self._configureOperator(self)
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/slot.py", line 1374, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/lazyflow/operator.py", line 498, in _setupOutputs
    self.setupOutputs()
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/ilastik/applets/featureSelection/opFeatureSelection.py", line 255, in setupOutputs
    super().setupOutputs()
  File "/home/pape/Work/software/conda/miniconda3/envs/shila/ilastik-meta/ilastik/ilastik/applets/featureSelection/opFeatureSelection.py", line 127, in setupOutputs
    assert "c" in oldAxes
AssertionError
```

I am using an env installed from: https://github.com/ilastik/ilastik/blob/main/notebooks/pixel_classification_api/environment.yml.
Let me know if you need the project file to reproduce this.

**Comment by m-novikov** [comment]
Reproducible when project is trained on image with 2 axes (x, y), when trained on 3 axes (x, y, c) even when c has size 1 works as expected.
[2464_PixelClassification_xy_input.ilp.zip](https://github.com/ilastik/ilastik/files/6895190/2464_PixelClassification_xy_input.ilp.zip)

**Comment by constantinpape** [comment]
Thanks for taking care of this, @m-novikov, @k-dominik. Are there any instructions on how I can set up a dev env to use the fixed version without waiting for a release?

**Comment by m-novikov** [comment]
@constantinpape I don't think this is related to the release, just pull latest `main` branch follow the instructions [here](https://github.com/ilastik/ilastik/blob/main/notebooks/Readme.md) and you should be good to go

**Comment by k-dominik** [comment]
Hey @constantinpape 

easiest is to follow our [Contributing guidelines](https://github.com/ilastik/ilastik/blob/main/CONTRIBUTING.md) that are even more simplified, currently...

**Comment by k-dominik** [comment]
> @constantinpape I don't think this is related to the release, just pull latest `main` branch follow the instructions [here](https://github.com/ilastik/ilastik/blob/main/notebooks/Readme.md) and you should be good to go

well, currently, you could also create an environment without the source by pulling the latest `ilastik-meta` package from `ilastik-forge`.
