### ISSUE TITLE
QT gets imported in headless mode

### ISSUE THREAD

**Issue by camielverdult** [ilastik/ilastik#2491]
## Describe the bug
QT gets imported in headless mode

## Expected behavior
QT does not get imported in headless mode

## To Reproduce
Within the ... workflow
1. Run beta 1.4.0b15-Linux like following:

```
./run_ilastik.sh --headless --project=TestProject.ilp --export_source="simple segmentation" ../images/IMG_20210827112833.00014\ -\ white.jpeg
```

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
WARNING 2021-10-09 08:51:17,438 __init__ 3482 139702250137408 Failed to import NeuralNet workflow; check dependencies: libGL.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/incredabox/ilastik-1.4.0b15-Linux/ilastik-meta/ilastik/ilastik/workflows/__init__.py", line 137, in <module>
    from .nnClassification import NNClassificationWorkflow
  File "/home/incredabox/ilastik-1.4.0b15-Linux/ilastik-meta/ilastik/ilastik/workflows/nnClassification/__init__.py", line 21, in <module>
    from .nnClassificationWorkflow import NNClassificationWorkflow
  File "/home/incredabox/ilastik-1.4.0b15-Linux/ilastik-meta/ilastik/ilastik/workflows/nnClassification/nnClassificationWorkflow.py", line 29, in <module>
    from ilastik.applets.serverConfiguration import ServerConfigApplet
  File "/home/incredabox/ilastik-1.4.0b15-Linux/ilastik-meta/ilastik/ilastik/applets/serverConfiguration/__init__.py", line 21, in <module>
    from .serverConfigApplet import ServerConfigApplet
  File "/home/incredabox/ilastik-1.4.0b15-Linux/ilastik-meta/ilastik/ilastik/applets/serverConfiguration/serverConfigApplet.py", line 24, in <module>
    from .opServerConfig import OpServerConfig
  File "/home/incredabox/ilastik-1.4.0b15-Linux/ilastik-meta/ilastik/ilastik/applets/serverConfiguration/opServerConfig.py", line 27, in <module>
    from .configStorage import SERVER_CONFIG
  File "/home/incredabox/ilastik-1.4.0b15-Linux/ilastik-meta/ilastik/ilastik/applets/serverConfiguration/configStorage.py", line 8, in <module>
    from volumina.utility import preferences
  File "/home/incredabox/ilastik-1.4.0b15-Linux/ilastik-meta/volumina/volumina/__init__.py", line 53, in <module>
    from . import api
  File "/home/incredabox/ilastik-1.4.0b15-Linux/ilastik-meta/volumina/volumina/api.py", line 25, in <module>
    from .pixelpipeline.imagepump import ImagePump
  File "/home/incredabox/ilastik-1.4.0b15-Linux/ilastik-meta/volumina/volumina/pixelpipeline/imagepump.py", line 30, in <module>
    from volumina.pixelpipeline.slicesources import PlanarSliceSource, SyncedSliceSources
  File "/home/incredabox/ilastik-1.4.0b15-Linux/ilastik-meta/volumina/volumina/pixelpipeline/slicesources.py", line 28, in <module>
    from .interface import DataSourceABC, PlanarSliceSourceABC, RequestABC
  File "/home/incredabox/ilastik-1.4.0b15-Linux/ilastik-meta/volumina/volumina/pixelpipeline/interface.py", line 29, in <module>
    from volumina.utility.qabc import QABC, abstractsignal
  File "/home/incredabox/ilastik-1.4.0b15-Linux/ilastik-meta/volumina/volumina/utility/__init__.py", line 25, in <module>
    from .getMainWindow import getMainWindow
  File "/home/incredabox/ilastik-1.4.0b15-Linux/ilastik-meta/volumina/volumina/utility/getMainWindow.py", line 1, in <module>
    from PyQt5.QtWidgets import QApplication, QWidget, QMainWindow
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

```

**Comment by camielverdult** [comment]
After installing the missing underlying dependencies by running following:

```
sudo apt update
sudo apt install ffmpeg libsm6 libxext6  -y
```

I now get a different error:
```
/home/incredabox/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/classifiers/__init__.py:20: UserWarning: init: Could not import tiktorch classifier
  warnings.warn("init: Could not import tiktorch classifier")
QXcbConnection: Could not connect to display 
Fatal Python error: Aborted

Thread 0x00007ff214cdd700 (most recent call first):
  File "/home/incredabox/ilastik-1.3.3post3-Linux/lib/python3.7/threading.py", line 300 in wait
  File "/home/incredabox/ilastik-1.3.3post3-Linux/lib/python3.7/threading.py", line 552 in wait
  File "/home/incredabox/ilastik-1.3.3post3-Linux/lib/python3.7/threading.py", line 1156 in run
  File "/home/incredabox/ilastik-1.3.3post3-Linux/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/home/incredabox/ilastik-1.3.3post3-Linux/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0x00007ff216e76700 (most recent call first):
  File "/home/incredabox/ilastik-1.3.3post3-Linux/lib/python3.7/threading.py", line 296 in wait
  File "/home/incredabox/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 154 in _get_next_job
  File "/home/incredabox/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 99 in run
  File "/home/incredabox/ilastik-1.3.3post3-Linux/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/home/incredabox/ilastik-1.3.3post3-Linux/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0x00007ff222382700 (most recent call first):
  File "/home/incredabox/ilastik-1.3.3post3-Linux/lib/python3.7/threading.py", line 296 in wait
  File "/home/incredabox/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 154 in _get_next_job
  File "/home/incredabox/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 99 in run
  File "/home/incredabox/ilastik-1.3.3post3-Linux/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/home/incredabox/ilastik-1.3.3post3-Linux/lib/python3.7/threading.py", line 885 in _bootstrap

Current thread 0x00007ff225066740 (most recent call first):
  File "/home/incredabox/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/shell/gui/startShellGui.py", line 61 in startShellGui
  File "/home/incredabox/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik_main.py", line 176 in main
  File "/home/incredabox/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik.py", line 128 in main
  File "/home/incredabox/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik.py", line 134 in <module>
./run_ilastik.sh: line 77: 12604 Aborted                 (core dumped) "${PREFIX}/bin/python" "${PREFIX}/ilastik-meta/ilastik/ilastik.py" "$@"
```
