### ISSUE TITLE
Experimental API: Python argument types in vigra.vigranumpycore.constructArrayFromAxistags did not match C++ signature

### ISSUE THREAD

**Issue by griffhurt** [ilastik/ilastik#2500]
## Describe the bug
I'm having the same issue as #2456, but it looks like that issue was accidentally closed and has not been reopened. I'm attempting to use the experimental API according to the [notebook](https://github.com/ilastik/ilastik/blob/main/notebooks/pixel_classification_api/pixel-classification-api.ipynb), but I'm getting an error about the vigra function `constructArrayFromAxisTags` having incorrect argument types when I reach the line `prediction = pipeline.predict(image)`. Because the project works when loaded into ilastik, I take it this is most likely an issue with how the API code is structured (specifically the calls to lazyflow). 

## Expected behavior
After loading the pipeline and image in the notebook, the function `pipeline.predict(image)` should return predictions instead of throwing an exception. 

## To Reproduce
1. Run the [pixel-classification-api notebook](https://github.com/ilastik/ilastik/blob/main/notebooks/pixel_classification_api/pixel-classification-api.ipynb)

## Error message/traceback

```Traceback (most recent call last):
  File "test_ilastik.py", line 12, in <module>
    prediction = pipeline.predict(image)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/ilastik/experimental/api/_base.py", line 70, in predict
    data = self._predict_op.PMaps.value[...]
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/slot.py", line 1015, in value
    temp = self[:].wait()
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 564, in _wait
   : DifferenceOfGaussiansFF (1, 1024, 1344) {'sigma0': 1.0, 'sigma1': 0.66, 'window_size': 2} True
   : DifferenceOfGaussiansFF (1, 1024, 1344) {'sigma0': 1.0, 'sigma1': 0.66, 'window_size': 2} True
    self._wait_within_foreign_thread(timeout)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 624, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/operator.py", line 595, in call_execute
   : DifferenceOfGaussiansFF (1, 1024, 1344) {'sigma0': 1.0, 'sigma1': 0.66, 'window_size': 2} True
   : DifferenceOfGaussiansFF (1, 1024, 1344) {'sigma0': 1.0, 'sigma1': 0.66, 'window_size': 2} True
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/operators/classifierOperators.py", line 483, in execute
    probabilities = self._calculate_probabilities(roi)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/operators/classifierOperators.py", line 595, in _calculate_probabilities
    input_data = self.Image[newKey].wait()
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 564, in _wait
    self._wait_within_foreign_thread(timeout)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 624, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/operator.py", line 595, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/operators/opReorderAxes.py", line 171, in execute
    self.Input(*in_roi).writeInto(result_input_view).wait()
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 564, in _wait
    self._wait_within_foreign_thread(timeout)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 624, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 860, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/operator.py", line 595, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/operators/opPixelFeaturesPresmoothed.py", line 490, in execute
    pool.wait()
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 1373, in wait
    self._clear_finishing_requests()
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 1467, in _clear_finishing_requests
    req.block()
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 547, in block
    self._wait(timeout)  # No return value. Use wait()
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 564, in _wait
    self._wait_within_foreign_thread(timeout)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 624, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/operator.py", line 595, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/operators/filterOperators.py", line 283, in execute
    step(
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/operators/filterOperators.py", line 245, in step
    result = self.filter_fn(source, **filter_kwargs)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/lazyflow/operators/filterOperators.py", line 421, in differenceOfGausssiansFF
    return fastfilters.gaussianSmoothing(image, sigma0, window_size) - fastfilters.gaussianSmoothing(
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/vigra/arraytypes.py", line 1706, in __sub__
    return ufunc.subtract(self, other)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/vigra/ufunc.py", line 296, in __call__
    o = outClass(shape, dtype=out_dtype, order='C', axistags=axistags, init=False)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/vigra/arraytypes.py", line 535, in __new__
    res = _constructArrayFromOrder(cls, obj, dtype, order, init)
  File "/Users/ghurt/miniconda3/envs/ilastik-api/lib/python3.8/site-packages/vigra/arraytypes.py", line 287, in _constructArrayFromOrder
    return _constructArrayFromAxistags(cls, shape, dtype, axistags, init)
Boost.Python.ArgumentError: Python argument types in
    vigra.vigranumpycore.constructArrayFromAxistags(type, tuple, numpy.dtype[float32], AxisTags, bool)
did not match C++ signature:
    constructArrayFromAxistags(boost::python::api::object, vigra::ArrayVector<long, std::__1::allocator<long> >, NPY_TYPES, vigra::AxisTags, bool)
```

## Screenshots
N/A

## Desktop:
 - ilastik-core version: 1.4.0b21.dev4+g7edd1dadb.d20211112 from conda
 - OS: macOS 11.5.2: Big Sur, miniconda 4.10.3

Thanks!

**Comment by griffhurt** [comment]
I just discussed this issue with one of my colleagues, and he was able to run the example API code on Windows 10 with the same conda setup. The author of #2456 was also using MacOS, so I believe this problem is not related to the API code and instead with the vigra library for Mac.

**Comment by k-dominik** [comment]
Hello @griffhurt,

thank you for reporting this. Also great that you point out the similarity to #2456. I think back then we didn't realize the root cause and it was solved by creating the environment as described in the notes for the notebook. With the `ilastik-core` package, however, everything should be pinned to the right versions... So I'm slightly puzzled.

could you please do a `conda list` and post the result here? I'm suspecting that its a numpy-vigra issue. Could you try setting up the environment with a numpy 1.19?

**Comment by griffhurt** [comment]
Hi @k-dominik,

I apologize for the late response. Running `conda list` revealed that an additional package I installed (cellprofiler with pip) updated numpy to version 1.21, which was the source of the problem. I reverted that package to a previous version using numpy 1.19 and it works now. I'm sorry for creating any confusion.
