### ISSUE TITLE
Ilastik API: prediction with 3D dataset with 2D features fails if fastfilters is not available

### ISSUE THREAD

**Issue by constantinpape** [ilastik/ilastik#2516]
## Describe the bug

Using the ilastik api to run prediction for a pixel classification with 3D data, but using 2D features does not work if fastiflters is not installed. Installing fastfilters fixes the issue. I think it would be good to either fix this behaviour when fastfilters is not available, or throw a more meaningful error message. (I just figured this out by chance while reporting this issue...).

## To Reproduce

```python
import numpy as np
from ilastik.experimental.api import from_project_file
from xarray import DataArray

ilp = from_project_file("vnc2d.ilp")
# note: calling this with 2d data and dims=("y", "x") fails with 
# ValueError: Number of spatial dims doesn't match. Classifier trained for 3 but input has 2
# so I add the singleton z axis
inp = DataArray(np.random.rand(1, 128, 128), dims=("z", "y", "x"))
pred = ilp.predict(inp)
```
The project is available [here](https://oc.embl.de/index.php/s/InUkMi1IX4GJcWD). Installing fastfilters fixes this issue.

## Error message/traceback

```pytb
Traceback (most recent call last):
  File "/home/pape/Work/playground/ilastik/test_ilastik_api_2d.py", line 8, in <module>
    pred = ilp.predict(inp)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/ilastik/experimental/api/_base.py", line 67, in predict
    self._reorder_op.Input.setValue(data)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1143, in setValue
    self._changed()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1361, in _changed_impl
    self._configureOperator(self)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1374, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/operator.py", line 518, in _setupOutputs
    oslot._setReady()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1265, in _setReady
    self._changed()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1354, in _changed_impl
    c._changed()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1354, in _changed_impl
    c._changed()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1361, in _changed_impl
    self._configureOperator(self)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1374, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/operator.py", line 518, in _setupOutputs
    oslot._setReady()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1265, in _setReady
    self._changed()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1354, in _changed_impl
    c._changed()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1361, in _changed_impl
    self._configureOperator(self)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1374, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/operator.py", line 501, in _setupOutputs
    self.setupOutputs()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/operators/opPixelFeaturesPresmoothed.py", line 188, in setupOutputs
    op.Input.connect(self.source.Output)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 543, in connect
    self._changed()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1361, in _changed_impl
    self._configureOperator(self)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1374, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/operator.py", line 501, in _setupOutputs
    self.setupOutputs()
  File "/home/pape/software/conda/miniconda3/envs/main39/lib/python3.9/site-packages/lazyflow/operators/filterOperators.py", line 103, in setupOutputs
    self.max_sigma = max(0.7, *filter_scales.values())
TypeError: '>' not supported between instances of 'tuple' and 'float'
```

## Desktop (please complete the following information):
 - ilastik version: current master 
 - OS: Ubuntu 20.04

**Comment by k-dominik** [comment]
Hey @constantinpape,

sorry you ran into this. There is currently a PR open (#2496, review appreciated) for a "proper" conda-recipe, (also available as `ilastik-core` on ilastik-forge for experimental use).

This doesn't address this issue directly of course. I guess we never tested that code path with vigra (which is also not used for filters on all OSses since 3 years at least...), so we should definitely either remove, or fix it!

**Comment by constantinpape** [comment]
> sorry you ran into this.

No worries, it's called `from experimental ...` after all ;).

> also available as `ilastik-core` on ilastik-forge for experimental use)

I have tried to use that, but it would have destroyed my environment by downgrading numpy. And I didn't want to set up a complete new env (as I needed this in an environment with pytorch and settng this up always takes some time), so I just soft linked ilastik and lazyflow into site-packages and then installed all the packages that threw ImportErrors. (That's also why I didn't notice fastfilters missing in the beginning). I will comment in the conda PR more.



> This doesn't address this issue directly of course. I guess we never tested that code path with vigra (which is also not used for filters on all OSses since 3 years at least...), so we should definitely either remove, or fix it!

Awesome, it would indeed be great to fix this ;).

**Comment by k-dominik** [comment]
current vigra build is not compatible with numpy>1.19...

**Comment by constantinpape** [comment]
> current vigra build (on conda-forge) is not compatible with numpy>1.19...

I am not so sure about this, writing some comments about it in the other PR right now ;)

**Comment by docuracy** [comment]
Hi, and many thanks for sharing your impressive work.

I'm trying to get the [pixel classification API](https://github.com/ilastik/ilastik/blob/f42c1bb0df75ff4ab590e9874f9f4ab29129a20f/notebooks/pixel_classification_api/pixel-classification-api.ipynb) to work on Google Colab, but hit the `TypeError` described above. A `! conda install -c conda-forge fastfilters` _seemed_ to clear that hurdle, but led to a `SlotNotReadyError` (though I think that might be a red herring). May I trouble you to take a quick look and let me know if you can see how to fix this?

https://colab.research.google.com/drive/16tR3MpFfCkGloI7ei8tFcKgbSrj6h70L?usp=sharing

**Comment by k-dominik** [comment]
Hi @docuracy,

you'll have to include the `ilastik-forge` channel (currently) to get _some_ of the required packages. See also this [environment file](https://github.com/ilastik/ilastik/blob/f42c1bb0df75ff4ab590e9874f9f4ab29129a20f/notebooks/pixel_classification_api/environment.yml)

Hope this gets you going!
Cheers
D

**Comment by docuracy** [comment]
Thanks, Dominik. The problem turned out to be a peculiarity of trying to run mamba in colab, but it may be of interest to others that I've got the experimental API example running now in Google Colab [here](https://colab.research.google.com/drive/12MSTVW4z9OyYv6jvReq3mWw60H2UG39y?usp=sharing).

It involves installing condacolab in order to get the dependencies (vigra z5py ndstructs fastfilters), but installing ilastik directly from the tarball.
