### ISSUE TITLE
Ilastk API: prediction gets stuck when not run in main process

### ISSUE THREAD

**Issue by constantinpape** [ilastik/ilastik#2517]
## Expected behavior

```python
import numpy as np    
from ilastik.experimental.api import from_project_file
from concurrent import futures 
from xarray import DataArray
  
ILP = "vnc2d.ilp"
  
  
def predict_ilp():
    ilp = from_project_file(ILP)    
    inp = DataArray(np.random.rand(1, 128, 128), dims=("z", "y", "x"))
    pred = ilp.predict(inp)
    print("Passed", pred.shape)


def predict_in_thread_or_process(pool):
    with pool(1) as ex:
        task = ex.submit(predict_ilp)
        task.result()


print("Main process")
predict_ilp()
print("In thread")
predict_in_thread_or_process(futures.ThreadPoolExecutor)
 predict_in_thread_or_process(pool) 
predict_in_thread_or_process(futures.ProcessPoolExecutor)
```

## To Reproduce
Within the ... workflow
1. Add some [2d/3d/4d/5d] data in the data selection applet
2. Go to ... applet, Click on '....'
3. Go to ... applet, make some annotations
4. ...

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
ERROR 2018-08-29 10:04:59,901 excepthooks 3936 140154429757184 Unhandled exception in thread: 'Worker #3'
ERROR 2018-08-29 10:04:59,901 excepthooks 3936 140154429757184 Traceback (most recent call last):
  File "/.../envs/idev/ilastik-meta/volumina/volumina/tiling.py", line 773, in _fetch_tile_layer
    img = ims_req.wait()
  File "/.../envs/idev/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 387, in wait
    return self.toImage()
  File "/.../envs/idev/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 425, in toImage
    raise NotImplementedError()
NotImplementedError

```

## Screenshots
If applicable, please add screenshots to help explain your problem.

## Desktop (please complete the following information):
 - ilastik version: [e.g. 1.3.2b1]
 - OS: [e.g. Ubuntu 18.04, macOS 10.12: Sierra (Fuji), Windows 10]

**Comment by k-dominik** [comment]
Thanks for providing the concise example - very easy to reproduce.

The root cause seems to be ilastik/lazyflow creating worker threads once imported. These will not be available to the forked processes.

Currently, there are a couple of workarounds, but I'm not sure if any of those are applicable in your case.

1. Never import anything from ilastik in your main thread
    Your code example will run through if you put the import (`from ilastik.experimental.api import from_project_file`) into the `predict_ilp` function, and never call this function from your main process.
1. Don't fork, but spawn (https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods). Your example works for me if I change it as follows (this is noticeably slower than forking):
   ```python
   import numpy as np
   from multiprocessing import set_start_method
   from concurrent import futures
   from xarray import DataArray
   from ilastik.experimental.api import from_project_file   
   
   ILP = "vnc2d.ilp"
   
   
   def predict_ilp():
       ilp = from_project_file(ILP)
       inp = DataArray(np.random.rand(1, 128, 128), dims=("z", "y", "x"))
       pred = ilp.predict(inp)
       print("Passed", pred.shape)
   
   
   def predict_in_thread_or_process(pool):
       with pool(1) as ex:
           task = ex.submit(predict_ilp)
           task.result()
   
   
   if __name__ == "__main__":
       set_start_method("spawn")
   
       print("Main process")
       predict_ilp()
       print("In thread")
       predict_in_thread_or_process(futures.ThreadPoolExecutor)
       print("In process")
       predict_in_thread_or_process(futures.ProcessPoolExecutor)
   ```
1. Don't use worker threads in lazyflow. This might be what you want anyway if you're going multiprocessing...
   ```python
   import numpy as np
   from concurrent import futures
   from xarray import DataArray
   import lazyflow
   from ilastik.experimental.api import from_project_file
   lazyflow.request.Request.reset_thread_pool(0)
   
   ILP = "vnc2d.ilp"
   
   
   def predict_ilp():
       ilp = from_project_file(ILP)
       inp = DataArray(np.random.rand(1, 128, 128), dims=("z", "y", "x"))
       pred = ilp.predict(inp)
       print("Passed", pred.shape)
   
   
   def predict_in_thread_or_process(pool):
       with pool(1) as ex:
           task = ex.submit(predict_ilp)
           task.result()
   
   
   print("Main process")
   predict_ilp()
   print("In thread")
   predict_in_thread_or_process(futures.ThreadPoolExecutor)
   print("In process")
   predict_in_thread_or_process(futures.ProcessPoolExecutor)
   
   ```

**Comment by constantinpape** [comment]
Thanks for looking into this @k-dominik. For my issue option 3 is the way to go and it's working now :).
It would be good to document this somehow, but feel free to close this issue.

**Comment by k-dominik** [comment]
I'd like to keep it open until we find a user friendly solution to this. I've to admit that I haven't thought about this before - so it's great that you brought it up!
