### ISSUE TITLE
Choose Export Image Settings fails in Neural Network Classification

### ISSUE THREAD

**Issue by constantinpape** [ilastik/ilastik#2542]
Clicking `Choose Export Image Settings ...` fails in the Neural Network Classification Workflow:
![ilastik-data-export-bug](https://user-images.githubusercontent.com/4263537/153875196-1a622020-0c37-4913-978d-71f9543b99d8.png)
Note that `Export data` still works.

This is using `ilastik-1.40.b23` with a tensorflow model; I haven't tested if the same issue occurs with other models.
@k-dominik in case you want to reproduce this: the proect is here: `/g/kreshuk/pape/Work/bioimageio/use-cases/case1/unet-prediction.ilp` and the model and h5 volume is in the `data` subfolder.

**Comment by constantinpape** [comment]
And here's the traceback from the log:
```
ERROR 2022-02-14 14:36:10,282 excepthooks 6443 139790402406400 Unhandled exception in thread: 'MainThread'                                                                                                                                                    
ERROR 2022-02-14 14:36:10,285 excepthooks 6443 139790402406400 Traceback (most recent call last):                                            
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/ilastik/applets/dataExport/dataExportGui.py", line 251, in _chooseSettings                                                                                                           
    settingsDlg = DataExportOptionsDlg(self, opExportModelOp)  
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/volumina/widgets/dataExportOptionsDlg.py", line 114, in __init__                                                                                                                     
    uic.loadUi(os.path.splitext(__file__)[0] + ".ui", self)    
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/__init__.py", line 227, in loadUi                                                                                                                                          
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)                                                            
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/Loader/loader.py", line 72, in loadUi                                                                                                                                      
    return self.parse(filename, resource_suffix, basedir)      
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 1030, in parse                                                                                                                                          
    actor(elem)                                                
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 828, in createUserInterface                                                                                                                             
    self.traverseWidgetTree(elem)                              
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree                                                                                                                              
    handler(self, child)                                       
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout                                                                                                                                    
    self.traverseWidgetTree(elem)                              
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree                                                                                                                              
    handler(self, child)                                       
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem                                                                                                                                      
    self.traverseWidgetTree(elem)                              
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree                                                                                                                              
    handler(self, child)                                       
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget                                                                                                                                    
    self.traverseWidgetTree(elem)                              
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree                                                                                                                              
    handler(self, child)                                       
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout                                                                                                                                    
    self.traverseWidgetTree(elem)                              
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree                                                                                                                              
    handler(self, child)                                                                                                                                                                                                                                      
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem                                                                                                                                      
    self.traverseWidgetTree(elem)                                                                                                                                                                                                                             
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree                                                                                                                              
    handler(self, child)                                                                                                       
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout                                                                                                                                    
    self.traverseWidgetTree(elem)                              
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree                                                                                                                              
    handler(self, child)                                       
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem                                                                                                                                      
    self.traverseWidgetTree(elem)                              
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree                                                                                                                              
    handler(self, child)                                                                                                                                                                                                                                      
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 264, in createWidget                                                                                                                                    
    self.stack.push(self.setupObject(widget_class, parent, elem))                                                                            
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 228, in setupObject                                                                                                                                     
    obj = self.factory.createQObject(clsname, name, args, is_attribute)                                                                                                                                                                                       
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/objcreator.py", line 118, in createQObject                                                                                                                                 
    return self._cpolicy.instantiate(factory, *args, **kwargs)        
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/PyQt5/uic/Loader/qobjectcreator.py", line 137, in instantiate                                                                                                                        
    return clsObject(*ctor_args)                                      
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/volumina/widgets/valueRangeWidget.py", line 58, in __init__                                                                                                                          
    self.setDType(dtype)                                              
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/volumina/widgets/valueRangeWidget.py", line 73, in setDType                                                                                                                          
    dtypeInfo = numpy.iinfo(dtype)                                    
  File "/g/kreshuk/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/numpy/core/getlimits.py", line 523, in __init__                                                                                                                                      
    raise ValueError("Invalid integer data type %r." % (self.kind,))                                                                         
ValueError: Invalid integer data type 'f'.    
```

**Comment by constantinpape** [comment]
The same issue happens in pixel classification, so this seems to be an issue with `ilastik-1.40.b23` in general and not with the NN workflow in particular.
