### ISSUE TITLE
NN Prediction: loading model fails with zip error

### ISSUE THREAD

**Issue by constantinpape** [ilastik/ilastik#2555]
Loading [this model](https://oc.embl.de/index.php/s/ke4UvZjULKVTbMB) fails with some zip error (see error below). The model works fine with `bioimageio test-model`, so this looks like an ilastik issue.
I am using ilastik 1.40b23 on linux.

```
20:28:17.471 [MainProcess/ThreadPoolExecutor-0_2] ERROR Exception calling application: zip argument #2 must support iteration
Traceback (most recent call last):
  File "/home/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/tiktorch/server/grpc/inference_servicer.py", line 45, in CreateModelSession
    model_info = session.client.get_model_info()
  File "/home/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/tiktorch/rpc/mp.py", line 96, in __call__
    return fut.result(timeout=timeout)
  File "/home/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/tiktorch/rpc/types.py", line 82, in result
    return super().result(timeout or self._timeout)
  File "/home/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
TypeError: zip argument #2 must support iteration
ERROR 2022-03-03 20:28:17,477 nnClassGui 10929 139926180812608 Traceback (most recent call last):
  File "/home/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/lazyflow/futures_utils.py", line 38, in _do_map
    res = func(f.result())
  File "/home/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/ilastik/applets/neuralNetwork/tiktorchController.py", line 152, in _createModelFromUpload
    session = connection.create_model_session(uploadId, [d.id for d in srvConfig.devices if d.enabled])
  File "/home/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/lazyflow/operators/tiktorch/classifier.py", line 379, in create_model_session
    inference_pb2.CreateModelSessionRequest(model_uri=f"upload://{upload_id}", deviceIds=devices)
  File "/home/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/pape/Work/software/src/ilastik/ilastik-1.4.0b23-Linux/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: zip argument #2 must support iteration"
	debug_error_string = "{"created":"@1646335697.473535276","description":"Error received from peer ipv4:127.0.0.1:33087","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Exception calling application: zip argument #2 must support iteration","grpc_status":2}"
```

**Comment by constantinpape** [comment]
Here's the correct link to the model: https://oc.embl.de/index.php/s/ke4UvZjULKVTbMB
(also updated above)

**Comment by k-dominik** [comment]
closed via https://github.com/ilastik/tiktorch/pull/199
thx for the example!
