### ISSUE TITLE
Can't load project

### ISSUE THREAD

**Issue by kpeebles01** [ilastik/ilastik#2565]
## Describe the bug
Please add a clear and concise description of what the bug is.

I was trying to organize the files and moved the program to a different folder, but it wouldn't open because it lost a path or something so I moved it back and now I can't open it and I'm not sure how to fix it. I would revert it to a previous save before I moved it but I don't know how to do that either. There is no guideline in the common problems for error messages either so I couldn't search for the issue.

## Expected behavior
Please add a clear and concise description of what you expected to happen.
I expected to open the project

## To Reproduce
Within the ... workflow
1. Add some [2d/3d/4d/5d] data in the data selection applet
2. Go to ... applet, Click on '....'
3. Go to ... applet, make some annotations
4. ...

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
ERROR 2018-08-29 10:04:59,901 excepthooks 3936 140154429757184 Unhandled exception in thread: 'Worker #3'
ERROR 2018-08-29 10:04:59,901 excepthooks 3936 140154429757184 Traceback (most recent call last):
  File "/.../envs/idev/ilastik-meta/volumina/volumina/tiling.py", line 773, in _fetch_tile_layer
    img = ims_req.wait()
  File "/.../envs/idev/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 387, in wait
    return self.toImage()
  File "/.../envs/idev/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 425, in toImage
    raise NotImplementedError()
NotImplementedError

```

## Screenshots
If applicable, please add screenshots to help explain your problem.
![ilastik error](https://user-images.githubusercontent.com/103610109/163280832-2046ffda-8c40-40ca-ab77-b33bc4d08286.png)

## Desktop (please complete the following information):
 - ilastik version: [e.g. 1.3.2b1]
 - OS: [e.g. Ubuntu 18.04, macOS 10.12: Sierra (Fuji), Windows 10]

**Comment by k-dominik** [comment]
Hi @kpeebles01,

thank you for the report!

This is one of the weaker points of ilastik. Depending on the location of the project file relative to the data files, it might save different types of links to the files.

In principle there are 3 different types of links:

* Absolute Link: Your data always resides in the same place on disk, even if you moved your project file since it was last opened.  // is automatically used when one has to go a step _up_ in the folder hierarchy from project file to image. E.g. project file in `/some/folder/for/project.ilp` and data in `/some/folder//for/data.tif`. Here you can only move the project file on the same machine.
* Relative Link: Your data is in the same parent directory tree as your project file. You may move your project file and data files simultaneously, but their relative locations must be fixed. // Automatically used if project file is in the same folder as data, or data deeper in the folder hierarchy. E.g. `/some/folder/project.ilp' for the project, and `/some/folder/data/image.tif` for the data. So here, moving the whole `/some/folder` to some different location will result in a valid project file (even if moved to a different machine)
* Copied to Project File: If you select this, your data will be copied to the project file the next time your project is saved. Pro: Your project file will always be valid, even if you move your data. Con: This creates a copy of your data.

Since moving back the project file didn't solve the problem for you there might be something else at play. If you can/want you could share the project file (without the data) and I can at least tell you in which configuration it _should_ work). If you want you can upload it here: https://oc.embl.de/index.php/s/rSFuhJuCG16QvpV (note the link expires in 48 hours).

Cheers
