### ISSUE TITLE
Lazyflow error on AMD Epyc

### ISSUE THREAD

**Issue by tboo** [ilastik/ilastik#2588]
## Describe the bug
I am unable to run a prediction for a pixel and object classification project from ilastik (both stable and latest beta) headless on an AMD Epyc 7702P Linux server. The very same workflow (and data) works flawless in and outside of Docker containers on Intel-based (Xeon 6134 and Xeon 6234)  Linux and Windows systems alike.

## Expected behavior

I expect the following command to execute (paths shortened for reading convenience)
` LAZYFLOW_THREADS=12 LAZYFLOW_TOTAL_RAM_MB=150000 ./run_ilastik.sh --headless --project=/projects/MyProject.ilp /projects/Image.JPG`

## Error message/traceback

On the AMD system I get the following error (under Debian 11 (native OS) and Ubuntu 20.04 (Container))

```
ERROR 2022-07-08 13:44:15,780 request 407896 140503398852352 Encountered exception while processing roi: (array([2681, 5360,    0]), array([4160, 6240,    1]))
ERROR 2022-07-08 13:44:24,152 excepthooks 407896 140504459274048 Unhandled exception in thread: 'MainThread'
ERROR 2022-07-08 13:44:24,154 excepthooks 407896 140504459274048 Traceback (most recent call last):
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/utility/roiRequestBatch.py", line 171, in execute
    self._activateNewRequest()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/utility/roiRequestBatch.py", line 216, in _activateNewRequest
    roi = next(self._roiIter)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik.py", line 134, in <module>
    main()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik.py", line 128, in main
    hShell = ilastik_main.main(parsed_args, workflow_cmdline_args)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik_main.py", line 170, in main
    f(shell)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik_main.py", line 347, in loadProject
    shell.openProjectFile(path, parsed_args.readonly)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/shell/headless/headlessShell.py", line 125, in openProjectFile
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/utility/timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 467, in _loadProject
    self.workflow.onProjectLoaded(self)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/workflows/objectClassification/objectClassificationWorkflow.py", line 352, in onProjectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 64, in run_export_from_parsed_args
    return self.run_export(role_path_dict, parsed_args.input_axes, sequence_axis=parsed_args.stack_along)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 118, in run_export
    progress_callback=partial(lerpProgressSignal, global_progress_start, global_progress_end),
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 181, in export_dataset
    opDataExport.run_export()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/dataExport/opDataExport.py", line 251, in run_export
    self._opFormattedExport.run_export()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operators/ioOperators/opFormattedDataExport.py", line 257, in run_export
    self._opExportSlot.run_export()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operators/ioOperators/opExportSlot.py", line 257, in run_export
    export_func()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operators/ioOperators/opExportSlot.py", line 342, in _export_2d
    opExport.run_export()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operators/ioOperators/opExport2DImage.py", line 76, in run_export
    data = self._opExportToArray.run_export_to_array()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operators/ioOperators/opExportToArray.py", line 37, in run_export_to_array
    streamer.execute()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/utility/bigRequestStreamer.py", line 290, in execute
    self._requestBatch.execute()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/utility/roiRequestBatch.py", line 206, in execute
    raise_with_traceback(exc_type(exc_value), exc_tb)
  File "/home/user/ilastik-1.3.3post3-Linux/lib/python3.7/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operators/opReorderAxes.py", line 171, in execute
    self.Input(*in_roi).writeInto(result_input_view).wait()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/user/ilastik-1.3.3post3-Linux/lib/python3.7/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operators/generic.py", line 592, in execute
    matrix = req.wait()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/user/ilastik-1.3.3post3-Linux/lib/python3.7/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operators/valueProviders.py", line 130, in execute
    req.wait()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/user/ilastik-1.3.3post3-Linux/lib/python3.7/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operators/generic.py", line 443, in execute
    self.Input(*input_roi).writeInto(result).wait()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/user/ilastik-1.3.3post3-Linux/lib/python3.7/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 841, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1384, in execute
    map_ = self.ObjectMap([t]).wait()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/user/ilastik-1.3.3post3-Linux/lib/python3.7/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1221, in execute
    classifier = self.Classifier.value
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1015, in value
    temp = self[:].wait()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/user/ilastik-1.3.3post3-Linux/lib/python3.7/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operators/valueProviders.py", line 310, in execute
    value = request.wait()[0]
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 698, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/home/user/ilastik-1.3.3post3-Linux/lib/python3.7/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/operator.py", line 591, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1096, in execute
    pool.wait()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1354, in wait
    self._clear_finishing_requests()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 1449, in _clear_finishing_requests
    req.block()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 547, in block
    self._wait(timeout)  # No return value. Use wait()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 569, in _wait
    self._wait_within_request(current_request)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 654, in _wait_within_request
    raise_with_traceback(exc_type(exc_value), exc_tb)
  File "/home/user/ilastik-1.3.3post3-Linux/lib/python3.7/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 1073, in fetch_features
    featstmp, row_names, col_names, labelstmp = make_feature_array(feats, selected, labels_image_filtered)
  File "/home/user/ilastik-1.3.3post3-Linux/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 963, in make_feature_array
    ft = ft[index]
IndexError: too many indices for array

```

Thanks a lot for looking into this.

Tobias

**Comment by tboo** [comment]
Hi -
yes this problem occurred for the very same file in the very same docker container. What puzzled me (and eventually solved the problem) is that the object classifier was still training during prediction as the (successful) prediction ended with:

```
INFO ilastik.applets.objectClassification.opObjectClassification: training on matrix of shape (368, 105)
INFO lazyflow.classifiers.parallelVigraRfLazyflowClassifier: Training took, 0.14736 seconds
INFO lazyflow.classifiers.parallelVigraRfLazyflowClassifier: Training complete. Average OOB: 0.035326086956521736
INFO ilastik.applets.objectClassification.opObjectClassification: training finished, average out-of-bag error: 0.035326086956521736
INFO ilastik.workflows.objectClassification.objectClassificationWorkflow: Completed Batch Processing
```

So the problem was, that the original training data was not in the project folder (of the machines where we experienced above error). I thought once trained, the training data does not need to be carried along. Is this only true for pixel classification? I am performing pixel+object classification. While I am almost 99% sure that I did save my project after a live update (and training) of the object classifier I am wondering if I did a mistake there and need to resave the project to get around dragging along training data.

**Comment by k-dominik** [comment]
Hey @tboo,

thank you very much for following up and adding additional information!

The Pixel + Object Classification workflow is not really intended for production use - it's mainly there to be able to do live demos. In practice we always recommend doing the two workflows separately. The issue with the retraining (this was a bug!) was tackled in https://github.com/ilastik/ilastik/pull/2419, but this is not in `1.3.3post3` that you are using. I'd recommend using the latest beta version of ilastik to solve the "retraining" issue.

But I'd also want to mention that the combined workflow still has issues, e.g. https://github.com/ilastik/ilastik/issues/2469

**Comment by tboo** [comment]
Thanks so much for clarifying this
