### ISSUE TITLE
Singleton dimension causes axes mismatch

### ISSUE THREAD

**Issue by FynnBe** [ilastik/ilastik#2589]
## Describe the bug
(headless) batch processing (for object detection) fails for raw png images and .h5 probabilities 

## Expected behavior
successfull export. The same raw/pred combination works when loaded in the "Data Selection" Applet

## To Reproduce
[example.zip](https://github.com/ilastik/ilastik/files/9093821/example.zip)
headless:
```
ilastik --headless --project=nimal2_downs_obj.ilp --export_source="Object Predictions" --raw_data *.png --prediction_maps *.h5/exported_data
```

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
ERROR 2022-07-12 15:49:47,573 log_exception 15480 6464 Project could not be loaded due to the exception shown above.
Aborting Project Open Action
ERROR 2022-07-12 15:49:51,674 excepthooks 15480 6464 Unhandled exception in thread: 'MainThread'
ERROR 2022-07-12 15:49:51,706 excepthooks 15480 6464 Traceback (most recent call last):
  File "C:\conda\envs\ilastik3\Scripts\ilastik-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\conda\envs\ilastik3\lib\site-packages\ilastik_scripts\ilastik_startup.py", line 146, in main
    main()
  File "C:\conda\envs\ilastik3\lib\site-packages\ilastik\__main__.py", line 30, in main
    hShell = app.main(parsed_args, workflow_cmdline_args)
  File "C:\conda\envs\ilastik3\lib\site-packages\ilastik\app.py", line 204, in main
    f(shell)
  File "C:\conda\envs\ilastik3\lib\site-packages\ilastik\app.py", line 399, in loadProject
    shell.openProjectFile(path, parsed_args.readonly)
  File "C:\conda\envs\ilastik3\lib\site-packages\ilastik\shell\headless\headlessShell.py", line 125, in openProjectFile
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "C:\conda\envs\ilastik3\lib\site-packages\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "C:\conda\envs\ilastik3\lib\site-packages\ilastik\shell\projectManager.py", line 467, in _loadProject
    self.workflow.onProjectLoaded(self)
  File "C:\conda\envs\ilastik3\lib\site-packages\ilastik\workflows\objectClassification\objectClassificationWorkflow.py", line 366, in onProjectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "C:\conda\envs\ilastik3\lib\site-packages\ilastik\applets\batchProcessing\batchProcessingApplet.py", line 108, in run_export_from_parsed_args
    lane_configs=self.dataSelectionApplet.lane_configs_from_parsed_args(parsed_args),
  File "C:\conda\envs\ilastik3\lib\site-packages\ilastik\applets\dataSelection\dataSelectionApplet.py", line 314, in lane_configs_from_parsed_args
    stack_along=parsed_args.stack_along,
  File "C:\conda\envs\ilastik3\lib\site-packages\ilastik\applets\dataSelection\dataSelectionApplet.py", line 289, in create_lane_configs
    infos = [self.create_dataset_info(url, axistags=axistags, sequence_axis=stack_along) for url in role_urls]
  File "C:\conda\envs\ilastik3\lib\site-packages\ilastik\applets\dataSelection\dataSelectionApplet.py", line 289, in <listcomp>
    infos = [self.create_dataset_info(url, axistags=axistags, sequence_axis=stack_along) for url in role_urls]
  File "C:\conda\envs\ilastik3\lib\site-packages\ilastik\applets\dataSelection\dataSelectionApplet.py", line 256, in create_dataset_info
    project_file=self.project_file,
  File "C:\conda\envs\ilastik3\lib\site-packages\ilastik\applets\dataSelection\opDataSelection.py", line 653, in create_or_fallback_to_absolute
    return cls(*args, **kwargs)
  File "C:\conda\envs\ilastik3\lib\site-packages\ilastik\applets\dataSelection\opDataSelection.py", line 646, in __init__
    super().__init__(**fs_info_kwargs)
  File "C:\conda\envs\ilastik3\lib\site-packages\ilastik\applets\dataSelection\opDataSelection.py", line 558, in __init__
    **info_kwargs,
  File "C:\conda\envs\ilastik3\lib\site-packages\ilastik\applets\dataSelection\opDataSelection.py", line 100, in __init__
    raise UnsuitedAxistagsException(self.axistags, self.laneShape)
ilastik.applets.dataSelection.opDataSelection.UnsuitedAxistagsException: Axistags AxisInfo: 'y' (type: Space)
AxisInfo: 'x' (type: Space)
AxisInfo: 'c' (type: Channels)
 don't fit data shape (1838, 256, 342, 1)
```

## Desktop (please complete the following information):
 - ilastik version: 1.4.0b29
 - OS: Windows 10

**Comment by k-dominik** [comment]
Hello @FynnBe,

I see this was on windows. what shell did you use? If you've used cmd, it doesn't support `*`-expansion - ilastik will interpret input as a stack. See this issue for a solution using Powershell: https://github.com/ilastik/ilastik/issues/1133

(verified your example works fine on osx, where `*` expansion is supported)

**Comment by FynnBe** [comment]
I see. Thanks for clearing this up!
