### ISSUE TITLE
Ilastik API prediction fails for some projects

### ISSUE THREAD

**Issue by constantinpape** [ilastik/ilastik#2592]
For some of my projects, the ilastik API for pixel classification fails with a fairly unspecific error. I couldn't find any pattern to see for which projects it fails and for which it doesn't.

An example project for which it fails is here: `/g/kreshuk/pape/MyProject3D.ilp`

And here's the full traceback:
```
Run prediction with ilastik
Traceback (most recent call last):
  File "/g/kreshuk/pape/Work/my_projects/mpi-nat-em/mito3d/segmentation/compare_shallow2deep.py", line 176, in <module>
    main()
  File "/g/kreshuk/pape/Work/my_projects/mpi-nat-em/mito3d/segmentation/compare_shallow2deep.py", line 153, in main
    rf_pred, enh2d = _predict_s2d(data, output_path, ilp_path_3d, enhancer_2d, ilp_key, enhancer_key,
  File "/g/kreshuk/pape/Work/my_projects/mpi-nat-em/mito3d/segmentation/compare_shallow2deep.py", line 74, in _predict_s2d
    rf_pred = _require_rf(data, ilp_path, output_path, ilp_key)
  File "/g/kreshuk/pape/Work/my_projects/mpi-nat-em/mito3d/segmentation/compare_shallow2deep.py", line 21, in _require_rf
    rf_pred[z] = ilp.predict(inp).values[0, ..., 1]
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/ilastik/experimental/api/_base.py", line 67, in predict
    self._reorder_op.Input.setValue(data)
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/slot.py", line 1143, in setValue
    self._changed()
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/slot.py", line 1361, in _changed_impl
    self._configureOperator(self)
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/slot.py", line 1374, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/operator.py", line 518, in _setupOutputs
    oslot._setReady()
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/slot.py", line 1265, in _setReady
    self._changed()
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/slot.py", line 1354, in _changed_impl
    c._changed()
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/slot.py", line 1361, in _changed_impl
    self._configureOperator(self)
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/slot.py", line 1374, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/lazyflow/operator.py", line 501, in _setupOutputs
    self.setupOutputs()
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/ilastik/applets/featureSelection/opFeatureSelection.py", line 255, in setupOutputs
    super().setupOutputs()
  File "/home/pape/Work/software/conda/miniconda3/envs/torch10/lib/python3.9/site-packages/ilastik/applets/featureSelection/opFeatureSelection.py", line 179, in setupOutputs
    if self.parent.parent.featureSelectionApplet._gui is None:
AttributeError: 'NoneType' object has no attribute 'parent'
```

**Comment by k-dominik** [comment]
> if self.parent.parent.featureSelectionApplet._gui is None:
😞

**Comment by k-dominik** [comment]
sorry I still didn't look into it - but I'm very sure it's because of the stack being too narrow for the selected features. That it manifests like this is a bug of course.
