### ISSUE TITLE
Failed to use pixel classification api in python

### ISSUE THREAD

**Issue by oeway** [ilastik/ilastik#2601]
## Describe the bug
I am trying the pixel classification api in python but got an error with the example.

## To Reproduce
 1. create an conda environement with the environment.yaml file from here: https://github.com/ilastik/ilastik/tree/main/notebooks/pixel_classification_api
   <details>
  <summary>Show installed conda packages</summary>
<pre>
$ conda list
# packages in environment at /home/hongquanli/miniconda3/envs/ilastik:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
affogato                  0.3.3            py38h4a1efea_0    conda-forge
alsa-lib                  1.2.3.2              h166bdaf_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py38h0a891b7_2    conda-forge
asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
blosc                     1.21.1               h83bc5f7_3    conda-forge
boost                     1.74.0           py38h2b96118_5    conda-forge
boost-cpp                 1.74.0               h312852a_4    conda-forge
brotli                    1.0.9                h166bdaf_7    conda-forge
brotli-bin                1.0.9                h166bdaf_7    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.2.0              pyhd8ed1ab_0    conda-forge
certifi                   2022.6.15        py38h578d9bd_0    conda-forge
cffi                      1.15.1           py38h4a40e3a_0    conda-forge
cloudpickle               2.1.0              pyhd8ed1ab_0    conda-forge
coin-or-cbc               2.10.8               h3786ebc_0    conda-forge
coin-or-cgl               0.60.6               h6f57e76_1    conda-forge
coin-or-clp               1.17.7               hc56784d_1    conda-forge
coin-or-osi               0.108.7              h2720bb7_1    conda-forge
coin-or-utils             2.11.6               h202d8b1_1    conda-forge
coincbc                   2.10.8            0_metapackage    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.0           py38h0a891b7_0    conda-forge
dask-core                 2022.8.1           pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
debugpy                   1.6.3            py38hfa26641_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dpct                      1.2.post39      py38_0_hc75b0f0_gb6c703d    ilastik-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
enum34                    1.1.10           py38h32f6830_2    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
executing                 0.10.0             pyhd8ed1ab_0    conda-forge
expat                     2.4.8                h27087fc_0    conda-forge
fastfilters               0.2.4.post83    py38_0_g4c7b2d9    ilastik-forge
fftw                      3.3.10          nompi_ha7695d1_103    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonttools                 4.36.0           py38h0a891b7_0    conda-forge
freetype                  2.12.1               hca18f0e_0    conda-forge
fs                        2.4.15             pyhd8ed1ab_0    conda-forge
fsspec                    2022.7.1           pyhd8ed1ab_0    conda-forge
future                    0.18.2           py38h578d9bd_5    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
glpk                      4.65              h9202a9a_1004    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
greenlet                  1.1.2            py38hfa26641_2    conda-forge
grpc-cpp                  1.48.0               hbad87ad_3    conda-forge
grpcio                    1.48.0           py38h5b6373e_3    conda-forge
gst-plugins-base          1.18.5               hf529b03_3    conda-forge
gstreamer                 1.18.5               h9f60fe5_3    conda-forge
h5py                      3.7.0           nompi_py38h8afedcf_100    conda-forge
hdf5                      1.12.1          nompi_h2386368_104    conda-forge
hytra                     1.1.4.post77      py_0_g3a9ebe9    ilastik-forge
icu                       68.2                 h9c3ff4c_0    conda-forge
ilastik-core              1.4.0rc2                   py_0    ilastik-forge
ilastik-feature-selection 0.123.post32      py_0_gffb1748    ilastik-forge
ilastikrag                0.1.3.post52      py_0_g348c634    ilastik-forge
ilastiktools              0.2.post37      py38_0_h8e2faf5_gb056a5f    ilastik-forge
imagecodecs-lite          2019.12.3        py38h71d37f0_5    conda-forge
imageio                   2.21.1             pyhfa7a67d_0    conda-forge
imath                     3.1.5                h6239696_0    conda-forge
importlib-metadata        4.11.4           py38h578d9bd_0    conda-forge
importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.15.1             pyh210e3f2_0    conda-forge
ipython                   8.4.0            py38h578d9bd_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
jsonschema                4.9.1              pyhd8ed1ab_0    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1           py38h578d9bd_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py38h43d8883_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1  
lemon                     1.3.1                hf0e68b2_5    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20220623.0      cxx17_h48a1fff_1    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
libbrotlidec              1.0.9                h166bdaf_7    conda-forge
libbrotlienc              1.0.9                h166bdaf_7    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libclang                  11.1.0          default_ha53f305_1    conda-forge
libcurl                   7.83.1               h7bff187_0    conda-forge
libdeflate                1.13                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libglib                   2.72.1               h2d90d5f_0    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
liblapacke                3.9.0           16_linux64_openblas    conda-forge
libllvm11                 11.1.0               hf817b99_3    conda-forge
libnghttp2                1.47.0               hdcd2b5c_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_1    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h753d276_4    conda-forge
libpq                     13.5                 hd57d9b9_1    conda-forge
libprotobuf               3.20.1               h6239696_1    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.4.0                h0e0dad5_3    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.10               h72842e0_4    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
llvm-openmp               14.0.4               he0ac6c6_0    conda-forge
llvmlite                  0.38.1           py38h38d86a4_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mamutexport               0.2.1.post6     py39_0_g9ab21f6    ilastik-forge
marching_cubes            0.3.post9       py38_0_hb110ab7_g1a4aa17    ilastik-forge
markupsafe                2.1.1            py38h0a891b7_1    conda-forge
matplotlib-base           3.5.3            py38h826bfd8_1    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py38h497a2fe_1005    conda-forge
mrcfile                   1.4.2              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.30               haf5c9bc_0    conda-forge
mysql-libs                8.0.30               h28c427c_0    conda-forge
nbconvert                 5.6.1              pyhd8ed1ab_2    conda-forge
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h5eee18b_3  
ndstructs                 0.0.5dev0                  py_0    ilastik-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
networkx                  2.8.5              pyhd8ed1ab_0    conda-forge
nifty                     1.2.1            py38h8343072_3    conda-forge
notebook                  6.4.12             pyha770c72_0    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.78                 h2350873_0    conda-forge
numba                     0.55.2           py38hdc3674a_0    conda-forge
numpy                     1.19.5           py38h8246c76_3    conda-forge
openexr                   3.1.5                he0ac6c6_0    conda-forge
openjpeg                  2.5.0                h7d73246_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3            py38h47df419_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pathlib                   1.0.1            py38h578d9bd_6    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0            py38ha3b2c9c_2    conda-forge
pip                       22.1.2           py38h06a4308_0  
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
psutil                    5.9.1            py38h0a891b7_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pyopengl                  3.1.6              pyhd8ed1ab_1    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py38ha8c2ead_4    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.18.1           py38h0a891b7_1    conda-forge
python                    3.8.13          h582c2e5_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-elf                0.4.5              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.1             pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytiff                    0.8.1            py38h96e7eb2_4    conda-forge
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0            py38h71d37f0_1    conda-forge
pyyaml                    6.0              py38h0a891b7_4    conda-forge
pyzmq                     23.2.1           py38hfc09fa9_0    conda-forge
qt                        5.12.9               hda022c4_4    conda-forge
re2                       2022.06.01           h27087fc_0    conda-forge
readline                  8.1.2                h7f8727e_1  
scikit-image              0.19.3           py38h47df419_1    conda-forge
scikit-learn              1.1.2            py38h0b08f9b_0    conda-forge
scipy                     1.9.0            py38hea3f02b_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                61.2.0           py38h06a4308_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
skan                      0.10.0             pyhd8ed1ab_0    conda-forge
snappy                    1.1.9                hbd366e4_1    conda-forge
sqlite                    3.39.2               h5082296_0  
stack_data                0.4.0              pyhd8ed1ab_0    conda-forge
terminado                 0.15.0           py38h578d9bd_0    conda-forge
testpath                  0.6.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tifffile                  2019.7.26.2              py38_0    conda-forge
tk                        8.6.12               h1ccaba5_0  
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py38h0a891b7_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
unicodedata2              14.0.0           py38h0a891b7_1    conda-forge
vigra                     1.11.1          py38h2064be1_1032    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.1             pyhd3eb1b0_0  
wsdt                      0.2.post27        py_0_g84ad11f    ilastik-forge
xarray                    2022.6.0           pyhd8ed1ab_1    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h7f8727e_1  
yaml                      0.2.5                h7f98852_2    conda-forge
yapsy                     1.12.2                     py_0    conda-forge
z5py                      2.0.15           py38h5407690_0    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h7f8727e_2  
zstd                      1.5.2                h6239696_4    conda-forge
</pre>
</details>

 3. activate the environement and run the python code in the notebook: https://github.com/ilastik/ilastik/blob/main/notebooks/pixel_classification_api/pixel-classification-api.ipynb
 

## Error message/traceback

<details>
  <summary>Show error log</summary>

<pre>

(ilastik) hongquanli@prakashlab-US-Desktop-Aegis-RS:~/Desktop/octopi-malaria/data visualizaiton - full FOV$ python test-ilastik.py 
test-ilastik.py:13: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning dissapear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  image = DataArray(imageio.imread("2d_cells_apoptotic_1channel.png"), dims=("y", "x"))
Traceback (most recent call last):
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/vigra/arraytypes.py", line 1271, in __getitem__
    res = numpy.ndarray.__getitem__(self, index)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test-ilastik.py", line 14, in <module>
    prediction = pipeline.predict(image)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/ilastik/experimental/api/_base.py", line 69, in predict
    data = self._predict_op.PMaps.value[...]
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/slot.py", line 1015, in value
    temp = self[:].wait()
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/request/request.py", line 564, in _wait
    self._wait_with## Screenshots
If applicable, please add screenshots to help explain your problem.

## Desktop (please complete the following information):
 - ilastik version: [e.g. 1.3.2b1]
 - OS: [e.g. Ubuntu 18.04, macOS 10.12: Sierra (Fuji), Windows 10]
 
 in_foreign_thread(timeout)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/request/request.py", line 624, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/operator.py", line 595, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/operators/classifierOperators.py", line 483, in execute
    probabilities = self._calculate_probabilities(roi)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/operators/classifierOperators.py", line 595, in _calculate_probabilities
    input_data = self.Image[newKey].wait()
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/request/request.py", line 564, in _wait
    self._wait_within_foreign_thread(timeout)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/request/request.py", line 624, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/operator.py", line 595, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/operators/opReorderAxes.py", line 171, in execute
    self.Input(*in_roi).writeInto(result_input_view).wait()
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/request/request.py", line 564, in _wait
    self._wait_within_foreign_thread(timeout)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/request/request.py", line 624, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/request/request.py", line 860, in __call__
    return self.func(*totalargs, **self.kwargs)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/slot.py", line 869, in __call__
    result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/operator.py", line 595, in call_execute
    return self.execute(slot, subindex, roi, result, **kwargs)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/operators/opPixelFeaturesPresmoothed.py", line 424, in execute
    presmoothed_source[j][i, ...] = self._computeGaussianSmoothing(
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/lazyflow/operators/opPixelFeaturesPresmoothed.py", line 511, in _computeGaussianSmoothing
    result[c_slice, z : z + 1] = fastfilters.gaussianSmoothing(
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/fastfilters/__init__.py", line 32, in func_wrapper
    return res.withAxes(array.axistags)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/vigra/arraytypes.py", line 1130, in withAxes
    res = self[slicing].transposeToNumpyOrder().transpose(permutation)
  File "/home/hongquanli/miniconda3/envs/ilastik/lib/python3.8/site-packages/vigra/arraytypes.py", line 1277, in __getitem__
    res = numpy.ndarray.__getitem__(self, tmpindex)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
</pre>

</details>

**Comment by k-dominik** [comment]
Hi @oeway,

thank you for adding the details. Could you give me hint on how you created the environment? I tried osx, linux and both resulted in working notebooks, but maybe I'm missing something.
