### ISSUE TITLE
Batch export error

### ISSUE THREAD

**Issue by kaushikaram** [ilastik/ilastik#2610]
I currently face an issue when batch processing files to export a simple segemnetation output as tif files. 
I get a `UnsuitedAxistagsException`. Ilastik version 1.4.0rc2 in Windows x64.

```pytb
INFO 2022-09-14 13:35:23,263 dataSelectionApplet 12848 19144 Using axistags from previous lane: [z y x, None]
ERROR 2022-09-14 13:35:23,323 excepthooks 12848 19144 Unhandled exception in thread: 'MainThread'
ERROR 2022-09-14 13:35:23,324 excepthooks 12848 19144 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.0rc2\lib\site-packages\ilastik\applets\batchProcessing\batchProcessingGui.py", line 318, in run_export
    lane_configs = self.parentApplet.dataSelectionApplet.create_lane_configs(role_inputs=role_inputs)
  File "C:\Program Files\ilastik-1.4.0rc2\lib\site-packages\ilastik\applets\dataSelection\dataSelectionApplet.py", line 289, in create_lane_configs
    infos = [self.create_dataset_info(url, axistags=axistags, sequence_axis=stack_along) for url in role_urls]
  File "C:\Program Files\ilastik-1.4.0rc2\lib\site-packages\ilastik\applets\dataSelection\dataSelectionApplet.py", line 289, in <listcomp>
    infos = [self.create_dataset_info(url, axistags=axistags, sequence_axis=stack_along) for url in role_urls]
  File "C:\Program Files\ilastik-1.4.0rc2\lib\site-packages\ilastik\applets\dataSelection\dataSelectionApplet.py", line 256, in create_dataset_info
    project_file=self.project_file,
  File "C:\Program Files\ilastik-1.4.0rc2\lib\site-packages\ilastik\applets\dataSelection\opDataSelection.py", line 653, in create_or_fallback_to_absolute
    return cls(*args, **kwargs)
  File "C:\Program Files\ilastik-1.4.0rc2\lib\site-packages\ilastik\applets\dataSelection\opDataSelection.py", line 646, in __init__
    super().__init__(**fs_info_kwargs)
  File "C:\Program Files\ilastik-1.4.0rc2\lib\site-packages\ilastik\applets\dataSelection\opDataSelection.py", line 558, in __init__
    **info_kwargs,
  File "C:\Program Files\ilastik-1.4.0rc2\lib\site-packages\ilastik\applets\dataSelection\opDataSelection.py", line 100, in __init__
    raise UnsuitedAxistagsException(self.axistags, self.laneShape)
ilastik.applets.dataSelection.opDataSelection.UnsuitedAxistagsException: Axistags AxisInfo: 'z' (type: Space)
AxisInfo: 'y' (type: Space)
AxisInfo: 'x' (type: Space)
 don't fit data shape (166, 2, 1021, 1021)
```

**Comment by k-dominik** [comment]
Hello @kaushikaram,

I see that you are doing some form of batch processing. Aere you doing this via the GUI, or via the terminal/cmd?

In any case it seems that the data you're supplying to ilastik has their axes different (and might not provide sufficient information for ilastik to determine the axis order). From looking at the shape `(166, 2, 1021, 1021)` I'd probably deduce `zcyx`. Your training data was most likely formatted differently (and per default ilastik will try to use the same axesorder as in training). It also looks like your training data might only have had a single channel? Is this possible? Then processing a 2-channel image will not work, as ilastik expects the same number of channels in all data.

Do me guesses make any sense? Please let me know if that is not the case and I'll try to dig in further (for this having the training image(s) as well as the data you want to batch process would be helpful.

Cheers
D

**Comment by kaushikaram** [comment]
Dear @k-dominik,
Thanks for a quick response. 
I am processing the files via GUI. Yes its correct that the number of channels were different in the training and process data set. I have rectified that and now the segmentation is in process.

Thanks!

Cheers,
Kaushik

**Comment by k-dominik** [comment]
Awesome - thanks for checking back! :)
