### ISSUE TITLE
Suggest Features without any annotations results in error

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2683]
## Describe the bug
In pixel classification, going to _Suggest Features_ without adding any annotations and then running it, results in an exception

## Expected behavior

suggest features button should not be clickable without _any_ features, tooltip show state what to do. In general we could also add a helpful message if _Suggest Features_ is run with few labels only...

## To Reproduce
Within the Pixel Classification workflow

1. create a new pixel classification project
2. load some data
3. select feauteres
4. click on Suggest Features, without adding any annotations, run it -> 💥 

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
ERROR 2023-03-06 11:22:23,592 excepthooks 42778 8592393728 Traceback (most recent call last):
  File "/.../ilastik-1.4.0-OSX.app/Contents/Resources/lib/python3.7/site-packages/ilastik/applets/pixelClassification/suggestFeaturesDialog.py", line 852, in _run_selection
    self.opFilterFeatureSelection.setupOutputs()
  File "/.../ilastik-1.4.0-OSX.app/Contents/Resources/lib/python3.7/site-packages/ilastik/applets/pixelClassification/opPixelClassification.py", line 707, in setupOutputs
    data, labels.astype("int"), self._filter_method
  File "/.../ilastik-1.4.0-OSX.app/Contents/Resources/lib/python3.7/site-packages/ilastik_feature_selection/filter_feature_selection.py", line 47, in __init__
    self._X = normalize_data_for_MI(np.asarray(X))
  File "/.../ilastik-1.4.0-OSX.app/Contents/Resources/lib/python3.7/site-packages/ilastik_feature_selection/filter_feature_selection.py", line 44, in normalize_data_for_MI
    X[:, i] -= X[:, i].min()
  File "/.../ilastik-1.4.0-OSX.app/Contents/Resources/lib/python3.7/site-packages/numpy/core/_methods.py", line 44, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
```

## Desktop (please complete the following information):
 - ilastik version: `1.4.0` 😞 
 - OS: all

**Comment by tanishac25** [comment]
Can you assign this issue to me @k-dominik ?.

**Comment by AryanK37** [comment]
@tanishac25 I already fixed the issue
Sorry i should have commented i am working on it.
