### ISSUE TITLE
Problems opening tiffs saved in fiji

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2729]
Not sure what I'm doing wrong. I exported the beloved "blobs" image from Fiji and wanted to open it in ilastik. I've exported it via save-as `tiff` (in Fiji) and also via `ome-tiff`. Could open neither in ilastik. There are definitely other tiff files I can open, but not these particular ones that are created in a pretty straight forward way.

Also this pops up an empty error message 😞 

I've debugged into it and it seems that these files do not have a `C` axis in the axis-tags. As both, Fiji/imagej and ome-tiff write such files, we should support those, too.

Attachments:
* [blob-tiffs.zip](https://github.com/ilastik/ilastik/files/12123750/blob-tiffs.zip)

<details>
<summary>traceback</summary>

```pytb
ERROR 2023-07-21 14:21:54,333 log_exception 25748 8329452352 Traceback (most recent call last):
  File "/.../ilastik/ilastik/applets/dataSelection/dataSelectionGui.py", line 430, in addFileNames
    info = self.instantiate_dataset_info(url=str(full_path), role=roleIndex)
  File "/.../ilastik/ilastik/applets/dataSelection/dataSelectionGui.py", line 583, in instantiate_dataset_info
    info = self.parentApplet.create_dataset_info(url=url, *info_args, **info_kwargs)
  File "/.../ilastik/ilastik/applets/dataSelection/dataSelectionApplet.py", line 252, in create_dataset_info
    return RelativeFilesystemDatasetInfo.create_or_fallback_to_absolute(
  File "/.../ilastik/ilastik/applets/dataSelection/opDataSelection.py", line 653, in create_or_fallback_to_absolute
    return cls(*args, **kwargs)
  File "/.../ilastik/ilastik/applets/dataSelection/opDataSelection.py", line 646, in __init__
    super().__init__(**fs_info_kwargs)
  File "/.../ilastik/ilastik/applets/dataSelection/opDataSelection.py", line 546, in __init__
    op_reader = OpInputDataReader(
  File "/.../ilastik/lazyflow/operator.py", line 140, in __call__
    instance._after_init()
  File "/.../ilastik/lazyflow/operator.py", line 313, in _after_init
    self._setupOutputs()
  File "/.../ilastik/lazyflow/operator.py", line 507, in _setupOutputs
    self.setupOutputs()
  File "/.../ilastik/lazyflow/operators/ioOperators/opInputDataReader.py", line 214, in setupOutputs
    self.internalOperators, self.internalOutput = openFunc(filePath)
  File "/.../ilastik/lazyflow/operators/ioOperators/opInputDataReader.py", line 608, in _attemptOpenAsTiff
    opReader.Filepath.setValue(filePath)
  File "/.../ilastik/lazyflow/slot.py", line 74, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "/.../ilastik/lazyflow/slot.py", line 1169, in setValue
    self._changed()
  File "/.../ilastik/lazyflow/slot.py", line 1354, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "/.../ilastik/lazyflow/slot.py", line 1349, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/.../ilastik/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/.../ilastik/lazyflow/slot.py", line 1387, in _changed_impl
    self._configureOperator(self)
  File "/.../ilastik/lazyflow/slot.py", line 1400, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "/.../ilastik/lazyflow/slot.py", line 1349, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/.../ilastik/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/.../ilastik/lazyflow/operator.py", line 507, in _setupOutputs
    self.setupOutputs()
  File "/.../ilastik/lazyflow/operators/ioOperators/opTiffReader.py", line 58, in setupOutputs
    assert axes[last_C_pos] == "C"
AssertionError
```

</details>

Versions (tested): 1.4.0, 1.4.1b6

**Comment by k-dominik** [comment]
some more details: the problem was introduced in a3c876a146a7fdd0ad6acd488c481f619beadc69

So current working assumption is that tifffile changed it's handling of "palette" like images.
