### ISSUE TITLE
Problem with Batch processing : AssertionError

### ISSUE THREAD

**Issue by Etzila** [ilastik/ilastik#2731]
## Issue
I've confronted an issue with batch processing.
First I choose **pixel classification**, choosing .tif image, adding all features, and choosing 5 different labels. Finally, I save the file in .npy (or .h5) format. However, in batch processing when I add some other .tif files to do the same process on them, I confronted this error:

![image](https://github.com/ilastik/ilastik/assets/130646588/0103b1c5-436a-4903-a467-14628100ee72)

## Error message/traceback

Here is the log file:
```pytb
INFO 2023-07-25 17:12:02,491 app 61780 61752 Using tiktorch executable: ['C:\\Program Files\\ilastik-1.4.0\\python.exe', '-m', 'tiktorch.server']
INFO 2023-07-25 17:12:02,492 app 61780 61752 config file location: <none>
INFO 2023-07-25 17:12:03,259 app 61780 61752 Starting ilastik from "C:\Program Files\ilastik-1.4.0\lib".
WARNING 2023-07-25 17:12:03,541 opConservationTracking 61780 61752 Could not find any ILP solver
WARNING 2023-07-25 17:12:03,554 opStructuredTracking 61780 61752 Could not find any ILP solver
WARNING 2023-07-25 17:12:03,555 structuredTrackingWorkflow 61780 61752 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
INFO 2023-07-25 17:12:07,805 projectManager 61780 61752 Opening Project: C:/0/Education/PhD/Project/Results/Main/Pictures/Hot band main/B5/B5_500-1.ilp
INFO 2023-07-25 17:12:07,963 acceleratesupport 61780 61752 No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
WARNING 2023-07-25 17:12:08,823 warnings 61780 61752 cache.py(221): UserWarning: FIXME: This is a slow way to look for the items we want.
TilesCache._layerCache should be a dict-of-dict-of-dict for faster lookup!
WARNING 2023-07-25 17:12:09,408 warnings 61780 60312 slicingtools.py(269): FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
INFO 2023-07-25 17:12:20,909 dataSelectionApplet 61780 61752 Using axistags from previous lane: [y x c, None]
ERROR 2023-07-25 17:12:20,915 excepthooks 61780 61752 Unhandled exception in thread: 'MainThread'
ERROR 2023-07-25 17:12:20,919 excepthooks 61780 61752 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\ilastik\applets\batchProcessing\batchProcessingGui.py", line 321, in run_export
    lane_configs = self.parentApplet.dataSelectionApplet.create_lane_configs(role_inputs=role_inputs)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\ilastik\applets\dataSelection\dataSelectionApplet.py", line 289, in create_lane_configs
    infos = [self.create_dataset_info(url, axistags=axistags, sequence_axis=stack_along) for url in role_urls]
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\ilastik\applets\dataSelection\dataSelectionApplet.py", line 289, in <listcomp>
    infos = [self.create_dataset_info(url, axistags=axistags, sequence_axis=stack_along) for url in role_urls]
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\ilastik\applets\dataSelection\dataSelectionApplet.py", line 256, in create_dataset_info
    project_file=self.project_file,
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\ilastik\applets\dataSelection\opDataSelection.py", line 653, in create_or_fallback_to_absolute
    return cls(*args, **kwargs)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\ilastik\applets\dataSelection\opDataSelection.py", line 646, in __init__
    super().__init__(**fs_info_kwargs)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\ilastik\applets\dataSelection\opDataSelection.py", line 547, in __init__
    graph=Graph(), WorkingDirectory=self.base_dir, FilePath=self.filePath, SequenceAxis=self.sequence_axis
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\operator.py", line 140, in __call__
    instance._after_init()
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\operator.py", line 306, in _after_init
    self._setupOutputs()
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\operator.py", line 500, in _setupOutputs
    self.setupOutputs()
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\operators\ioOperators\opInputDataReader.py", line 214, in setupOutputs
    self.internalOperators, self.internalOutput = openFunc(filePath)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\operators\ioOperators\opInputDataReader.py", line 608, in _attemptOpenAsTiff
    opReader.Filepath.setValue(filePath)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\slot.py", line 1143, in setValue
    self._changed()
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\slot.py", line 1361, in _changed_impl
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\slot.py", line 1374, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\operator.py", line 500, in _setupOutputs
    self.setupOutputs()
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\operators\ioOperators\opTiffReader.py", line 58, in setupOutputs
    assert axes[last_C_pos] == "C"
AssertionError

```

## Screenshots
![image](https://github.com/ilastik/ilastik/assets/130646588/f1b2d44d-2240-4cce-bba7-816cf66eac22)

## Desktop
 - ilastik version: [1.4.0]
 - OS: [Windows 10, 21H2]

**Comment by Etzila** [comment]
Hi @k-dominik 
Thanks a lot for your quick response. That was really helpful.
