### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by alexlenail** [ilastik/ilastik#2738]
## Describe the bug
In the Pixel + Object classification workflow, I create an image with 3 color channels. I then proceed to step 2: Feature Selection, click "select features", and Ilastik immediately crashes. Log is attached at the bottom.  

## Error message/traceback

The first error is this one: 
```pytb
ERROR 2023-08-03 18:36:44,550 log_exception 73932 6285930496 Traceback (most recent call last):
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/objectClassification/opObjectClassification.py", line 143, in do_export
    prediction_label = predictions[t][object_id]
IndexError: index 1 is out of bounds for axis 0 with size 0
```

## Screenshots
<img width="638" alt="image" src="https://github.com/ilastik/ilastik/assets/2761597/ee41b800-0c1b-44c6-a9cc-ea68452463e1">

## Desktop (please complete the following information):
 - ilastik version: 1.4.1b6
 - OS: macOS 13.4.1 (22F82) // Apple M1 Max Silicon

## beginning of logfile (github not allowing full logfile -- too long): 
<details> 

```pytb
INFO 2023-07-14 15:24:52,480 app 27661 8492981760 Using tiktorch executable: ['/private/var/folders/mq/yzq45gh52xn7zz498z7cjtkw0000gn/T/AppTranslocation/68792FE2-FDA4-4F24-8798-4142BE65132A/d/ilastik-1.4.1b6-arm64-OSX.app/Contents/MacOS/python', '-m', 'tiktorch.server']
INFO 2023-07-14 15:24:52,480 app 27661 8492981760 config file location: <none>
INFO 2023-07-14 15:24:53,278 app 27661 8492981760 Starting ilastik from "/private/var/folders/mq/yzq45gh52xn7zz498z7cjtkw0000gn/T/AppTranslocation/68792FE2-FDA4-4F24-8798-4142BE65132A/d/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9".
INFO 2023-07-14 15:49:59,469 acceleratesupport 27661 8492981760 No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
INFO 2023-07-14 16:33:28,801 app 28650 8492981760 Using tiktorch executable: ['/private/var/folders/mq/yzq45gh52xn7zz498z7cjtkw0000gn/T/AppTranslocation/68792FE2-FDA4-4F24-8798-4142BE65132A/d/ilastik-1.4.1b6-arm64-OSX.app/Contents/MacOS/python', '-m', 'tiktorch.server']
INFO 2023-07-14 16:33:28,801 app 28650 8492981760 config file location: <none>
INFO 2023-07-14 16:33:29,500 app 28650 8492981760 Starting ilastik from "/private/var/folders/mq/yzq45gh52xn7zz498z7cjtkw0000gn/T/AppTranslocation/68792FE2-FDA4-4F24-8798-4142BE65132A/d/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9".
INFO 2023-07-14 16:33:33,897 projectManager 28650 8492981760 Opening Project: /Users/alex/Desktop/AAV_titration/AAV_titration.ilp
INFO 2023-07-14 16:33:34,010 acceleratesupport 28650 8492981760 No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
INFO 2023-07-14 16:46:49,448 parallelVigraRfLazyflowClassifier 28650 6240776192 Training took, 0.027771 seconds
INFO 2023-07-14 16:46:49,479 parallelVigraRfLazyflowClassifier 28650 6240776192 Training complete. Average OOB: 0.0
INFO 2023-07-14 16:48:25,625 parallelVigraRfLazyflowClassifier 28650 6190297088 Training took, 0.002432 seconds
INFO 2023-07-14 16:48:25,626 parallelVigraRfLazyflowClassifier 28650 6190297088 Training complete. Average OOB: 0.002789863672139098
INFO 2023-07-14 16:48:37,213 parallelVigraRfLazyflowClassifier 28650 6308081664 Training took, 0.003168 seconds
INFO 2023-07-14 16:48:37,213 parallelVigraRfLazyflowClassifier 28650 6308081664 Training complete. Average OOB: 0.006298292361902904
INFO 2023-07-14 16:48:52,465 parallelVigraRfLazyflowClassifier 28650 6240776192 Training took, 0.041091 seconds
INFO 2023-07-14 16:48:52,465 parallelVigraRfLazyflowClassifier 28650 6240776192 Training complete. Average OOB: 0.011605303447068463
INFO 2023-07-14 16:48:54,560 parallelVigraRfLazyflowClassifier 28650 6223949824 Training took, 0.067344 seconds
INFO 2023-07-14 16:48:54,595 parallelVigraRfLazyflowClassifier 28650 6223949824 Training complete. Average OOB: 0.015531794563773176
INFO 2023-07-14 16:49:13,800 parallelVigraRfLazyflowClassifier 28650 6207123456 Training took, 0.002934 seconds
INFO 2023-07-14 16:49:13,800 parallelVigraRfLazyflowClassifier 28650 6207123456 Training complete. Average OOB: 0.0032180437979888246
INFO 2023-07-14 16:52:40,278 parallelVigraRfLazyflowClassifier 28650 6240776192 Training took, 0.002941 seconds
INFO 2023-07-14 16:52:40,279 parallelVigraRfLazyflowClassifier 28650 6240776192 Training complete. Average OOB: 0.003988522822083392
INFO 2023-07-14 16:52:52,318 parallelVigraRfLazyflowClassifier 28650 6240776192 Training took, 0.010224 seconds
INFO 2023-07-14 16:52:52,318 parallelVigraRfLazyflowClassifier 28650 6240776192 Training complete. Average OOB: 0.006197974570792806
INFO 2023-07-14 16:52:54,026 parallelVigraRfLazyflowClassifier 28650 6308081664 Training took, 0.003424 seconds
INFO 2023-07-14 16:52:54,026 parallelVigraRfLazyflowClassifier 28650 6308081664 Training complete. Average OOB: 0.004580170497418938
INFO 2023-07-14 16:53:34,555 parallelVigraRfLazyflowClassifier 28650 6274428928 Training took, 0.002693 seconds
INFO 2023-07-14 16:53:34,555 parallelVigraRfLazyflowClassifier 28650 6274428928 Training complete. Average OOB: 0.004820893721472927
INFO 2023-07-14 16:54:04,559 parallelVigraRfLazyflowClassifier 28650 6207123456 Training took, 0.003021 seconds
INFO 2023-07-14 16:54:04,560 parallelVigraRfLazyflowClassifier 28650 6207123456 Training complete. Average OOB: 0.009835437351486611
INFO 2023-07-14 16:54:07,328 parallelVigraRfLazyflowClassifier 28650 6308081664 Training took, 0.009039 seconds
INFO 2023-07-14 16:54:07,328 parallelVigraRfLazyflowClassifier 28650 6308081664 Training complete. Average OOB: 0.005197339951478839
INFO 2023-07-14 17:08:39,568 parallelVigraRfLazyflowClassifier 28650 6207123456 Training took, 0.007442 seconds
INFO 2023-07-14 17:08:39,569 parallelVigraRfLazyflowClassifier 28650 6207123456 Training complete. Average OOB: 0.014503135525202566
INFO 2023-08-02 14:07:57,139 parallelVigraRfLazyflowClassifier 28650 6223949824 Training took, 0.03843 seconds
INFO 2023-08-02 14:07:57,141 parallelVigraRfLazyflowClassifier 28650 6223949824 Training complete. Average OOB: 0.022869294488787793
INFO 2023-08-02 14:08:16,889 parallelVigraRfLazyflowClassifier 28650 6274428928 Training took, 0.081952 seconds
INFO 2023-08-02 14:08:16,890 parallelVigraRfLazyflowClassifier 28650 6274428928 Training complete. Average OOB: 0.014014856286463333
INFO 2023-08-02 14:56:13,462 parallelVigraRfLazyflowClassifier 28650 6291255296 Training took, 0.008356 seconds
INFO 2023-08-02 14:56:13,464 parallelVigraRfLazyflowClassifier 28650 6291255296 Training complete. Average OOB: 0.01938131019636182
INFO 2023-08-02 16:06:05,129 objectExtractionGui 28650 6190297088 Object Extraction: done.
ERROR 2023-08-02 16:13:04,169 countingOperators 28650 6223949824 ERROR: could not learn regressor
ERROR 2023-08-02 16:13:04,170 countingOperators 28650 6223949824 fullFeatMatrix shape = (1, 49), dtype = float64
ERROR 2023-08-02 16:13:04,174 countingOperators 28650 6223949824 fullLabelsMatrix shape = (1,), dtype = float64
INFO 2023-08-02 16:41:48,730 app 73897 8492981760 Using tiktorch executable: ['/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/MacOS/python', '-m', 'tiktorch.server']
INFO 2023-08-02 16:41:48,730 app 73897 8492981760 config file location: <none>
INFO 2023-08-02 16:41:49,477 app 73897 8492981760 Starting ilastik from "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9".
INFO 2023-08-02 16:41:59,742 app 73915 8492981760 Using tiktorch executable: ['/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/MacOS/python', '-m', 'tiktorch.server']
INFO 2023-08-02 16:41:59,742 app 73915 8492981760 config file location: <none>
INFO 2023-08-02 16:42:00,325 app 73915 8492981760 Starting ilastik from "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9".
INFO 2023-08-02 16:42:05,902 app 73932 8492981760 Using tiktorch executable: ['/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/MacOS/python', '-m', 'tiktorch.server']
INFO 2023-08-02 16:42:05,902 app 73932 8492981760 config file location: <none>
INFO 2023-08-02 16:42:06,486 app 73932 8492981760 Starting ilastik from "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9".
INFO 2023-08-02 16:42:11,131 projectManager 73932 8492981760 Opening Project: /Users/alex/Desktop/AAV_titration/pixel_object_classification.ilp
INFO 2023-08-02 16:42:11,233 acceleratesupport 73932 8492981760 No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
INFO 2023-08-03 17:53:55,846 parallelVigraRfLazyflowClassifier 73932 6184972288 Training took, 0.052423 seconds
INFO 2023-08-03 17:53:55,848 parallelVigraRfLazyflowClassifier 73932 6184972288 Training complete. Average OOB: 0.06019480851720482
INFO 2023-08-03 18:02:30,757 parallelVigraRfLazyflowClassifier 73932 6201798656 Training took, 0.077653 seconds
INFO 2023-08-03 18:02:30,758 parallelVigraRfLazyflowClassifier 73932 6201798656 Training complete. Average OOB: 0.06703487410864278
INFO 2023-08-03 18:29:27,520 objectExtractionGui 73932 6184972288 Object Extraction: done.
INFO 2023-08-03 18:29:59,260 objectExtractionGui 73932 6201798656 Object Extraction: done.
INFO 2023-08-03 18:36:43,839 ioOperators 73932 12020903936 Data shape: (5108, 10091, 1)
INFO 2023-08-03 18:36:43,861 bigRequestStreamer 73932 12020903936 Estimated RAM usage per pixel is 260.0B * safety factor (2.0)
INFO 2023-08-03 18:36:43,861 bigRequestStreamer 73932 12020903936 determining blockshape assuming available_ram is 44.9GiB, split between 8 threads
INFO 2023-08-03 18:36:43,862 bigRequestStreamer 73932 12020903936 Chose blockshape: (3405, 3404, 1)
INFO 2023-08-03 18:36:43,862 bigRequestStreamer 73932 12020903936 Estimated RAM usage per block is 5.6GiB
ERROR 2023-08-03 18:36:44,550 log_exception 73932 6285930496 Traceback (most recent call last):
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/objectClassification/opObjectClassification.py", line 143, in do_export
    prediction_label = predictions[t][object_id]
IndexError: index 1 is out of bounds for axis 0 with size 0

ERROR 2023-08-03 18:36:44,550 log_exception 73932 6285930496 Export failed
ERROR 2023-08-03 18:36:44,552 log_exception 73932 12020903936 Traceback (most recent call last):
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/dataExport/dataExportGui.py", line 429, in exportSync
    self.parentApplet.post_process_lane_export(lane_index)
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/objectClassification/objectClassificationDataExportApplet.py", line 63, in post_process_lane_export
    req = self._tableExporter.export_object_data(lane_index, show_gui=False).wait()
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 541, in wait
    return self._wait(timeout)
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 564, in _wait
    self._wait_within_foreign_thread(timeout)
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 624, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/future/utils/__init__.py", line 449, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/objectClassification/opObjectClassification.py", line 143, in do_export
    prediction_label = predictions[t][object_id]
IndexError: index 1 is out of bounds for axis 0 with size 0

ERROR 2023-08-03 18:36:44,553 log_exception 73932 12020903936 Failed to generate export file: 
/Users/alex/Desktop/AAV_titration/round1/0224-2023 AAV pilot staining_10_young_high_512_Merged_Processed001_RAW_ch00_Object Identities.h5/exported_data
index 1 is out of bounds for axis 0 with size 0
INFO 2023-08-03 18:42:25,404 opObjectClassification 73932 6201798656 training on matrix of shape (4, 15)
INFO 2023-08-03 18:42:25,407 parallelVigraRfLazyflowClassifier 73932 6201798656 Training took, 0.000609 seconds
INFO 2023-08-03 18:42:25,407 parallelVigraRfLazyflowClassifier 73932 6201798656 Training complete. Average OOB: 0.0
INFO 2023-08-03 18:42:25,407 opObjectClassification 73932 6201798656 training finished, average out-of-bag error: 0.0
INFO 2023-08-03 18:42:32,736 ioOperators 73932 12020903936 Data shape: (5108, 10091, 1)
INFO 2023-08-03 18:42:32,751 bigRequestStreamer 73932 12020903936 Estimated RAM usage per pixel is 260.0B * safety factor (2.0)
INFO 2023-08-03 18:42:32,751 bigRequestStreamer 73932 12020903936 determining blockshape assuming available_ram is 44.9GiB, split between 8 threads
INFO 2023-08-03 18:42:32,751 bigRequestStreamer 73932 12020903936 Chose blockshape: (3405, 3404, 1)
INFO 2023-08-03 18:42:32,751 bigRequestStreamer 73932 12020903936 Estimated RAM usage per block is 5.6GiB
INFO 2023-08-03 18:42:35,554 exportFile 73932 6252277760 Fetching object features for feature table...
INFO 2023-08-03 18:50:29,598 dataSelectionApplet 73932 8492981760 Using axistags from previous lane: [y x, None]
INFO 2023-08-03 18:50:29,955 batchProcessingApplet 73932 6184972288 Exporting to /Users/alex/Desktop/AAV_titration/round1/0224-2023 AAV pilot staining_7_old_high_512_merged_Processed001_RAW_ch00_Object Identities.h5/exported_data
INFO 2023-08-03 18:50:29,963 ioOperators 73932 6184972288 Data shape: (6027, 10546, 1)
INFO 2023-08-03 18:50:29,978 bigRequestStreamer 73932 6184972288 Estimated RAM usage per pixel is 260.0B * safety factor (2.0)
INFO 2023-08-03 18:50:29,978 bigRequestStreamer 73932 6184972288 determining blockshape assuming available_ram is 44.9GiB, split between 8 threads
INFO 2023-08-03 18:50:29,979 bigRequestStreamer 73932 6184972288 Chose blockshape: (3405, 3404, 1)
INFO 2023-08-03 18:50:29,979 bigRequestStreamer 73932 6184972288 Estimated RAM usage per block is 5.6GiB
INFO 2023-08-03 18:53:07,388 exportFile 73932 6184972288 Fetching object features for feature table...
INFO 2023-08-03 18:56:57,361 exportFile 73932 6252277760 exported 381417 tables to /Users/alex/Desktop/AAV_titration/round1/0224-2023 AAV pilot staining_10_young_high_512_Merged_Processed001_RAW_ch00.h5.
INFO 2023-08-03 18:56:57,696 exportingOperator 73932 6252277760 Export finished. None
INFO 2023-08-03 18:57:13,450 exportFile 73932 6269104128 Fetching object features for feature table...
ERROR 2023-08-03 19:14:24,355 log_exception 73932 6269104128 Traceback (most recent call last):
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/request/request.py", line 360, in _execute
    self._result = self.fn()
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/objectClassification/opObjectClassification.py", line 185, in do_export
    export_file.write_all(settings["file type"], settings["compression"])
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/utility/exportFile.py", line 450, in write_all
    with h5py.File(self.file_name, "w") as fout:
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/Applications/ilastik-1.4.1b6-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/h5py/_hl/files.py", line 237, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 126, in h5py.h5f.create
OSError: Unable to create file (unable to truncate a file which is already open)
```

</details>

**Comment by alexlenail** [comment]
Rather peculiarly, this error does not occur if I go to step 2: Feature Selection, in a Pixel Classification workflow _alone_ (without the object classification)

**Comment by k-dominik** [comment]
Hi @alexlenail,

thank you for the detailed report, and sorry you're running into problems there.
In general we do not recommend to use the combined workflow due to huge memory requirements and also because there are quirks that we could never quite iron out. In the end this workflow is only used for demonstration purposes (and will be removed in the future).

Best practice would be to have to separate projects and use the results from pixel classification in an object classification project.

Hope this helps, and again, sorry you ran into this.

Cheers
D
