### ISSUE TITLE
not responding under Windows 10 - version 1.4.0.post1-gpu 

### ISSUE THREAD

**Issue by michael-seg** [ilastik/ilastik#2781]
I have experienced troubles with adding new images (raw data) in the first step of the workflow: pixel classification
Always 
Maybe s.o. can help. 

![screenshot](https://github.com/ilastik/ilastik/assets/153013069/e8e17c0f-7e3d-41b2-bc97-956ec859b775)

**Comment by k-dominik** [comment]
Hi @michael-seg,

this is definitely not what should happen! Can you maybe post a portion of your log file (_Settings_ -> _open log folder_)? There could be information there that helps us understand the issue better. Also, what file format are you using? If you can open your image in Fiji, you could use [our export plugin](https://github.com/ilastik/ilastik4ij#ilastik-imagej-modules) to produce an `.h5` file that should definitely work!

Hope we can resolve this quickly.

Cheers
D

**Comment by michael-seg** [comment]
[log.txt](https://github.com/ilastik/ilastik/files/13589523/log.txt)

I used .tif format

Thank you for your help dominik.
Best
Michael

**Comment by michael-seg** [comment]
also if i want to export as .hdf5 with your fiji-plugin, this one comes up:


java.lang.IllegalArgumentException: HDF5 export file must have '.h5' suffix
	at org.ilastik.ilastik4ij.io.ExportCommand.run(ExportCommand.java:85)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
[ERROR] Command errored: Export HDF5

**Comment by michael-seg** [comment]
also same problem with .h5 files, unfortunetly btw

[log.txt](https://github.com/ilastik/ilastik/files/13601289/log.txt)

Kind 
Michael
