### ISSUE TITLE
RuntimeError: Precondition violation!

### ISSUE THREAD

**Issue by Frodulphe** [ilastik/ilastik#2783]
## Describe the bug
I'm using Ilastik in Pixel classification and when I try to import my images in 'input data', which are crop jpg images by ImageJ, this error message appears:
**RuntimeError:
Precondition violation!
Unable to open file 'file name'.
(D:\bld\vigra_1659002732746\work\src\impex\codecmanager.cxx:203)**

## To Reproduce
1. Input data
2. + Add new
3. Add separate Image(s)...

## Error message/traceback
**RuntimeError:
Precondition violation!
Unable to open file 'file name'.
(D:\bld\vigra_1659002732746\work\src\impex\codecmanager.cxx:203)**

Starting ilastik from "C:\Program Files\ilastik-1.4.0\lib".
ERROR 2023-12-13 12:06:07,476 log_exception 11068 8164 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\ilastik\applets\dataSelection\dataSelectionGui.py", line 430, in addFileNames
    info = self.instantiate_dataset_info(url=str(full_path), role=roleIndex)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\ilastik\applets\dataSelection\dataSelectionGui.py", line 583, in instantiate_dataset_info
    info = self.parentApplet.create_dataset_info(url=url, *info_args, **info_kwargs)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\ilastik\applets\dataSelection\dataSelectionApplet.py", line 256, in create_dataset_info
    project_file=self.project_file,
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\ilastik\applets\dataSelection\opDataSelection.py", line 653, in create_or_fallback_to_absolute
    return cls(*args, **kwargs)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\ilastik\applets\dataSelection\opDataSelection.py", line 646, in __init__
    super().__init__(**fs_info_kwargs)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\ilastik\applets\dataSelection\opDataSelection.py", line 547, in __init__
    graph=Graph(), WorkingDirectory=self.base_dir, FilePath=self.filePath, SequenceAxis=self.sequence_axis
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\operator.py", line 140, in __call__
    instance._after_init()
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\operator.py", line 306, in _after_init
    self._setupOutputs()
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\operator.py", line 500, in _setupOutputs
    self.setupOutputs()
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\operators\ioOperators\opInputDataReader.py", line 214, in setupOutputs
    self.internalOperators, self.internalOutput = openFunc(filePath)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\operators\ioOperators\opInputDataReader.py", line 631, in _attemptOpenWithVigraImpex
    vigraReader.Filename.setValue(filePath)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\slot.py", line 73, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\slot.py", line 1143, in setValue
    self._changed()
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\slot.py", line 1328, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\slot.py", line 1361, in _changed_impl
    self._configureOperator(self)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\slot.py", line 1374, in _configureOperator
    self.maybe_call_within_transaction(self.operator._setupOutputs)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\slot.py", line 1323, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\operator.py", line 500, in _setupOutputs
    self.setupOutputs()
  File "C:\Program Files\ilastik-1.4.0\lib\site-packages\lazyflow\operators\ioOperators\ioOperators.py", line 59, in setupOutputs
    info = vigra.impex.ImageInfo(filename)
RuntimeError:
Precondition violation!
Unable to open file 'P:A/Experiments/Transfo RNAi-Dominante négative/Scans/CROP/pAnnGUS1b/plante1.jpg'.
(D:\bld\vigra_1659002732746\work\src\impex\codecmanager.cxx:203)

## Screenshots
![image](https://github.com/ilastik/ilastik/assets/153729374/ee91ff0a-9a62-47db-a4b4-f1b58b9785ea)

## Desktop (please complete the following information):
 - ilastik version: 1.4.0
 - OS: Windows 10

**Comment by btbest** [comment]
Hi @Frodulphe! First and maybe simplest thing to try: It looks like one folder in that path has an é in the name. I'm not sure if this is really the problem, but renaming it to avoid special characters might work. If that doesn't help, my next question would be whether you are tied to jpg-format? Otherwise, I would suggest trying a different format like tif or png. If you install the [ilastik-FIJI plugin](https://www.ilastik.org/documentation/fiji_export/plugin), you can use it export to ilastik-native h5 format, which will also speed up computations in ilastik.

**Comment by Frodulphe** [comment]
Hi,
I renamed my files and it works ! Thank you very much

De : Benedikt Best ***@***.***>
Envoyé : mercredi 13 décembre 2023 15:13
À : ilastik/ilastik ***@***.***>
Cc : Anais Delers ***@***.***>; Mention ***@***.***>
Objet : Re: [ilastik/ilastik] RuntimeError: Precondition violation! (Issue #2783)


Hi @Frodulphe<https://github.com/Frodulphe>! First and maybe simplest thing to try: It looks like one folder in that path has an é in the name. I'm not sure if this is really the problem, but renaming it to avoid special characters might work. If that doesn't help, my next question would be whether you are tied to jpg-format? Otherwise, I would suggest trying a different format like tif or png. If you install the ilastik-FIJI plugin<https://www.ilastik.org/documentation/fiji_export/plugin>, you can use it export to ilastik-native h5 format, which will also speed up computations in ilastik.

**Comment by btbest** [comment]
Great to hear! I will close this issue then :)
