### ISSUE TITLE
Large file closing doesn't always work (cache clearing error?)

### ISSUE THREAD

**Issue by oanegros** [ilastik/ilastik#2787]
When working with a `.ilp` with 11 large tif-files, closing the project doesnt always fully work, keeping the icon active and often requiring a `^C`/force quit.

After pressing close, the window closes, but the process stays in the task bar and stays alive in the terminal. 

Last message i get is usually:
`QLayout::removewidget: Cannot remove a null widget.`
which seems innocuous. 
I now got (on windows, through Anaconda Prompt):
```
ERROR 2023-12-18 13:27:25,483 log_exception 5128 31140 Traceback (most recent call last):
  File "C:\Users\Public\Documents\Oane_ilastik\ilastik\lazyflow\operators\cacheMemoryManager.py", line 186, in cleanup
    self.totalCacheMemory(total)
  File "C:\Users\Public\Documents\Oane_ilastik\ilastik\lazyflow\utility\orderedSignal.py", line 80, in _call
    f(args, *kw)
  File "C:\Users\Public\Documents\Oane_ilastik\ilastik\ilastik\shell\gui\ilastikShell.py", line 208, in printIt
    self.memoryWidget.setMemoryBytes(msg)
  File "C:\Users\Public\Documents\Oane_ilastik\ilastik\ilastik\shell\gui\ilastikShell.py", line 160, in setMemoryBytes
    self.label.setText("Cached Data: %1.1f MB" % (bytes / (1024.0 ** 2.0)))
RuntimeError: wrapped C/C++ object of type QLabel has been deleted
```
which also is a UI error, but more related to cache clearing, which seems to be the issue as i haven't gotten this with smaller projects.

**Comment by k-dominik** [comment]
Thank you for the report @oanegros. Really curious about this one - so you didn't save the project, it's really close project, it takes a long time and then the force quit....

**Comment by oanegros** [comment]
Later i just did something else and after like 20 minutes it closed without further message as far as i remember
