### ISSUE TITLE
Failed to initialize model

### ISSUE THREAD

**Issue by daviddaytw** [ilastik/ilastik#2788]
## Describe the bug
Ilastik failed to load the local model. This error happens in Neural Network Classification and Trainable Domain Adaptation workflows. 

## Expected behavior
Please add a clear and concise description of what you expected to happen.

## To Reproduce

Within the Neural Network Classification workflow
1. Add some multi-channel 2D data in the data selection applet
2. Go to NN prediction applet and drag a downloaded model to the input field. (I used ilastik version of https://bioimage.io/#/?id=10.5281%2Fzenodo.5764892)
3. Click on activate model

Within the Trainable Domain Adaptation workflow
1. Add some multi-channel 2D data in the data selection applet.
2. Go to the feature selection applet and select some features.
3. Go to the Training applet and select a downloaded model in the choose model input. (I used ilastik version of https://bioimage.io/#/?id=10.5281%2Fzenodo.5764892)
4. Click on activate model

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
C:\Program Files\ilastik-1.4.1b13\lib\site-packages\bioimageio\spec\shared\_resolve_source.py:440: CacheWarning: found cached C:\Users\David\AppData\Local\Temp\David\bioimageio_cache\https\raw.githubusercontent.com\bioimage-io\bioimage.io\main\site.config.json. Skipping download of https://raw.githubusercontent.com/bioimage-io/bioimage.io/main/site.config.json.
  warnings.warn(f"found cached {local_path}. Skipping download of {uri}.", category=CacheWarning)
C:\Program Files\ilastik-1.4.1b13\lib\site-packages\bioimageio\spec\shared\_resolve_source.py:440: CacheWarning: found cached C:\Users\David\AppData\Local\Temp\David\bioimageio_cache\https\bioimage-io.github.io\collection-bioimage-io\collection.json. Skipping download of https://bioimage-io.github.io/collection-bioimage-io/collection.json.
  warnings.warn(f"found cached {local_path}. Skipping download of {uri}.", category=CacheWarning)
13:54:04.083 [MainProcess/ThreadPoolExecutor-0_0] INFO Created session de879ed98e5e4d38a4a1c800e13a3c0d
13:54:04.108 [MainProcess/ThreadPoolExecutor-0_0] DEBUG Registered close handler <bound method _Lease.terminate of <tiktorch.server.device_pool._Lease object at 0x0000023D45A67430>> for session de879ed98e5e4d38a4a1c800e13a3c0d
13:54:04.108 [MainProcess/ThreadPoolExecutor-0_0] DEBUG Registered close handler <tiktorch.rpc.mp.create_client.<locals>._make_method.<locals>.MethodWrapper object at 0x0000023D45331A60> for session de879ed98e5e4d38a4a1c800e13a3c0d
C:\Program Files\ilastik-1.4.1b13\lib\site-packages\bioimageio\spec\shared\schema.py:46: ValidationWarning: tags: Missing tags corresponding to bioimage.io categories: [{'framework': ['tensorflow', 'pytorch', 'tensorflow.js']}, {'software': ['ilastik', 'imagej', 'fiji', 'imjoy', 'deepimagej', 'napari']}, {'method': ['stardist', 'cellpose', 'yolo', 'care', 'n2v', 'denoiseg']}]
  warnings.warn(msg, category=ValidationWarning)
Process ModelSessionProcess:
Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.1b13\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\ilastik-1.4.1b13\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\tiktorch\server\session\process.py", line 134, in _run_model_session_process
    session_proc = ModelSessionProcess(model_zip, devices)
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\tiktorch\server\session\process.py", line 96, in __init__
    model = load_resource_description(pathlib.Path(_tmp_file.name))
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\bioimageio\core\resource_io\io_.py", line 57, in load_resource_description
    rd: ResourceDescription = resolve_raw_node(raw_rd=raw_rd, nodes_module=nodes)
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\bioimageio\core\resource_io\utils.py", line 122, in resolve_raw_node
    rd = SourceNodeTransformer().transform(rd)
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 56, in transform
    return transformer(node, **kwargs)  # noqa
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 145, in generic_transformer
    node, **{name: self.transform(value, **kwargs) for name, value in iter_fields(node)}
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 145, in <dictcomp>
    node, **{name: self.transform(value, **kwargs) for name, value in iter_fields(node)}
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 56, in transform
    return transformer(node, **kwargs)  # noqa
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 65, in transform_dict
    return {key: self.transform(value, **kwargs) for key, value in node.items()}
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 65, in <dictcomp>
    return {key: self.transform(value, **kwargs) for key, value in node.items()}
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 56, in transform
    return transformer(node, **kwargs)  # noqa
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 145, in generic_transformer
    node, **{name: self.transform(value, **kwargs) for name, value in iter_fields(node)}
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 145, in <dictcomp>
    node, **{name: self.transform(value, **kwargs) for name, value in iter_fields(node)}
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 56, in transform
    return transformer(node, **kwargs)  # noqa
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\bioimageio\core\resource_io\utils.py", line 84, in transform_ResolvedImportableSourceFile
    assert importlib_spec is not None
AssertionError
13:54:05.155 [MainProcess/ClientPoller[IRPCModelSession]] WARNING Communication channel closed. Shutting Down.
13:54:05.157 [MainProcess/ThreadPoolExecutor-0_0] ERROR Exception calling application:
Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.1b13\lib\multiprocessing\connection.py", line 301, in _recv_bytes
    ov, err = _winapi.ReadFile(self._handle, bsize,
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\grpc\_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\tiktorch\server\grpc\inference_servicer.py", line 45, in CreateModelSession
    model_info = session.client.get_model_info()
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\tiktorch\rpc\mp.py", line 96, in __call__
    return fut.result(timeout=timeout)
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\tiktorch\rpc\types.py", line 82, in result
    return super().result(timeout or self._timeout)
  File "C:\Program Files\ilastik-1.4.1b13\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Program Files\ilastik-1.4.1b13\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\tiktorch\rpc\mp.py", line 134, in _poller
    msg = self._conn.recv()
  File "C:\Program Files\ilastik-1.4.1b13\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Program Files\ilastik-1.4.1b13\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
ERROR 2023-12-26 13:54:05,245 modelStateControl 12676 26068 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\lazyflow\futures_utils.py", line 38, in _do_map
    res = func(f.result())
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\ilastik\applets\neuralNetwork\tiktorchController.py", line 236, in _createModelFromUpload
    session = connection.create_model_session(uploadId, [d.id for d in srvConfig.devices if d.enabled])
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\lazyflow\operators\tiktorch\classifier.py", line 440, in create_model_session
    session = self._client.CreateModelSession(
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\grpc\_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Program Files\ilastik-1.4.1b13\lib\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: "
        debug_error_string = "{"created":"@1703627645.229000000","description":"Error received from peer ipv4:127.0.0.1:62945","file":"src/core/lib/surface/call.cc","file_line":1070,"grpc_message":"Exception calling application: ","grpc_status":2}"
```

## Screenshots
If applicable, please add screenshots to help explain your problem.
![image](https://github.com/ilastik/ilastik/assets/47077427/a11a5421-ce04-442d-a629-eabdc7efbd7f)

## Desktop (please complete the following information):
 - ilastik version: 1.4.1b13
 - OS: Ubuntu 20.04 and Windows 10

**Comment by daviddaytw** [comment]
I tried to debug the error, and these are some inspections I have done:

1. The sha1sum of the outputted zip in https://github.com/ilastik/tiktorch/blob/b5a3349ca93e8dd1ebc7207e7875636b39edfb32/tiktorch/server/session/process.py#L94 does not match with the checksum of original zip.
3. This error happens with any model (even the built-in EnhancerModel)
4. This error is platform-independent; I can reproduce it in Windows and Ubuntu. 
5. The neural network classification workflow works well using the same model's DOI.

It would be constructive to nail down the bug if someone could tell me the expected behavior.

**Comment by daviddaytw** [comment]
It successfully loaded the model after I used the TorchScript weight instead of clicking the ilastik button that would download PyTorch State Dict on BioImage.IO. Is this the right solution?

**Comment by k-dominik** [comment]
Hi @daviddaytw,

thank you very much for letting is know and for your patience in finding a way around that issue! Bummer that the pytorch state dict weights have stopped working, and even worse, that those are the default when clicking the ilastik icon. We'll fix that!

Cheers
Dominik

**Comment by Sajanth1** [comment]
I have run into the exact same error while trying to load the default models within the Trainable Domain Adaptation workflow. Strangely, the built-in EnhancerMitochondriaEM2D works (sometimes) but the model that I would like to use— EnhancerBoundaryEM2D—doesn't. What should I do?

**Comment by k-dominik** [comment]
This is now fixed with newer versions of tiktorch that use newer versions of the bioimageio libraries. Confirmed current release 1.4.1rc2 and the example mentioned in this comment: https://github.com/ilastik/ilastik/issues/2788#issuecomment-1869799194
