### ISSUE TITLE
problem with running NN

### ISSUE THREAD

**Issue by mocherry** [ilastik/ilastik#2827]
Dear all

## Describe the bug
When trying to run the NN Prediction workflow, there is an error: Failed to initialize model.
I downloaded: mitchondriaemsegmentation2d.zip
isung the ilastik-download button and loaded it into ilastik

## Expected behavior
Well, I expected the pipeline to run and produce results, what else.

## Error message/traceback

```pytb
If applicable, please add tracebacks with formatting, such as
C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\lazyflow\operators\opLabelVolume.py:144: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if method is "vigra":
C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\lazyflow\utility\pipeline.py:80: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if "Input" is slots:
Starting ilastik from "C:\Program Files\ilastik-1.4.1b13-gpu\lib".
25048
C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\spec\shared\_resolve_source.py:440: CacheWarning: found cached C:\Users\kirsch\AppData\Local\Temp\kirsch\bioimageio_cache\https\raw.githubusercontent.com\bioimage-io\bioimage.io\main\site.config.json. Skipping download of https://raw.githubusercontent.com/bioimage-io/bioimage.io/main/site.config.json.
  warnings.warn(f"found cached {local_path}. Skipping download of {uri}.", category=CacheWarning)
C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\spec\shared\_resolve_source.py:440: CacheWarning: found cached C:\Users\kirsch\AppData\Local\Temp\kirsch\bioimageio_cache\https\bioimage-io.github.io\collection-bioimage-io\collection.json. Skipping download of https://bioimage-io.github.io/collection-bioimage-io/collection.json.
  warnings.warn(f"found cached {local_path}. Skipping download of {uri}.", category=CacheWarning)

CUDA version: 11.3
CUDA_PATH C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3
CUDA_PATH_V12_3 C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3

Available devices:
  * cpu
  * cuda:0

Starting server on 127.0.0.1:50447
Writing connection data to C:\Users\kirsch\AppData\Local\Temp\tiktorch_connectiong9_l7_0u\conn.json
QFont::fromString: Invalid description '(empty)'
QFont::fromString: Invalid description '(empty)'
QFont::fromString: Invalid description '(empty)'
100%|███████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 10987.70it/s]
C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\spec\shared\_resolve_source.py:440: CacheWarning: found cached C:\Users\kirsch\AppData\Local\Temp\kirsch\bioimageio_cache\https\raw.githubusercontent.com\bioimage-io\bioimage.io\main\site.config.json. Skipping download of https://raw.githubusercontent.com/bioimage-io/bioimage.io/main/site.config.json.
  warnings.warn(f"found cached {local_path}. Skipping download of {uri}.", category=CacheWarning)
C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\spec\shared\_resolve_source.py:440: CacheWarning: found cached C:\Users\kirsch\AppData\Local\Temp\kirsch\bioimageio_cache\https\bioimage-io.github.io\collection-bioimage-io\collection.json. Skipping download of https://bioimage-io.github.io/collection-bioimage-io/collection.json.
  warnings.warn(f"found cached {local_path}. Skipping download of {uri}.", category=CacheWarning)
15:01:55.740 [MainProcess/ThreadPoolExecutor-0_0] INFO Created session c6781f55d9b947c7be20faddeb3327f5
15:01:55.741 [MainProcess/ThreadPoolExecutor-0_0] DEBUG Registered close handler <bound method _Lease.terminate of <tiktorch.server.device_pool._Lease object at 0x000001B852C78D00>> for session c6781f55d9b947c7be20faddeb3327f5
15:01:55.741 [MainProcess/ThreadPoolExecutor-0_0] DEBUG Registered close handler <tiktorch.rpc.mp.create_client.<locals>._make_method.<locals>.MethodWrapper object at 0x000001B852C74A30> for session c6781f55d9b947c7be20faddeb3327f5
C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\spec\shared\schema.py:46: ValidationWarning: tags: Missing tags corresponding to bioimage.io categories: [{'framework': ['tensorflow', 'pytorch', 'tensorflow.js']}, {'software': ['ilastik', 'imagej', 'fiji', 'imjoy', 'deepimagej', 'napari']}, {'method': ['stardist', 'cellpose', 'yolo', 'care', 'n2v', 'denoiseg']}]
  warnings.warn(msg, category=ValidationWarning)
Process ModelSessionProcess:
Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\tiktorch\server\session\process.py", line 134, in _run_model_session_process
    session_proc = ModelSessionProcess(model_zip, devices)
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\tiktorch\server\session\process.py", line 96, in __init__
    model = load_resource_description(pathlib.Path(_tmp_file.name))
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\core\resource_io\io_.py", line 57, in load_resource_description
    rd: ResourceDescription = resolve_raw_node(raw_rd=raw_rd, nodes_module=nodes)
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\core\resource_io\utils.py", line 122, in resolve_raw_node
    rd = SourceNodeTransformer().transform(rd)
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 56, in transform
    return transformer(node, **kwargs)  # noqa
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 145, in generic_transformer
    node, **{name: self.transform(value, **kwargs) for name, value in iter_fields(node)}
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 145, in <dictcomp>
    node, **{name: self.transform(value, **kwargs) for name, value in iter_fields(node)}
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 56, in transform
    return transformer(node, **kwargs)  # noqa
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 65, in transform_dict
    return {key: self.transform(value, **kwargs) for key, value in node.items()}
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 65, in <dictcomp>
    return {key: self.transform(value, **kwargs) for key, value in node.items()}
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 56, in transform
    return transformer(node, **kwargs)  # noqa
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 145, in generic_transformer
    node, **{name: self.transform(value, **kwargs) for name, value in iter_fields(node)}
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 145, in <dictcomp>
    node, **{name: self.transform(value, **kwargs) for name, value in iter_fields(node)}
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\spec\shared\node_transformer.py", line 56, in transform
    return transformer(node, **kwargs)  # noqa
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\bioimageio\core\resource_io\utils.py", line 84, in transform_ResolvedImportableSourceFile
    assert importlib_spec is not None
AssertionError
15:01:56.365 [MainProcess/ClientPoller[IRPCModelSession]] WARNING Communication channel closed. Shutting Down.
15:01:56.365 [MainProcess/ThreadPoolExecutor-0_0] ERROR Exception calling application:
Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\multiprocessing\connection.py", line 301, in _recv_bytes
    ov, err = _winapi.ReadFile(self._handle, bsize,
BrokenPipeError: [WinError 109] Die Pipe wurde beendet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\grpc\_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\tiktorch\server\grpc\inference_servicer.py", line 45, in CreateModelSession
    model_info = session.client.get_model_info()
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\tiktorch\rpc\mp.py", line 96, in __call__
    return fut.result(timeout=timeout)
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\tiktorch\rpc\types.py", line 82, in result
    return super().result(timeout or self._timeout)
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\tiktorch\rpc\mp.py", line 134, in _poller
    msg = self._conn.recv()
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
ERROR 2024-02-27 15:01:56,372 modelStateControl 4260 21984 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\lazyflow\futures_utils.py", line 38, in _do_map
    res = func(f.result())
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\ilastik\applets\neuralNetwork\tiktorchController.py", line 236, in _createModelFromUpload
    session = connection.create_model_session(uploadId, [d.id for d in srvConfig.devices if d.enabled])
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\lazyflow\operators\tiktorch\classifier.py", line 440, in create_model_session
    session = self._client.CreateModelSession(
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\grpc\_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Program Files\ilastik-1.4.1b13-gpu\lib\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: "
        debug_error_string = "{"created":"@1709042516.367000000","description":"Error received from peer ipv4:127.0.0.1:50447","file":"src/core/lib/surface/call.cc","file_line":1070,"grpc_message":"Exception calling application: ","grpc_status":2}"
>
```

## Screenshots
If applicable, please add screenshots to help explain your problem.
![grafik](https://github.com/ilastik/ilastik/assets/23337193/da2fc27f-689f-4af9-bd32-b224b15cf019)

## Desktop (please complete the following information):
 - ilastik version: ilastik-1.4.1b13-gpu-win64.exe
 - OS: [Windows 10]

**Comment by k-dominik** [comment]
Hi @mocherry,

unfortunately we have this bug currently with models that come with pytorch state dict weights? Where did you get this model? Most of the models on [bioimage.io](https://bioimage.io) are available also in torchscript format, which will work...

Hope we can help you quickly!
Cheers
Dominik
