### ISSUE TITLE
Can not open files for training on Windows 10

### ISSUE THREAD

**Issue by nobrown88** [ilastik/ilastik#2834]
## Describe the bug
I have tried to create a new project in both Ilastik1.4 and 1.3.3 on a Windows 10 lab computer on the network, but it can not find the files, even if they are saved on the computer C: itself or on the server. Also, why is it going to forward slash in windows? Here's the error message:

  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\dataSelection\opDataSelection.py", line 221, in expand_path
    raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), os.path.pathsep.join(missing_files))
FileNotFoundError: [Errno 2] No such file or directory: '/data'

## Expected behavior
I expected to open my .h5 files to train for pixel classification

## To Reproduce
I've tried uninstalling and re-installing different versions and have saved the training data in multiple different server and hard-drive locations.

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

C:\Program Files\ilastik-1.3.3post3\ilastik-meta\lazyflow\lazyflow\classifiers\__init__.py:20: UserWarning: init: Could not import tiktorch classifier
  warnings.warn("init: Could not import tiktorch classifier")
Starting ilastik from "C:\Program Files\ilastik-1.3.3post3".
ERROR 2024-03-18 15:47:06,030 log_exception 19780 19776 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\dataSelection\dataSelectionGui.py", line 408, in addFileNames
    new_infos = self._createDatasetInfos(roleIndex, paths)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\dataSelection\dataSelectionGui.py", line 529, in _createDatasetInfos
    info = self._createDatasetInfo(roleIndex, filePath, roi)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\dataSelection\dataSelectionGui.py", line 578, in _createDatasetInfo
    subvolume_roi=roi,
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\dataSelection\opDataSelection.py", line 542, in create_or_fallback_to_absolute
    return cls(*args, **kwargs)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\dataSelection\opDataSelection.py", line 535, in __init__
    super().__init__(**fs_info_kwargs)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\dataSelection\opDataSelection.py", line 436, in __init__
    self.expanded_paths = self.expand_path(filePath, cwd=self.base_dir)
  File "C:\Program Files\ilastik-1.3.3post3\ilastik-meta\ilastik\ilastik\applets\dataSelection\opDataSelection.py", line 221, in expand_path
    raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), os.path.pathsep.join(missing_files))
FileNotFoundError: [Errno 2] No such file or directory: '/data'

```


## Screenshots
![image](https://github.com/ilastik/ilastik/assets/163914705/2db362ae-9ad6-4ffe-95ad-0fdd04121341)



## Desktop (please complete the following information):
 - ilastik version: 1.3.3 here but have tried all 1.4s
 - OS: Windows 10
 
 <!---
For developers only:
in order to reproduce the environment properly it is of great help to know the exact commits for each of the main packages.

for d in ilastik lazyflow volumina; do
    (cd $d && echo "$d ilastik/$d@$(git rev-parse --verify HEAD)")
done

Just run the the preceding for loop in your shell from your ilastik-meta folder and paste the output below, after the comment mark.
Example output:

ilastik ilastik/ilastik@b060889258b8e8e5a8291d1c391dcfeb80474131
lazyflow ilastik/lazyflow@f1eaa478381ca27cf1ee43e4a26c96175a914073
volumina ilastik/volumina@0431fcefd75ecba2ddc3fe1fe86b47f65132f76b
--->

**Comment by k-dominik** [comment]
Dear @nobrown88,

thank you for reporting this. Moving ilastik project files can be a bit tricky. It goes back to the way ilastik saves the information to the input files in the project file. In principle there are 3 possibilities:

> 
>    * Absolute Link: Your data always resides in the same place on disk, even if you moved your project file since it was last opened.
>    * Relative Link: Your data is in the same parent directory tree as your project file. You may move your project file and data files simultaneously, but their relative locations must be fixed.
>    * Copied to Project File: If you select this, your data will be copied to the project file the next time your project is saved. Pro: Your project file will always be valid, even if you move your data. Con: This creates a copy of your data.
>

Do you remember how and on what machine the project was created?

This linkage of input data seems to not work anymore. Possible causes: a) links were relative, and only the project, but not the data was moved, or b) links were absolute but project is being opened on a different computer, which maybe has different mount points to the network drive.

In any case, did you get a message like the following:
<img width="532" alt="image" src="https://github.com/ilastik/ilastik/assets/24434157/557e4da0-92fa-4501-bb92-162b46365ce5">

This gives you the opportunity to restore the link by navigating to the missing file.

I know this is not terribly convenient.

note on the forward slash: ilastik saves the paths in normalized form. As a side note: Windows understands forward slashes, too.

**Comment by k-dominik** [comment]
Hello @nobrown88, did you get back to this?
