### ISSUE TITLE
Feature Selection constraint prevents adding dataset, crashes ilastik

### ISSUE THREAD

**Issue by btbest** [ilastik/ilastik#2836]
When adding a dataset to a project that already has active downstream applets, these may reject the new dataset and raise a DatasetConstraintError. The user flow for adding a dataset responds by opening a dialog that allows the user to e.g. reorder axes of the dataset to be added. In this case, the constraint is from Feature Selection ("Some of your selected scales are too large for your dataset"). Cancelling the Dataset Properties dialog that pops up in this case does not properly reset the GUI state, and the downstream applet remains active for the user to navigate to. Doing so crashes ilastik because the Feature Selection applet looks for a single-lane GUI, but no lanes and hence no GUIs exist.

## Expected behavior
Naively: Cancelling the Dataset Properties dialog should correctly reset the GUI and deactivate downstream applets.

When thinking about it: Applets like Feature Selection can continue to impose constraints on data selection even when all lanes are removed, so they should remain active if their backend is instantiated, and should be able to handle lane count = 0. Or there should be some other way for the user to remove the constraint (e.g. by resetting the applet completely).

## To Reproduce
Within Pixel Classification
1. Add some data in the data selection applet (e.g. some screenshot png)
2. Go to Feature Selection, add features to the largest scale the dataset can handle
3. Go back to data selection, remove the dataset -- Feature Selection applet becomes deactivated
4. Click Add New, and attempt to add a much smaller dataset (e.g. a tiny crop from the screenshot)
5. Feature Selection should raise a DatasetConstraintError about some scales being too large
6. Ok the error, Dataset Properties should pop up
7. Cancel Dataset Properties
8. Feature Selection applet remains active, click it to provoke the error below

## Error message/traceback

```pytb
ERROR 2024-04-03 17:53:23,115 excepthooks 12296 20896 Unhandled exception in thread: 'MainThread'
ERROR 2024-04-03 17:53:23,134 excepthooks 12296 20896 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.1b15\lib\site-packages\ilastik\shell\gui\ilastikShell.py", line 1225, in handleAppletBarItemExpanded
    self.setSelectedAppletDrawer(modelIndex)
  File "C:\Program Files\ilastik-1.4.1b15\lib\site-packages\ilastik\shell\gui\ilastikShell.py", line 1244, in setSelectedAppletDrawer
    self.showCentralWidget(applet_index)
  File "C:\Program Files\ilastik-1.4.1b15\lib\site-packages\ilastik\shell\gui\ilastikShell.py", line 1261, in showCentralWidget
    centralWidget = self._applets[applet_index].getMultiLaneGui().centralWidget()
  File "C:\Program Files\ilastik-1.4.1b15\lib\site-packages\ilastik\applets\base\singleToMultiGuiAdapter.py", line 69, in centralWidget
    if self.currentGui() is None:
  File "C:\Program Files\ilastik-1.4.1b15\lib\site-packages\ilastik\applets\base\singleToMultiGuiAdapter.py", line 47, in currentGui
    if self._guis[self._imageLaneIndex] is None:
IndexError: list index out of range

```

## Screenshots
The user can end up on the Feature Selection applet, with the data selection gui still loaded: 
![image](https://github.com/ilastik/ilastik/assets/63287233/5fddd13f-822e-423e-a142-ba891a21f9b4)

## Desktop:
 - ilastik version: 1.4.1b15
 - OS: Win11, probably all OSes though

**Comment by btbest** [comment]
Closing because we decided it's a feature, not a bug.

In the sense that when a downstream applet is imposing constraints on what datasets can be loaded, the user should have a chance to go to the applet and remove the constraint. Doing so should be independent of any individual lane existing, therefore in such a situation, the downstream applet should not need a single-lane GUI anyway.

Plus, the user flow is acceptable now. Feature Selection deactivates after removing the last dataset, making it clear that data must be loaded to progress. When loading incompatible data, Feature Selection complains. The user can cancel the load, but Feature Selection is now activated and the user can move there to deselect incompatible features.

Nice-to-have would be for the code to be explicit that this is intended functionality.
