### ISSUE TITLE
Unable to use K-Neighbors classifier for pixel classification

### ISSUE THREAD

**Issue by titouanlegourrierec** [ilastik/ilastik#2845]
## Describe the bug
When I try to do pixel classification using K-Neighbors Classifier (sklearn), I get the attached error message.

## Error message/traceback

```pytb
ERROR 2024-04-16 19:12:50,378 excepthooks 75708 8289270464 Traceback (most recent call last):
  File "/Applications/ilastik-1.4.1b15-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/pixelClassification/suggestFeaturesDialog.py", line 919, in _run_selection
    new_segmentation, new_oob, new_time = self.retrieve_segmentation(new_matrix)
  File "/Applications/ilastik-1.4.1b15-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/pixelClassification/suggestFeaturesDialog.py", line 631, in retrieve_segmentation
    oob_err = 100.0 * numpy.mean(self.opPixelClassification.opTrain.outputs["Classifier"].value.oobs)
AttributeError: 'SklearnLazyflowClassifier' object has no attribute 'oobs'
```

## Screenshots
<img width="1317" alt="image" src="https://github.com/ilastik/ilastik/assets/118545638/bbdf4e9b-e67a-4ce9-97d5-415529fb3243">

## Desktop (please complete the following information):
 - ilastik version: ilastik-1.4.1b15-arm64-OSX
 - OS: macOS 14.4.1

**Comment by k-dominik** [comment]
Hello @titouanlegourrierec,

I can reproduce this issue. This happens during automatic feature selection (thank you for attaching the screenshot). I don't think the "suggest features" functionality ever supported classifiers other than the vigra random forest.

We will not fix this (sorry) - In our experience there is no benefit in using a different shallow classifier. Is there a particular reason you need the KNN here?

Note: We plan to remove the functionality to change classifiers in the future.

**Comment by titouanlegourrierec** [comment]
I wanted to study the effects of using different models and color spaces to detect diseases on wheat leaves in order to maximize the performance of the model used.

So there is no particular reason for the specific use of KNN.

Thanks for your reply!

**Comment by k-dominik** [comment]
Thank you for your understanding. We'll keep this issue open until classifiers are hidden.

Usually we refer to the following paper on this question:

> Fernández-Delgado, Manuel, et al. "Do we need hundreds of classifiers to solve real world classification problems?." The journal of machine learning research 15.1 (2014): 3133-3181.

[available here](https://www.jmlr.org/papers/volume15/delgado14a/delgado14a.pdf)
