### ISSUE TITLE
Headless breaks if output h5 is corrupted

### ISSUE THREAD

**Issue by oanegros** [ilastik/ilastik#2861]
If the output h5 file is corrupted due to a previous run opening this and crashing, a new run will not work as it cannot open the output file.

`ERROR 2024-05-21 09:26:07,156 log_exception 3124137 140737354065728 Project could not be loaded due to the exception shown above.
Aborting Project Open Action
ERROR 2024-05-21 09:26:08,338 excepthooks 3124137 140737354065728 Unhandled exception in thread: 'MainThread'
ERROR 2024-05-21 09:26:08,344 excepthooks 3124137 140737354065728 Traceback (most recent call last):
  File "/g/koehler/Oane/sh_ilastik/ilastik/ilastik_scripts/ilastik_startup.py", line 151, in <module>
    main()
  File "/g/koehler/Oane/sh_ilastik/ilastik/ilastik_scripts/ilastik_startup.py", line 147, in main
    main()
  File "/g/koehler/Oane/sh_ilastik/ilastik/ilastik/__main__.py", line 30, in main
    hShell = app.main(parsed_args, workflow_cmdline_args)
  File "/g/koehler/Oane/sh_ilastik/ilastik/ilastik/app.py", line 204, in main
    f(shell)
  File "/g/koehler/Oane/sh_ilastik/ilastik/ilastik/app.py", line 399, in loadProject
    shell.openProjectFile(path, parsed_args.readonly)
  File "/g/koehler/Oane/sh_ilastik/ilastik/ilastik/shell/headless/headlessShell.py", line 125, in openProjectFile
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "/g/koehler/Oane/sh_ilastik/ilastik/lazyflow/utility/timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "/g/koehler/Oane/sh_ilastik/ilastik/ilastik/shell/projectManager.py", line 472, in _loadProject
    self.workflow.onProjectLoaded(self)
  File "/g/koehler/Oane/sh_ilastik/ilastik/ilastik/workflows/objectClassification/objectClassificationWorkflow.py", line 367, in onProjectLoaded
    self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
  File "/g/koehler/Oane/sh_ilastik/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 107, in run_export_from_parsed_args
    return self.run_export(
  File "/g/koehler/Oane/sh_ilastik/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 155, in run_export
    result = self.export_dataset(
  File "/g/koehler/Oane/sh_ilastik/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 198, in export_dataset
    result = export_function(opDataExport)
  File "/g/koehler/Oane/sh_ilastik/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 168, in do_normal_export
    opDataExport.run_export()
  File "/g/koehler/Oane/sh_ilastik/ilastik/ilastik/applets/dataExport/opDataExport.py", line 248, in run_export
    self._opFormattedExport.run_export()
  File "/g/koehler/Oane/sh_ilastik/ilastik/lazyflow/operators/ioOperators/opFormattedDataExport.py", line 276, in run_export
    self._opExportSlot.run_export()
  File "/g/koehler/Oane/sh_ilastik/ilastik/lazyflow/operators/ioOperators/opExportSlot.py", line 258, in run_export
    export_func()
  File "/g/koehler/Oane/sh_ilastik/ilastik/lazyflow/operators/ioOperators/opExportSlot.py", line 266, in _export_h5n5
    with OpStreamingH5N5Reader.get_h5_n5_file(export_components.externalPath, mode="a") as h5N5File:
  File "/g/koehler/Oane/sh_ilastik/ilastik/lazyflow/operators/ioOperators/opStreamingH5N5Reader.py", line 163, in get_h5_n5_file
    return h5py.File(filepath, mode)
  File "/g/koehler/Oane/sh_ilastik/shilastik_20230803_env/lib/python3.9/site-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/g/koehler/Oane/sh_ilastik/shilastik_20230803_env/lib/python3.9/site-packages/h5py/_hl/files.py", line 243, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048)
`

**Comment by btbest** [comment]
What would even be a helpful behaviour here for ilastik when the specified output file is corrupted..?

**Comment by oanegros** [comment]
for my use-case i wouldve hoped it overwrote the corrupted file (i had issues in my scripts which crashed ilastik, and needed to keep changing my output filename or remove all earlier output files for each new test)

**Comment by btbest** [comment]
Ah right, now I get the scenario.

If only there was a file-open mode "Read/write, create if exists, delete and recreate if corrupt" 🙃

**Comment by oanegros** [comment]
couldnt that just be a `try`/`except`?

**Comment by btbest** [comment]
I think that's basically what it boils down to. try/except OSError with a check for "truncated file" in the error string...
