### ISSUE TITLE
Could not load project file: Unable to get group info

### ISSUE THREAD

**Issue by pdd2110** [ilastik/ilastik#2871]
## Describe the bug
We were training a pixel classifier and when trying to save after a long period of training without saving it stopped responding. Force quit the program after about an hour. The project failed to load after restarting. 

## Error message/traceback
We're receiving the following error message:

![image](https://github.com/ilastik/ilastik/assets/63357900/77c0650d-0168-41a8-919e-3a779b07e94c)

And here is the message in the console:

```Starting ilastik in debug mode from "C:\Program Files\ilastik-1.4.0.post1-gpu\lib".
ERROR 2024-07-02 13:49:45,068 log_exception 23432 25560 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.0.post1-gpu\lib\site-packages\ilastik\shell\projectManager.py", line 465, in _loadProject
    serializer.deserializeFromHdf5(self.currentProjectFile, projectFilePath, self._headless)
  File "C:\Program Files\ilastik-1.4.0.post1-gpu\lib\site-packages\ilastik\applets\base\appletSerializer.py", line 1149, in deserializeFromHdf5
    ss.deserialize(topGroup)
  File "C:\Program Files\ilastik-1.4.0.post1-gpu\lib\site-packages\ilastik\applets\pixelClassification\pixelClassificationSerializer.py", line 98, in deserialize
    super().deserialize(group)
  File "C:\Program Files\ilastik-1.4.0.post1-gpu\lib\site-packages\ilastik\applets\base\appletSerializer.py", line 267, in deserialize
    self._deserialize(group[self.name], self.inslot)
  File "C:\Program Files\ilastik-1.4.0.post1-gpu\lib\site-packages\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\ilastik-1.4.0.post1-gpu\lib\site-packages\ilastik\applets\base\appletSerializer.py", line 577, in _deserialize
    num = len(mygroup)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Program Files\ilastik-1.4.0.post1-gpu\lib\site-packages\h5py\_hl\group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
RuntimeError: Unable to get group info (addr overflow, addr = 7323819, size = 328, eoa = 4430882)

ERROR 2024-07-02 13:49:45,070 log_exception 23432 25560 Project could not be loaded due to the exception shown above.
Aborting Project Open Action
ERROR 2024-07-02 13:49:45,467 log_exception 23432 25560 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.0.post1-gpu\lib\site-packages\ilastik\shell\gui\ilastikShell.py", line 1649, in _loadProject
    self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
  File "C:\Program Files\ilastik-1.4.0.post1-gpu\lib\site-packages\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\ilastik-1.4.0.post1-gpu\lib\site-packages\ilastik\shell\projectManager.py", line 465, in _loadProject
    serializer.deserializeFromHdf5(self.currentProjectFile, projectFilePath, self._headless)
  File "C:\Program Files\ilastik-1.4.0.post1-gpu\lib\site-packages\ilastik\applets\base\appletSerializer.py", line 1149, in deserializeFromHdf5
    ss.deserialize(topGroup)
  File "C:\Program Files\ilastik-1.4.0.post1-gpu\lib\site-packages\ilastik\applets\pixelClassification\pixelClassificationSerializer.py", line 98, in deserialize
    super().deserialize(group)
  File "C:\Program Files\ilastik-1.4.0.post1-gpu\lib\site-packages\ilastik\applets\base\appletSerializer.py", line 267, in deserialize
    self._deserialize(group[self.name], self.inslot)
  File "C:\Program Files\ilastik-1.4.0.post1-gpu\lib\site-packages\lazyflow\utility\timer.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\ilastik-1.4.0.post1-gpu\lib\site-packages\ilastik\applets\base\appletSerializer.py", line 577, in _deserialize
    num = len(mygroup)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Program Files\ilastik-1.4.0.post1-gpu\lib\site-packages\h5py\_hl\group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
RuntimeError: Unable to get group info (addr overflow, addr = 7323819, size = 328, eoa = 4430882)

```

## Desktop (please complete the following information):
 - ilastik version: Attempted with both 1.4.0rc2 and 1.4.0.post1-gpu. Also tried debug mode with the former but received the same error. 
 - OS: Windows 10

**Comment by k-dominik** [comment]
Hello @pdd2110,

the error looks like the project file is corrupted. Unfortunately, force-quitting/crashing ilastik during saving can result in that. I'm sad that I have to say that there is no reliable way to recover the data from this project. The only way is to retrain - sorry.

Best,
Dominik
