### ISSUE TITLE
NN Classification GPU prediction fails remote desktop environment

### ISSUE THREAD

**Issue by thodkatz** [ilastik/ilastik#2885]
## Issue
I have attempted to run ilastik in a remote machine launching vncserver and connecting to it with a vnc client. The goal was to utilize the gpu of the remote machine. 

First of all, to enable the gpu workflow, I had to modify the `dev/enviroment.yaml` :
https://github.com/ilastik/ilastik/blob/2db14b46c4573483b27bccfc82972c52640d490b/dev/environment-dev.yml#L60
I am not sure, what is the intention of the above line, because I tried to search for a package like `pytorch-cuda`, but it doesn't exist. I think it should be replaced with:
```
- cudatoolkit = 11.3
```

So based on the above change, the cuda and the gpu device were seemed to be detected.
```
CUDA version: 11.7
CUDA_VISIBLE_DEVICES 5

Available devices:
  * cpu
  * cuda:0
```

Then:
-  Choose `Neural Network Classification (Local)`
- Add image https://zenodo.org/api/files/ac8ecde9-bafd-4c2c-9ede-0f4a47077d31/sample_input_0.tif
- Choose model `kind-seashell`
- Click `Live Prediction`

![image](https://github.com/user-attachments/assets/a4cb9d5d-4265-42cb-9534-2c441c44e8ca)

Prediction seems to fail. I have also attached the logs 
[log.txt](https://github.com/user-attachments/files/16267203/log.txt)

The stack trace with the main issue:
```pytb
ERROR 2024-07-17 13:15:56,676 classifier 2648009 140736735860480 Predict call failed with exception.
Traceback (most recent call last):
  File "/home/katzalis/ilastik/lazyflow/operators/tiktorch/classifier.py", line 345, in predict
    resp = resp.result()
  File "/home/katzalis/miniforge3/envs/ilastik/lib/python3.9/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: "
	debug_error_string = "{"created":"@1721214956.676210260","description":"Error received from peer ipv4:127.0.0.1:35061","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Exception calling application: ","grpc_status":2}"
>
ERROR 2024-07-17 13:15:56,677 operators 2648009 140736719075072 Prediction failed with exception.
Traceback (most recent call last):
  File "/home/katzalis/ilastik/lazyflow/operators/tiktorch/operators.py", line 272, in execute
    result[...] = session.predict([input_data], [predictions_roi], [axistags])[0]
TypeError: 'int' object is not subscriptable
```

I tried to debug the issue, with setting up a remote coding development and forwarding the x11, so I can work locally, instead with the vnc client, but I am able to reproduce the problem only with the vnc client, and I can't understand why this is happening.

## Desktop (please complete the following information):
- remote machine kreshuk group gpu node 5
 
ilastik ilastik/ilastik@bc06fcaa4d1b4013a068ad8166e2c15aa83c61ec
lazyflow ilastik/lazyflow@a12bf383a32f4bd98e9a182965507807150e924f
volumina ilastik/volumina@baf0c1348f67b7c306d5a1cb62003c6958c1d1ba

**Comment by Tomaz-Vieira** [comment]
Maybe you were looking at a different conda channel? Here's the `pytorch-cuda` package [in conda-dorge](https://anaconda.org/pytorch/pytorch-cuda). I don't know if that's enough to cause trouble, but I guess it's worth trying before we go hunting for other problems

**Comment by thodkatz** [comment]
Yes, I am sorry! Indeed `pytorch-cuda` exists but not the version 11.3. I tried the latest one 12.4, and the next available after 11.3, which is 11.6. For both cases the problem is the same. So actually seems to be irrelevant with the package, but it has to do with the `vncserver`, because otherwise I am not getting this issue e.g. forwarding x11 with ssh.
