### ISSUE TITLE
Stacking of .tiff and .h5 does not work

### ISSUE THREAD

**Issue by FynnBe** [ilastik/ilastik#2917]
## Describe the bug
When selecting "Create volume from image stack" in the input data applet. selecting a .tiff and an .h5 file seems possible:
![image](https://github.com/user-attachments/assets/d908d10d-7fc0-4ef2-8e19-d65fb1341db7)
but the create volume from image stack file list stays empty and the console shows an error:
```pytb
ERROR 2024-10-15 10:55:50,240 excepthooks 23560 40040 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.4.1b20\lib\site-packages\ilastik\widgets\stackFileSelectionWidget.py", line 321, in _selectFiles
    internal_paths = self._h5N5FindCommonInternal(fileNames)
  File "C:\Program Files\ilastik-1.4.1b20\lib\site-packages\ilastik\widgets\stackFileSelectionWidget.py", line 227, in _h5N5FindCommonInternal
    tmp = set([x["name"] for x in lsH5N5(h5, minShape=2)])
  File "C:\Program Files\ilastik-1.4.1b20\lib\site-packages\lazyflow\utility\pathHelpers.py", line 378, in lsH5N5
    h5N5FileObject.visititems(addObjectNames)
AttributeError: 'NoneType' object has no attribute 'visititems'
```

## Expected behavior
A meaningful (error) message or that it just works.

## Desktop (please complete the following information):
 - ilastik version: [e.g. 1.4.1b20]
 - OS: Windows 10

**Comment by btbest** [comment]
Definitely the "meaningful error" route... the backend error would've been explicit, if the execution got that far:

`raise ValueError(f"Multiple extensions unsupported as a single data source: {self.expanded_paths}")`
