### ISSUE TITLE
qt-designer: plugins interface broken for featureTableWidget

### ISSUE THREAD

**Issue by lfiaschi** [ilastik/ilastik#417]
When trying to import the plugin of the feature table widget in the qt-designer I obtain the following error:

Traceback (most recent call last):
  File "/home/lfiaschi/workspace/ilastik-projects/ilastik/ilastik/widgets/featureTableWidget_plugin.py", line 27, in createWidget
    [0.3, 0.7, 1, 1.6, 3.5, 5.0, 10.0] \
  File "/home/lfiaschi/workspace/ilastik-projects/ilastik/ilastik/widgets/featureTableWidget.py", line 388, in createTableForFeatureDlg
    self._addVHeader()
  File "/home/lfiaschi/workspace/ilastik-projects/ilastik/ilastik/widgets/featureTableWidget.py", line 552, in _addVHeader
    for group, features in self._featureGroupMapping:
ValueError: too many values to unpack
Designer: The custom widget factory registered for widgets of class FeatureTableWidget returned 0.
*\* WARNING Factory failed to create  "FeatureTableWidget" 
Error while reparenting!
QMetaProperty::read: Unable to handle unregistered datatype 'QList<QColor>' for property 'KColorCombo::colors'
QMetaProperty::read: Unable to handle unregistered datatype 'SelectionBehavior' for property 'QTabBar::selectionBehaviorOnRemove'
QMetaProperty::read: Unable to handle unregistered datatype 'KUrl' for property 'KUrlRequester::url'
QMetaProperty::read: Unable to handle unregistered datatype 'QList<QChar>' for property 'KCharSelect::displayedChars'
QMetaProperty::read: Unable to handle unregistered datatype 'KUrl' for property 'KUrlRequester::url'
Hspell: can't open /usr/share/hspell/hebrew.wgz.sizes.
Enchant dict for "en_US" 0x2aca7c0

**Comment by k-dominik** [comment]
(coming 9 years late to the party): It's not the only plugin that's broken. Maybe we should get rid of them all - they're not used and if I have to go for qtdesigner for some reason I'm usually fine using just custom widget there... shall we remove the stuff and close this issue @akreshuk?
