### ISSUE TITLE
Incomprehensible Error Message than remove file from Data Selection while Thresholding calculates

### ISSUE THREAD

**Issue by kamay** [ilastik/ilastik#539]
Error Message appears than try to remove the Data from Data Selection while ilastik compute result in "Thresholding". Also the error message appears the file is removed from the list.

The Message of the error dialog is:
Can't get data from slot <class 'lazyflow.operators.opReorderAxes.OpReorderAxes'>.Output yet. It isn't ready.First upstream problem slot is: "Input" :  defaultdict(<function <lambda> at 0x7fc3e9951140>, {'NOTREADY': None, 'shape': (250, 250, 250, 2), '_dirty': False, 'dtype': <type 'numpy.float32'>, 'axistags': x y z c, '_ready': False, 'drange': (0.0, 1.0)})

``` python
ERROR: volumina tiling layer rendering worker thread caught an unhandled exception.  See above.Traceback (most recent call last):
  File "/tmp/guest-A2Tp5m/ilastik/src/volumina-HEAD/volumina/tiling.py", line 554, in _dirtyLayersWorker
    img = image_req.wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/volumina-HEAD/volumina/pixelpipeline/imagesources.py", line 263, in wait
    self._arrayreq.wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/volumina-HEAD/volumina/pixelpipeline/slicesources.py", line 22, in wait
    return self._sp(self._ar.wait())
  File "/tmp/guest-A2Tp5m/ilastik/src/volumina-HEAD/volumina/pixelpipeline/datasources.py", line 400, in wait
    rawData = self._rawRequest.wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/volumina-HEAD/volumina/pixelpipeline/datasources.py", line 181, in wait
    a = self._req.wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 311, in wait
    return self._wait(timeout)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 334, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 219, in _execute
    self._result = self.fn()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 718, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/operators/opReorderAxes.py", line 81, in execute
    self.Input( *in_roi ).writeInto( result_input_view ).wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 311, in wait
    return self._wait(timeout)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 334, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 219, in _execute
    self._result = self.fn()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 581, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 718, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/operators/opCompressedCache.py", line 66, in execute
    return self._executeOutput(roi, destination)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/operators/opCompressedCache.py", line 89, in _executeOutput
    reqPool.wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 746, in wait
    req.wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 311, in wait
    return self._wait(timeout)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 334, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 219, in _execute
    self._result = self.fn()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/operators/opCompressedCache.py", line 265, in _ensureCached
    data = self.Input(*entire_block_roi).wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 311, in wait
    return self._wait(timeout)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 337, in _wait
    self._wait_within_request( current_request )
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 219, in _execute
    self._result = self.fn()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 718, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/operators/generic.py", line 373, in execute
    r.wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 311, in wait
    return self._wait(timeout)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 337, in _wait
    self._wait_within_request( current_request )
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 219, in _execute
    self._result = self.fn()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 581, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 718, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/operators/opFilterLabels.py", line 33, in execute
    req.wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 311, in wait
    return self._wait(timeout)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 337, in _wait
    self._wait_within_request( current_request )
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 219, in _execute
    self._result = self.fn()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 581, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 718, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/operators/opCompressedCache.py", line 66, in execute
    return self._executeOutput(roi, destination)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/operators/opCompressedCache.py", line 89, in _executeOutput
    reqPool.wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 746, in wait
    req.wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 311, in wait
    return self._wait(timeout)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 337, in _wait
    self._wait_within_request( current_request )
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 219, in _execute
    self._result = self.fn()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/operators/opCompressedCache.py", line 265, in _ensureCached
    data = self.Input(*entire_block_roi).wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 311, in wait
    return self._wait(timeout)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 337, in _wait
    self._wait_within_request( current_request )
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 219, in _execute
    self._result = self.fn()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 718, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/operators/opVigraLabelVolume.py", line 42, in execute
    inputData = self.Input(roi.start, roi.stop).wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 311, in wait
    return self._wait(timeout)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 337, in _wait
    self._wait_within_request( current_request )
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 219, in _execute
    self._result = self.fn()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 718, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/operators/generic.py", line 646, in execute
    matrix = req.wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 311, in wait
    return self._wait(timeout)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 337, in _wait
    self._wait_within_request( current_request )
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 219, in _execute
    self._result = self.fn()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 718, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/tmp/guest-A2Tp5m/ilastik/src/ilastik-HEAD/ilastik/applets/thresholdTwoLevels/opThresholdTwoLevels.py", line 63, in execute
    data = self.Input( *inputRoi ).wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 311, in wait
    return self._wait(timeout)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 337, in _wait
    self._wait_within_request( current_request )
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 219, in _execute
    self._result = self.fn()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 718, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/operators/generic.py", line 435, in execute
    self.inputs["Input"][tuple(newKey)].writeInto(result).wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 311, in wait
    return self._wait(timeout)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 337, in _wait
    self._wait_within_request( current_request )
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 219, in _execute
    self._result = self.fn()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/request/request.py", line 581, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 718, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 1347, in execute
    return self.operator.execute(self, totalIndex, roi, result)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/operators/generic.py", line 126, in execute
    ttt = self.inputs["Input"][newKey].wait()
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 853, in __getitem__
    return self(pslice=key)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 1126, in __call__
    return self.get(roi)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 657, in get
    return self.partner.get(roi)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 657, in get
    return self.partner.get(roi)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 657, in get
    return self.partner.get(roi)
  File "/tmp/guest-A2Tp5m/ilastik/src/lazyflow-HEAD/lazyflow/slot.py", line 664, in get
    assert self.ready(), msg
AssertionError: Can't get data from slot <class 'lazyflow.operators.opReorderAxes.OpReorderAxes'>.Output yet. It isn't ready.First upstream problem slot is: "Input" :  defaultdict(<function <lambda> at 0x7fc3e9951140>, {'NOTREADY': None, 'shape': (250, 250, 250, 2), '_dirty': False, 'dtype': <type 'numpy.float32'>, 'axistags': x y z c, '_ready': False, 'drange': (0.0, 1.0)})

ERROR: volumina tiling layer rendering worker thread caught an unhandled exception.  See above.
```

**Comment by akreshuk** [comment]
i just tried this one again - deleted the input image in the data selection applet while thresholding was computing. It didn't crash and carried on nicely, but after it did remove the input image all the downstream applets became disabled and didn't get re-enabled when I added some new input. However, this case is so rare I'm inclined to close it.
