### ISSUE TITLE
Open new project from ilastik fails

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#741]
If you decide to switch to a new pixel classification project, when already working on some other pixel classification project in ilastik, you get:

```python
Traceback (most recent call last):
  File "/home/akreshuk/ilastik/ilastik/utility/gui/thunkEvent.py", line 63, in eventFilter
    event()
  File "/home/akreshuk/ilastik/ilastik/utility/gui/thunkEvent.py", line 20, in __call__
    self.thunk()
  File "/home/akreshuk/ilastik/ilastik/shell/gui/ilastikShell.py", line 1294, in _setAppletEnabled
    applet_index = self._applets.index(applet)
ValueError: <ilastik.applets.dataSelection.dataSelectionApplet.DataSelectionApplet object at 0x4a4f950> is not in list
Traceback (most recent call last):
  File "/home/akreshuk/ilastik/ilastik/utility/gui/thunkEvent.py", line 63, in eventFilter
    event()
  File "/home/akreshuk/ilastik/ilastik/utility/gui/thunkEvent.py", line 20, in __call__
    self.thunk()
  File "/home/akreshuk/ilastik/ilastik/shell/gui/ilastikShell.py", line 1294, in _setAppletEnabled
    applet_index = self._applets.index(applet)
ValueError: <ilastik.applets.featureSelection.featureSelectionApplet.FeatureSelectionApplet object at 0x4a58590> is not in list
Traceback (most recent call last):
  File "/home/akreshuk/ilastik/ilastik/utility/gui/thunkEvent.py", line 63, in eventFilter
    event()
  File "/home/akreshuk/ilastik/ilastik/utility/gui/thunkEvent.py", line 20, in __call__
    self.thunk()
  File "/home/akreshuk/ilastik/ilastik/shell/gui/ilastikShell.py", line 1294, in _setAppletEnabled
    applet_index = self._applets.index(applet)
ValueError: <ilastik.applets.pixelClassification.pixelClassificationApplet.PixelClassificationApplet object at 0x4a64bd0> is not in list
Traceback (most recent call last):
  File "/home/akreshuk/ilastik/ilastik/utility/gui/thunkEvent.py", line 63, in eventFilter
    event()
  File "/home/akreshuk/ilastik/ilastik/utility/gui/thunkEvent.py", line 20, in __call__
    self.thunk()
  File "/home/akreshuk/ilastik/ilastik/shell/gui/ilastikShell.py", line 1294, in _setAppletEnabled
    applet_index = self._applets.index(applet)
ValueError: <ilastik.applets.pixelClassification.pixelClassificationDataExportApplet.PixelClassificationDataExportApplet object at 0x50e1c90> is not in list
Traceback (most recent call last):
  File "/home/akreshuk/ilastik/ilastik/utility/gui/thunkEvent.py", line 63, in eventFilter
    event()
  File "/home/akreshuk/ilastik/ilastik/utility/gui/thunkEvent.py", line 20, in __call__
    self.thunk()
  File "/home/akreshuk/ilastik/ilastik/shell/gui/ilastikShell.py", line 1294, in _setAppletEnabled
    applet_index = self._applets.index(applet)
ValueError: <ilastik.applets.dataSelection.dataSelectionApplet.DataSelectionApplet object at 0x50fb410> is not in list
Traceback (most recent call last):
  File "/home/akreshuk/ilastik/ilastik/utility/gui/thunkEvent.py", line 63, in eventFilter
    event()
  File "/home/akreshuk/ilastik/ilastik/utility/gui/thunkEvent.py", line 20, in __call__
    self.thunk()
  File "/home/akreshuk/ilastik/ilastik/shell/gui/ilastikShell.py", line 1294, in _setAppletEnabled
    applet_index = self._applets.index(applet)
ValueError: <ilastik.applets.pixelClassification.pixelClassificationDataExportApplet.PixelClassificationDataExportApplet object at 0x5105190> is not in list
```

**Comment by stuarteberg** [comment]
The "New Project" menu item has been removed (as noted above), but the "Close Project" menu item is re-enabled in non-debug mode (via b225f6de20002f1f1bd79abf3bd9bff626de8b88).  When a user wants to make a new project, the procedure is "Close Project", then select the workflow from the startup screen.
