### ISSUE TITLE
Closing a project leads to an error message

### ISSUE THREAD

**Issue by JensNRAD** [ilastik/ilastik#777]
After exporting a prediction in the Pixel Classification Workflow and closing the project (to start with a new one) I get the following error:

```
RuntimeError: wrapped C/C++ object of type QLabel has been deleted.
```

**Comment by emilmelnikov** [comment]
The similar error still occurs, but now it complains about `QDoubleSpinBox`:

```pytb
ERROR 2019-06-27 11:53:41,264 excepthooks 7584 12004 Unhandled exception in thread: 'MainThread'
ERROR 2019-06-27 11:53:41,265 excepthooks 7584 12004 Traceback (most recent call last):
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 1128, in onCloseActionTriggered
    if not self.ensureNoCurrentProject():
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 1591, in ensureNoCurrentProject
    self.closeCurrentProject()
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\ilastik\ilastik\shell\gui\ilastikShell.py", line 1561, in closeCurrentProject
    self.projectManager.cleanUp()
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 238, in cleanUp
    raise e
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 235, in cleanUp
    self._closeCurrentProject()
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\ilastik\ilastik\shell\projectManager.py", line 517, in _closeCurrentProject
    self.workflow.cleanUp()
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\ilastik\ilastik\workflow.py", line 177, in cleanUp
    super(Workflow, self).cleanUp()
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\operator.py", line 385, in cleanUp
    self._disconnect()
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\operator.py", line 364, in _disconnect
    child._disconnect()
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\operator.py", line 361, in _disconnect
    s.resize(0)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\slot.py", line 124, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\slot.py", line 737, in resize
    self.removeSlot(len(self) - 1, len(self) - 1, propagate=False)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\slot.py", line 124, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\slot.py", line 829, in removeSlot
    self._sig_removed(self, position, finalsize)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\utility\orderedSignal.py", line 80, in __call__
    f(*args, **kw)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\operatorWrapper.py", line 211, in _callbackPostRemoved
    self._removeInnerOperator(index, size)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\operatorWrapper.py", line 285, in _removeInnerOperator
    oslot.removeSlot(index, length)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\slot.py", line 122, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\slot.py", line 815, in removeSlot
    self._sig_remove(self, position, finalsize)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\utility\orderedSignal.py", line 80, in __call__
    f(*args, **kw)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\ilastik\ilastik\workflow.py", line 240, in _removeImageLane
    a.topLevelOperator.removeLane(index, finalLength)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\ilastik\ilastik\utility\opMultiLaneWrapper.py", line 43, in removeLane
    self._removeInnerOperator(laneIndex, numLanes-1)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\operatorWrapper.py", line 289, in _removeInnerOperator
    outerSlot.removeSlot(index, length)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\slot.py", line 122, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\slot.py", line 818, in removeSlot
    slot.disconnect()
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\slot.py", line 122, in call_in_setup_context
    return func(self, *args, **kwargs)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\slot.py", line 699, in disconnect
    self._changed()
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\slot.py", line 1480, in _changed
    self._sig_changed(self)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\lazyflow\lazyflow\utility\orderedSignal.py", line 80, in __call__
    f(*args, **kw)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\ilastik\ilastik\utility\bind.py", line 64, in __call__
    self.f(*(self.bound_args + args[0:self.numUnboundArgs]))
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\ilastik\ilastik\utility\gui\threadRouter.py", line 76, in routed
    val = func(*args, **kwargs)
  File "C:\Program Files\ilastik-1.3.3b2\ilastik-meta\ilastik\ilastik\applets\thresholdTwoLevels\thresholdTwoLevelsGui.py", line 141, in _updateGuiFromOperator
    self._drawer.sigmaSpinBox_Z.setVisible(data_has_z_axis)
RuntimeError: wrapped C/C++ object of type QDoubleSpinBox has been deleted
```
