### ISSUE TITLE
Object feature computation error should be a pop-up

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#866]
In 3D, after the features are computed (count, mean, mean in n., variance, variance in n., skewness, skewness in n., kurtosis, kurtosis in n.). I thought I fixed this like three times already. Works for 2D.

```
ERROR 2014-03-25 21:15:36,035 projectManager 13181 140687089596160 Project Save Action failed due to the following exception:
Traceback (most recent call last):
File "/home/anna/ilastik/ilastik/shell/projectManager.py", line 229, in saveProject
    item.serializeToHdf5(self.currentProjectFile, self.currentProjectPath)
  File "/home/anna/ilastik/ilastik/applets/base/appletSerializer.py", line 791, in serializeToHdf5
    ss.serialize(topGroup)
  File "/home/anna/ilastik/ilastik/applets/objectExtraction/objectExtractionSerializer.py", line 61, in serialize
    for key, val in region_features.iteritems():
AttributeError: 'int' object has no attribute 'iteritems'
```

**Comment by akreshuk** [comment]
Object features haven't filed for a while on the ilastik side. Vigra failures either crash or stall the whole program anyway. I'll close it for now, let' re-open if it happens again.
