### ISSUE TITLE
IndexError: subslots list index is out of range when canceling data properties dialog

### ISSUE THREAD

**Issue by nkrasows** [ilastik/ilastik#950]
Open Carving; Input Data: Add seperate Image(s): one rgb jpeg image.
A warning appears saying that only 1 channel images are allowed -> press OK -> Dataset Properties appear ->press Cancel
The Index Error That appears will always come back if one OKs it.
Ilastik can then not be used anymore.

![carving_3cherror](https://cloud.githubusercontent.com/assets/3493433/3554284/8ce35dba-090b-11e4-9640-bb26b3236bea.png)

**Comment by stuarteberg** [comment]
Can't reproduce this any more.  It's been fixed.

**Comment by m-novikov** [comment]
Reproducible with following steps:
1. Create Pixel Classification workflow
2. Add 3 channel image
3. Try to add 4 channel image which will result in "Dataset Needs Correction" error
4. Press ok in error dialog. And cancel in consecutive "Dataset property" dialog
<details><summary>Traceback</summary>
<p>

```python
  File "/home/novikov/projects/ilastik-project/lazyflow/lazyflow/slot.py", line 1419, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/novikov/projects/ilastik-project/lazyflow/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/novikov/projects/ilastik-project/lazyflow/lazyflow/slot.py", line 1450, in _changed_impl
    c._changed()
  File "/home/novikov/projects/ilastik-project/lazyflow/lazyflow/slot.py", line 1424, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "/home/novikov/projects/ilastik-project/lazyflow/lazyflow/slot.py", line 1419, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/novikov/projects/ilastik-project/lazyflow/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/novikov/projects/ilastik-project/lazyflow/lazyflow/slot.py", line 1450, in _changed_impl
    c._changed()
  File "/home/novikov/projects/ilastik-project/lazyflow/lazyflow/slot.py", line 1424, in _changed
    self.maybe_call_within_transaction(self._changed_impl)
  File "/home/novikov/projects/ilastik-project/lazyflow/lazyflow/slot.py", line 1419, in maybe_call_within_transaction
    self.graph.maybe_call_within_transaction(fn)
  File "/home/novikov/projects/ilastik-project/lazyflow/lazyflow/graph.py", line 143, in maybe_call_within_transaction
    fn()
  File "/home/novikov/projects/ilastik-project/lazyflow/lazyflow/slot.py", line 1439, in _changed_impl
    self._sig_ready(self)
  File "/home/novikov/projects/ilastik-project/lazyflow/lazyflow/utility/orderedSignal.py", line 80, in __call__
    f(*args, **kw)
  File "/home/novikov/projects/ilastik-project/ilastik/ilastik/applets/pixelClassification/opPixelClassification.py", line 203, in handleInputReady
    self._checkConstraints( index )
  File "/home/novikov/projects/ilastik-project/ilastik/ilastik/applets/pixelClassification/opPixelClassification.py", line 294, in _checkConstraints
    .format( thisLaneTaggedShape['c'], validShape['c'] ) )
ilastik.applets.base.applet.DatasetConstraintError: Constraint of 'Pixel Classification' applet was violated: All input images must have the same number of channels.  Your new image has 4 channel(s), but your other images have 3 channel(s).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/novikov/projects/ilastik-project/ilastik/ilastik/applets/dataSelection/dataSelectionGui.py", line 403, in addFiles
    self.addFileNames(fileNames, roleIndex, startingLane)
  File "/home/novikov/projects/ilastik-project/ilastik/ilastik/applets/dataSelection/dataSelectionGui.py", line 480, in addFileNames
    loaded_all = self._configureOpWithInfos(roleIndex, startingLane, endingLane, infos)
  File "/home/novikov/projects/ilastik-project/ilastik/ilastik/applets/dataSelection/dataSelectionGui.py", line 626, in _configureOpWithInfos
    self._opTopRemoveDset(originalSize, laneIndex, roleIndex)
  File "/home/novikov/projects/ilastik-project/ilastik/ilastik/applets/dataSelection/dataSelectionGui.py", line 649, in _opTopRemoveDset
    self.topLevelOperator.DatasetGroup[laneIndex][roleIndex].setValue(None)
  File "/home/novikov/projects/ilastik-project/lazyflow/lazyflow/slot.py", line 1015, in __getitem__
    return self._subSlots[key]
IndexError: list index out of range
```
</p>
</details>
</summary>

**Comment by k-dominik** [comment]
this seems to be gone, most likely due to @Tomaz-Vieira heroic DataSelection refactoring :pray:
