### ISSUE TITLE
csv export for tracking

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#975]
and other object-level workflows, but tracking especially. With object features.

**Comment by akreshuk** [comment]
That works now, but the interface is still sub-optimal:
Since a single "Export" button launches exporting for both images and tables, both are always exported. Which means that you _have_ to export images to export a table.

**Comment by chaubold** [comment]
And at the moment if you choose 2D skeleton or convex hull features they will not show up in the exported table. Could also be fixed by #1247, need to check that.

**Comment by JaimeIvanCervantes** [comment]
@chaubold This will be fixed by #1247 indeed. Merge coming soon.

**Comment by chaubold** [comment]
Unfortunately not quite. Currently investigating this:

```
ERROR 2016-07-08 14:21:47,442 log_exception 93428 7232569344 Export failed
ERROR 2016-07-08 14:21:47,444 log_exception 93428 7232569344 Traceback (most recent call last):
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/ilastik/ilastik/applets/dataExport/dataExportGui.py", line 388, in exportSlots
    self.parentApplet.post_process_lane_export(lane_index)
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 384, in post_process_lane_export
    show_gui=False)
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/ilastik/ilastik/utility/exportingOperator.py", line 73, in export_object_data
    request.submit()
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 517, in do_export
    self._do_export_impl(settings, selected_features, progress_slot, object_feature_slot, label_image, lane_index, filename_suffix)
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/ilastik/ilastik/applets/tracking/base/opTrackingBase.py", line 636, in _do_export_impl
    {"selection": selected_features})
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 270, in add_columns
    columns = flatten_ilastik_feature_table(col_data, extra["selection"], self.InsertionProgress)
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 61, in flatten_ilastik_feature_table
    computed_feature.update(request.wait())
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/lazyflow/lazyflow/request/request.py", line 503, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opRelabeledMergerFeatureExtraction.py", line 197, in execute
    result[t][name][k] = self._merge_features(result[t][name][k], v, mapping[t])
KeyError: 'Coord<Principal<Kurtosis>>'
```

**Comment by JaimeIvanCervantes** [comment]
If there are any features missing, we can add them to `allFeaturesObjectCount` in the config file: https://github.com/ilastik/ilastik/blob/master/ilastik/applets/tracking/conservation/config.py

`allFeaturesObjectCount` contains the features that should be included in `opObjectExtraction`. If any feature is missing here, then it will not be computed.

**Comment by chaubold** [comment]
A very similar error just popped up for me during the workshop:

```
ERROR 2016-07-12 14:10:00,369 log_exception 19180 5251461120 Export failed
ERROR 2016-07-12 14:10:00,374 log_exception 19180 6740299776 Traceback (most recent call last):
  File "/Users/chaubold/Desktop/ilastik-1.2.0rc3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/dataExport/dataExportGui.py", line 388, in exportSlots
    self.parentApplet.post_process_lane_export(lane_index)
  File "/Users/chaubold/Desktop/ilastik-1.2.0rc3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py", line 386, in post_process_lane_export
    req.wait()
  File "/Users/chaubold/Desktop/ilastik-1.2.0rc3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/Users/chaubold/Desktop/ilastik-1.2.0rc3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 503, in _wait
    self._wait_within_foreign_thread( timeout )
  File "/Users/chaubold/Desktop/ilastik-1.2.0rc3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/Users/chaubold/Desktop/ilastik-1.2.0rc3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opConservationTracking.py", line 517, in do_export
    self._do_export_impl(settings, selected_features, progress_slot, object_feature_slot, label_image, lane_index, filename_suffix)
  File "/Users/chaubold/Desktop/ilastik-1.2.0rc3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/tracking/base/opTrackingBase.py", line 636, in _do_export_impl
    {"selection": selected_features})
  File "/Users/chaubold/Desktop/ilastik-1.2.0rc3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 270, in add_columns
    columns = flatten_ilastik_feature_table(col_data, extra["selection"], self.InsertionProgress)
  File "/Users/chaubold/Desktop/ilastik-1.2.0rc3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 61, in flatten_ilastik_feature_table
    computed_feature.update(request.wait())
  File "/Users/chaubold/Desktop/ilastik-1.2.0rc3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/Users/chaubold/Desktop/ilastik-1.2.0rc3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/Users/chaubold/Desktop/ilastik-1.2.0rc3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/Users/chaubold/Desktop/ilastik-1.2.0rc3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/Users/chaubold/Desktop/ilastik-1.2.0rc3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/tracking/conservation/opRelabeledMergerFeatureExtraction.py", line 197, in execute
    result[t][name][k] = self._merge_features(result[t][name][k], v, mapping[t])
KeyError: 0
```

**Comment by stuarteberg** [comment]
Can this be closed by now, @JaimeIvanCervantes ?

**Comment by JaimeIvanCervantes** [comment]
This was solved in the latest release.
