### ISSUE TITLE
Importing raw data and prediction map while reordering axes crashes

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#992]
**Steps to reproduce:**
- start a new Object Classification or Tracking from Prediction Map workflow
- load some raw data and change the axes order (I changed from xyzc to tyxc)
- load the prediction map, reorder axes as well
- **crash** with the following log: https://gist.github.com/chaubold/e3486acc53cb3a167ce6

@christophdecker experienced similar issues, but apparently got rid of them by pulling ilastik and lazyflow master. This does not fix it for me though.

**Comment by emii** [comment]
Hi, I also see similar behaviour.

* Started pixel classification in three dimensions and exported it to (z,y,x) .h5 (this allowed me to open the prediction in matlab with the native dimensions of the raw data (x,y,z   ?)...which doesn't make sense to transpose to (z,y,x) in the first place).
* Started Conservation tracking and imported raw data (z,x,y) and reordered axes by assigning 'z' as my time dimension (t,x,y). I did the same with the probabilities but Ilastik crashed. I suppose it still had the native dimension information hardcoded and ignores the axes transposition performed in the batch prediction export.

**Comment by chaubold** [comment]
> Started pixel classification in three dimensions and exported it to (z,y,x) .h5 (this allowed me to open the prediction in matlab with the native dimensions of the raw data (x,y,z ?)...which doesn't make sense to transpose to (z,y,x) in the first place).

I guess you could open it in matlab properly because matlab ignores the [AxisTags](http://ukoethe.github.io/vigra/doc-release/vigranumpy/index.html#axistags-and-the-vigraarray-data-structure) that we use to ease swapping axes.

**Comment by burgerdev** [comment]
Hi @emii, 
does the segfault occur *every time* you try changing the axes, or is it random? I managed to reproduce it once, but when I wanted to repeat it for a core dump I could not get it to segfault. If you see this every time, would you mind sharing your data so we can investigate further?

**Comment by burgerdev** [comment]
Nevermind, I could finally reproduce this. Backtrace yielded a segfault in Qt4, which was the last location where I would have looked for it. Seems like the dialog is accessing things not meant to be accessed, or deleting stuff that is still in use somewhere else.

```backtrace
#0  0x00007fffe9426faf in QMetaObject::changeGuard(QObject**, QObject*) () from /usr/lib/libQtCore.so.4
#1  0x00007fffe9d96ccd in ?? () from /usr/lib/libQtGui.so.4
#2  0x00007fffea7f645b in ?? () from /usr/lib/python2.7/site-packages/PyQt4/QtGui.so
#3  0x00007fffe998f9c0 in QWidget::event(QEvent*) () from /usr/lib/libQtGui.so.4
#4  0x00007fffe9d9af1b in QMenu::event(QEvent*) () from /usr/lib/libQtGui.so.4
#5  0x00007fffea7f4e9b in ?? () from /usr/lib/python2.7/site-packages/PyQt4/QtGui.so
#6  0x00007fffe993913c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#7  0x00007fffe9940156 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#8  0x00007fffea9bda46 in ?? () from /usr/lib/python2.7/site-packages/PyQt4/QtGui.so
#9  0x00007fffe940dd4d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQtCore.so.4
#10 0x00007fffe993f75d in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/libQtGui.so.4
#11 0x00007fffe99bb0cc in ?? () from /usr/lib/libQtGui.so.4
#12 0x00007fffe99b910d in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib/libQtGui.so.4
#13 0x00007fffe99e2082 in ?? () from /usr/lib/libQtGui.so.4
#14 0x00007fffe8c3c9fd in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#15 0x00007fffe8c3cce0 in ?? () from /usr/lib/libglib-2.0.so.0
#16 0x00007fffe8c3cd8c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#17 0x00007fffe943e044 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#18 0x00007fffe99e2156 in ?? () from /usr/lib/libQtGui.so.4
#19 0x00007fffe940c5c1 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#20 0x00007fffe940c935 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#21 0x00007fffe9d99a07 in QMenu::exec(QPoint const&, QAction*) () from /usr/lib/libQtGui.so.4
#22 0x00007fffe9da4e5f in ?? () from /usr/lib/libQtGui.so.4
#23 0x00007fffe9421e20 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/libQtCore.so.4
#24 0x00007fffe9d101b6 in ?? () from /usr/lib/libQtGui.so.4
#25 0x00007fffe9d10b23 in QAbstractButton::mousePressEvent(QMouseEvent*) () from /usr/lib/libQtGui.so.4
#26 0x00007fffea9a10fb in ?? () from /usr/lib/python2.7/site-packages/PyQt4/QtGui.so
#27 0x00007fffe9990580 in QWidget::event(QEvent*) () from /usr/lib/libQtGui.so.4
#28 0x00007fffea9a1c8b in ?? () from /usr/lib/python2.7/site-packages/PyQt4/QtGui.so
#29 0x00007fffe993913c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#30 0x00007fffe9940156 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#31 0x00007fffea9bda46 in ?? () from /usr/lib/python2.7/site-packages/PyQt4/QtGui.so
#32 0x00007fffe940dd4d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQtCore.so.4
#33 0x00007fffe993f75d in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/libQtGui.so.4
#34 0x00007fffe99ba742 in ?? () from /usr/lib/libQtGui.so.4
#35 0x00007fffe99b910d in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib/libQtGui.so.4
#36 0x00007fffe99e2082 in ?? () from /usr/lib/libQtGui.so.4
#37 0x00007fffe8c3c9fd in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#38 0x00007fffe8c3cce0 in ?? () from /usr/lib/libglib-2.0.so.0
#39 0x00007fffe8c3cd8c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#40 0x00007fffe943e044 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#41 0x00007fffe99e2156 in ?? () from /usr/lib/libQtGui.so.4
#42 0x00007fffe940c5c1 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#43 0x00007fffe940c935 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#44 0x00007fffe94122e9 in QCoreApplication::exec() () from /usr/lib/libQtCore.so.4
#45 0x00007fffea9bbe6b in ?? () from /usr/lib/python2.7/site-packages/PyQt4/QtGui.so
#46 0x00007ffff7af4b3f in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#47 0x00007ffff7af5abc in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#48 0x00007ffff7a823cc in function_call () from /usr/lib/libpython2.7.so.1.0
#49 0x00007ffff7a5d9e3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#50 0x00007ffff7af2671 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#51 0x00007ffff7af5abc in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#52 0x00007ffff7af4786 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#53 0x00007ffff7af4833 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#54 0x00007ffff7af5abc in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#55 0x00007ffff7af5bd9 in PyEval_EvalCode () from /usr/lib/libpython2.7.so.1.0
#56 0x00007ffff7b0f03f in run_mod () from /usr/lib/libpython2.7.so.1.0
#57 0x00007ffff7b10212 in PyRun_FileExFlags () from /usr/lib/libpython2.7.so.1.0
#58 0x00007ffff7b11427 in PyRun_SimpleFileExFlags () from /usr/lib/libpython2.7.so.1.0
#59 0x00007ffff7b234a1 in Py_Main () from /usr/lib/libpython2.7.so.1.0
#60 0x00007ffff7474790 in __libc_start_main () from /usr/lib/libc.so.6
#61 0x0000555555554859 in _start ()
```
